Repository OCA/purchase-workflow, pull requests merged in 2018-11, with the labels that each got.

#593 [FIX] purchase_landed_cost: error on deleting cost lines
  purchase_landed_cost/__manifest__.py
  purchase_landed_cost/i18n/purchase_landed_cost.pot
  purchase_landed_cost/models/purchase_cost_distribution.py
  purchase_landed_cost/tests/__init__.py
  purchase_landed_cost/tests/test_purchase_landed_cost.py
Labels: needs review

#605 [10.0][IMP] subcontracted_service: add route to procurement rules
  subcontracted_service/__manifest__.py
  subcontracted_service/migrations/10.0.2.0.0/pre-migration.py
  subcontracted_service/models/warehouse.py
Labels: approved

#563 [MIG] procurement_purchase_no_grouping: Migration to 11.0
  procurement_purchase_no_grouping/README.rst
  procurement_purchase_no_grouping/__init__.py
  procurement_purchase_no_grouping/__manifest__.py
  procurement_purchase_no_grouping/i18n/de.po
  procurement_purchase_no_grouping/i18n/es.po
  procurement_purchase_no_grouping/i18n/es_ES.po
  procurement_purchase_no_grouping/i18n/es_MX.po
  procurement_purchase_no_grouping/i18n/es_PE.po
  procurement_purchase_no_grouping/i18n/fi.po
  procurement_purchase_no_grouping/i18n/fr.po
  procurement_purchase_no_grouping/i18n/fr_BE.po
  procurement_purchase_no_grouping/i18n/fr_FR.po
  procurement_purchase_no_grouping/i18n/gl.po
  procurement_purchase_no_grouping/i18n/hr.po
  procurement_purchase_no_grouping/i18n/it.po
  procurement_purchase_no_grouping/i18n/nl.po
  procurement_purchase_no_grouping/i18n/nl_NL.po
  procurement_purchase_no_grouping/i18n/procurement_purchase_no_grouping.pot
  procurement_purchase_no_grouping/i18n/pt_BR.po
  procurement_purchase_no_grouping/i18n/pt_PT.po
  procurement_purchase_no_grouping/i18n/ro.po
  procurement_purchase_no_grouping/i18n/sl.po
  procurement_purchase_no_grouping/i18n/tr_TR.po
  procurement_purchase_no_grouping/i18n/vi_VN.po
  procurement_purchase_no_grouping/i18n/zh_CN.po
  procurement_purchase_no_grouping/models/__init__.py
  procurement_purchase_no_grouping/models/procurement_rule.py
  procurement_purchase_no_grouping/models/product_category.py
  procurement_purchase_no_grouping/models/purchase_order.py
  procurement_purchase_no_grouping/readme/CONFIGURE.rst
  procurement_purchase_no_grouping/readme/CONTRIBUTORS.rst
  procurement_purchase_no_grouping/readme/DESCRIPTION.rst
  procurement_purchase_no_grouping/static/description/index.html
  procurement_purchase_no_grouping/tests/__init__.py
  procurement_purchase_no_grouping/tests/test_procurement_purchase_no_grouping.py
  procurement_purchase_no_grouping/views/product_category_view.xml
Labels: needs review

#607 [9.0] purchase_open_qty: fix unit of measure conversion
  purchase_open_qty/models/purchase_order.py
  purchase_open_qty/tests/test_purchase_open_qty.py
Labels: approved, ready to merge
