Repository OCA/purchase-workflow, pull requests merged in 2018-12, with the labels that each got.

#615 [12.0][MIG] purchase_order_archive
  purchase_order_archive/README.rst
  purchase_order_archive/__init__.py
  purchase_order_archive/__manifest__.py
  purchase_order_archive/i18n/purchase_order_archive.pot
  purchase_order_archive/models/__init__.py
  purchase_order_archive/models/purchase_order.py
  purchase_order_archive/readme/CONTRIBUTORS.rst
  purchase_order_archive/readme/DESCRIPTION.rst
  purchase_order_archive/readme/USAGE.rst
  purchase_order_archive/static/description/icon.png
  purchase_order_archive/static/description/index.html
  purchase_order_archive/views/purchase_order.xml
Labels: approved, needs review, ready to merge

#618 [12.0][MIG] purchase_delivery_split_date
  purchase_delivery_split_date/README.rst
  purchase_delivery_split_date/__init__.py
  purchase_delivery_split_date/__manifest__.py
  purchase_delivery_split_date/i18n/ca.po
  purchase_delivery_split_date/i18n/de.po
  purchase_delivery_split_date/i18n/es.po
  purchase_delivery_split_date/i18n/es_MX.po
  purchase_delivery_split_date/i18n/es_PE.po
  purchase_delivery_split_date/i18n/fi.po
  purchase_delivery_split_date/i18n/fr.po
  purchase_delivery_split_date/i18n/gl.po
  purchase_delivery_split_date/i18n/hr.po
  purchase_delivery_split_date/i18n/it.po
  purchase_delivery_split_date/i18n/nl_NL.po
  purchase_delivery_split_date/i18n/pt_BR.po
  purchase_delivery_split_date/i18n/pt_PT.po
  purchase_delivery_split_date/i18n/purchase_delivery_split_date.pot
  purchase_delivery_split_date/i18n/ro.po
  purchase_delivery_split_date/i18n/sl.po
  purchase_delivery_split_date/models/__init__.py
  purchase_delivery_split_date/models/purchase.py
  purchase_delivery_split_date/readme/CONTRIBUTORS.rst
  purchase_delivery_split_date/readme/DESCRIPTION.rst
  purchase_delivery_split_date/readme/HISTORY.rst
  purchase_delivery_split_date/readme/USAGE.rst
  purchase_delivery_split_date/static/description/index.html
  purchase_delivery_split_date/static/description/split_delivery.png
  purchase_delivery_split_date/tests/__init__.py
  purchase_delivery_split_date/tests/test_purchase_delivery.py
Labels: approved, ready to merge

#620 [MIG] purchase_order_line_description: Migration to 11.0
  purchase_order_line_description/README.rst
  purchase_order_line_description/__init__.py
  purchase_order_line_description/__manifest__.py
  purchase_order_line_description/i18n/de.po
  purchase_order_line_description/i18n/es.po
  purchase_order_line_description/i18n/es_MX.po
  purchase_order_line_description/i18n/fi.po
  purchase_order_line_description/i18n/fr.po
  purchase_order_line_description/i18n/it.po
  purchase_order_line_description/i18n/nl_NL.po
  purchase_order_line_description/i18n/pt_BR.po
  purchase_order_line_description/i18n/pt_PT.po
  purchase_order_line_description/i18n/purchase_order_line_description.pot
  purchase_order_line_description/i18n/ro.po
  purchase_order_line_description/i18n/sl.po
  purchase_order_line_description/models/__init__.py
  purchase_order_line_description/models/purchase_order_line.py
  purchase_order_line_description/models/res_config_settings.py
  purchase_order_line_description/readme/CONFIGURE.rst
  purchase_order_line_description/readme/CONTRIBUTORS.rst
  purchase_order_line_description/readme/DESCRIPTION.rst
  purchase_order_line_description/readme/USAGE.rst
  purchase_order_line_description/security/res_groups_security.xml
  purchase_order_line_description/static/description/icon.png
  purchase_order_line_description/static/description/index.html
  purchase_order_line_description/tests/__init__.py
  purchase_order_line_description/tests/test_purchase_order_line_description.py
  purchase_order_line_description/views/purchase_config_settings_view.xml
Labels: approved, needs review
