Repository OCA/purchase-workflow, pull requests merged in 2019-10, with the labels that each got.

#709 [10.0][ENH]better extensibility for messages in purchase requests
  purchase_request_to_rfq/models/purchase_order.py
  purchase_request_to_rfq/models/stock.py
Labels: approved

#711 [11.0][FIX]reception notification in purchase_request is not triggered
  purchase_request/models/stock_picking.py
Labels: approved, ready to merge

#757 [12.0][FIX]allocation creation when min_qty is greater than qty requested
  purchase_request/security/ir.model.access.csv
  purchase_request/tests/test_purchase_request_allocation.py
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: approved

#760 [12.0][FIX] purchase_request: Don't copy allocation information on duplication
  purchase_request/models/purchase_order.py
Labels: approved

#694 [12.0][ADD] purchase_deposit
  purchase_deposit/__init__.py
  purchase_deposit/__manifest__.py
  purchase_deposit/models/__init__.py
  purchase_deposit/models/invoice.py
  purchase_deposit/models/purchase.py
  purchase_deposit/models/res_config_settings.py
  purchase_deposit/readme/CONFIGURATION.rst
  purchase_deposit/readme/CONTRIBUTORS.rst
  purchase_deposit/readme/DESCRIPTION.rst
  purchase_deposit/readme/USAGE.rst
  purchase_deposit/tests/__init__.py
  purchase_deposit/tests/test_purchase_deposit.py
  purchase_deposit/views/purchase_view.xml
  purchase_deposit/views/res_config_settings_views.xml
  purchase_deposit/wizard/__init__.py
  purchase_deposit/wizard/purchase_make_invoice_advance.py
  purchase_deposit/wizard/purchase_make_invoice_advance_views.xml
Labels: approved, ready to merge

#738 [11.0][FIX] purchase_request: _action_cancel mail activity
  purchase_request/models/stock_move.py
  purchase_request/models/stock_picking.py
Labels: approved

#651 [10][IMP] purchase_request_to_rfq (add currency and payment term)
  purchase_request_to_rfq/README.rst
  purchase_request_to_rfq/__manifest__.py
  purchase_request_to_rfq/wizard/purchase_request_line_make_purchase_order.py
Labels: approved, ready to merge

#739 [12.0][ADD] purchase_invoice_plan
  purchase_invoice_plan/__init__.py
  purchase_invoice_plan/__manifest__.py
  purchase_invoice_plan/models/__init__.py
  purchase_invoice_plan/models/purchase.py
  purchase_invoice_plan/readme/CONTRIBUTORS.rst
  purchase_invoice_plan/readme/DESCRIPTION.rst
  purchase_invoice_plan/readme/USAGE.rst
  purchase_invoice_plan/security/ir.model.access.csv
  purchase_invoice_plan/static/description/index.html
  purchase_invoice_plan/tests/__init__.py
  purchase_invoice_plan/tests/test_purchase_invoice_plan.py
  purchase_invoice_plan/views/purchase_view.xml
  purchase_invoice_plan/wizard/__init__.py
  purchase_invoice_plan/wizard/purchase_create_invoice_plan.py
  purchase_invoice_plan/wizard/purchase_create_invoice_plan_view.xml
  purchase_invoice_plan/wizard/purchase_make_planned_invoice.py
  purchase_invoice_plan/wizard/purchase_make_planned_invoice_view.xml
Labels: approved, ready to merge

#767 [12.0][ADD] purchase_requisition_tier_validation
  purchase_requisition_tier_validation/README.rst
  purchase_requisition_tier_validation/__init__.py
  purchase_requisition_tier_validation/__manifest__.py
  purchase_requisition_tier_validation/models/__init__.py
  purchase_requisition_tier_validation/models/purchase_requisition.py
  purchase_requisition_tier_validation/models/tier_definition.py
  purchase_requisition_tier_validation/readme/CONFIGURE.rst
  purchase_requisition_tier_validation/readme/CONTRIBUTORS.rst
  purchase_requisition_tier_validation/readme/DESCRIPTION.rst
  purchase_requisition_tier_validation/readme/INSTALL.rst
  purchase_requisition_tier_validation/readme/USAGE.rst
  purchase_requisition_tier_validation/static/description/icon.png
  purchase_requisition_tier_validation/static/description/index.html
  purchase_requisition_tier_validation/tests/__init__.py
  purchase_requisition_tier_validation/tests/test_purchase_requisition_tier_validation.py
  purchase_requisition_tier_validation/views/purchase_requisition_view.xml
Labels: approved, needs review, ready to merge

#781 [12.0][UPD] *: adapt icons to font-awesome
  purchase_exception/views/purchase_view.xml
  purchase_landed_cost/views/purchase_cost_distribution_view.xml
  purchase_request/views/purchase_request_view.xml
Labels: approved
