Repository OCA/purchase-workflow, pull requests merged in 2019-02, with the labels that each got.

#646 [11.0][IMP] purchase_request. Improve searching
  purchase_request/__manifest__.py
  purchase_request/models/purchase_request.py
  purchase_request/views/purchase_request_view.xml
Labels: approved

#648 [11.0][FIX]purchase_request
  purchase_request/models/purchase_request.py
Labels: approved, needs review

#627 [11.0] purchase_request_product_usage
  purchase_request_product_usage/README.rst
  purchase_request_product_usage/__init__.py
  purchase_request_product_usage/__manifest__.py
  purchase_request_product_usage/models/__init__.py
  purchase_request_product_usage/models/purchase_request.py
  purchase_request_product_usage/readme/CONTRIBUTORS.rst
  purchase_request_product_usage/readme/DESCRIPTION.rst
  purchase_request_product_usage/readme/USAGE.rst
  purchase_request_product_usage/security/ir.model.access.csv
  purchase_request_product_usage/static/description/icon.png
  purchase_request_product_usage/static/description/index.html
  purchase_request_product_usage/tests/__init__.py
  purchase_request_product_usage/tests/test_purchase_request_product_usage.py
  purchase_request_product_usage/views/purchase_request_view.xml
  purchase_request_product_usage/wizards/__init__.py
  purchase_request_product_usage/wizards/purchase_request_line_make_purchase_order.py
  purchase_request_product_usage/wizards/purchase_request_line_make_purchase_order_view.xml
Labels: approved, ready to merge

#612 [ADD] purchase_order_line_deep_sort: new module
  purchase_order_line_deep_sort/README.rst
  purchase_order_line_deep_sort/__init__.py
  purchase_order_line_deep_sort/__manifest__.py
  purchase_order_line_deep_sort/i18n/es.po
  purchase_order_line_deep_sort/i18n/purchase_order_line_deep_sort.pot
  purchase_order_line_deep_sort/models/__init__.py
  purchase_order_line_deep_sort/models/purchase_order.py
  purchase_order_line_deep_sort/models/res_company.py
  purchase_order_line_deep_sort/models/res_config_settings.py
  purchase_order_line_deep_sort/readme/CONFIGURE.rst
  purchase_order_line_deep_sort/readme/CONTRIBUTORS.rst
  purchase_order_line_deep_sort/readme/DESCRIPTION.rst
  purchase_order_line_deep_sort/readme/ROADMAP.rst
  purchase_order_line_deep_sort/readme/USAGE.rst
  purchase_order_line_deep_sort/static/description/index.html
  purchase_order_line_deep_sort/tests/__init__.py
  purchase_order_line_deep_sort/tests/test_purchase_order_line_deep_sort.py
  purchase_order_line_deep_sort/views/purchase_order_views.xml
  purchase_order_line_deep_sort/views/res_config_settings_views.xml
Labels: approved
