Repository OCA/purchase-workflow, pull requests merged in 2019-11, with the labels that each got.

#786 [11.0][FIX] purchase_order_product_recommendation: performance
  purchase_order_product_recommendation/wizards/purchase_order_recommendation.py
Labels: approved

#788 [12.0][FIX] purchase_delivery_split_date: date_planned is datetime
  purchase_delivery_split_date/models/purchase.py
Labels: approved

#784 [12.0][FIX] purchase_request: singleton error on cancel po
  purchase_request/models/purchase_order.py
Labels: approved, needs review

#659 [10.0][IMP]purchase_request
  purchase_request/__manifest__.py
  purchase_request/models/purchase_request.py
  purchase_request/views/purchase_request_view.xml
  purchase_request_procurement/__manifest__.py
  purchase_request_procurement/migrations/10.0.1.1.0/post-migration.py
  purchase_request_procurement/models/procurement_order.py
  purchase_request_procurement/models/purchase_request.py
  purchase_request_procurement/tests/test_purchase_request_procurement.py
  purchase_request_procurement/views/purchase_request_view.xml
  purchase_request_to_rfq/__manifest__.py
  purchase_request_to_rfq/views/purchase_order_view.xml
Labels: approved

#790 [11.0][ADD] purchase_stock_price_unit_sync: Update cost price in stock…
  purchase_stock_price_unit_sync/README.rst
  purchase_stock_price_unit_sync/__init__.py
  purchase_stock_price_unit_sync/__manifest__.py
  purchase_stock_price_unit_sync/models/__init__.py
  purchase_stock_price_unit_sync/models/purchase_order.py
  purchase_stock_price_unit_sync/readme/CONTRIBUTORS.rst
  purchase_stock_price_unit_sync/readme/DESCRIPTION.rst
  purchase_stock_price_unit_sync/static/description/icon.png
  purchase_stock_price_unit_sync/static/description/index.html
  purchase_stock_price_unit_sync/tests/__init__.py
  purchase_stock_price_unit_sync/tests/test_purchase_stock_price_unit_sync.py
Labels: approved

#671 [FIX] 10.0 purchase_request_to_rfq: linked procurements
  purchase_request_to_rfq/wizard/purchase_request_line_make_purchase_order.py
Labels: approved

#726 [ADD] purchase_exception: migration script to v12
  purchase_exception/migrations/12.0.1.0.1/noupdate_changes.xml
  purchase_exception/migrations/12.0.1.0.1/post-migration.py
Labels: approved, needs review, ready to merge

#791 [12.0][FIX] purchase_request: allocations
  purchase_request/migrations/12.0.1.0.0/post-migration.py
  purchase_request/models/purchase_order.py
  purchase_request/models/purchase_request_allocation.py
  purchase_request/models/purchase_request_line.py
  purchase_request/models/stock_move.py
  purchase_request/models/stock_move_line.py
  purchase_request/readme/CONFIGURE.rst
  purchase_request/tests/test_purchase_request_allocation.py
  purchase_request/tests/test_purchase_request_to_rfq.py
  purchase_request/views/purchase_request_line_view.xml
  purchase_request/views/stock_move_views.xml
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: approved, needs review, ready to merge

#796 [12.0][FIX]purchase_request migration to 12.0
  purchase_request/migrations/12.0.1.0.0/post-migration.py
Labels: approved

#800 [12.0][purchase_line_procurement_group] fixes an error that prevented confirming a PO when a product and a service was included
  purchase_line_procurement_group/models/purchase.py
Labels: approved

#761 [12.0][IMP] purchase_request: store preferred supplier
  purchase_request/models/purchase_request_line.py
Labels: approved, ready to merge

#802 [11.0][FIX] purchase_line_procurement_group (backport)
  purchase_line_procurement_group/models/purchase.py
Labels: approved

#807 [IMP] purchase_order_product_recommendation: Duplicity products with default code to avoid crash tests with product_code_unique module installed
  purchase_order_product_recommendation/tests/test_recommendation.py
Labels: approved

#805 [IMP] purchase_order_product_recommendation: extra filters
  purchase_order_product_recommendation/i18n/es.po
  purchase_order_product_recommendation/i18n/purchase_order_product_recommendation.pot
  purchase_order_product_recommendation/readme/USAGE.rst
  purchase_order_product_recommendation/tests/test_recommendation.py
  purchase_order_product_recommendation/wizards/purchase_order_recommendation.py
  purchase_order_product_recommendation/wizards/purchase_order_recommendation_view.xml
Labels: approved

#809 [FIX] purchase_order_product_recommendation: tests
  purchase_order_product_recommendation/tests/test_recommendation.py
Labels: approved
