Repository OCA/purchase-workflow, pull requests merged in 2020-05, with the labels that each got.

#908 [12.0] Add module purchase_reception_status
  purchase_reception_status/__init__.py
  purchase_reception_status/__manifest__.py
  purchase_reception_status/models/__init__.py
  purchase_reception_status/models/purchase_order.py
  purchase_reception_status/readme/CONTRIBUTORS.rst
  purchase_reception_status/readme/DESCRIPTION.rst
  purchase_reception_status/readme/USAGE.rst
  purchase_reception_status/views/purchase_order.xml
Labels: approved, bot is merging ⏳

#907 [12.0][FIX] purchase_landed_cost : fix flake8 before other PR
  purchase_landed_cost/models/purchase_cost_distribution.py
Labels: approved, bot is merging ⏳

#902 [12.0][FIX] purchase_open_qty
  purchase_open_qty/readme/CONTRIBUTORS.rst
  purchase_open_qty/views/purchase_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#910 [11.0][FIX] purchase_open_qty: not able to filter by pending/receiving quan…
  purchase_open_qty/readme/CONTRIBUTORS.rst
  purchase_open_qty/views/purchase_view.xml
Labels: approved, bot is merging ⏳

#914 [13.0][FIX] purchase_order_product_recommendation: Greenify CI
  purchase_order_product_recommendation/wizards/purchase_order_recommendation.py
Labels: bot is merging ⏳

#913 [13.0][FIX] purchase_open_quantity
  purchase_open_qty/readme/CONTRIBUTORS.rst
  purchase_open_qty/views/purchase_view.xml
Labels: approved, bot is merging ⏳

#900 [13.0][MIG] purchase_delivery_split_date
  purchase_delivery_split_date/README.rst
  purchase_delivery_split_date/__init__.py
  purchase_delivery_split_date/__manifest__.py
  purchase_delivery_split_date/i18n/ca.po
  purchase_delivery_split_date/i18n/de.po
  purchase_delivery_split_date/i18n/es.po
  purchase_delivery_split_date/i18n/es_MX.po
  purchase_delivery_split_date/i18n/es_PE.po
  purchase_delivery_split_date/i18n/fi.po
  purchase_delivery_split_date/i18n/fr.po
  purchase_delivery_split_date/i18n/gl.po
  purchase_delivery_split_date/i18n/hr.po
  purchase_delivery_split_date/i18n/it.po
  purchase_delivery_split_date/i18n/nl_NL.po
  purchase_delivery_split_date/i18n/pt_BR.po
  purchase_delivery_split_date/i18n/pt_PT.po
  purchase_delivery_split_date/i18n/purchase_delivery_split_date.pot
  purchase_delivery_split_date/i18n/ro.po
  purchase_delivery_split_date/i18n/sl.po
  purchase_delivery_split_date/i18n/zh_CN.po
  purchase_delivery_split_date/models/__init__.py
  purchase_delivery_split_date/models/purchase.py
  purchase_delivery_split_date/readme/CONTRIBUTORS.rst
  purchase_delivery_split_date/readme/DESCRIPTION.rst
  purchase_delivery_split_date/readme/HISTORY.rst
  purchase_delivery_split_date/readme/USAGE.rst
  purchase_delivery_split_date/static/description/icon.png
  purchase_delivery_split_date/static/description/index.html
  purchase_delivery_split_date/static/description/split_delivery.png
  purchase_delivery_split_date/tests/__init__.py
  purchase_delivery_split_date/tests/test_purchase_delivery.py
  setup/purchase_delivery_split_date/odoo/addons/purchase_delivery_split_date
  setup/purchase_delivery_split_date/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#906 [13.0] [MIG] supplier_calendar
  setup/supplier_calendar/odoo/addons/supplier_calendar
  setup/supplier_calendar/setup.py
  supplier_calendar/README.rst
  supplier_calendar/__init__.py
  supplier_calendar/__manifest__.py
  supplier_calendar/i18n/supplier_calendar.pot
  supplier_calendar/models/__init__.py
  supplier_calendar/models/product.py
  supplier_calendar/models/purchase.py
  supplier_calendar/models/res_partner.py
  supplier_calendar/models/stock_rule.py
  supplier_calendar/readme/CONFIGURE.rst
  supplier_calendar/readme/CONTRIBUTORS.rst
  supplier_calendar/readme/DESCRIPTION.rst
  supplier_calendar/readme/USAGE.rst
  supplier_calendar/static/description/icon.png
  supplier_calendar/static/description/index.html
  supplier_calendar/tests/__init__.py
  supplier_calendar/tests/test_supplier_calendar.py
  supplier_calendar/views/product_view.xml
  supplier_calendar/views/res_partner_view.xml
Labels: bot is merging ⏳

#909 [13.0][FIX] Invoice tax calculation
  purchase_product_usage/models/account_move.py
Labels: approved, bot is merging ⏳, ready to merge

#916 13.0[MIG] purchase_location_by_line
  purchase_location_by_line/README.rst
  purchase_location_by_line/__init__.py
  purchase_location_by_line/__manifest__.py
  purchase_location_by_line/i18n/ca.po
  purchase_location_by_line/i18n/de.po
  purchase_location_by_line/i18n/es.po
  purchase_location_by_line/i18n/es_MX.po
  purchase_location_by_line/i18n/es_PE.po
  purchase_location_by_line/i18n/fi.po
  purchase_location_by_line/i18n/fr.po
  purchase_location_by_line/i18n/gl.po
  purchase_location_by_line/i18n/hr.po
  purchase_location_by_line/i18n/it.po
  purchase_location_by_line/i18n/nl_NL.po
  purchase_location_by_line/i18n/pt_BR.po
  purchase_location_by_line/i18n/pt_PT.po
  purchase_location_by_line/i18n/purchase_location_by_line.pot
  purchase_location_by_line/i18n/ro.po
  purchase_location_by_line/i18n/sl.po
  purchase_location_by_line/models/__init__.py
  purchase_location_by_line/models/purchase.py
  purchase_location_by_line/models/stock_picking.py
  purchase_location_by_line/readme/CONTRIBUTORS.rst
  purchase_location_by_line/readme/DESCRIPTION.rst
  purchase_location_by_line/static/description/icon.png
  purchase_location_by_line/static/description/index.html
  purchase_location_by_line/tests/__init__.py
  purchase_location_by_line/tests/test_purchase_delivery.py
  purchase_location_by_line/views/purchase_view.xml
  setup/purchase_location_by_line/odoo/addons/purchase_location_by_line
  setup/purchase_location_by_line/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#871 [12.0][ADD] purchase_order_uninvoiced_amount: Show uninvoiced amount on purchase order tree
  purchase_order_uninvoiced_amount/README.rst
  purchase_order_uninvoiced_amount/__init__.py
  purchase_order_uninvoiced_amount/__manifest__.py
  purchase_order_uninvoiced_amount/i18n/en_US.po
  purchase_order_uninvoiced_amount/i18n/es.po
  purchase_order_uninvoiced_amount/i18n/purchase_order_uninvoiced_amount.pot
  purchase_order_uninvoiced_amount/models/__init__.py
  purchase_order_uninvoiced_amount/models/purchase_order.py
  purchase_order_uninvoiced_amount/readme/CONTRIBUTORS.rst
  purchase_order_uninvoiced_amount/readme/DESCRIPTION.rst
  purchase_order_uninvoiced_amount/static/description/icon.png
  purchase_order_uninvoiced_amount/static/description/index.html
  purchase_order_uninvoiced_amount/tests/__init__.py
  purchase_order_uninvoiced_amount/tests/test_purchase_order_uninvoiced_amount.py
  purchase_order_uninvoiced_amount/views/purchase_order_view.xml
Labels: bot is merging ⏳

#915 [13.0][FIX] purchase_deposit
  purchase_deposit/wizard/purchase_make_invoice_advance.py
Labels: approved, bot is merging ⏳, ready to merge
