Repository OCA/purchase-workflow, pull requests merged in 2020-12, with the labels that each got.

#1031 [14.0][MIG] purchase_last_price_info: Migration to 14.0
  purchase_last_price_info/README.rst
  purchase_last_price_info/__init__.py
  purchase_last_price_info/__manifest__.py
  purchase_last_price_info/hooks.py
  purchase_last_price_info/i18n/ca.po
  purchase_last_price_info/i18n/de.po
  purchase_last_price_info/i18n/el_GR.po
  purchase_last_price_info/i18n/es.po
  purchase_last_price_info/i18n/es_ES.po
  purchase_last_price_info/i18n/eu.po
  purchase_last_price_info/i18n/fi.po
  purchase_last_price_info/i18n/fr.po
  purchase_last_price_info/i18n/fr_CH.po
  purchase_last_price_info/i18n/fr_FR.po
  purchase_last_price_info/i18n/gl.po
  purchase_last_price_info/i18n/hr.po
  purchase_last_price_info/i18n/hr_HR.po
  purchase_last_price_info/i18n/it.po
  purchase_last_price_info/i18n/nl.po
  purchase_last_price_info/i18n/nl_NL.po
  purchase_last_price_info/i18n/pt.po
  purchase_last_price_info/i18n/pt_BR.po
  purchase_last_price_info/i18n/purchase_last_price_info.pot
  purchase_last_price_info/i18n/ro.po
  purchase_last_price_info/i18n/ru.po
  purchase_last_price_info/i18n/sk.po
  purchase_last_price_info/i18n/sl.po
  purchase_last_price_info/i18n/tr.po
  purchase_last_price_info/i18n/tr_TR.po
  purchase_last_price_info/i18n/vi_VN.po
  purchase_last_price_info/i18n/zh_CN.po
  purchase_last_price_info/models/__init__.py
  purchase_last_price_info/models/product.py
  purchase_last_price_info/models/purchase.py
  purchase_last_price_info/readme/CONTRIBUTORS.rst
  purchase_last_price_info/readme/DESCRIPTION.rst
  purchase_last_price_info/readme/USAGE.rst
  purchase_last_price_info/static/description/icon.png
  purchase_last_price_info/static/description/index.html
  purchase_last_price_info/static/description/purchase_last_price.png
  purchase_last_price_info/tests/__init__.py
  purchase_last_price_info/tests/test_purchase_last_price_info.py
  purchase_last_price_info/views/product_views.xml
Labels: approved, bot is merging ⏳

#1003 [14.0][MIG] purchase_tier_validation
  purchase_tier_validation/__init__.py
  purchase_tier_validation/__manifest__.py
  purchase_tier_validation/i18n/es.po
  purchase_tier_validation/i18n/purchase_tier_validation.pot
  purchase_tier_validation/i18n/zh_CN.po
  purchase_tier_validation/models/__init__.py
  purchase_tier_validation/models/purchase_order.py
  purchase_tier_validation/models/tier_definition.py
  purchase_tier_validation/readme/CONFIGURE.rst
  purchase_tier_validation/readme/CONTRIBUTORS.rst
  purchase_tier_validation/readme/DESCRIPTION.rst
  purchase_tier_validation/readme/INSTALL.rst
  purchase_tier_validation/readme/USAGE.rst
  purchase_tier_validation/static/description/icon.png
  purchase_tier_validation/tests/__init__.py
  purchase_tier_validation/tests/common.py
  purchase_tier_validation/tests/test_tier_validation.py
  purchase_tier_validation/tests/tier_validation_tester.py
  purchase_tier_validation/views/purchase_order_view.xml
  setup/purchase_tier_validation/odoo/addons/purchase_tier_validation
  setup/purchase_tier_validation/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1006 [14.0][MIG] purchase_work_acceptance
  purchase_work_acceptance/README.rst
  purchase_work_acceptance/__init__.py
  purchase_work_acceptance/__manifest__.py
  purchase_work_acceptance/data/work_acceptance_sequence.xml
  purchase_work_acceptance/i18n/purchase_work_acceptance.pot
  purchase_work_acceptance/models/__init__.py
  purchase_work_acceptance/models/account_move.py
  purchase_work_acceptance/models/purchase.py
  purchase_work_acceptance/models/res_config_settings.py
  purchase_work_acceptance/models/stock_picking.py
  purchase_work_acceptance/models/work_acceptance.py
  purchase_work_acceptance/readme/CONFIGURE.rst
  purchase_work_acceptance/readme/CONTRIBUTORS.rst
  purchase_work_acceptance/readme/DESCRIPTION.rst
  purchase_work_acceptance/readme/USAGE.rst
  purchase_work_acceptance/security/ir.model.access.csv
  purchase_work_acceptance/security/security.xml
  purchase_work_acceptance/static/description/icon.png
  purchase_work_acceptance/static/description/index.html
  purchase_work_acceptance/tests/__init__.py
  purchase_work_acceptance/tests/test_purchase_work_acceptance.py
  purchase_work_acceptance/views/account_move_views.xml
  purchase_work_acceptance/views/purchase_views.xml
  purchase_work_acceptance/views/res_config_settings_views.xml
  purchase_work_acceptance/views/stock_picking_views.xml
  purchase_work_acceptance/views/work_acceptance_views.xml
  purchase_work_acceptance/wizard/__init__.py
  purchase_work_acceptance/wizard/select_work_acceptance_wizard.py
  purchase_work_acceptance/wizard/select_work_acceptance_wizard_views.xml
  setup/purchase_work_acceptance/odoo/addons/purchase_work_acceptance
  setup/purchase_work_acceptance/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1036 [13.0][FIX] purchase_isolated_rfq, fix cancel error
  purchase_isolated_rfq/views/purchase_views.xml
Labels: bot is merging ⏳

#1011 [13.0][ADD] purchase_tier_validation_forward
  purchase_tier_validation_forward/__init__.py
  purchase_tier_validation_forward/__manifest__.py
  purchase_tier_validation_forward/readme/CONFIGURE.rst
  purchase_tier_validation_forward/readme/CONTRIBUTORS.rst
  purchase_tier_validation_forward/readme/DESCRIPTION.rst
  purchase_tier_validation_forward/readme/INSTALL.rst
  purchase_tier_validation_forward/static/description/icon.png
  purchase_tier_validation_forward/views/purchase_order_view.xml
  setup/purchase_tier_validation_forward/odoo/addons/purchase_tier_validation_forward
  setup/purchase_tier_validation_forward/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#965 [13.0] [MIG] purchase all shipments
  purchase_all_shipments/README.rst
  purchase_all_shipments/__init__.py
  purchase_all_shipments/__manifest__.py
  purchase_all_shipments/i18n/es.po
  purchase_all_shipments/i18n/purchase_all_shipments.pot
  purchase_all_shipments/models/__init__.py
  purchase_all_shipments/models/purchase_order.py
  purchase_all_shipments/readme/CONTRIBUTORS.rst
  purchase_all_shipments/readme/DESCRIPTION.rst
  purchase_all_shipments/static/description/icon.png
  purchase_all_shipments/tests/__init__.py
  purchase_all_shipments/tests/test_three_step_reception.py
  purchase_all_shipments/views/purchase_order_views.xml
  setup/purchase_all_shipments/odoo/addons/purchase_all_shipments
  setup/purchase_all_shipments/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1045 [13.0][FIX] purchase_manual_currency: Misspell "refrese" should be "refresh"
  purchase_manual_currency/models/purchase.py
  purchase_manual_currency/tests/test_purchase_manual_currency.py
  purchase_manual_currency/views/purchase_views.xml
Labels: bot is merging ⏳

#1048 [IMP] purchase_order_secondary_unit: more clear string field
  purchase_order_secondary_unit/i18n/es.po
  purchase_order_secondary_unit/i18n/purchase_order_secondary_unit.pot
  purchase_order_secondary_unit/models/product_template.py
Labels: approved, bot is merging ⏳

#1051 UPD travis to recent config
  .travis.yml
Labels: approved, bot is merging ⏳

#1047 [12.0][FIX] purchase_discount
  purchase_discount/views/report_purchaseorder.xml
Labels: approved, bot is merging ⏳, ready to merge

#1028 [14.0][MIG] purchase_delivery_split_date
  purchase_delivery_split_date/README.rst
  purchase_delivery_split_date/__init__.py
  purchase_delivery_split_date/__manifest__.py
  purchase_delivery_split_date/i18n/ca.po
  purchase_delivery_split_date/i18n/de.po
  purchase_delivery_split_date/i18n/es.po
  purchase_delivery_split_date/i18n/es_MX.po
  purchase_delivery_split_date/i18n/es_PE.po
  purchase_delivery_split_date/i18n/fi.po
  purchase_delivery_split_date/i18n/fr.po
  purchase_delivery_split_date/i18n/gl.po
  purchase_delivery_split_date/i18n/hr.po
  purchase_delivery_split_date/i18n/it.po
  purchase_delivery_split_date/i18n/nl_NL.po
  purchase_delivery_split_date/i18n/pt_BR.po
  purchase_delivery_split_date/i18n/pt_PT.po
  purchase_delivery_split_date/i18n/purchase_delivery_split_date.pot
  purchase_delivery_split_date/i18n/ro.po
  purchase_delivery_split_date/i18n/sl.po
  purchase_delivery_split_date/i18n/zh_CN.po
  purchase_delivery_split_date/models/__init__.py
  purchase_delivery_split_date/models/purchase.py
  purchase_delivery_split_date/readme/CONTRIBUTORS.rst
  purchase_delivery_split_date/readme/DESCRIPTION.rst
  purchase_delivery_split_date/readme/HISTORY.rst
  purchase_delivery_split_date/readme/USAGE.rst
  purchase_delivery_split_date/static/description/icon.png
  purchase_delivery_split_date/static/description/index.html
  purchase_delivery_split_date/static/description/split_delivery.png
  purchase_delivery_split_date/tests/__init__.py
  purchase_delivery_split_date/tests/test_purchase_delivery.py
  setup/purchase_delivery_split_date/odoo/addons/purchase_delivery_split_date
  setup/purchase_delivery_split_date/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1056 [12.0][IMP] purchase_order_uninvoiced_amount: the amount depends on the invoice policy of the products.
  purchase_order_uninvoiced_amount/README.rst
  purchase_order_uninvoiced_amount/models/purchase_order.py
  purchase_order_uninvoiced_amount/readme/CONTRIBUTORS.rst
  purchase_order_uninvoiced_amount/static/description/index.html
  purchase_order_uninvoiced_amount/tests/test_purchase_order_uninvoiced_amount.py
Labels: approved, bot is merging ⏳, ready to merge
