Repository OCA/purchase-workflow, pull requests merged in 2020-06, with the labels that each got.

#919 [MIG] purchase_order_line_deep_sort: Migration to 13.0
  purchase_order_line_deep_sort/README.rst
  purchase_order_line_deep_sort/__init__.py
  purchase_order_line_deep_sort/__manifest__.py
  purchase_order_line_deep_sort/i18n/es.po
  purchase_order_line_deep_sort/i18n/purchase_order_line_deep_sort.pot
  purchase_order_line_deep_sort/models/__init__.py
  purchase_order_line_deep_sort/models/purchase_order.py
  purchase_order_line_deep_sort/models/res_company.py
  purchase_order_line_deep_sort/models/res_config_settings.py
  purchase_order_line_deep_sort/readme/CONFIGURE.rst
  purchase_order_line_deep_sort/readme/CONTRIBUTORS.rst
  purchase_order_line_deep_sort/readme/DESCRIPTION.rst
  purchase_order_line_deep_sort/readme/ROADMAP.rst
  purchase_order_line_deep_sort/readme/USAGE.rst
  purchase_order_line_deep_sort/static/description/icon.png
  purchase_order_line_deep_sort/static/description/index.html
  purchase_order_line_deep_sort/tests/__init__.py
  purchase_order_line_deep_sort/tests/test_purchase_order_line_deep_sort.py
  purchase_order_line_deep_sort/views/purchase_order_views.xml
  purchase_order_line_deep_sort/views/res_config_settings_views.xml
  setup/purchase_order_line_deep_sort/odoo/addons/purchase_order_line_deep_sort
  setup/purchase_order_line_deep_sort/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#903 [13.0][ADD] purchase_order_line_packaging_qty
  purchase_order_line_packaging_qty/__init__.py
  purchase_order_line_packaging_qty/__manifest__.py
  purchase_order_line_packaging_qty/models/__init__.py
  purchase_order_line_packaging_qty/models/purchase_order_line.py
  purchase_order_line_packaging_qty/readme/CONTRIBUTORS.rst
  purchase_order_line_packaging_qty/readme/DESCRIPTION.rst
  purchase_order_line_packaging_qty/tests/__init__.py
  purchase_order_line_packaging_qty/tests/test_purchase_order_line_packaging_qty.py
  purchase_order_line_packaging_qty/views/purchase_order.xml
Labels: approved, bot is merging ⏳

#925 [FIX] purchase_discount: set currency rate correctly
  purchase_discount/tests/test_purchase_discount.py
Labels: bot is merging ⏳

#926 [13.0] [FIX] purchase_discount: set currency rate correctly
  purchase_discount/tests/test_purchase_discount.py
Labels: bot is merging ⏳

#921 [13.0][IMP] purchase_order_line_packaging_qty: allow to set packaging from a procurement.
  purchase_order_line_packaging_qty/models/__init__.py
  purchase_order_line_packaging_qty/models/stock_rule.py
Labels: approved, bot is merging ⏳

#924 [13.0] [FIX] purchase_request: disable creation from form view
  purchase_request/views/purchase_request_line_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#905 [IMP] [12.0] purchase_delivery_split_date
  purchase_delivery_split_date/__manifest__.py
  purchase_delivery_split_date/models/purchase.py
  purchase_delivery_split_date/readme/HISTORY.rst
Labels: approved, bot is merging ⏳, ready to merge

#923 [12.0] [FIX] purchase_request: disable creation from form view
  purchase_request/views/purchase_request_line_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#929 [FIX] purchase_triple_discount: bad display of discounts 2 and 3 in supplierinfo form view
  purchase_triple_discount/views/product_supplierinfo_view.xml
Labels: approved, bot is merging ⏳

#931 [13.0][FIX] purchase_order_line_packaging_qty: Make packaging optional
  purchase_order_line_packaging_qty/models/purchase_order_line.py
Labels: approved, bot is merging ⏳

#928 [ADD] purchase_delays
  supplier_calendar/tests/test_supplier_calendar.py
  vendor_transport_lead_time/README.rst
  vendor_transport_lead_time/__init__.py
  vendor_transport_lead_time/__manifest__.py
  vendor_transport_lead_time/models/__init__.py
  vendor_transport_lead_time/models/product_supplierinfo.py
  vendor_transport_lead_time/readme/DESCRIPTION.rst
  vendor_transport_lead_time/readme/HISTORY.rst
  vendor_transport_lead_time/static/description/icon.png
  vendor_transport_lead_time/static/description/index.html
  vendor_transport_lead_time/tests/__init__.py
  vendor_transport_lead_time/tests/test_delay.py
  vendor_transport_lead_time/views/product_supplierinfo.xml
Labels: approved, bot is merging ⏳, ready to merge
