Repository OCA/purchase-workflow, pull requests merged in 2020-02, with the labels that each got.

#853 [13.0][FIX] purchase_request: Proper Run Buy implementation
  purchase_request/README.rst
  purchase_request/__manifest__.py
  purchase_request/data/purchase_request_data.xml
  purchase_request/data/purchase_request_sequence.xml
  purchase_request/demo/purchase_request_demo.xml
  purchase_request/models/orderpoint.py
  purchase_request/models/product_template.py
  purchase_request/models/purchase_order.py
  purchase_request/models/purchase_request.py
  purchase_request/models/purchase_request_allocation.py
  purchase_request/models/purchase_request_line.py
  purchase_request/models/stock_move.py
  purchase_request/models/stock_move_line.py
  purchase_request/models/stock_picking.py
  purchase_request/models/stock_rule.py
  purchase_request/readme/CONTRIBUTORS.rst
  purchase_request/reports/report_purchase_request.xml
  purchase_request/security/purchase_request.xml
  purchase_request/static/description/index.html
  purchase_request/tests/test_purchase_request.py
  purchase_request/tests/test_purchase_request_allocation.py
  purchase_request/tests/test_purchase_request_procurement.py
  purchase_request/tests/test_purchase_request_to_rfq.py
  purchase_request/views/product_template.xml
  purchase_request/views/purchase_order_view.xml
  purchase_request/views/purchase_request_line_view.xml
  purchase_request/views/purchase_request_report.xml
  purchase_request/views/purchase_request_view.xml
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
  purchase_request/wizard/purchase_request_line_make_purchase_order_view.xml
Labels: approved, needs review, ready to merge

#857 [11.0][ADD] purchase_representative
  purchase_representative/README.rst
  purchase_representative/__init__.py
  purchase_representative/__manifest__.py
  purchase_representative/hooks.py
  purchase_representative/models/__init__.py
  purchase_representative/models/procurement_rule.py
  purchase_representative/models/purchase_order.py
  purchase_representative/readme/CONTRIBUTORS.rst
  purchase_representative/readme/DESCRIPTION.rst
  purchase_representative/readme/ROADMAP.rst
  purchase_representative/readme/USAGE.rst
  purchase_representative/static/description/icon.png
  purchase_representative/static/description/index.html
  purchase_representative/views/purchase_order_view.xml
Labels: approved, ready to merge

#859 [13.0][MIG] procurement_purchase_no_grouping: Migration to 13.0
  procurement_purchase_no_grouping/README.rst
  procurement_purchase_no_grouping/__init__.py
  procurement_purchase_no_grouping/__manifest__.py
  procurement_purchase_no_grouping/i18n/de.po
  procurement_purchase_no_grouping/i18n/es.po
  procurement_purchase_no_grouping/i18n/es_ES.po
  procurement_purchase_no_grouping/i18n/es_MX.po
  procurement_purchase_no_grouping/i18n/es_PE.po
  procurement_purchase_no_grouping/i18n/fi.po
  procurement_purchase_no_grouping/i18n/fr.po
  procurement_purchase_no_grouping/i18n/fr_BE.po
  procurement_purchase_no_grouping/i18n/fr_FR.po
  procurement_purchase_no_grouping/i18n/gl.po
  procurement_purchase_no_grouping/i18n/hr.po
  procurement_purchase_no_grouping/i18n/it.po
  procurement_purchase_no_grouping/i18n/nl.po
  procurement_purchase_no_grouping/i18n/nl_NL.po
  procurement_purchase_no_grouping/i18n/procurement_purchase_no_grouping.pot
  procurement_purchase_no_grouping/i18n/pt_BR.po
  procurement_purchase_no_grouping/i18n/pt_PT.po
  procurement_purchase_no_grouping/i18n/ro.po
  procurement_purchase_no_grouping/i18n/sl.po
  procurement_purchase_no_grouping/i18n/tr_TR.po
  procurement_purchase_no_grouping/i18n/vi_VN.po
  procurement_purchase_no_grouping/i18n/zh_CN.po
  procurement_purchase_no_grouping/models/__init__.py
  procurement_purchase_no_grouping/models/product_category.py
  procurement_purchase_no_grouping/models/purchase_order.py
  procurement_purchase_no_grouping/models/stock_rule.py
  procurement_purchase_no_grouping/readme/CONFIGURE.rst
  procurement_purchase_no_grouping/readme/CONTRIBUTORS.rst
  procurement_purchase_no_grouping/readme/DESCRIPTION.rst
  procurement_purchase_no_grouping/static/description/icon.png
  procurement_purchase_no_grouping/static/description/index.html
  procurement_purchase_no_grouping/tests/__init__.py
  procurement_purchase_no_grouping/tests/test_procurement_purchase_no_grouping.py
  procurement_purchase_no_grouping/views/product_category_view.xml
Labels: approved, ready to merge

#835 [12.0] product_supplier_code_purchase
  product_supplier_code_purchase/README.rst
  product_supplier_code_purchase/__init__.py
  product_supplier_code_purchase/__manifest__.py
  product_supplier_code_purchase/i18n/de.po
  product_supplier_code_purchase/i18n/es.po
  product_supplier_code_purchase/i18n/es_MX.po
  product_supplier_code_purchase/i18n/fi.po
  product_supplier_code_purchase/i18n/fr.po
  product_supplier_code_purchase/i18n/it.po
  product_supplier_code_purchase/i18n/nl_NL.po
  product_supplier_code_purchase/i18n/product_supplier_code_purchase.pot
  product_supplier_code_purchase/i18n/pt_BR.po
  product_supplier_code_purchase/i18n/pt_PT.po
  product_supplier_code_purchase/i18n/ro.po
  product_supplier_code_purchase/i18n/sl.po
  product_supplier_code_purchase/models/__init__.py
  product_supplier_code_purchase/models/purchase_order.py
  product_supplier_code_purchase/readme/CONTRIBUTORS.rst
  product_supplier_code_purchase/readme/DESCRIPTION.rst
  product_supplier_code_purchase/readme/USAGE.rst
  product_supplier_code_purchase/static/description/icon.png
  product_supplier_code_purchase/static/description/index.html
  product_supplier_code_purchase/tests/__init__.py
  product_supplier_code_purchase/tests/test_product_supplier_code_purchase.py
  product_supplier_code_purchase/views/purchase_order_view.xml
Labels: approved, ready to merge

#851 [13.0][ADD] purchase_isolated_rfq
  purchase_isolated_rfq/README.rst
  purchase_isolated_rfq/__init__.py
  purchase_isolated_rfq/__manifest__.py
  purchase_isolated_rfq/data/ir_sequence_data.xml
  purchase_isolated_rfq/hooks.py
  purchase_isolated_rfq/models/__init__.py
  purchase_isolated_rfq/models/purchase_order.py
  purchase_isolated_rfq/readme/CONTRIBUTORS.rst
  purchase_isolated_rfq/readme/DESCRIPTION.rst
  purchase_isolated_rfq/readme/USAGE.rst
  purchase_isolated_rfq/static/description/index.html
  purchase_isolated_rfq/tests/__init__.py
  purchase_isolated_rfq/tests/test_purchase_isolated_rfq.py
  purchase_isolated_rfq/views/purchase_views.xml
Labels: approved, ready to merge

#841 [13.0][MIG] purchase_order_secondary_unit
  oca_dependencies.txt
  purchase_order_secondary_unit/README.rst
  purchase_order_secondary_unit/__init__.py
  purchase_order_secondary_unit/__manifest__.py
  purchase_order_secondary_unit/i18n/es.po
  purchase_order_secondary_unit/i18n/purchase_order_secondary_unit.pot
  purchase_order_secondary_unit/models/__init__.py
  purchase_order_secondary_unit/models/product_template.py
  purchase_order_secondary_unit/models/purchase_order.py
  purchase_order_secondary_unit/readme/CONTRIBUTORS.rst
  purchase_order_secondary_unit/readme/DESCRIPTION.rst
  purchase_order_secondary_unit/readme/USAGE.rst
  purchase_order_secondary_unit/static/description/icon.png
  purchase_order_secondary_unit/static/description/index.html
  purchase_order_secondary_unit/tests/__init__.py
  purchase_order_secondary_unit/tests/test_purchase_order_secondary_unit.py
  purchase_order_secondary_unit/views/product_views.xml
  purchase_order_secondary_unit/views/purchase_order_views.xml
Labels: approved, ready to merge

#866 [IMP] purchase_order_product_recommendation: Add 'numeric_step' widget
  purchase_order_product_recommendation/README.rst
  purchase_order_product_recommendation/readme/DESCRIPTION.rst
  purchase_order_product_recommendation/static/description/index.html
  purchase_order_product_recommendation/wizards/purchase_order_recommendation_view.xml
Labels: approved

#228 [9.0] [port] purchase analytic global
  purchase_analytic_global/README.rst
  purchase_analytic_global/__init__.py
  purchase_analytic_global/__openerp__.py
  purchase_analytic_global/i18n/fr.po
  purchase_analytic_global/i18n/purchase_analytic_global.pot
  purchase_analytic_global/models/__init__.py
  purchase_analytic_global/models/purchase.py
  purchase_analytic_global/static/description/icon.png
  purchase_analytic_global/views/purchase.xml
Labels: approved
