Repository OCA/purchase-workflow, pull requests merged in 2020-03, with the labels that each got.

#874 [13.0][MIG] purchase_requisition_tier_validation
  purchase_requisition_tier_validation/README.rst
  purchase_requisition_tier_validation/__init__.py
  purchase_requisition_tier_validation/__manifest__.py
  purchase_requisition_tier_validation/i18n/purchase_requisition_tier_validation.pot
  purchase_requisition_tier_validation/models/__init__.py
  purchase_requisition_tier_validation/models/purchase_requisition.py
  purchase_requisition_tier_validation/models/tier_definition.py
  purchase_requisition_tier_validation/readme/CONFIGURE.rst
  purchase_requisition_tier_validation/readme/CONTRIBUTORS.rst
  purchase_requisition_tier_validation/readme/DESCRIPTION.rst
  purchase_requisition_tier_validation/readme/INSTALL.rst
  purchase_requisition_tier_validation/readme/USAGE.rst
  purchase_requisition_tier_validation/static/description/icon.png
  purchase_requisition_tier_validation/static/description/index.html
  purchase_requisition_tier_validation/tests/__init__.py
  purchase_requisition_tier_validation/tests/test_purchase_requisition_tier_validation.py
  purchase_requisition_tier_validation/views/purchase_requisition_view.xml
Labels: approved

#872 [12.0][FIX] purchase_request: Migration script 11.0 -> 12.0
  purchase_request/migrations/12.0.1.0.0/post-migration.py
Labels: approved, ready to merge

#876 [10.0][ADD] purchase_request - unlink pr and prl only when pr is draft
  purchase_request/models/purchase_request.py
  purchase_request/tests/test_purchase_request.py
Labels: approved

#877 [12.0][FWDPORT] purchase_request - Unlinking of a pr or a prl is only possible if pr is draft
  purchase_request/models/purchase_request.py
  purchase_request/models/purchase_request_line.py
  purchase_request/tests/test_purchase_request.py
Labels: approved, ready to merge

#878 [13.0][FWDPORT] purchase_request - Unlinking of a pr or a prl is only possible if pr is draft
  purchase_request/models/purchase_request.py
  purchase_request/models/purchase_request_line.py
  purchase_request/tests/test_purchase_request.py
Labels: approved, ready to merge

#873 [12.0][FIX] purchase_request: allow Purchase users to see purchase requests
  purchase_request/security/ir.model.access.csv
Labels: approved, ready to merge

#884 [13.0][FWD] purchase_request: allow Purchase users to see purchase re…
  purchase_request/security/ir.model.access.csv
Labels: approved

#861 [13.0][MIG] purchase_deposit
  purchase_deposit/README.rst
  purchase_deposit/__init__.py
  purchase_deposit/__manifest__.py
  purchase_deposit/i18n/purchase_deposit.pot
  purchase_deposit/models/__init__.py
  purchase_deposit/models/purchase.py
  purchase_deposit/models/res_config_settings.py
  purchase_deposit/readme/CONFIGURATION.rst
  purchase_deposit/readme/CONTRIBUTORS.rst
  purchase_deposit/readme/DESCRIPTION.rst
  purchase_deposit/readme/USAGE.rst
  purchase_deposit/static/description/icon.png
  purchase_deposit/static/description/index.html
  purchase_deposit/tests/__init__.py
  purchase_deposit/tests/test_purchase_deposit.py
  purchase_deposit/views/purchase_view.xml
  purchase_deposit/views/res_config_settings_views.xml
  purchase_deposit/wizard/__init__.py
  purchase_deposit/wizard/purchase_make_invoice_advance.py
  purchase_deposit/wizard/purchase_make_invoice_advance_views.xml
  setup/purchase_deposit/odoo/addons/purchase_deposit
  setup/purchase_deposit/setup.py
Labels: approved, ready to merge

#882 [13.0][MIG] purchase_order_product_recommendation : Migration to 13.0
  purchase_order_product_recommendation/README.rst
  purchase_order_product_recommendation/__init__.py
  purchase_order_product_recommendation/__manifest__.py
  purchase_order_product_recommendation/i18n/es.po
  purchase_order_product_recommendation/i18n/purchase_order_product_recommendation.pot
  purchase_order_product_recommendation/readme/CONTRIBUTORS.rst
  purchase_order_product_recommendation/readme/DESCRIPTION.rst
  purchase_order_product_recommendation/readme/USAGE.rst
  purchase_order_product_recommendation/static/description/icon.png
  purchase_order_product_recommendation/static/description/index.html
  purchase_order_product_recommendation/tests/__init__.py
  purchase_order_product_recommendation/tests/test_recommendation.py
  purchase_order_product_recommendation/views/purchase_order_view.xml
  purchase_order_product_recommendation/wizards/__init__.py
  purchase_order_product_recommendation/wizards/purchase_order_recommendation.py
  purchase_order_product_recommendation/wizards/purchase_order_recommendation_view.xml
  purchase_order_product_recommendation_brand/i18n/es.po
  setup/purchase_order_product_recommendation/odoo/addons/purchase_order_product_recommendation
  setup/purchase_order_product_recommendation/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#725 ADD purchase_price_recalculation module
  purchase_price_recalculation/README.rst
  purchase_price_recalculation/__init__.py
  purchase_price_recalculation/__manifest__.py
  purchase_price_recalculation/model/__init__.py
  purchase_price_recalculation/model/purchase_order.py
  purchase_price_recalculation/readme/CONTRIBUTORS.rst
  purchase_price_recalculation/readme/CREDITS.rst
  purchase_price_recalculation/readme/DESCRIPTION.rst
  purchase_price_recalculation/readme/USAGE.rst
  purchase_price_recalculation/static/description/fig1.png
  purchase_price_recalculation/static/description/fig2.png
  purchase_price_recalculation/static/description/icon.png
  purchase_price_recalculation/static/description/index.html
  purchase_price_recalculation/view/actions_server.xml
Labels: approved, bot is merging ⏳
