Repository OCA/purchase-workflow, pull requests merged in 2020-10, with the labels that each got.

#981 [12.0] [MIG] purchase_order_general_discount: Migration to v12.0
  purchase_order_general_discount/README.rst
  purchase_order_general_discount/__init__.py
  purchase_order_general_discount/__manifest__.py
  purchase_order_general_discount/i18n/es.po
  purchase_order_general_discount/i18n/purchase_order_general_discount.pot
  purchase_order_general_discount/models/__init__.py
  purchase_order_general_discount/models/purchase_order.py
  purchase_order_general_discount/models/res_company.py
  purchase_order_general_discount/models/res_config_settings.py
  purchase_order_general_discount/models/res_partner.py
  purchase_order_general_discount/readme/CONFIGURE.rst
  purchase_order_general_discount/readme/CONTRIBUTORS.rst
  purchase_order_general_discount/readme/DESCRIPTION.rst
  purchase_order_general_discount/readme/USAGE.rst
  purchase_order_general_discount/static/description/icon.png
  purchase_order_general_discount/static/description/index.html
  purchase_order_general_discount/tests/__init__.py
  purchase_order_general_discount/tests/test_purchase_order_general_discount.py
  purchase_order_general_discount/views/purchase_order_view.xml
  purchase_order_general_discount/views/res_config_view.xml
  purchase_order_general_discount/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#891 13.0 mig purchase_blanket_order
  purchase_blanket_order/README.rst
  purchase_blanket_order/__init__.py
  purchase_blanket_order/__manifest__.py
  purchase_blanket_order/data/ir_cron.xml
  purchase_blanket_order/data/sequence.xml
  purchase_blanket_order/i18n/purchase_blanket_order.pot
  purchase_blanket_order/models/__init__.py
  purchase_blanket_order/models/blanket_orders.py
  purchase_blanket_order/models/purchase_config_settings.py
  purchase_blanket_order/models/purchase_order.py
  purchase_blanket_order/readme/CONTRIBUTORS.rst
  purchase_blanket_order/readme/DESCRIPTION.rst
  purchase_blanket_order/readme/USAGE.rst
  purchase_blanket_order/report/report.xml
  purchase_blanket_order/report/templates.xml
  purchase_blanket_order/security/ir.model.access.csv
  purchase_blanket_order/security/security.xml
  purchase_blanket_order/static/description/BO_actions.png
  purchase_blanket_order/static/description/BO_form.png
  purchase_blanket_order/static/description/BO_lines.png
  purchase_blanket_order/static/description/BO_menu.png
  purchase_blanket_order/static/description/PO_BOLine.png
  purchase_blanket_order/static/description/PO_from_BO.png
  purchase_blanket_order/static/description/icon.png
  purchase_blanket_order/static/description/index.html
  purchase_blanket_order/tests/__init__.py
  purchase_blanket_order/tests/test_purchase_blanket_order.py
  purchase_blanket_order/tests/test_purchase_order.py
  purchase_blanket_order/views/purchase_blanket_order_views.xml
  purchase_blanket_order/views/purchase_config_settings.xml
  purchase_blanket_order/views/purchase_order_views.xml
  purchase_blanket_order/wizard/__init__.py
  purchase_blanket_order/wizard/create_purchase_orders.py
  purchase_blanket_order/wizard/create_purchase_orders.xml
  setup/purchase_blanket_order/odoo/addons/purchase_blanket_order
  setup/purchase_blanket_order/setup.py
Labels: approved, bot is merging ⏳

#968 [13.0][ADD] purchase_manual_currency
  purchase_manual_currency/README.rst
  purchase_manual_currency/__init__.py
  purchase_manual_currency/__manifest__.py
  purchase_manual_currency/data/purchase_data.xml
  purchase_manual_currency/models/__init__.py
  purchase_manual_currency/models/purchase.py
  purchase_manual_currency/readme/CONTRIBUTORS.rst
  purchase_manual_currency/readme/DESCRIPTION.rst
  purchase_manual_currency/readme/USAGE.rst
  purchase_manual_currency/static/description/index.html
  purchase_manual_currency/tests/__init__.py
  purchase_manual_currency/tests/test_purchase_manual_currency.py
  purchase_manual_currency/views/purchase_views.xml
  setup/purchase_manual_currency/odoo/addons/purchase_manual_currency
  setup/purchase_manual_currency/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#969 [FIX] vendor_transport_lead_time: fixing 'delay' field + PO integration
  vendor_transport_lead_time/__manifest__.py
  vendor_transport_lead_time/models/__init__.py
  vendor_transport_lead_time/models/product_supplierinfo.py
  vendor_transport_lead_time/models/purchase_order_line.py
  vendor_transport_lead_time/report/purchase_order_template.xml
  vendor_transport_lead_time/tests/__init__.py
  vendor_transport_lead_time/tests/test_delay.py
  vendor_transport_lead_time/tests/test_purchase_order.py
  vendor_transport_lead_time/views/product_supplierinfo.xml
  vendor_transport_lead_time/views/purchase_order_line.xml
Labels: approved, bot is merging ⏳

#987 [IMP] purchase_request: Speed up stock_move company constraint
  purchase_request/models/purchase_request_allocation.py
  purchase_request/models/stock_move.py
  purchase_request/tests/test_purchase_request_allocation.py
Labels: approved, bot is merging ⏳

#991 [FIX] Convert invoice amount to expense currency
  purchase_landed_cost/wizard/import_invoice_line.py
Labels: approved, bot is merging ⏳

#977 [11.0][MIG]purchase_manual_delivery
  purchase_manual_delivery/README.rst
  purchase_manual_delivery/__init__.py
  purchase_manual_delivery/__manifest__.py
  purchase_manual_delivery/i18n/purchase_manual_delivery.pot
  purchase_manual_delivery/models/__init__.py
  purchase_manual_delivery/models/purchase_order.py
  purchase_manual_delivery/readme/CONTRIBUTORS.rst
  purchase_manual_delivery/readme/DESCRIPTION.rst
  purchase_manual_delivery/readme/USAGE.rst
  purchase_manual_delivery/static/description/create_incoming_shipment_button.png
  purchase_manual_delivery/static/description/create_incoming_shipment_wizard.png
  purchase_manual_delivery/static/description/icon.png
  purchase_manual_delivery/static/description/index.html
  purchase_manual_delivery/tests/__init__.py
  purchase_manual_delivery/tests/test_purchase_manual_delivery.py
  purchase_manual_delivery/views/purchase_order_views.xml
  purchase_manual_delivery/wizard/__init__.py
  purchase_manual_delivery/wizard/create_manual_stock_picking.py
  purchase_manual_delivery/wizard/create_manual_stock_picking.xml
Labels: approved, bot is merging ⏳, ready to merge

#983 [12.0][ADD] purchase_default_terms_conditions
  purchase_default_terms_conditions/README.rst
  purchase_default_terms_conditions/__init__.py
  purchase_default_terms_conditions/__manifest__.py
  purchase_default_terms_conditions/i18n/pt_BR.po
  purchase_default_terms_conditions/i18n/purchase_default_terms_conditions.pot
  purchase_default_terms_conditions/models/__init__.py
  purchase_default_terms_conditions/models/res_company.py
  purchase_default_terms_conditions/models/res_config_settings.py
  purchase_default_terms_conditions/readme/CONFIGURE.rst
  purchase_default_terms_conditions/readme/CONTRIBUTORS.rst
  purchase_default_terms_conditions/readme/CREDITS.rst
  purchase_default_terms_conditions/readme/DESCRIPTION.rst
  purchase_default_terms_conditions/readme/USAGE.rst
  purchase_default_terms_conditions/static/description/banner.png
  purchase_default_terms_conditions/static/description/icon.png
  purchase_default_terms_conditions/static/description/index.html
  purchase_default_terms_conditions/views/res_config_settings.xml
Labels: approved, bot is merging ⏳, ready to merge

#998 [14.0][MIG] purchase_order_archive
  purchase_order_archive/README.rst
  purchase_order_archive/__init__.py
  purchase_order_archive/__manifest__.py
  purchase_order_archive/i18n/purchase_order_archive.pot
  purchase_order_archive/i18n/zh_CN.po
  purchase_order_archive/models/__init__.py
  purchase_order_archive/models/purchase_order.py
  purchase_order_archive/readme/CONTRIBUTORS.rst
  purchase_order_archive/readme/DESCRIPTION.rst
  purchase_order_archive/readme/USAGE.rst
  purchase_order_archive/static/description/icon.png
  purchase_order_archive/static/description/index.html
  purchase_order_archive/views/purchase_order.xml
Labels: approved, bot is merging ⏳

#999 [13.0][FIX] purchase_request: multi-company rules
  purchase_request/security/purchase_request.xml
Labels: approved, bot is merging ⏳

#997 [ADD] purchase_request: Make product.template#purchase_request a property
  purchase_request/__manifest__.py
  purchase_request/migrations/12.0.5.0.0/post-migration.py
  purchase_request/models/product_template.py
Labels: approved, bot is merging ⏳

#984 [12.0][FIX] purchase_work_acceptance - WA Reference on invoices
  purchase_work_acceptance/models/account_invoice.py
  purchase_work_acceptance/models/work_acceptance.py
  purchase_work_acceptance/tests/test_purchase_work_acceptance.py
  purchase_work_acceptance/views/account_invoice_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#996 [ADD] purchase_request: Make product.template#purchase_request a property
  purchase_request/__manifest__.py
  purchase_request/migrations/13.0.4.0.0/post-migration.py
  purchase_request/models/product_template.py
Labels: approved, bot is merging ⏳

#917 [13.0] [MIG] purchase_reception_status
  purchase_reception_status/README.rst
  purchase_reception_status/__init__.py
  purchase_reception_status/__manifest__.py
  purchase_reception_status/i18n/purchase_reception_status.pot
  purchase_reception_status/models/__init__.py
  purchase_reception_status/models/purchase_order.py
  purchase_reception_status/readme/CONTRIBUTORS.rst
  purchase_reception_status/readme/DESCRIPTION.rst
  purchase_reception_status/readme/USAGE.rst
  purchase_reception_status/static/description/icon.png
  purchase_reception_status/static/description/index.html
  purchase_reception_status/views/purchase_order.xml
  setup/purchase_reception_status/odoo/addons/purchase_reception_status
  setup/purchase_reception_status/setup.py
Labels: bot is merging ⏳
