Repository OCA/purchase-workflow, pull requests merged in 2020-04, with the labels that each got.

#886 [12.0][MIG] purchase_minimum_amount v11 to v12
  purchase_minimum_amount/README.rst
  purchase_minimum_amount/__init__.py
  purchase_minimum_amount/__manifest__.py
  purchase_minimum_amount/data/purchase_block_reason_data.xml
  purchase_minimum_amount/i18n/de.po
  purchase_minimum_amount/i18n/es.po
  purchase_minimum_amount/i18n/es_MX.po
  purchase_minimum_amount/i18n/fr.po
  purchase_minimum_amount/i18n/it.po
  purchase_minimum_amount/i18n/pt_BR.po
  purchase_minimum_amount/i18n/purchase_minimum_amount.pot
  purchase_minimum_amount/i18n/sl.po
  purchase_minimum_amount/models/__init__.py
  purchase_minimum_amount/models/partner.py
  purchase_minimum_amount/models/purchase_order.py
  purchase_minimum_amount/static/description/icon.png
  purchase_minimum_amount/tests/__init__.py
  purchase_minimum_amount/tests/test_po_minimum_amount_block.py
  purchase_minimum_amount/views/purchase_order_view.xml
  purchase_minimum_amount/views/res_partner_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#881 [12.0][ADD] supplier_calendar
  supplier_calendar/README.rst
  supplier_calendar/__init__.py
  supplier_calendar/__manifest__.py
  supplier_calendar/models/__init__.py
  supplier_calendar/models/product.py
  supplier_calendar/models/purchase.py
  supplier_calendar/models/res_partner.py
  supplier_calendar/models/stock_rule.py
  supplier_calendar/readme/CONFIGURE.rst
  supplier_calendar/readme/CONTRIBUTORS.rst
  supplier_calendar/readme/DESCRIPTION.rst
  supplier_calendar/readme/USAGE.rst
  supplier_calendar/static/description/icon.png
  supplier_calendar/static/description/index.html
  supplier_calendar/tests/__init__.py
  supplier_calendar/tests/test_supplier_calendar.py
  supplier_calendar/views/product_view.xml
  supplier_calendar/views/res_partner_view.xml
Labels: bot is merging ⏳

#832 [10.0][FIX]purchase_order_line_sequence.
  purchase_order_line_sequence/models/purchase.py
Labels: approved, bot is merging ⏳, ready to merge

#889 [12.0][FIX]purchase_order_line_sequence. Do not update move sequence in mov…
  purchase_order_line_sequence/models/purchase.py
Labels: approved, bot is merging ⏳, ready to merge

#890 [IMP] 12.0 purchase_delivery_split_date
  purchase_delivery_split_date/__manifest__.py
  purchase_delivery_split_date/models/purchase.py
  purchase_delivery_split_date/readme/CONTRIBUTORS.rst
  purchase_delivery_split_date/readme/HISTORY.rst
  purchase_delivery_split_date/tests/test_purchase_delivery.py
Labels: approved, bot is merging ⏳, needs review

#893 [FIX] purchase_quick search view primary
  purchase_quick/README.rst
  purchase_quick/__manifest__.py
  purchase_quick/models/purchase_order.py
  purchase_quick/readme/USAGE.rst
  purchase_quick/static/description/index.html
  purchase_quick/views/product_view.xml
Labels: approved, bot is merging ⏳
