Repository OCA/purchase-workflow, pull requests merged in 2021-01, with the labels that each got.

#1034 [14.0][MIG] purchase_order_uninvoiced_amount
  purchase_order_uninvoiced_amount/README.rst
  purchase_order_uninvoiced_amount/__init__.py
  purchase_order_uninvoiced_amount/__manifest__.py
  purchase_order_uninvoiced_amount/i18n/en_US.po
  purchase_order_uninvoiced_amount/i18n/es.po
  purchase_order_uninvoiced_amount/i18n/purchase_order_uninvoiced_amount.pot
  purchase_order_uninvoiced_amount/models/__init__.py
  purchase_order_uninvoiced_amount/models/purchase_order.py
  purchase_order_uninvoiced_amount/readme/CONTRIBUTORS.rst
  purchase_order_uninvoiced_amount/readme/DESCRIPTION.rst
  purchase_order_uninvoiced_amount/static/description/icon.png
  purchase_order_uninvoiced_amount/static/description/index.html
  purchase_order_uninvoiced_amount/tests/__init__.py
  purchase_order_uninvoiced_amount/tests/test_purchase_order_uninvoiced_amount.py
  purchase_order_uninvoiced_amount/views/purchase_order_view.xml
  setup/purchase_order_uninvoiced_amount/odoo/addons/purchase_order_uninvoiced_amount
  setup/purchase_order_uninvoiced_amount/setup.py
Labels: bot is merging ⏳

#1029 [14.0][MIG] purchase_location_by_line
  purchase_location_by_line/README.rst
  purchase_location_by_line/__init__.py
  purchase_location_by_line/__manifest__.py
  purchase_location_by_line/i18n/ca.po
  purchase_location_by_line/i18n/de.po
  purchase_location_by_line/i18n/es.po
  purchase_location_by_line/i18n/es_MX.po
  purchase_location_by_line/i18n/es_PE.po
  purchase_location_by_line/i18n/fi.po
  purchase_location_by_line/i18n/fr.po
  purchase_location_by_line/i18n/gl.po
  purchase_location_by_line/i18n/hr.po
  purchase_location_by_line/i18n/it.po
  purchase_location_by_line/i18n/nl_NL.po
  purchase_location_by_line/i18n/pt_BR.po
  purchase_location_by_line/i18n/pt_PT.po
  purchase_location_by_line/i18n/purchase_location_by_line.pot
  purchase_location_by_line/i18n/ro.po
  purchase_location_by_line/i18n/sl.po
  purchase_location_by_line/models/__init__.py
  purchase_location_by_line/models/purchase.py
  purchase_location_by_line/models/stock_picking.py
  purchase_location_by_line/readme/CONTRIBUTORS.rst
  purchase_location_by_line/readme/DESCRIPTION.rst
  purchase_location_by_line/static/description/icon.png
  purchase_location_by_line/static/description/index.html
  purchase_location_by_line/tests/__init__.py
  purchase_location_by_line/tests/test_purchase_delivery.py
  purchase_location_by_line/views/purchase_view.xml
  setup/purchase_location_by_line/odoo/addons/purchase_location_by_line
  setup/purchase_location_by_line/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1044 [14.0][MIG] purchase_order_line_deep_sort
  purchase_order_line_deep_sort/README.rst
  purchase_order_line_deep_sort/__init__.py
  purchase_order_line_deep_sort/__manifest__.py
  purchase_order_line_deep_sort/i18n/es.po
  purchase_order_line_deep_sort/i18n/purchase_order_line_deep_sort.pot
  purchase_order_line_deep_sort/models/__init__.py
  purchase_order_line_deep_sort/models/purchase_order.py
  purchase_order_line_deep_sort/models/res_company.py
  purchase_order_line_deep_sort/models/res_config_settings.py
  purchase_order_line_deep_sort/readme/CONFIGURE.rst
  purchase_order_line_deep_sort/readme/CONTRIBUTORS.rst
  purchase_order_line_deep_sort/readme/DESCRIPTION.rst
  purchase_order_line_deep_sort/readme/ROADMAP.rst
  purchase_order_line_deep_sort/readme/USAGE.rst
  purchase_order_line_deep_sort/static/description/icon.png
  purchase_order_line_deep_sort/static/description/index.html
  purchase_order_line_deep_sort/tests/__init__.py
  purchase_order_line_deep_sort/tests/test_purchase_order_line_deep_sort.py
  purchase_order_line_deep_sort/views/purchase_order_views.xml
  purchase_order_line_deep_sort/views/res_config_settings_views.xml
  setup/purchase_order_line_deep_sort/odoo/addons/purchase_order_line_deep_sort
  setup/purchase_order_line_deep_sort/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1043 [14.0][FIX] purchase_tier_validation, set manual view = False
  purchase_tier_validation/models/purchase_order.py
  purchase_tier_validation/views/purchase_order_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#822 [12.0][MIG] purchase_requisition_auto_rfq
  purchase_requisition_auto_rfq/README.rst
  purchase_requisition_auto_rfq/__init__.py
  purchase_requisition_auto_rfq/__manifest__.py
  purchase_requisition_auto_rfq/demo/product_product.xml
  purchase_requisition_auto_rfq/i18n/fr.po
  purchase_requisition_auto_rfq/i18n/purchase_requisition_auto_rfq.pot
  purchase_requisition_auto_rfq/models/__init__.py
  purchase_requisition_auto_rfq/models/purchase_requisition.py
  purchase_requisition_auto_rfq/readme/CONTRIBUTORS.rst
  purchase_requisition_auto_rfq/readme/DESCRIPTION.rst
  purchase_requisition_auto_rfq/readme/USAGE.rst
  purchase_requisition_auto_rfq/static/description/icon.png
  purchase_requisition_auto_rfq/static/description/index.html
  purchase_requisition_auto_rfq/tests/__init__.py
  purchase_requisition_auto_rfq/tests/test_purchase_requisition.py
  purchase_requisition_auto_rfq/view/purchase_requisition.xml
Labels: approved, bot is merging ⏳

#1042 [14.0][FIX] purchase_request_tier_validation, manual view = False
  purchase_request_tier_validation/models/purchase_request.py
  purchase_request_tier_validation/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1024 [14.0][MIG] purchase_invoice_plan
  purchase_invoice_plan/README.rst
  purchase_invoice_plan/__init__.py
  purchase_invoice_plan/__manifest__.py
  purchase_invoice_plan/i18n/purchase_invoice_plan.pot
  purchase_invoice_plan/models/__init__.py
  purchase_invoice_plan/models/purchase.py
  purchase_invoice_plan/readme/CONTRIBUTORS.rst
  purchase_invoice_plan/readme/DESCRIPTION.rst
  purchase_invoice_plan/readme/USAGE.rst
  purchase_invoice_plan/security/ir.model.access.csv
  purchase_invoice_plan/static/description/icon.png
  purchase_invoice_plan/static/description/index.html
  purchase_invoice_plan/tests/__init__.py
  purchase_invoice_plan/tests/test_purchase_invoice_plan.py
  purchase_invoice_plan/views/purchase_view.xml
  purchase_invoice_plan/wizard/__init__.py
  purchase_invoice_plan/wizard/purchase_create_invoice_plan.py
  purchase_invoice_plan/wizard/purchase_create_invoice_plan_view.xml
  purchase_invoice_plan/wizard/purchase_make_planned_invoice.py
  purchase_invoice_plan/wizard/purchase_make_planned_invoice_view.xml
  setup/purchase_invoice_plan/odoo/addons/purchase_invoice_plan
  setup/purchase_invoice_plan/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1069 [13.0][FIX] purchase_manual_currency: Use assertAlmostEqual for float comparison
  purchase_manual_currency/tests/test_purchase_manual_currency.py
Labels: bot is merging ⏳

#1015 [14.0][MIG] purchase_manual_currency
  purchase_manual_currency/README.rst
  purchase_manual_currency/__init__.py
  purchase_manual_currency/__manifest__.py
  purchase_manual_currency/data/purchase_data.xml
  purchase_manual_currency/i18n/purchase_manual_currency.pot
  purchase_manual_currency/models/__init__.py
  purchase_manual_currency/models/purchase.py
  purchase_manual_currency/readme/CONTRIBUTORS.rst
  purchase_manual_currency/readme/DESCRIPTION.rst
  purchase_manual_currency/readme/USAGE.rst
  purchase_manual_currency/static/description/icon.png
  purchase_manual_currency/static/description/index.html
  purchase_manual_currency/tests/__init__.py
  purchase_manual_currency/tests/test_purchase_manual_currency.py
  purchase_manual_currency/views/purchase_views.xml
  setup/purchase_manual_currency/odoo/addons/purchase_manual_currency
  setup/purchase_manual_currency/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1057 [13.0][ADD] purchase_stock_secondary_unit: add new module that allows to pass the secondary unit from a purchase order to the related pickings
  purchase_stock_secondary_unit/README.rst
  purchase_stock_secondary_unit/__init__.py
  purchase_stock_secondary_unit/__manifest__.py
  purchase_stock_secondary_unit/i18n/es.po
  purchase_stock_secondary_unit/models/__init__.py
  purchase_stock_secondary_unit/models/purchase_order_line.py
  purchase_stock_secondary_unit/readme/CONTRIBUTORS.rst
  purchase_stock_secondary_unit/readme/DESCRIPTION.rst
  purchase_stock_secondary_unit/readme/USAGE.rst
  purchase_stock_secondary_unit/static/description/icon.png
  purchase_stock_secondary_unit/static/description/index.html
  purchase_stock_secondary_unit/tests/__init__.py
  purchase_stock_secondary_unit/tests/test_purchase_stock_secondary_unit.py
  setup/purchase_stock_secondary_unit/odoo/addons/purchase_stock_secondary_unit
  setup/purchase_stock_secondary_unit/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1062 [IMP] various: improve code style and performance by improve ``all()`…
  purchase_request/models/purchase_request.py
  purchase_request/models/purchase_request_line.py
Labels: approved, bot is merging ⏳

#1075 [14.0][FIX] purchase_work_acceptance: field WA Reference
  purchase_work_acceptance/models/stock_picking.py
Labels: approved, bot is merging ⏳

#1074 [13.0][FIX] purchase_order_secondary_unit, error selecting 2nd_uom when no product_id
  purchase_order_secondary_unit/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#1061 [IMP] purchase_request: Setting default payment term from supplier
  purchase_request/tests/test_purchase_request_to_rfq.py
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: approved, bot is merging ⏳

#1033 [14.0][MIG] purchase_discount: Migration to 14.0
  purchase_discount/README.rst
  purchase_discount/__init__.py
  purchase_discount/__manifest__.py
  purchase_discount/i18n/de.po
  purchase_discount/i18n/el_GR.po
  purchase_discount/i18n/es.po
  purchase_discount/i18n/es_MX.po
  purchase_discount/i18n/fr.po
  purchase_discount/i18n/fr_CH.po
  purchase_discount/i18n/hr.po
  purchase_discount/i18n/it.po
  purchase_discount/i18n/nl.po
  purchase_discount/i18n/pt_BR.po
  purchase_discount/i18n/pt_PT.po
  purchase_discount/i18n/purchase_discount.pot
  purchase_discount/i18n/sl.po
  purchase_discount/i18n/zh_CN.po
  purchase_discount/images/purchase_discount.png
  purchase_discount/models/__init__.py
  purchase_discount/models/product_supplierinfo.py
  purchase_discount/models/purchase_order.py
  purchase_discount/models/res_partner.py
  purchase_discount/models/stock_move.py
  purchase_discount/readme/CONTRIBUTORS.rst
  purchase_discount/readme/DESCRIPTION.rst
  purchase_discount/readme/ROADMAP.rst
  purchase_discount/readme/USAGE.rst
  purchase_discount/report/__init__.py
  purchase_discount/report/purchase_report.py
  purchase_discount/static/description/icon.png
  purchase_discount/static/description/icon.svg
  purchase_discount/static/description/index.html
  purchase_discount/static/description/product_supplierinfo_form.png
  purchase_discount/static/description/res_partner_company_form.png
  purchase_discount/static/description/res_partner_individual_form.png
  purchase_discount/tests/__init__.py
  purchase_discount/tests/test_product_supplierinfo_discount.py
  purchase_discount/tests/test_purchase_discount.py
  purchase_discount/views/product_supplierinfo_view.xml
  purchase_discount/views/purchase_discount_view.xml
  purchase_discount/views/report_purchaseorder.xml
  purchase_discount/views/res_partner_view.xml
  setup/purchase_discount/odoo/addons/purchase_discount
  setup/purchase_discount/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1052 [12.0][IMP] procurement_purchase_no_grouping: Add product_category in procured_purchase_grouping field
  procurement_purchase_no_grouping/i18n/es.po
  procurement_purchase_no_grouping/i18n/procurement_purchase_no_grouping.pot
  procurement_purchase_no_grouping/models/product_category.py
  procurement_purchase_no_grouping/models/stock_rule.py
  procurement_purchase_no_grouping/readme/CONFIGURE.rst
  procurement_purchase_no_grouping/readme/CONTRIBUTORS.rst
  procurement_purchase_no_grouping/tests/test_procurement_purchase_no_grouping.py
Labels: approved, bot is merging ⏳

#1071 [13.0][MIG] purchase_landed_cost: Migration to 13.0
  purchase_landed_cost/README.rst
  purchase_landed_cost/__init__.py
  purchase_landed_cost/__manifest__.py
  purchase_landed_cost/data/purchase_cost_distribution_sequence.xml
  purchase_landed_cost/i18n/es.po
  purchase_landed_cost/i18n/fr.po
  purchase_landed_cost/i18n/it.po
  purchase_landed_cost/i18n/pt_BR.po
  purchase_landed_cost/i18n/purchase_landed_cost.pot
  purchase_landed_cost/i18n/ro.po
  purchase_landed_cost/i18n/sl.po
  purchase_landed_cost/i18n/zh_CN.po
  purchase_landed_cost/models/__init__.py
  purchase_landed_cost/models/account_move.py
  purchase_landed_cost/models/purchase_cost_distribution.py
  purchase_landed_cost/models/purchase_expense_type.py
  purchase_landed_cost/models/purchase_order.py
  purchase_landed_cost/models/stock_picking.py
  purchase_landed_cost/readme/CONTRIBUTORS.rst
  purchase_landed_cost/readme/DESCRIPTION.rst
  purchase_landed_cost/readme/ROADMAP.rst
  purchase_landed_cost/security/ir.model.access.csv
  purchase_landed_cost/security/purchase_landed_cost_security.xml
  purchase_landed_cost/static/description/icon.png
  purchase_landed_cost/static/description/images/expenses_types.png
  purchase_landed_cost/static/description/images/purchase_order_expense_line.png
  purchase_landed_cost/static/description/images/purchase_order_expense_main.png
  purchase_landed_cost/static/description/index.html
  purchase_landed_cost/tests/__init__.py
  purchase_landed_cost/tests/test_purchase_landed_cost.py
  purchase_landed_cost/views/account_move_view.xml
  purchase_landed_cost/views/purchase_cost_distribution_line_expense_view.xml
  purchase_landed_cost/views/purchase_cost_distribution_view.xml
  purchase_landed_cost/views/purchase_expense_type_view.xml
  purchase_landed_cost/views/purchase_order_view.xml
  purchase_landed_cost/views/stock_picking_view.xml
  purchase_landed_cost/wizard/__init__.py
  purchase_landed_cost/wizard/import_invoice_line.py
  purchase_landed_cost/wizard/import_invoice_line_wizard_view.xml
  purchase_landed_cost/wizard/import_landed_cost_pickings_wizard.py
  purchase_landed_cost/wizard/import_landed_cost_pickings_wizard_view.xml
  purchase_landed_cost/wizard/picking_import_wizard.py
  purchase_landed_cost/wizard/picking_import_wizard_view.xml
  setup/purchase_landed_cost/odoo/addons/purchase_landed_cost
  setup/purchase_landed_cost/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1080 [12.0][FIX] procurement_purchase_no_grouping: In product_category grouping need to separate in some purchase orders
  procurement_purchase_no_grouping/models/stock_rule.py
  procurement_purchase_no_grouping/tests/test_procurement_purchase_no_grouping.py
Labels: approved, bot is merging ⏳, ready to merge

#1084 [12.0][FIX] purchase_allowed_product: Add use_only_supplied_product to invoice form
  purchase_allowed_product/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳
