Repository OCA/purchase-workflow, pull requests merged in 2021-02, with the labels that each got.

#1077 [13.0][IMP] procurement_purchase_no_grouping: Add product_category in procured_purchase_grouping field
  procurement_purchase_no_grouping/i18n/es.po
  procurement_purchase_no_grouping/i18n/procurement_purchase_no_grouping.pot
  procurement_purchase_no_grouping/models/product_category.py
  procurement_purchase_no_grouping/models/res_company.py
  procurement_purchase_no_grouping/models/stock_rule.py
  procurement_purchase_no_grouping/readme/CONFIGURE.rst
  procurement_purchase_no_grouping/readme/CONTRIBUTORS.rst
  procurement_purchase_no_grouping/tests/test_procurement_purchase_no_grouping.py
Labels: approved, bot is merging ⏳

#1091 [12.0][IMP] purchase_discount: Add tracking to default_supplierinfo_discount on partners
  purchase_discount/models/res_partner.py
  purchase_discount/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#1092 [13.0][IMP] purchase_discount: Add tracking to default_supplierinfo_discount on partners
  purchase_discount/models/res_partner.py
  purchase_discount/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#1078 [14.0][IMP] purchase_work_acceptance: show accepted qty, show button create wa
  purchase_work_acceptance/models/purchase.py
  purchase_work_acceptance/tests/test_purchase_work_acceptance.py
  purchase_work_acceptance/views/purchase_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#1086 [13.0][IMP] purchase_order_uninvoiced_amount: Add amount_untaxed in purchase_order_view_tree
  purchase_order_uninvoiced_amount/views/purchase_order_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1108 [14.0][FIX] purchase_discount: Allow move to be False if not assigned
  purchase_discount/models/purchase_order.py
Labels: bot is merging ⏳

#1105 [13.0][FIX] purchase_order_uninvoiced_amount: Allow amount_uninvoiced negative
  purchase_order_uninvoiced_amount/models/purchase_order.py
  purchase_order_uninvoiced_amount/readme/CONTRIBUTORS.rst
  purchase_order_uninvoiced_amount/tests/test_purchase_order_uninvoiced_amount.py
Labels: approved, bot is merging ⏳

#1109 [12.0][FIX] purchase_order_uninvoiced_amount: Allow amount_uninvoiced negative
  purchase_order_uninvoiced_amount/models/purchase_order.py
  purchase_order_uninvoiced_amount/readme/CONTRIBUTORS.rst
  purchase_order_uninvoiced_amount/tests/test_purchase_order_uninvoiced_amount.py
Labels: approved, bot is merging ⏳

#1090 [13.0][FIX] purchase_delivery_split_date crash with notes and sections with corfirmation
  purchase_delivery_split_date/README.rst
  purchase_delivery_split_date/models/purchase.py
Labels: approved, bot is merging ⏳, ready to merge

#1110 [14.0][FIX] purchase_delivery_split_date: Error when PO has Sections …
  purchase_delivery_split_date/models/purchase.py
  purchase_delivery_split_date/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#1082 [12.0][FIX] purchase_order_product_recommendation: Add vendor for new line
  purchase_order_product_recommendation/wizards/purchase_order_recommendation.py
Labels: approved, bot is merging ⏳, ready to merge

#1111 [13.0][FIX] purchase_product_usage: Change only account if usage is defined in POL
  purchase_product_usage/models/account_move.py
Labels: approved, bot is merging ⏳

#1076 [IMP] purchase_last_price_info: Add last_purchase_price field dependa…
  purchase_last_price_info/models/product.py
Labels: approved, bot is merging ⏳, ready to merge

#1008 [13.0] [MIG] purchase_line_procurement_group
  purchase_line_procurement_group/README.rst
  purchase_line_procurement_group/__init__.py
  purchase_line_procurement_group/__manifest__.py
  purchase_line_procurement_group/i18n/fr.po
  purchase_line_procurement_group/i18n/purchase_line_procurement_group.pot
  purchase_line_procurement_group/i18n/zh_CN.po
  purchase_line_procurement_group/models/__init__.py
  purchase_line_procurement_group/models/purchase.py
  purchase_line_procurement_group/models/stock_move.py
  purchase_line_procurement_group/models/stock_rule.py
  purchase_line_procurement_group/readme/CONTRIBUTORS.rst
  purchase_line_procurement_group/readme/CREDITS.rst
  purchase_line_procurement_group/readme/DESCRIPTION.rst
  purchase_line_procurement_group/static/description/icon.png
  purchase_line_procurement_group/static/description/index.html
  purchase_line_procurement_group/tests/__init__.py
  purchase_line_procurement_group/tests/test_po_line_proc_group.py
  purchase_line_procurement_group/views/purchase.xml
  setup/purchase_line_procurement_group/odoo/addons/purchase_line_procurement_group
  setup/purchase_line_procurement_group/setup.py
Labels: approved, bot is merging ⏳

#1113 [13.0][IMP] purchase_request: emails conditionals
  purchase_request/models/purchase_order.py
  purchase_request/models/purchase_request_allocation.py
  purchase_request/models/stock_move_line.py
  purchase_request/models/stock_picking.py
Labels: approved, bot is merging ⏳

#1100 [14.0][ADD]Added Module purchase_order_line_menu
  purchase_order_line_menu/README.rst
  purchase_order_line_menu/__init__.py
  purchase_order_line_menu/__manifest__.py
  purchase_order_line_menu/readme/CONTRIBUTORS.rst
  purchase_order_line_menu/readme/DESCRIPTION.rst
  purchase_order_line_menu/readme/USAGE.rst
  purchase_order_line_menu/static/description/index.html
  purchase_order_line_menu/views/purchase_order_line_views.xml
  setup/purchase_order_line_menu/odoo/addons/purchase_order_line_menu
  setup/purchase_order_line_menu/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1117 [13.0] [IMP] purchase_request: index on created_purchase_request_line_id
  purchase_request/models/stock_move.py
Labels: approved, bot is merging ⏳

#1119 [14.0] [IMP] purchase_request: index on created_purchase_request_line_id
  purchase_request/models/stock_move.py
Labels: approved, bot is merging ⏳

#1114 [13.0][MIG] purchase_order_line_stock_available: Migration to 13.0
  purchase_order_line_stock_available/README.rst
  purchase_order_line_stock_available/__init__.py
  purchase_order_line_stock_available/__manifest__.py
  purchase_order_line_stock_available/i18n/es.po
  purchase_order_line_stock_available/i18n/pt_BR.po
  purchase_order_line_stock_available/i18n/purchase_order_line_stock_available.pot
  purchase_order_line_stock_available/i18n/sl.po
  purchase_order_line_stock_available/models/__init__.py
  purchase_order_line_stock_available/models/purchase.py
  purchase_order_line_stock_available/readme/CONTRIBUTORS.rst
  purchase_order_line_stock_available/readme/DESCRIPTION.rst
  purchase_order_line_stock_available/readme/USAGE.rst
  purchase_order_line_stock_available/static/description/icon.png
  purchase_order_line_stock_available/static/description/index.html
  purchase_order_line_stock_available/tests/__init__.py
  purchase_order_line_stock_available/tests/test_purchase.py
  purchase_order_line_stock_available/views/purchase_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1121 [13.0] [MIG] purchase_exception
  purchase_exception/README.rst
  purchase_exception/__init__.py
  purchase_exception/__manifest__.py
  purchase_exception/data/purchase_exception_data.xml
  purchase_exception/i18n/fr.po
  purchase_exception/i18n/purchase_exception.pot
  purchase_exception/i18n/zh_CN.po
  purchase_exception/models/__init__.py
  purchase_exception/models/exception_rule.py
  purchase_exception/models/purchase.py
  purchase_exception/models/purchase_line.py
  purchase_exception/readme/CONTRIBUTORS.rst
  purchase_exception/readme/DESCRIPTION.rst
  purchase_exception/readme/USAGE.rst
  purchase_exception/static/description/icon.png
  purchase_exception/static/description/index.html
  purchase_exception/tests/__init__.py
  purchase_exception/tests/test_purchase_exception.py
  purchase_exception/views/purchase_view.xml
  purchase_exception/wizard/__init__.py
  purchase_exception/wizard/purchase_exception_confirm.py
  purchase_exception/wizard/purchase_exception_confirm_view.xml
  setup/purchase_exception/odoo/addons/purchase_exception
  setup/purchase_exception/setup.py
Labels: approved, bot is merging ⏳

#1123 [MIG] purchase_order_approval_block: Migration to 13.0
  purchase_order_approval_block/README.rst
  purchase_order_approval_block/__init__.py
  purchase_order_approval_block/__manifest__.py
  purchase_order_approval_block/data/purchase_exception_data.xml
  purchase_order_approval_block/i18n/fr.po
  purchase_order_approval_block/i18n/purchase_order_approval_block.pot
  purchase_order_approval_block/models/__init__.py
  purchase_order_approval_block/models/purchase_approval_block_reason.py
  purchase_order_approval_block/models/purchase_order.py
  purchase_order_approval_block/security/ir.model.access.csv
  purchase_order_approval_block/security/purchase_order_approval_block_security.xml
  purchase_order_approval_block/static/description/icon.png
  purchase_order_approval_block/tests/__init__.py
  purchase_order_approval_block/tests/test_po_approval_block_reason.py
  purchase_order_approval_block/tests/test_purchase_order_approval_block.py
  purchase_order_approval_block/views/purchase_approval_block_reason_view.xml
  purchase_order_approval_block/views/purchase_order_view.xml
  purchase_order_approval_block/wizard/__init__.py
  purchase_order_approval_block/wizard/purchase_exception_confirm.py
Labels: approved, bot is merging ⏳

#1085 [12.0][FIX] purchase_picking_state: `show_purchase` unused in 12.0
  purchase_picking_state/views/purchase_view.xml
Labels: approved, bot is merging ⏳

#1095 [14.0][FIX] purchase_location_by_line : Too many receipts are created
  purchase_delivery_split_date/models/purchase.py
  purchase_location_by_line/README.rst
  purchase_location_by_line/models/purchase.py
Labels: approved, bot is merging ⏳, ready to merge
