Repository OCA/purchase-workflow, pull requests merged in 2021-03, with the labels that each got.

#1124 [MIG] purchase_minimum_amount: Migration to 13.0
  purchase_minimum_amount/README.rst
  purchase_minimum_amount/__init__.py
  purchase_minimum_amount/__manifest__.py
  purchase_minimum_amount/data/purchase_block_reason_data.xml
  purchase_minimum_amount/i18n/de.po
  purchase_minimum_amount/i18n/es.po
  purchase_minimum_amount/i18n/es_MX.po
  purchase_minimum_amount/i18n/fr.po
  purchase_minimum_amount/i18n/it.po
  purchase_minimum_amount/i18n/pt_BR.po
  purchase_minimum_amount/i18n/purchase_minimum_amount.pot
  purchase_minimum_amount/i18n/sl.po
  purchase_minimum_amount/models/__init__.py
  purchase_minimum_amount/models/partner.py
  purchase_minimum_amount/models/purchase_order.py
  purchase_minimum_amount/static/description/icon.png
  purchase_minimum_amount/tests/__init__.py
  purchase_minimum_amount/tests/test_po_minimum_amount_block.py
  purchase_minimum_amount/views/purchase_order_view.xml
  purchase_minimum_amount/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#1001 [13.0][MIG] purchase_stock_price_unit_sync: Migration to v13.0
  purchase_stock_price_unit_sync/README.rst
  purchase_stock_price_unit_sync/__init__.py
  purchase_stock_price_unit_sync/__manifest__.py
  purchase_stock_price_unit_sync/i18n/purchase_stock_price_unit_sync.pot
  purchase_stock_price_unit_sync/models/__init__.py
  purchase_stock_price_unit_sync/models/purchase_order.py
  purchase_stock_price_unit_sync/readme/CONTRIBUTORS.rst
  purchase_stock_price_unit_sync/readme/DESCRIPTION.rst
  purchase_stock_price_unit_sync/static/description/icon.png
  purchase_stock_price_unit_sync/static/description/index.html
  purchase_stock_price_unit_sync/tests/__init__.py
  purchase_stock_price_unit_sync/tests/test_purchase_stock_price_unit_sync.py
Labels: approved, bot is merging ⏳, ready to merge

#1104 [14.0][MIG] purchase_requisition_tier_validation
  purchase_requisition_tier_validation/__init__.py
  purchase_requisition_tier_validation/__manifest__.py
  purchase_requisition_tier_validation/i18n/purchase_requisition_tier_validation.pot
  purchase_requisition_tier_validation/i18n/zh_CN.po
  purchase_requisition_tier_validation/models/__init__.py
  purchase_requisition_tier_validation/models/purchase_requisition.py
  purchase_requisition_tier_validation/models/tier_definition.py
  purchase_requisition_tier_validation/readme/CONFIGURE.rst
  purchase_requisition_tier_validation/readme/CONTRIBUTORS.rst
  purchase_requisition_tier_validation/readme/DESCRIPTION.rst
  purchase_requisition_tier_validation/readme/INSTALL.rst
  purchase_requisition_tier_validation/readme/USAGE.rst
  purchase_requisition_tier_validation/static/description/icon.png
  purchase_requisition_tier_validation/static/description/index.html
  purchase_requisition_tier_validation/tests/__init__.py
  purchase_requisition_tier_validation/tests/test_purchase_requisition_tier_validation.py
  purchase_requisition_tier_validation/views/purchase_requisition_view.xml
  setup/purchase_requisition_tier_validation/odoo/addons/purchase_requisition_tier_validation
  setup/purchase_requisition_tier_validation/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1099 [14.0] [MIG] product_form_purchase_link
  product_form_purchase_link/README.rst
  product_form_purchase_link/__init__.py
  product_form_purchase_link/__manifest__.py
  product_form_purchase_link/i18n/product_form_purchase_link.pot
  product_form_purchase_link/readme/CONTRIBUTORS.rst
  product_form_purchase_link/readme/DESCRIPTION.rst
  product_form_purchase_link/readme/USAGE.rst
  product_form_purchase_link/static/description/icon.png
  product_form_purchase_link/static/description/index.html
  product_form_purchase_link/views/product_product.xml
  product_form_purchase_link/views/product_template.xml
  product_form_purchase_link/views/purchase_order_line.xml
  setup/product_form_purchase_link/odoo/addons/product_form_purchase_link
  setup/product_form_purchase_link/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#883 [13.0][MIG] purchase_order_product_recommendation_brand: Migration to 13.0
  oca_dependencies.txt
  purchase_order_product_recommendation_brand/README.rst
  purchase_order_product_recommendation_brand/__init__.py
  purchase_order_product_recommendation_brand/__manifest__.py
  purchase_order_product_recommendation_brand/i18n/es.po
  purchase_order_product_recommendation_brand/i18n/purchase_order_product_recommendation_brand.pot
  purchase_order_product_recommendation_brand/readme/CONTRIBUTORS.rst
  purchase_order_product_recommendation_brand/readme/DESCRIPTION.rst
  purchase_order_product_recommendation_brand/readme/ROADMAP.rst
  purchase_order_product_recommendation_brand/readme/USAGE.rst
  purchase_order_product_recommendation_brand/static/description/icon.png
  purchase_order_product_recommendation_brand/static/description/index.html
  purchase_order_product_recommendation_brand/tests/__init__.py
  purchase_order_product_recommendation_brand/tests/test_recommendation.py
  purchase_order_product_recommendation_brand/wizards/__init__.py
  purchase_order_product_recommendation_brand/wizards/purchase_order_recommendation.py
  purchase_order_product_recommendation_brand/wizards/purchase_order_recommendation_view.xml
  setup/purchase_order_product_recommendation_brand/odoo/addons/purchase_order_product_recommendation_brand
  setup/purchase_order_product_recommendation_brand/setup.py
Labels: bot is merging ⏳

#1130 [13.0][FIX] purchase_discount: fix acl error for low level users
  purchase_discount/models/stock_move.py
Labels: approved, bot is merging ⏳

#1132 [13.0][UPD] Eficent -> ForgeFlow and add fragmented readme
  purchase_exception/README.rst
  purchase_exception/data/purchase_exception_data.xml
  purchase_exception/readme/USAGE.rst
  purchase_exception/static/description/index.html
  purchase_minimum_amount/__manifest__.py
  purchase_minimum_amount/data/purchase_block_reason_data.xml
  purchase_minimum_amount/models/partner.py
  purchase_minimum_amount/models/purchase_order.py
  purchase_minimum_amount/readme/CONFIGURE.rst
  purchase_minimum_amount/readme/CONTRIBUTORS.rst
  purchase_minimum_amount/readme/DESCRIPTION.rst
  purchase_minimum_amount/readme/USAGE.rst
  purchase_minimum_amount/tests/test_po_minimum_amount_block.py
  purchase_minimum_amount/views/purchase_order_view.xml
  purchase_minimum_amount/views/res_partner_view.xml
  purchase_order_approval_block/__manifest__.py
  purchase_order_approval_block/models/purchase_approval_block_reason.py
  purchase_order_approval_block/models/purchase_order.py
  purchase_order_approval_block/readme/CONFIGURE.rst
  purchase_order_approval_block/readme/CONTRIBUTORS.rst
  purchase_order_approval_block/readme/DESCRIPTION.rst
  purchase_order_approval_block/readme/USAGE.rst
  purchase_order_approval_block/security/purchase_order_approval_block_security.xml
  purchase_order_approval_block/tests/test_po_approval_block_reason.py
  purchase_order_approval_block/tests/test_purchase_order_approval_block.py
  purchase_order_approval_block/views/purchase_approval_block_reason_view.xml
  purchase_order_approval_block/views/purchase_order_view.xml
  purchase_order_approval_block/wizard/purchase_exception_confirm.py
Labels: approved, bot is merging ⏳

#1088 [14.0] [MIG] purchase_order_line_price_history: Migrated the module from 13 to 14.
  purchase_order_line_price_history/README.rst
  purchase_order_line_price_history/__init__.py
  purchase_order_line_price_history/__manifest__.py
  purchase_order_line_price_history/i18n/es.po
  purchase_order_line_price_history/i18n/purchase_order_line_price_history.pot
  purchase_order_line_price_history/readme/CONTRIBUTORS.rst
  purchase_order_line_price_history/readme/DESCRIPTION.rst
  purchase_order_line_price_history/readme/ROADMAP.rst
  purchase_order_line_price_history/readme/USAGE.rst
  purchase_order_line_price_history/security/ir.model.access.csv
  purchase_order_line_price_history/static/description/icon.png
  purchase_order_line_price_history/static/description/index.html
  purchase_order_line_price_history/tests/__init__.py
  purchase_order_line_price_history/tests/test_purchase_order_line_price_history.py
  purchase_order_line_price_history/views/purchase_views.xml
  purchase_order_line_price_history/wizards/__init__.py
  purchase_order_line_price_history/wizards/purchase_order_line_price_history.py
  purchase_order_line_price_history/wizards/purchase_order_line_price_history.xml
  setup/purchase_order_line_price_history/odoo/addons/purchase_order_line_price_history
  setup/purchase_order_line_price_history/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1131 [12.0][IMP] purchase_request: Add analytic tags and propagate to PO
  purchase_request/models/purchase_request_line.py
  purchase_request/tests/test_purchase_request_to_rfq.py
  purchase_request/views/purchase_request_line_view.xml
  purchase_request/views/purchase_request_view.xml
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: approved, bot is merging ⏳

#1097 [14.0][FIX] purchase_work_acceptance: stock picking domain wa_id
  purchase_work_acceptance/models/stock_picking.py
  purchase_work_acceptance/views/purchase_views.xml
  purchase_work_acceptance/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#1059 [14.0][MIG] purchase_reception_status
  purchase_reception_status/README.rst
  purchase_reception_status/__init__.py
  purchase_reception_status/__manifest__.py
  purchase_reception_status/i18n/it.po
  purchase_reception_status/i18n/purchase_reception_status.pot
  purchase_reception_status/models/__init__.py
  purchase_reception_status/models/purchase_order.py
  purchase_reception_status/readme/CONTRIBUTORS.rst
  purchase_reception_status/readme/DESCRIPTION.rst
  purchase_reception_status/readme/USAGE.rst
  purchase_reception_status/static/description/icon.png
  purchase_reception_status/static/description/index.html
  purchase_reception_status/views/purchase_order.xml
  setup/purchase_reception_status/odoo/addons/purchase_reception_status
  setup/purchase_reception_status/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1135 [13.0][IMP] purchase_request: Add analytic tags and propagate to PO
  purchase_request/models/purchase_request_line.py
  purchase_request/tests/test_purchase_request_to_rfq.py
  purchase_request/views/purchase_request_line_view.xml
  purchase_request/views/purchase_request_view.xml
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: approved, bot is merging ⏳

#1136 [14.0][IMP] purchase_request: Add analytic tags and propagate to PO
  purchase_request/models/purchase_request_line.py
  purchase_request/tests/test_purchase_request_to_rfq.py
  purchase_request/views/purchase_request_line_view.xml
  purchase_request/views/purchase_request_view.xml
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: approved, bot is merging ⏳

#1025 [14.0][MIG] purchase_work_acceptance_invoice_plan
  purchase_work_acceptance_invoice_plan/README.rst
  purchase_work_acceptance_invoice_plan/__init__.py
  purchase_work_acceptance_invoice_plan/__manifest__.py
  purchase_work_acceptance_invoice_plan/models/__init__.py
  purchase_work_acceptance_invoice_plan/models/purchase.py
  purchase_work_acceptance_invoice_plan/models/work_acceptance.py
  purchase_work_acceptance_invoice_plan/readme/CONTRIBUTORS.rst
  purchase_work_acceptance_invoice_plan/readme/DESCRIPTION.rst
  purchase_work_acceptance_invoice_plan/readme/USAGE.rst
  purchase_work_acceptance_invoice_plan/security/ir.model.access.csv
  purchase_work_acceptance_invoice_plan/static/description/index.html
  purchase_work_acceptance_invoice_plan/tests/__init__.py
  purchase_work_acceptance_invoice_plan/tests/test_purchase_work_acceptance_invoice_plan.py
  purchase_work_acceptance_invoice_plan/views/purchase_views.xml
  purchase_work_acceptance_invoice_plan/views/work_acceptance_view.xml
  purchase_work_acceptance_invoice_plan/wizard/__init__.py
  purchase_work_acceptance_invoice_plan/wizard/select_work_acceptance_invoice_plan_wizard.py
  purchase_work_acceptance_invoice_plan/wizard/select_work_acceptance_invoice_plan_wizard_views.xml
  setup/purchase_work_acceptance_invoice_plan/odoo/addons/purchase_work_acceptance_invoice_plan
  setup/purchase_work_acceptance_invoice_plan/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#828 [13.0][MIG] purchase_force_invoiced
  purchase_force_invoiced/README.rst
  purchase_force_invoiced/__init__.py
  purchase_force_invoiced/__manifest__.py
  purchase_force_invoiced/i18n/purchase_force_invoiced.pot
  purchase_force_invoiced/i18n/zh_CN.po
  purchase_force_invoiced/model/__init__.py
  purchase_force_invoiced/model/purchase.py
  purchase_force_invoiced/readme/CONTRIBUTORS.rst
  purchase_force_invoiced/readme/DESCRIPTION.rst
  purchase_force_invoiced/readme/USAGE.rst
  purchase_force_invoiced/static/description/icon.png
  purchase_force_invoiced/static/description/index.html
  purchase_force_invoiced/tests/__init__.py
  purchase_force_invoiced/tests/test_purchase_force_invoiced.py
  purchase_force_invoiced/view/purchase_view.xml
  setup/purchase_force_invoiced/odoo/addons/purchase_force_invoiced
  setup/purchase_force_invoiced/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#942 [13.0][MIG] purchase_request_order_approved
  purchase_request_order_approved/README.rst
  purchase_request_order_approved/__init__.py
  purchase_request_order_approved/__manifest__.py
  purchase_request_order_approved/i18n/es.po
  purchase_request_order_approved/i18n/fr.po
  purchase_request_order_approved/i18n/nl_NL.po
  purchase_request_order_approved/i18n/purchase_request_order_approved.pot
  purchase_request_order_approved/i18n/purchase_request_to_rfq_order_approved.pot
  purchase_request_order_approved/i18n/sl.po
  purchase_request_order_approved/init_hook.py
  purchase_request_order_approved/models/__init__.py
  purchase_request_order_approved/models/purchase_request.py
  purchase_request_order_approved/readme/CONTRIBUTORS.rst
  purchase_request_order_approved/readme/DESCRIPTION.rst
  purchase_request_order_approved/static/description/icon.png
  purchase_request_order_approved/static/description/index.html
  purchase_request_order_approved/tests/__init__.py
  purchase_request_order_approved/tests/test_purchase_request_order_approved.py
  purchase_request_order_approved/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1134 [13.0][FIX] purchase_order_approval_block: stock dependency is unneeded
  purchase_order_approval_block/__manifest__.py
Labels: bot is merging ⏳

#1054 [12.0][FIX] purchase_order_line_description: translated description
  purchase_order_line_description/models/purchase_order_line.py
  purchase_order_line_description/tests/test_purchase_order_line_description.py
Labels: approved, bot is merging ⏳
