Repository OCA/purchase-workflow, pull requests merged in 2021-06, with the labels that each got.

#1189 [FIX] purchase_discount: access error
  purchase_discount/models/stock_move.py
Labels: bot is merging ⏳

#1196 [14.0][IMP] purchase_request, use tracking=True
  purchase_request/models/purchase_request.py
  purchase_request/models/purchase_request_line.py
  purchase_request/tests/test_purchase_request_to_rfq.py
Labels: approved, bot is merging ⏳

#1207 [14.0][IMP] Change "Purchase requests" to "Purchase Requests"
  purchase_request/views/purchase_request_view.xml
Labels: bot is merging ⏳

#1208 [14.0][IMP] Add seperator tag on filter state
  purchase_request/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳

#1187 [14.0][IMP] purchase_work_acceptance_invoice_plan
  purchase_work_acceptance_invoice_plan/models/purchase.py
Labels: bot is merging ⏳

#1214 [14.0][IMP] purchase_open_qty, field optional='hide'
  purchase_open_qty/views/purchase_view.xml
Labels: approved, bot is merging ⏳

#985 [13.0][ADD] purchase_substate
  purchase_substate/__init__.py
  purchase_substate/__manifest__.py
  purchase_substate/data/purchase_substate_data.xml
  purchase_substate/data/purchase_substate_demo.xml
  purchase_substate/data/purchase_substate_mail_template_data.xml
  purchase_substate/models/__init__.py
  purchase_substate/models/purchase_order.py
  purchase_substate/readme/CONTRIBUTORS.rst
  purchase_substate/readme/DESCRIPTION.rst
  purchase_substate/readme/USAGE.rst
  purchase_substate/static/description/index.html
  purchase_substate/tests/__init__.py
  purchase_substate/tests/test_purchase_substate.py
  purchase_substate/views/purchase_views.xml
  setup/purchase_substate/odoo/addons/purchase_substate
  setup/purchase_substate/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1222 [FIX] purchase_discount: supplierinfo with no template
  purchase_discount/models/product_supplierinfo.py
Labels: approved, bot is merging ⏳
