Repository OCA/purchase-workflow, pull requests merged in 2021-07, with the labels that each got.

#1223 [FIX] purchase_discount: supplierinfo with no template
  purchase_discount/models/product_supplierinfo.py
Labels: approved, bot is merging ⏳

#319 [10.0] [ADD] add new module to allow invoicing from purchase order lines
  purchase_order_line_invoicing/README.rst
  purchase_order_line_invoicing/__init__.py
  purchase_order_line_invoicing/__manifest__.py
  purchase_order_line_invoicing/models/__init__.py
  purchase_order_line_invoicing/models/res_partner.py
  purchase_order_line_invoicing/tests/__init__.py
  purchase_order_line_invoicing/tests/test_purchase_order_line_invoicing_wizard.py
  purchase_order_line_invoicing/views/res_partner_views.xml
  purchase_order_line_invoicing/wizards/__init__.py
  purchase_order_line_invoicing/wizards/purchase_order_line_invoicing_wizard.py
  purchase_order_line_invoicing/wizards/purchase_order_line_invoicing_wizard.xml
  setup/purchase_order_line_invoicing/odoo/__init__.py
  setup/purchase_order_line_invoicing/odoo/addons/__init__.py
  setup/purchase_order_line_invoicing/odoo/addons/purchase_order_line_invoicing
  setup/purchase_order_line_invoicing/setup.py
  setup/purchase_order_lines_invoice/odoo/__init__.py
  setup/purchase_order_lines_invoice/odoo/addons/__init__.py
  setup/purchase_order_lines_invoice/odoo/addons/purchase_order_lines_invoice
  setup/purchase_order_lines_invoice/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1020 [14.0][ADD]purchase_work_acceptance_late_fines
  purchase_work_acceptance_late_fines/__init__.py
  purchase_work_acceptance_late_fines/__manifest__.py
  purchase_work_acceptance_late_fines/models/__init__.py
  purchase_work_acceptance_late_fines/models/account_move.py
  purchase_work_acceptance_late_fines/models/res_company.py
  purchase_work_acceptance_late_fines/models/res_config_settings.py
  purchase_work_acceptance_late_fines/models/work_acceptance.py
  purchase_work_acceptance_late_fines/readme/CONFIGURE.rst
  purchase_work_acceptance_late_fines/readme/CONTRIBUTORS.rst
  purchase_work_acceptance_late_fines/readme/DESCRIPTION.rst
  purchase_work_acceptance_late_fines/readme/USAGE.rst
  purchase_work_acceptance_late_fines/security/security.xml
  purchase_work_acceptance_late_fines/static/description/index.html
  purchase_work_acceptance_late_fines/tests/__init__.py
  purchase_work_acceptance_late_fines/tests/test_work_acceptance_late_fine.py
  purchase_work_acceptance_late_fines/views/account_move_views.xml
  purchase_work_acceptance_late_fines/views/res_config_settings_views.xml
  purchase_work_acceptance_late_fines/views/work_acceptance_views.xml
  setup/purchase_work_acceptance_late_fines/odoo/addons/purchase_work_acceptance_late_fines
  setup/purchase_work_acceptance_late_fines/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1060 [14.0][MIG] purchase_order_line_sequence
  oca_dependencies.txt
  purchase_order_line_sequence/README.rst
  purchase_order_line_sequence/__init__.py
  purchase_order_line_sequence/__manifest__.py
  purchase_order_line_sequence/hooks.py
  purchase_order_line_sequence/i18n/fr.po
  purchase_order_line_sequence/i18n/purchase_order_line_sequence.pot
  purchase_order_line_sequence/models/__init__.py
  purchase_order_line_sequence/models/invoice.py
  purchase_order_line_sequence/models/purchase.py
  purchase_order_line_sequence/models/purchase_line.py
  purchase_order_line_sequence/readme/CONTRIBUTORS.rst
  purchase_order_line_sequence/readme/DESCRIPTION.rst
  purchase_order_line_sequence/readme/ROADMAP.rst
  purchase_order_line_sequence/readme/USAGE.rst
  purchase_order_line_sequence/static/description/icon.png
  purchase_order_line_sequence/static/description/index.html
  purchase_order_line_sequence/tests/__init__.py
  purchase_order_line_sequence/tests/test_po_lines_sequence.py
  purchase_order_line_sequence/views/purchase_view.xml
  purchase_order_line_sequence/views/report_purchaseorder.xml
  purchase_order_line_sequence/views/report_purchasequotation.xml
Labels: approved, bot is merging ⏳, ready to merge

#1181 [14.0][MIG] purchase_request_department: Migration to 14.0
  purchase_request_department/README.rst
  purchase_request_department/__init__.py
  purchase_request_department/__manifest__.py
  purchase_request_department/hooks.py
  purchase_request_department/i18n/de.po
  purchase_request_department/i18n/es.po
  purchase_request_department/i18n/es_EC.po
  purchase_request_department/i18n/fr.po
  purchase_request_department/i18n/hr.po
  purchase_request_department/i18n/it.po
  purchase_request_department/i18n/nb.po
  purchase_request_department/i18n/nb_NO.po
  purchase_request_department/i18n/nl_NL.po
  purchase_request_department/i18n/pt_BR.po
  purchase_request_department/i18n/purchase_request_department.pot
  purchase_request_department/i18n/sl.po
  purchase_request_department/i18n/tr.po
  purchase_request_department/i18n/zh_CN.po
  purchase_request_department/models/__init__.py
  purchase_request_department/models/purchase_request.py
  purchase_request_department/readme/CONTRIBUTORS.rst
  purchase_request_department/readme/CREDITS.rst
  purchase_request_department/readme/DESCRIPTION.rst
  purchase_request_department/readme/USAGE.rst
  purchase_request_department/static/description/icon.png
  purchase_request_department/static/description/index.html
  purchase_request_department/tests/__init__.py
  purchase_request_department/tests/test_purchase_request_department.py
  purchase_request_department/views/purchase_request_department_view.xml
  setup/purchase_request_department/odoo/addons/purchase_request_department
  setup/purchase_request_department/setup.py
Labels: approved, bot is merging ⏳

#1215 [14.0][MIG] purchase_exception
  purchase_exception/__init__.py
  purchase_exception/__manifest__.py
  purchase_exception/data/purchase_exception_data.xml
  purchase_exception/i18n/fr.po
  purchase_exception/i18n/purchase_exception.pot
  purchase_exception/i18n/zh_CN.po
  purchase_exception/models/__init__.py
  purchase_exception/models/exception_rule.py
  purchase_exception/models/purchase.py
  purchase_exception/models/purchase_line.py
  purchase_exception/readme/CONTRIBUTORS.rst
  purchase_exception/readme/DESCRIPTION.rst
  purchase_exception/security/ir.model.access.csv
  purchase_exception/static/description/icon.png
  purchase_exception/static/description/index.html
  purchase_exception/tests/__init__.py
  purchase_exception/tests/test_purchase_exception.py
  purchase_exception/views/purchase_view.xml
  purchase_exception/wizard/__init__.py
  purchase_exception/wizard/purchase_exception_confirm.py
  purchase_exception/wizard/purchase_exception_confirm_view.xml
  setup/purchase_exception/odoo/addons/purchase_exception
  setup/purchase_exception/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1126 [14.0][ADD] purchase_request_cancel_confirm
  purchase_request_cancel_confirm/__init__.py
  purchase_request_cancel_confirm/__manifest__.py
  purchase_request_cancel_confirm/model/__init__.py
  purchase_request_cancel_confirm/model/purchase_request.py
  purchase_request_cancel_confirm/readme/CONTRIBUTORS.rst
  purchase_request_cancel_confirm/readme/DESCRIPTION.rst
  purchase_request_cancel_confirm/static/description/icon.png
  purchase_request_cancel_confirm/static/description/index.html
  purchase_request_cancel_confirm/tests/__init__.py
  purchase_request_cancel_confirm/tests/test_purchase_request_cancel_confirm.py
  setup/purchase_request_cancel_confirm/odoo/addons/purchase_request_cancel_confirm
  setup/purchase_request_cancel_confirm/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1226 [14.0][MIG] purchase_minimum_amount, purchase_order_approval_block
  purchase_minimum_amount/README.rst
  purchase_minimum_amount/__init__.py
  purchase_minimum_amount/__manifest__.py
  purchase_minimum_amount/data/purchase_block_reason_data.xml
  purchase_minimum_amount/i18n/de.po
  purchase_minimum_amount/i18n/es.po
  purchase_minimum_amount/i18n/es_MX.po
  purchase_minimum_amount/i18n/fr.po
  purchase_minimum_amount/i18n/it.po
  purchase_minimum_amount/i18n/pt_BR.po
  purchase_minimum_amount/i18n/purchase_minimum_amount.pot
  purchase_minimum_amount/i18n/sl.po
  purchase_minimum_amount/models/__init__.py
  purchase_minimum_amount/models/partner.py
  purchase_minimum_amount/models/purchase_order.py
  purchase_minimum_amount/readme/CONFIGURE.rst
  purchase_minimum_amount/readme/CONTRIBUTORS.rst
  purchase_minimum_amount/readme/DESCRIPTION.rst
  purchase_minimum_amount/readme/USAGE.rst
  purchase_minimum_amount/static/description/icon.png
  purchase_minimum_amount/static/description/index.html
  purchase_minimum_amount/tests/__init__.py
  purchase_minimum_amount/tests/test_po_minimum_amount_block.py
  purchase_minimum_amount/views/purchase_order_view.xml
  purchase_minimum_amount/views/res_partner_view.xml
  purchase_order_approval_block/README.rst
  purchase_order_approval_block/__init__.py
  purchase_order_approval_block/__manifest__.py
  purchase_order_approval_block/data/purchase_exception_data.xml
  purchase_order_approval_block/i18n/fr.po
  purchase_order_approval_block/i18n/purchase_order_approval_block.pot
  purchase_order_approval_block/models/__init__.py
  purchase_order_approval_block/models/purchase_approval_block_reason.py
  purchase_order_approval_block/models/purchase_order.py
  purchase_order_approval_block/readme/CONFIGURE.rst
  purchase_order_approval_block/readme/CONTRIBUTORS.rst
  purchase_order_approval_block/readme/DESCRIPTION.rst
  purchase_order_approval_block/readme/USAGE.rst
  purchase_order_approval_block/security/ir.model.access.csv
  purchase_order_approval_block/security/purchase_order_approval_block_security.xml
  purchase_order_approval_block/static/description/icon.png
  purchase_order_approval_block/static/description/index.html
  purchase_order_approval_block/tests/__init__.py
  purchase_order_approval_block/tests/test_po_approval_block_reason.py
  purchase_order_approval_block/tests/test_purchase_order_approval_block.py
  purchase_order_approval_block/views/purchase_approval_block_reason_view.xml
  purchase_order_approval_block/views/purchase_order_view.xml
  purchase_order_approval_block/wizard/__init__.py
  purchase_order_approval_block/wizard/purchase_exception_confirm.py
  setup/purchase_minimum_amount/odoo/addons/purchase_minimum_amount
  setup/purchase_minimum_amount/setup.py
  setup/purchase_order_approval_block/odoo/addons/purchase_order_approval_block
  setup/purchase_order_approval_block/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1072 [14.0][ADD] purchase_request_type
  purchase_request_type/__init__.py
  purchase_request_type/__manifest__.py
  purchase_request_type/data/purchase_request_type.xml
  purchase_request_type/models/__init__.py
  purchase_request_type/models/purchase_request.py
  purchase_request_type/models/purchase_request_type.py
  purchase_request_type/readme/CONFIGURE.rst
  purchase_request_type/readme/CONTRIBUTORS.rst
  purchase_request_type/readme/DESCRIPTION.rst
  purchase_request_type/readme/ROADMAP.rst
  purchase_request_type/readme/USAGE.rst
  purchase_request_type/security/ir.model.access.csv
  purchase_request_type/security/security.xml
  purchase_request_type/static/description/icon.png
  purchase_request_type/static/description/index.html
  purchase_request_type/tests/__init__.py
  purchase_request_type/tests/test_purchase_request_type.py
  purchase_request_type/views/purchase_request_type_view.xml
  purchase_request_type/views/purchase_request_view.xml
Labels: bot is merging ⏳

#1030 [14.0][MIG] purchase_order_approved
  purchase_order_approved/README.rst
  purchase_order_approved/__init__.py
  purchase_order_approved/__manifest__.py
  purchase_order_approved/i18n/am.po
  purchase_order_approved/i18n/ar.po
  purchase_order_approved/i18n/ca.po
  purchase_order_approved/i18n/da.po
  purchase_order_approved/i18n/de.po
  purchase_order_approved/i18n/el_GR.po
  purchase_order_approved/i18n/es.po
  purchase_order_approved/i18n/es_ES.po
  purchase_order_approved/i18n/es_MX.po
  purchase_order_approved/i18n/eu.po
  purchase_order_approved/i18n/fi.po
  purchase_order_approved/i18n/fr.po
  purchase_order_approved/i18n/fr_CA.po
  purchase_order_approved/i18n/fr_FR.po
  purchase_order_approved/i18n/gl.po
  purchase_order_approved/i18n/hr.po
  purchase_order_approved/i18n/hr_HR.po
  purchase_order_approved/i18n/it.po
  purchase_order_approved/i18n/nb.po
  purchase_order_approved/i18n/nb_NO.po
  purchase_order_approved/i18n/nl.po
  purchase_order_approved/i18n/nl_BE.po
  purchase_order_approved/i18n/nl_NL.po
  purchase_order_approved/i18n/pt_BR.po
  purchase_order_approved/i18n/purchase_order_approved.pot
  purchase_order_approved/i18n/ro.po
  purchase_order_approved/i18n/sk.po
  purchase_order_approved/i18n/sl.po
  purchase_order_approved/i18n/tr.po
  purchase_order_approved/i18n/vi_VN.po
  purchase_order_approved/i18n/zh_CN.po
  purchase_order_approved/models/__init__.py
  purchase_order_approved/models/purchase_order.py
  purchase_order_approved/models/res_company.py
  purchase_order_approved/models/res_config.py
  purchase_order_approved/readme/CONFIGURE.rst
  purchase_order_approved/readme/CONTRIBUTORS.rst
  purchase_order_approved/readme/DESCRIPTION.rst
  purchase_order_approved/readme/HISTORY.rst
  purchase_order_approved/readme/USAGE.rst
  purchase_order_approved/static/description/icon.png
  purchase_order_approved/static/description/index.html
  purchase_order_approved/static/description/schema.png
  purchase_order_approved/tests/__init__.py
  purchase_order_approved/tests/test_purchase_order_approved.py
  purchase_order_approved/views/purchase_order_view.xml
  purchase_order_approved/views/res_config_view.xml
  setup/purchase_order_approved/odoo/addons/purchase_order_approved
  setup/purchase_order_approved/setup.py
Labels: bot is merging ⏳

#1232 [14.0][IMP] purchase_request, add total estimated cost on PR head
  purchase_request/models/purchase_request.py
  purchase_request/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳

#1229 [11.0][FIX] purchase_allowed_product: Add use_only_supplied_product t…
  purchase_allowed_product/views/account_invoice_view.xml
Labels: bot is merging ⏳

#1220 [13.0][FIX] purchase_delivery_split pickings same date
  purchase_delivery_split_date/models/purchase.py
  purchase_delivery_split_date/tests/test_purchase_delivery.py
Labels: bot is merging ⏳

#1197 [14.0][MIG] - purchase_fop_shipping
  purchase_fop_shipping/README.rst
  purchase_fop_shipping/__init__.py
  purchase_fop_shipping/__manifest__.py
  purchase_fop_shipping/i18n/de.po
  purchase_fop_shipping/i18n/es.po
  purchase_fop_shipping/i18n/es_PE.po
  purchase_fop_shipping/i18n/fr.po
  purchase_fop_shipping/i18n/fr_BE.po
  purchase_fop_shipping/i18n/gl.po
  purchase_fop_shipping/i18n/hr.po
  purchase_fop_shipping/i18n/it.po
  purchase_fop_shipping/i18n/nl.po
  purchase_fop_shipping/i18n/nl_NL.po
  purchase_fop_shipping/i18n/pt_BR.po
  purchase_fop_shipping/i18n/purchase_fop_shipping.pot
  purchase_fop_shipping/i18n/ro.po
  purchase_fop_shipping/i18n/sl.po
  purchase_fop_shipping/i18n/vi_VN.po
  purchase_fop_shipping/models/__init__.py
  purchase_fop_shipping/models/partner.py
  purchase_fop_shipping/models/purchase.py
  purchase_fop_shipping/security/res_groups.xml
  purchase_fop_shipping/static/description/icon.png
  purchase_fop_shipping/tests/__init__.py
  purchase_fop_shipping/tests/test_fop_shipping.py
  purchase_fop_shipping/views/purchase_order.xml
  purchase_fop_shipping/views/res_partner.xml
  setup/purchase_fop_shipping/odoo/addons/purchase_fop_shipping
  setup/purchase_fop_shipping/setup.py
Labels: bot is merging ⏳

#1172 [13.0][MIG] purchase_propagate_qty
  purchase_propagate_qty/README.rst
  purchase_propagate_qty/__init__.py
  purchase_propagate_qty/__manifest__.py
  purchase_propagate_qty/i18n/purchase_propagate_qty.pot
  purchase_propagate_qty/models/__init__.py
  purchase_propagate_qty/models/purchase.py
  purchase_propagate_qty/readme/CONTRIBUTORS.rst
  purchase_propagate_qty/readme/DESCRIPTION.rst
  purchase_propagate_qty/readme/HISTORY.rst
  purchase_propagate_qty/readme/USAGE.rst
  purchase_propagate_qty/static/description/icon.png
  purchase_propagate_qty/static/description/index.html
  purchase_propagate_qty/tests/__init__.py
  purchase_propagate_qty/tests/test_purchase_delivery.py
  setup/purchase_propagate_qty/odoo/addons/purchase_propagate_qty
  setup/purchase_propagate_qty/setup.py
Labels: approved, bot is merging ⏳
