Repository OCA/purchase-workflow, pull requests merged in 2021-05, with the labels that each got.

#1138 [10.0][FIX] purchase_request_to_rfq: domain on existing purchase order lines
  purchase_request_to_rfq/wizard/purchase_request_line_make_purchase_order.py
Labels: bot is merging ⏳

#1165 [13.0][ADD] purchase_order_product_recommendation_xlsx: New module that allow to print recommendations
  purchase_order_product_recommendation_xlsx/README.rst
  purchase_order_product_recommendation_xlsx/__init__.py
  purchase_order_product_recommendation_xlsx/__manifest__.py
  purchase_order_product_recommendation_xlsx/i18n/es.po
  purchase_order_product_recommendation_xlsx/i18n/purchase_order_product_recommendation_xlsx.pot
  purchase_order_product_recommendation_xlsx/readme/CONTRIBUTORS.rst
  purchase_order_product_recommendation_xlsx/readme/DESCRIPTION.rst
  purchase_order_product_recommendation_xlsx/readme/USAGE.rst
  purchase_order_product_recommendation_xlsx/report/__init__.py
  purchase_order_product_recommendation_xlsx/report/recommendation_xlsx.py
  purchase_order_product_recommendation_xlsx/report/recommendation_xlsx.xml
  purchase_order_product_recommendation_xlsx/static/description/index.html
  purchase_order_product_recommendation_xlsx/tests/__init__.py
  purchase_order_product_recommendation_xlsx/tests/test_recommendation.py
  purchase_order_product_recommendation_xlsx/wizards/__init__.py
  purchase_order_product_recommendation_xlsx/wizards/purchase_order_recommendation.py
  purchase_order_product_recommendation_xlsx/wizards/purchase_order_recommendation_view.xml
  setup/purchase_order_product_recommendation_xlsx/odoo/addons/purchase_order_product_recommendation_xlsx
  setup/purchase_order_product_recommendation_xlsx/setup.py
Labels: approved, bot is merging ⏳

#1170 [14.0][FIX] purchase_order_type, default type not set
  purchase_order_type/models/purchase_order.py
  purchase_order_type/tests/test_purchase_order_type.py
Labels: approved, bot is merging ⏳

#1171 [13.0][IMP] purchase_order_product_recommendation: Add Product name and product code
  purchase_order_product_recommendation/i18n/es.po
  purchase_order_product_recommendation/i18n/purchase_order_product_recommendation.pot
  purchase_order_product_recommendation/wizards/purchase_order_recommendation.py
  purchase_order_product_recommendation/wizards/purchase_order_recommendation_view.xml
Labels: approved, bot is merging ⏳

#1016 [14.0][MIG] purchase_isolated_rfq
  purchase_isolated_rfq/README.rst
  purchase_isolated_rfq/__init__.py
  purchase_isolated_rfq/__manifest__.py
  purchase_isolated_rfq/data/ir_sequence_data.xml
  purchase_isolated_rfq/hooks.py
  purchase_isolated_rfq/i18n/purchase_isolated_rfq.pot
  purchase_isolated_rfq/i18n/zh_CN.po
  purchase_isolated_rfq/models/__init__.py
  purchase_isolated_rfq/models/purchase_order.py
  purchase_isolated_rfq/readme/CONTRIBUTORS.rst
  purchase_isolated_rfq/readme/DESCRIPTION.rst
  purchase_isolated_rfq/readme/USAGE.rst
  purchase_isolated_rfq/static/description/icon.png
  purchase_isolated_rfq/static/description/index.html
  purchase_isolated_rfq/tests/__init__.py
  purchase_isolated_rfq/tests/test_purchase_isolated_rfq.py
  purchase_isolated_rfq/views/purchase_views.xml
  setup/purchase_isolated_rfq/odoo/addons/purchase_isolated_rfq
  setup/purchase_isolated_rfq/setup.py
Labels: approved, bot is merging ⏳

#1103 [14.0] [MIG] purchase_product_usage
  purchase_product_usage/README.rst
  purchase_product_usage/__init__.py
  purchase_product_usage/__manifest__.py
  purchase_product_usage/i18n/purchase_product_usage.pot
  purchase_product_usage/i18n/zh_CN.po
  purchase_product_usage/models/__init__.py
  purchase_product_usage/models/account_move.py
  purchase_product_usage/models/purchase_order_line.py
  purchase_product_usage/models/purchase_product_usage.py
  purchase_product_usage/readme/CONFIGURE.rst
  purchase_product_usage/readme/CONTRIBUTORS.rst
  purchase_product_usage/readme/DESCRIPTION.rst
  purchase_product_usage/readme/USAGE.rst
  purchase_product_usage/security/ir.model.access.csv
  purchase_product_usage/security/purchase_product_usage.xml
  purchase_product_usage/static/description/icon.png
  purchase_product_usage/static/description/index.html
  purchase_product_usage/tests/__init__.py
  purchase_product_usage/tests/test_purchase_product_usage.py
  purchase_product_usage/views/purchase_order_line_view.xml
  purchase_product_usage/views/purchase_product_usage_view.xml
  setup/purchase_product_usage/odoo/addons/purchase_product_usage
  setup/purchase_product_usage/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1182 [FIX] purchase_isolated_rfq: Remove selection attribute on rfq_state as it is a related field
  purchase_isolated_rfq/models/purchase_order.py
Labels: bot is merging ⏳

#1174 [14.0][MIG] purchase_reception_notify: Migration to 14.0
  purchase_reception_notify/README.rst
  purchase_reception_notify/__init__.py
  purchase_reception_notify/__manifest__.py
  purchase_reception_notify/data/mail.xml
  purchase_reception_notify/hooks.py
  purchase_reception_notify/i18n/it.po
  purchase_reception_notify/i18n/purchase_reception_notify.pot
  purchase_reception_notify/i18n/zh_CN.po
  purchase_reception_notify/models/__init__.py
  purchase_reception_notify/models/stock_picking.py
  purchase_reception_notify/readme/CONTRIBUTORS.rst
  purchase_reception_notify/readme/DESCRIPTION.rst
  purchase_reception_notify/readme/USAGE.rst
  purchase_reception_notify/static/description/icon.png
  purchase_reception_notify/static/description/index.html
  purchase_reception_notify/tests/__init__.py
  purchase_reception_notify/tests/test_purchase_reception_notify.py
  setup/purchase_reception_notify/odoo/addons/purchase_reception_notify
  setup/purchase_reception_notify/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1175 [13.0][FIX] purchase_delivery_split_date
  purchase_delivery_split_date/models/purchase.py
  purchase_delivery_split_date/tests/test_purchase_delivery.py
Labels: approved, bot is merging ⏳, ready to merge

#1184 [14.0][FIX] purchase_request, action.sudo().read()
  purchase_request/models/purchase_request.py
Labels: approved, bot is merging ⏳

#1120 [14.0][IMP] purchase_request, auto sequence only when saved
  purchase_request/models/purchase_request.py
  purchase_request/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1193 [14.0][FIX] purchase_work_acceptance, action.sudo().read()
  purchase_work_acceptance/models/purchase.py
  purchase_work_acceptance/wizard/select_work_acceptance_wizard.py
Labels: approved, bot is merging ⏳

#1192 [13.0][FIX] purchase_delivery_split_date with tz
  purchase_delivery_split_date/models/purchase.py
  purchase_delivery_split_date/tests/test_purchase_delivery.py
Labels: approved, bot is merging ⏳
