Repository OCA/purchase-workflow, pull requests merged in 2021-08, with the labels that each got.

#1219 [14.0][FIX] purchase_work_acceptance_evaluation, editable evalulation when no state required
  purchase_work_acceptance_evaluation/models/work_acceptance.py
Labels: approved, bot is merging ⏳, ready to merge

#1225 [12.0][MIG] purchase_order_line_packaging_qty
  purchase_order_line_packaging_qty/README.rst
  purchase_order_line_packaging_qty/__init__.py
  purchase_order_line_packaging_qty/__manifest__.py
  purchase_order_line_packaging_qty/i18n/purchase_order_line_packaging_qty.pot
  purchase_order_line_packaging_qty/models/__init__.py
  purchase_order_line_packaging_qty/models/purchase_order_line.py
  purchase_order_line_packaging_qty/models/stock_rule.py
  purchase_order_line_packaging_qty/readme/CONTRIBUTORS.rst
  purchase_order_line_packaging_qty/readme/DESCRIPTION.rst
  purchase_order_line_packaging_qty/static/description/icon.png
  purchase_order_line_packaging_qty/static/description/index.html
  purchase_order_line_packaging_qty/tests/__init__.py
  purchase_order_line_packaging_qty/tests/test_purchase_order_line_packaging_qty.py
  purchase_order_line_packaging_qty/views/purchase_order.xml
Labels: approved, bot is merging ⏳, ready to merge

#1238 Init copier template
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  purchase_all_shipments/__manifest__.py
  purchase_invoice_plan/__manifest__.py
  purchase_order_line_price_history/__manifest__.py
  purchase_order_line_price_history_discount/__manifest__.py
  purchase_request/__manifest__.py
  purchase_substate/__manifest__.py
  supplier_calendar/__manifest__.py
  vendor_transport_lead_time/__manifest__.py
Labels: approved, bot is merging ⏳

#1180 [14.0][IMP] purchase_invoice_plan, misc improvements
  purchase_invoice_plan/models/purchase.py
  purchase_invoice_plan/tests/test_purchase_invoice_plan.py
  purchase_invoice_plan/views/purchase_view.xml
  purchase_invoice_plan/wizard/purchase_make_planned_invoice.py
Labels: bot is merging ⏳

#1237 [12.0][FIX] purchase_request: compute preferred supplier in multicompany
  purchase_request/models/purchase_request_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1245 [14.0][FIX] Remove duplicate record id
  purchase_order_uninvoiced_amount/views/purchase_order_view.xml
Labels: bot is merging ⏳

#1247 [14.0][FIX] purchase_request_type, use tracking=True
  purchase_request_type/models/purchase_request.py
Labels: bot is merging ⏳
