Repository OCA/purchase-workflow, pull requests merged in 2021-04, with the labels that each got.

#1152 [14.0][FIX] purchase_invoice_plan: Fix default journal type
  purchase_invoice_plan/models/purchase.py
Labels: approved, bot is merging ⏳

#1147 [14.0][FIX] purchase_order_type: No need toggle_active button
  purchase_order_type/views/view_purchase_order_type.xml
Labels: bot is merging ⏳

#1098 [14.0] [MIG] purchase_security
  purchase_security/README.rst
  purchase_security/__init__.py
  purchase_security/__manifest__.py
  purchase_security/i18n/it.po
  purchase_security/i18n/purchase_security.pot
  purchase_security/readme/CONFIGURATION.rst
  purchase_security/readme/CONTRIBUTORS.rst
  purchase_security/readme/DESCRIPTION.rst
  purchase_security/readme/USAGE.rst
  purchase_security/security/security.xml
  purchase_security/static/description/icon.png
  purchase_security/static/description/index.html
  purchase_security/tests/__init__.py
  purchase_security/tests/test_access_rights.py
  setup/purchase_security/odoo/addons/purchase_security
  setup/purchase_security/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#952 [10.0][MIG][BACKPORT] purchase_deposit
  purchase_deposit/README.rst
  purchase_deposit/__init__.py
  purchase_deposit/__manifest__.py
  purchase_deposit/i18n/purchase_deposit.pot
  purchase_deposit/models/__init__.py
  purchase_deposit/models/invoice.py
  purchase_deposit/models/purchase.py
  purchase_deposit/models/res_config_settings.py
  purchase_deposit/readme/CONFIGURATION.rst
  purchase_deposit/readme/CONTRIBUTORS.rst
  purchase_deposit/readme/DESCRIPTION.rst
  purchase_deposit/readme/USAGE.rst
  purchase_deposit/static/description/icon.png
  purchase_deposit/static/description/index.html
  purchase_deposit/tests/__init__.py
  purchase_deposit/tests/test_purchase_deposit.py
  purchase_deposit/views/purchase_view.xml
  purchase_deposit/views/res_config_settings_views.xml
  purchase_deposit/wizard/__init__.py
  purchase_deposit/wizard/purchase_make_invoice_advance.py
  purchase_deposit/wizard/purchase_make_invoice_advance_views.xml
Labels: approved, bot is merging ⏳

#1146 [13.0] purchase_delivery_split_date: fix move assign after split
  purchase_delivery_split_date/models/purchase.py
Labels: approved, bot is merging ⏳

#1032 [14.0][MIG] purchase_order_secondary_unit
  oca_dependencies.txt
  purchase_order_secondary_unit/README.rst
  purchase_order_secondary_unit/__init__.py
  purchase_order_secondary_unit/__manifest__.py
  purchase_order_secondary_unit/i18n/es.po
  purchase_order_secondary_unit/i18n/purchase_order_secondary_unit.pot
  purchase_order_secondary_unit/models/__init__.py
  purchase_order_secondary_unit/models/product_template.py
  purchase_order_secondary_unit/models/purchase_order.py
  purchase_order_secondary_unit/readme/CONTRIBUTORS.rst
  purchase_order_secondary_unit/readme/DESCRIPTION.rst
  purchase_order_secondary_unit/readme/USAGE.rst
  purchase_order_secondary_unit/static/description/icon.png
  purchase_order_secondary_unit/static/description/index.html
  purchase_order_secondary_unit/tests/__init__.py
  purchase_order_secondary_unit/tests/test_purchase_order_secondary_unit.py
  purchase_order_secondary_unit/views/product_views.xml
  purchase_order_secondary_unit/views/purchase_order_views.xml
  setup/purchase_order_secondary_unit/odoo/addons/purchase_order_secondary_unit
  setup/purchase_order_secondary_unit/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1021 [14.0][ADD]purchase_work_acceptance_evaluation
  purchase_work_acceptance_evaluation/__init__.py
  purchase_work_acceptance_evaluation/__manifest__.py
  purchase_work_acceptance_evaluation/demo/evaluation_data.xml
  purchase_work_acceptance_evaluation/models/__init__.py
  purchase_work_acceptance_evaluation/models/res_config_settings.py
  purchase_work_acceptance_evaluation/models/work_acceptance.py
  purchase_work_acceptance_evaluation/models/work_acceptance_evaluation.py
  purchase_work_acceptance_evaluation/readme/CONFIGURE.rst
  purchase_work_acceptance_evaluation/readme/CONTRIBUTORS.rst
  purchase_work_acceptance_evaluation/readme/DESCRIPTION.rst
  purchase_work_acceptance_evaluation/readme/USAGE.rst
  purchase_work_acceptance_evaluation/security/ir.model.access.csv
  purchase_work_acceptance_evaluation/security/security.xml
  purchase_work_acceptance_evaluation/static/description/index.html
  purchase_work_acceptance_evaluation/tests/__init__.py
  purchase_work_acceptance_evaluation/tests/test_purchase_work_acceptance_evaluation.py
  purchase_work_acceptance_evaluation/views/res_config_settings_views.xml
  purchase_work_acceptance_evaluation/views/work_acceptance_evaluation_views.xml
  purchase_work_acceptance_evaluation/views/work_acceptance_views.xml
  setup/purchase_work_acceptance_evaluation/odoo/addons/purchase_work_acceptance_evaluation
  setup/purchase_work_acceptance_evaluation/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1079 [14.0][ADD] purchase_rfq_number
  purchase_rfq_number/__init__.py
  purchase_rfq_number/__manifest__.py
  purchase_rfq_number/data/ir_sequence_data.xml
  purchase_rfq_number/models/__init__.py
  purchase_rfq_number/models/purchase_order.py
  purchase_rfq_number/models/res_company.py
  purchase_rfq_number/readme/CONFIGURE.rst
  purchase_rfq_number/readme/CONTRIBUTORS.rst
  purchase_rfq_number/readme/CREDITS.rst
  purchase_rfq_number/readme/DESCRIPTION.rst
  purchase_rfq_number/reports/purchase_report_templates.xml
  purchase_rfq_number/static/description/icon.png
  purchase_rfq_number/tests/__init__.py
  purchase_rfq_number/tests/test_purchase_order.py
  purchase_rfq_number/views/purchase_views.xml
  purchase_rfq_number/views/res_config_settings_views.xml
  setup/purchase_rfq_number/odoo/addons/purchase_rfq_number
  setup/purchase_rfq_number/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1156 [12.0][ADD] Add purchase_requisition_line_description module
  purchase_requisition_line_description/README.rst
  purchase_requisition_line_description/__init__.py
  purchase_requisition_line_description/__manifest__.py
  purchase_requisition_line_description/models/__init__.py
  purchase_requisition_line_description/models/purchase_requisition_line.py
  purchase_requisition_line_description/readme/CONTRIBUTORS.rst
  purchase_requisition_line_description/readme/DESCRIPTION.rst
  purchase_requisition_line_description/readme/USAGE.rst
  purchase_requisition_line_description/report/purchase_requisition_report.xml
  purchase_requisition_line_description/tests/__init__.py
  purchase_requisition_line_description/tests/test_purchase_requisition_line_description.py
  purchase_requisition_line_description/views/purchase_requisition.xml
Labels: approved, bot is merging ⏳, ready to merge

#1160 [14.0][FIX] purchase_work_acceptance: Set invoice date manually on tests
  purchase_work_acceptance/tests/test_purchase_work_acceptance.py
Labels: bot is merging ⏳

#1163 [13.0][FIX] purchase_order_product_recommendation: Fix tests
  purchase_order_product_recommendation/tests/test_recommendation.py
Labels: approved, bot is merging ⏳

#1164 [13.0][FIX] purchase_order_product_recommendation_brand: There is not products when a brand is selected
  purchase_order_product_recommendation_brand/wizards/purchase_order_recommendation.py
Labels: approved, bot is merging ⏳
