Repository OCA/purchase-workflow, pull requests merged in 2021-12, with the labels that each got.

#1049 ADD 8.0 purchase_update_proposal
  purchase_update_proposal/README.rst
  purchase_update_proposal/__init__.py
  purchase_update_proposal/__openerp__.py
  purchase_update_proposal/demo/demo.xml
  purchase_update_proposal/i18n/fr.po
  purchase_update_proposal/models/__init__.py
  purchase_update_proposal/models/partner.py
  purchase_update_proposal/models/purchase_order.py
  purchase_update_proposal/models/purchase_order_line.py
  purchase_update_proposal/models/purchase_proposal.py
  purchase_update_proposal/readme/AUTHOR.rst
  purchase_update_proposal/readme/DESCRIPTION.rst
  purchase_update_proposal/readme/USAGE.rst
  purchase_update_proposal/security/ir.model.access.csv
  purchase_update_proposal/security/security.xml
  purchase_update_proposal/static/description/index.html
  purchase_update_proposal/static/description/purchaser.png
  purchase_update_proposal/static/description/supplier.png
  purchase_update_proposal/tests/__init__.py
  purchase_update_proposal/tests/test_proposal.py
  purchase_update_proposal/tests/test_proposal_with_picking.py
  purchase_update_proposal/views/partner.xml
  purchase_update_proposal/views/purchase_line_proposal.xml
  purchase_update_proposal/views/purchase_order.xml
  purchase_update_proposal/views/supplier_purchase_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#765 [12.0][ADD] purchase_invoice_plan_deposit
  purchase_invoice_plan_deposit/__init__.py
  purchase_invoice_plan_deposit/__manifest__.py
  purchase_invoice_plan_deposit/models/__init__.py
  purchase_invoice_plan_deposit/models/purchase.py
  purchase_invoice_plan_deposit/readme/CONTRIBUTORS.rst
  purchase_invoice_plan_deposit/readme/DESCRIPTION.rst
Labels: needs review, bot is merging ⏳

#1122 [13.0] [REF] purchase_request: move stock.move cancel activity creation in hook
  purchase_request/models/stock_move.py
Labels: bot is merging ⏳

#1309 [13.0][ADD] purchase_partner_selectable_option: This module limits the partners to be selected in the purchases orders.
  purchase_partner_selectable_option/README.rst
  purchase_partner_selectable_option/__init__.py
  purchase_partner_selectable_option/__manifest__.py
  purchase_partner_selectable_option/i18n/es.po
  purchase_partner_selectable_option/i18n/purchase_partner_selectable_option.pot
  purchase_partner_selectable_option/models/__init__.py
  purchase_partner_selectable_option/models/res_partner.py
  purchase_partner_selectable_option/readme/CONTRIBUTORS.rst
  purchase_partner_selectable_option/readme/DESCRIPTION.rst
  purchase_partner_selectable_option/readme/USAGE.rst
  purchase_partner_selectable_option/static/description/icon.png
  purchase_partner_selectable_option/static/description/index.html
  purchase_partner_selectable_option/tests/__init__.py
  purchase_partner_selectable_option/tests/test_purchase_partner_selectable_option.py
  purchase_partner_selectable_option/views/purchase_order_view.xml
  purchase_partner_selectable_option/views/res_partner_view.xml
  setup/purchase_partner_selectable_option/odoo/addons/purchase_partner_selectable_option
  setup/purchase_partner_selectable_option/setup.py
Labels: approved, bot is merging ⏳

#1313 [13.0][FIX][IMP] purchase_security: prevent access error & rules for order lines
  purchase_security/__manifest__.py
  purchase_security/readme/CONTRIBUTORS.rst
  purchase_security/readme/USAGE.rst
  purchase_security/security/security.xml
  purchase_security/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#1317 [13.0][FIX] purchase_partner_selectable_option: Improve domain in partner_id field from purchase order.
  purchase_partner_selectable_option/__manifest__.py
  purchase_partner_selectable_option/models/__init__.py
  purchase_partner_selectable_option/models/purchase_order.py
  purchase_partner_selectable_option/tests/test_purchase_partner_selectable_option.py
  purchase_partner_selectable_option/views/purchase_order_view.xml
Labels: approved, bot is merging ⏳

#1290 [13.0][ADD] purchase_order_type_dashboard
  purchase_order_type_dashboard/__init__.py
  purchase_order_type_dashboard/__manifest__.py
  purchase_order_type_dashboard/models/__init__.py
  purchase_order_type_dashboard/models/purchase_order_type.py
  purchase_order_type_dashboard/readme/CONTRIBUTORS.rst
  purchase_order_type_dashboard/readme/DESCRIPTION.rst
  purchase_order_type_dashboard/tests/__init__.py
  purchase_order_type_dashboard/tests/test_purchase_order_type_dashboard.py
  purchase_order_type_dashboard/views/menu_purchase_order.xml
  purchase_order_type_dashboard/views/view_purchase_order.xml
  purchase_order_type_dashboard/views/view_purchase_order_type.xml
  setup/purchase_order_type_dashboard/setup.py
Labels: bot is merging ⏳

#1314 [14.0][FW] purchase_delivery_split_date: multiple ports from 12.0, 13.0
  purchase_delivery_split_date/models/purchase.py
  purchase_delivery_split_date/readme/HISTORY.rst
  purchase_delivery_split_date/tests/test_purchase_delivery.py
Labels: approved, ready to merge, bot is merging ⏳

#1177 [14.0][ADD] purchase_request_exception
  purchase_request_exception/__init__.py
  purchase_request_exception/__manifest__.py
  purchase_request_exception/data/purchase_request_exception_data.xml
  purchase_request_exception/models/__init__.py
  purchase_request_exception/models/exception_rule.py
  purchase_request_exception/models/purchase_request.py
  purchase_request_exception/models/purchase_request_line.py
  purchase_request_exception/readme/CONTRIBUTORS.rst
  purchase_request_exception/readme/DESCRIPTION.rst
  purchase_request_exception/security/ir.model.access.csv
  purchase_request_exception/static/description/icon.png
  purchase_request_exception/tests/__init__.py
  purchase_request_exception/tests/test_purchase_request_exception.py
  purchase_request_exception/views/purchase_request_view.xml
  purchase_request_exception/wizard/__init__.py
  purchase_request_exception/wizard/purchase_request_exception_confirm.py
  purchase_request_exception/wizard/purchase_request_exception_confirm_view.xml
  setup/purchase_request_exception/odoo/addons/purchase_request_exception
  setup/purchase_request_exception/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1322 [14.0] [MIG] purchase_discount: Port PR from 12.0 to 14.0
  purchase_discount/README.rst
  purchase_discount/models/product_supplierinfo.py
  purchase_discount/models/res_partner.py
  purchase_discount/models/stock_move.py
  purchase_discount/readme/CONTRIBUTORS.rst
  purchase_discount/static/description/index.html
  purchase_discount/views/report_purchaseorder.xml
Labels: approved, bot is merging ⏳

#1320 [15.0][MIG] purchase_reception_notify
  purchase_reception_notify/README.rst
  purchase_reception_notify/__init__.py
  purchase_reception_notify/__manifest__.py
  purchase_reception_notify/data/mail.xml
  purchase_reception_notify/hooks.py
  purchase_reception_notify/i18n/it.po
  purchase_reception_notify/i18n/purchase_reception_notify.pot
  purchase_reception_notify/i18n/zh_CN.po
  purchase_reception_notify/models/__init__.py
  purchase_reception_notify/models/stock_picking.py
  purchase_reception_notify/readme/CONTRIBUTORS.rst
  purchase_reception_notify/readme/DESCRIPTION.rst
  purchase_reception_notify/readme/USAGE.rst
  purchase_reception_notify/static/description/icon.png
  purchase_reception_notify/static/description/index.html
  purchase_reception_notify/tests/__init__.py
  purchase_reception_notify/tests/test_purchase_reception_notify.py
  setup/purchase_reception_notify/odoo/addons/purchase_reception_notify
  setup/purchase_reception_notify/setup.py
Labels: approved, bot is merging ⏳
