Repository OCA/purchase-workflow, pull requests merged in 2022-12, with the labels that each got.

#1678 [14.0][FIX] purchase_*_cancel_confirm: Add missing ir.config_parameter on tests
  purchase_cancel_confirm/tests/test_purchase_cancel_confirm.py
  purchase_request_cancel_confirm/tests/test_purchase_request_cancel_confirm.py
Labels: bot is merging ⏳

#1633 [ADD][14.0] purchase_order_payment_term_report
  purchase_order_payment_term_report/README.rst
  purchase_order_payment_term_report/__init__.py
  purchase_order_payment_term_report/__manifest__.py
  purchase_order_payment_term_report/models/__init__.py
  purchase_order_payment_term_report/models/purchase_order.py
  purchase_order_payment_term_report/readme/CONTRIBUTORS.rst
  purchase_order_payment_term_report/readme/DESCRIPTION.rst
  purchase_order_payment_term_report/reports/report_purchase_order.xml
  purchase_order_payment_term_report/views/purchase_order.xml
  setup/purchase_order_payment_term_report/odoo/addons/purchase_order_payment_term_report
  setup/purchase_order_payment_term_report/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1665 [IMP] purchase_open_qty: remove qty_to_invoice field and computation
  purchase_open_qty/models/purchase_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1680 [15.0][MIG] purchase_security: Migration to version 15.0
  purchase_security/README.rst
  purchase_security/__init__.py
  purchase_security/__manifest__.py
  purchase_security/i18n/it.po
  purchase_security/i18n/purchase_security.pot
  purchase_security/readme/CONFIGURATION.rst
  purchase_security/readme/CONTRIBUTORS.rst
  purchase_security/readme/DESCRIPTION.rst
  purchase_security/readme/USAGE.rst
  purchase_security/security/security.xml
  purchase_security/static/description/icon.png
  purchase_security/static/description/index.html
  purchase_security/tests/__init__.py
  purchase_security/tests/test_access_rights.py
  setup/purchase_security/odoo/addons/purchase_security
  setup/purchase_security/setup.py
Labels: approved, bot is merging ⏳

#1403 [15.0] [MIG] purchase_representative
  purchase_representative/README.rst
  purchase_representative/__init__.py
  purchase_representative/__manifest__.py
  purchase_representative/i18n/purchase_representative.pot
  purchase_representative/models/__init__.py
  purchase_representative/models/stock_rule.py
  purchase_representative/readme/CONTRIBUTORS.rst
  purchase_representative/readme/DESCRIPTION.rst
  purchase_representative/readme/USAGE.rst
  purchase_representative/static/description/icon.png
  purchase_representative/static/description/index.html
  setup/purchase_representative/odoo/addons/purchase_representative
  setup/purchase_representative/setup.py
Labels: approved, bot is merging ⏳

#1682 [13.0][IMP] product_form_purchase_link: do not filter out rfq
  product_form_purchase_link/views/purchase_order_line.xml
Labels: approved, bot is merging ⏳

#1645 [14.0][IMP] purchase_order_vendor_product: fix description, add to file roadmap
  purchase_order_vendor_product/readme/ROADMAP.rst
Labels: approved, ready to merge, bot is merging ⏳

#1677 [16.0][MIG] purchase_commercial_partner
  purchase_commercial_partner/README.rst
  purchase_commercial_partner/__init__.py
  purchase_commercial_partner/__manifest__.py
  purchase_commercial_partner/i18n/de.po
  purchase_commercial_partner/i18n/es.po
  purchase_commercial_partner/i18n/es_ES.po
  purchase_commercial_partner/i18n/es_PE.po
  purchase_commercial_partner/i18n/fr.po
  purchase_commercial_partner/i18n/fr_BE.po
  purchase_commercial_partner/i18n/gl.po
  purchase_commercial_partner/i18n/hr.po
  purchase_commercial_partner/i18n/it.po
  purchase_commercial_partner/i18n/nl.po
  purchase_commercial_partner/i18n/nl_NL.po
  purchase_commercial_partner/i18n/pt_BR.po
  purchase_commercial_partner/i18n/purchase_commercial_partner.pot
  purchase_commercial_partner/i18n/ro.po
  purchase_commercial_partner/i18n/sl.po
  purchase_commercial_partner/i18n/vi_VN.po
  purchase_commercial_partner/models/__init__.py
  purchase_commercial_partner/models/purchase_order.py
  purchase_commercial_partner/readme/CONTRIBUTORS.rst
  purchase_commercial_partner/readme/DESCRIPTION.rst
  purchase_commercial_partner/readme/USAGE.rst
  purchase_commercial_partner/static/description/icon.png
  purchase_commercial_partner/static/description/index.html
  purchase_commercial_partner/views/purchase_order.xml
  purchase_commercial_partner/views/purchase_report.xml
  setup/purchase_commercial_partner/odoo/addons/purchase_commercial_partner
  setup/purchase_commercial_partner/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1622 [15.0][MIG] purchase_order_product_recommendation_brand: Migration to version 15.0
  purchase_order_product_recommendation_brand/README.rst
  purchase_order_product_recommendation_brand/__init__.py
  purchase_order_product_recommendation_brand/__manifest__.py
  purchase_order_product_recommendation_brand/i18n/es.po
  purchase_order_product_recommendation_brand/i18n/purchase_order_product_recommendation_brand.pot
  purchase_order_product_recommendation_brand/readme/CONTRIBUTORS.rst
  purchase_order_product_recommendation_brand/readme/DESCRIPTION.rst
  purchase_order_product_recommendation_brand/readme/ROADMAP.rst
  purchase_order_product_recommendation_brand/readme/USAGE.rst
  purchase_order_product_recommendation_brand/static/description/icon.png
  purchase_order_product_recommendation_brand/static/description/index.html
  purchase_order_product_recommendation_brand/tests/__init__.py
  purchase_order_product_recommendation_brand/tests/test_recommendation.py
  purchase_order_product_recommendation_brand/wizards/__init__.py
  purchase_order_product_recommendation_brand/wizards/purchase_order_recommendation.py
  purchase_order_product_recommendation_brand/wizards/purchase_order_recommendation_view.xml
  setup/purchase_order_product_recommendation_brand/odoo/addons/purchase_order_product_recommendation_brand
  setup/purchase_order_product_recommendation_brand/setup.py
Labels: approved, bot is merging ⏳

#1527 [15.0][MIG] procurement_purchase_sale_no_grouping: Migration to 15.0
  procurement_purchase_sale_no_grouping/README.rst
  procurement_purchase_sale_no_grouping/__init__.py
  procurement_purchase_sale_no_grouping/__manifest__.py
  procurement_purchase_sale_no_grouping/i18n/procurement_purchase_sale_no_grouping.pot
  procurement_purchase_sale_no_grouping/models/__init__.py
  procurement_purchase_sale_no_grouping/models/purchase_order.py
  procurement_purchase_sale_no_grouping/models/sale_order.py
  procurement_purchase_sale_no_grouping/readme/CONFIGURE.rst
  procurement_purchase_sale_no_grouping/readme/CONTRIBUTORS.rst
  procurement_purchase_sale_no_grouping/readme/DESCRIPTION.rst
  procurement_purchase_sale_no_grouping/static/description/icon.png
  procurement_purchase_sale_no_grouping/static/description/index.html
  procurement_purchase_sale_no_grouping/tests/__init__.py
  procurement_purchase_sale_no_grouping/tests/test_procurement_purchase_no_grouping.py
  setup/procurement_purchase_sale_no_grouping/odoo/addons/procurement_purchase_sale_no_grouping
  setup/procurement_purchase_sale_no_grouping/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1688 [15.0][MIG] purchase_order_general_discount: Migration to version 15.0
  purchase_order_general_discount/README.rst
  purchase_order_general_discount/__init__.py
  purchase_order_general_discount/__manifest__.py
  purchase_order_general_discount/i18n/es.po
  purchase_order_general_discount/i18n/pt.po
  purchase_order_general_discount/i18n/purchase_order_general_discount.pot
  purchase_order_general_discount/models/__init__.py
  purchase_order_general_discount/models/purchase_order.py
  purchase_order_general_discount/models/res_company.py
  purchase_order_general_discount/models/res_config_settings.py
  purchase_order_general_discount/models/res_partner.py
  purchase_order_general_discount/readme/CONFIGURE.rst
  purchase_order_general_discount/readme/CONTRIBUTORS.rst
  purchase_order_general_discount/readme/DESCRIPTION.rst
  purchase_order_general_discount/readme/USAGE.rst
  purchase_order_general_discount/static/description/icon.png
  purchase_order_general_discount/static/description/index.html
  purchase_order_general_discount/tests/__init__.py
  purchase_order_general_discount/tests/test_purchase_order_general_discount.py
  purchase_order_general_discount/views/purchase_order_view.xml
  purchase_order_general_discount/views/res_config_view.xml
  purchase_order_general_discount/views/res_partner_view.xml
  setup/purchase_order_general_discount/odoo/addons/purchase_order_general_discount
  setup/purchase_order_general_discount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1660 [14.0][ADD] purchase_vendor_bill_breakdown
  purchase_vendor_bill_breakdown/README.rst
  purchase_vendor_bill_breakdown/__init__.py
  purchase_vendor_bill_breakdown/__manifest__.py
  purchase_vendor_bill_breakdown/data/demo.xml
  purchase_vendor_bill_breakdown/models/__init__.py
  purchase_vendor_bill_breakdown/models/account_move.py
  purchase_vendor_bill_breakdown/models/product_supplierinfo.py
  purchase_vendor_bill_breakdown/models/product_supplierinfo_component.py
  purchase_vendor_bill_breakdown/models/purchase_order.py
  purchase_vendor_bill_breakdown/models/purchase_order_line.py
  purchase_vendor_bill_breakdown/models/purchase_order_line_component.py
  purchase_vendor_bill_breakdown/readme/CONTRIBUTORS.rst
  purchase_vendor_bill_breakdown/readme/DESCRIPTION.rst
  purchase_vendor_bill_breakdown/readme/USAGE.rst
  purchase_vendor_bill_breakdown/security/ir.model.access.csv
  purchase_vendor_bill_breakdown/tests/__init__.py
  purchase_vendor_bill_breakdown/tests/common.py
  purchase_vendor_bill_breakdown/tests/test_account_move_create.py
  purchase_vendor_bill_breakdown/tests/test_components_flow.py
  purchase_vendor_bill_breakdown/tests/test_product_supplierinfo.py
  purchase_vendor_bill_breakdown/tests/test_product_supplierinfo_component.py
  purchase_vendor_bill_breakdown/tests/test_purchase_order.py
  purchase_vendor_bill_breakdown/tests/test_purchase_order_line.py
  purchase_vendor_bill_breakdown/views/product_supplierinfo_views.xml
  purchase_vendor_bill_breakdown/views/product_template_view.xml
  purchase_vendor_bill_breakdown/views/purchase_order_views.xml
  setup/purchase_vendor_bill_breakdown/odoo/addons/purchase_vendor_bill_breakdown
  setup/purchase_vendor_bill_breakdown/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1673 [16.0][ADD] purchase_stock_packaging
  purchase_stock_packaging/README.rst
  purchase_stock_packaging/__init__.py
  purchase_stock_packaging/__manifest__.py
  purchase_stock_packaging/models/__init__.py
  purchase_stock_packaging/models/purchase_order_line.py
  purchase_stock_packaging/readme/CONTRIBUTORS.rst
  purchase_stock_packaging/readme/DESCRIPTION.rst
  purchase_stock_packaging/readme/USAGE.rst
  purchase_stock_packaging/static/description/icon.png
  purchase_stock_packaging/static/description/index.html
  purchase_stock_packaging/tests/__init__.py
  purchase_stock_packaging/tests/test_purchase_packaging.py
  setup/purchase_stock_packaging/odoo/addons/purchase_stock_packaging
  setup/purchase_stock_packaging/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1690 [16.0] [MIG] purchase_order_line_menu
  purchase_order_line_menu/README.rst
  purchase_order_line_menu/__init__.py
  purchase_order_line_menu/__manifest__.py
  purchase_order_line_menu/i18n/es.po
  purchase_order_line_menu/i18n/fr_FR.po
  purchase_order_line_menu/i18n/purchase_order_line_menu.pot
  purchase_order_line_menu/readme/CONTRIBUTORS.rst
  purchase_order_line_menu/readme/DESCRIPTION.rst
  purchase_order_line_menu/readme/USAGE.rst
  purchase_order_line_menu/static/description/icon.png
  purchase_order_line_menu/static/description/index.html
  purchase_order_line_menu/views/purchase_order_line_views.xml
  setup/purchase_order_line_menu/odoo/addons/purchase_order_line_menu
  setup/purchase_order_line_menu/setup.py
Labels: approved, ready to merge, bot is merging ⏳
