Repository OCA/purchase-workflow, pull requests merged in 2022-09, with the labels that each got.

#1375 [14.0][MIG] purchase_stock_price_unit_sync: Migration to 14.0
  purchase_stock_price_unit_sync/README.rst
  purchase_stock_price_unit_sync/__init__.py
  purchase_stock_price_unit_sync/__manifest__.py
  purchase_stock_price_unit_sync/i18n/purchase_stock_price_unit_sync.pot
  purchase_stock_price_unit_sync/models/__init__.py
  purchase_stock_price_unit_sync/models/purchase_order.py
  purchase_stock_price_unit_sync/readme/CONTRIBUTORS.rst
  purchase_stock_price_unit_sync/readme/DESCRIPTION.rst
  purchase_stock_price_unit_sync/static/description/icon.png
  purchase_stock_price_unit_sync/static/description/index.html
  purchase_stock_price_unit_sync/tests/__init__.py
  purchase_stock_price_unit_sync/tests/test_purchase_stock_price_unit_sync.py
  setup/purchase_stock_price_unit_sync/odoo/addons/purchase_stock_price_unit_sync
  setup/purchase_stock_price_unit_sync/setup.py
Labels: approved, bot is merging ⏳

#1556 [13.0][IMP] purchase_order_uninvoiced_amount: Make field stored to fix the grouped sum values in purchase tree view
  purchase_order_uninvoiced_amount/models/purchase_order.py
Labels: approved, bot is merging ⏳

#1558 [14.0][IMP] purchase_order_uninvoiced_amount: Make field stored to fix the grouped sum values in purchase tree view
  purchase_order_uninvoiced_amount/models/purchase_order.py
Labels: approved, bot is merging ⏳

#1559 [13.0][FIX] purchase_landed_cost: Avoid error in moves if the user does not have any purchase permission.
  purchase_landed_cost/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#1529 [14.0][FIX] duplicate quantity on manual delivery
  purchase_manual_delivery/wizard/create_manual_stock_picking.py
Labels: approved, bot is merging ⏳

#1439 [14.0][FIX] purchase_request: merging two lines had wrong quantities
  purchase_request/models/purchase_request_line.py
Labels: approved, bot is merging ⏳

#1544 [IMP] purchase_request: make mail sending optional
  purchase_request/__manifest__.py
  purchase_request/models/__init__.py
  purchase_request/models/purchase_order.py
  purchase_request/models/purchase_request_allocation.py
  purchase_request/models/res_company.py
  purchase_request/models/res_config_settings.py
  purchase_request/models/stock_move_line.py
  purchase_request/models/stock_picking.py
  purchase_request/readme/CONFIGURE.rst
  purchase_request/views/res_config_settings.xml
Labels: bot is merging ⏳

#1498 [15.0][MIG] purchase_location_by_line
  purchase_location_by_line/README.rst
  purchase_location_by_line/__init__.py
  purchase_location_by_line/__manifest__.py
  purchase_location_by_line/i18n/ca.po
  purchase_location_by_line/i18n/de.po
  purchase_location_by_line/i18n/es.po
  purchase_location_by_line/i18n/es_MX.po
  purchase_location_by_line/i18n/es_PE.po
  purchase_location_by_line/i18n/fi.po
  purchase_location_by_line/i18n/fr.po
  purchase_location_by_line/i18n/gl.po
  purchase_location_by_line/i18n/hr.po
  purchase_location_by_line/i18n/it.po
  purchase_location_by_line/i18n/nl_NL.po
  purchase_location_by_line/i18n/pt_BR.po
  purchase_location_by_line/i18n/pt_PT.po
  purchase_location_by_line/i18n/purchase_location_by_line.pot
  purchase_location_by_line/i18n/ro.po
  purchase_location_by_line/i18n/sl.po
  purchase_location_by_line/models/__init__.py
  purchase_location_by_line/models/purchase.py
  purchase_location_by_line/models/stock_picking.py
  purchase_location_by_line/readme/CONTRIBUTORS.rst
  purchase_location_by_line/readme/DESCRIPTION.rst
  purchase_location_by_line/static/description/icon.png
  purchase_location_by_line/static/description/index.html
  purchase_location_by_line/tests/__init__.py
  purchase_location_by_line/tests/test_purchase_delivery.py
  purchase_location_by_line/views/purchase_view.xml
  setup/purchase_location_by_line/odoo/addons/purchase_location_by_line
  setup/purchase_location_by_line/setup.py
Labels: approved, bot is merging ⏳

#1533 [IMP] purchase_partner_incoterm: use commercial_partner_id
  purchase_partner_incoterm/__manifest__.py
  purchase_partner_incoterm/migrations/14.0.3.0.0/post-migration.py
  purchase_partner_incoterm/models/purchase_order.py
  purchase_partner_incoterm/models/res_partner.py
  purchase_partner_incoterm/readme/CONTRIBUTORS.rst
  purchase_partner_incoterm/views/partner_view.xml
Labels: approved, bot is merging ⏳

#1337 [15.0][MIG] purchase_advance_payment
  purchase_advance_payment/README.rst
  purchase_advance_payment/__init__.py
  purchase_advance_payment/__manifest__.py
  purchase_advance_payment/i18n/fr.po
  purchase_advance_payment/i18n/purchase_advance_payment.pot
  purchase_advance_payment/models/__init__.py
  purchase_advance_payment/models/payment.py
  purchase_advance_payment/models/purchase_order.py
  purchase_advance_payment/readme/CONTRIBUTORS.rst
  purchase_advance_payment/readme/DESCRIPTION.rst
  purchase_advance_payment/readme/USAGE.rst
  purchase_advance_payment/security/ir.model.access.csv
  purchase_advance_payment/static/description/icon.png
  purchase_advance_payment/static/description/index.html
  purchase_advance_payment/tests/__init__.py
  purchase_advance_payment/tests/test_purchase_advance_payment.py
  purchase_advance_payment/views/purchase_view.xml
  purchase_advance_payment/wizard/__init__.py
  purchase_advance_payment/wizard/purchase_advance_payment_wizard.py
  purchase_advance_payment/wizard/purchase_advance_payment_wizard_view.xml
  setup/purchase_advance_payment/odoo/addons/purchase_advance_payment
  setup/purchase_advance_payment/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1567 [14.0][MIG] purchase_order_qty_change_no_recompute
  purchase_order_qty_change_no_recompute/README.rst
  purchase_order_qty_change_no_recompute/__init__.py
  purchase_order_qty_change_no_recompute/__manifest__.py
  purchase_order_qty_change_no_recompute/i18n/purchase_order_qty_change_no_recompute.pot
  purchase_order_qty_change_no_recompute/models/__init__.py
  purchase_order_qty_change_no_recompute/models/purchase_order.py
  purchase_order_qty_change_no_recompute/readme/CONTRIBUTORS.rst
  purchase_order_qty_change_no_recompute/readme/DESCRIPTION.rst
  purchase_order_qty_change_no_recompute/readme/USAGE.rst
  purchase_order_qty_change_no_recompute/static/description/icon.png
  purchase_order_qty_change_no_recompute/static/description/index.html
  purchase_order_qty_change_no_recompute/tests/__init__.py
  purchase_order_qty_change_no_recompute/tests/test_purchase_order_qty_change.py
  setup/purchase_order_qty_change_no_recompute/odoo/addons/purchase_order_qty_change_no_recompute
  setup/purchase_order_qty_change_no_recompute/setup.py
Labels: approved, bot is merging ⏳

#1573 [13.0][FIX] purchase_blanket_order: Misc changes
  purchase_blanket_order/models/blanket_orders.py
  purchase_blanket_order/report/templates.xml
  purchase_blanket_order/views/purchase_blanket_order_views.xml
Labels: approved, bot is merging ⏳

#1450 [15.0] [MIG] purchase_exception
  oca_dependencies.txt
  purchase_exception/README.rst
  purchase_exception/__init__.py
  purchase_exception/__manifest__.py
  purchase_exception/data/purchase_exception_data.xml
  purchase_exception/i18n/fr.po
  purchase_exception/i18n/purchase_exception.pot
  purchase_exception/i18n/zh_CN.po
  purchase_exception/models/__init__.py
  purchase_exception/models/exception_rule.py
  purchase_exception/models/purchase.py
  purchase_exception/models/purchase_line.py
  purchase_exception/readme/CONTRIBUTORS.rst
  purchase_exception/readme/DESCRIPTION.rst
  purchase_exception/security/ir.model.access.csv
  purchase_exception/static/description/icon.png
  purchase_exception/static/description/index.html
  purchase_exception/tests/__init__.py
  purchase_exception/tests/test_purchase_exception.py
  purchase_exception/views/purchase_view.xml
  purchase_exception/wizard/__init__.py
  purchase_exception/wizard/purchase_exception_confirm.py
  purchase_exception/wizard/purchase_exception_confirm_view.xml
  setup/purchase_exception/odoo/addons/purchase_exception
  setup/purchase_exception/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1575 [15.0][FIX] purchase_blanket_order: Misc changes
  purchase_blanket_order/report/templates.xml
  purchase_blanket_order/views/purchase_blanket_order_views.xml
Labels: approved, bot is merging ⏳

#1581 [13.0][FIX] purchase_blanket_order: Set force_save="1" to Order Lines to prevent inconsistencies
  purchase_blanket_order/views/purchase_blanket_order_views.xml
Labels: approved, bot is merging ⏳

#1582 [14.0][FIX] purchase_blanket_order: Set force_save="1" to Order Lines to prevent inconsistencies
  purchase_blanket_order/views/purchase_blanket_order_views.xml
Labels: bot is merging ⏳

#1583 [15.0][FIX] purchase_blanket_order: Set force_save="1" to Order Lines to prevent inconsistencies
  purchase_blanket_order/views/purchase_blanket_order_views.xml
Labels: bot is merging ⏳

#1584 [15.0][MIG] purchase_order_line_price_history: Migration to 15.0
  purchase_order_line_price_history/README.rst
  purchase_order_line_price_history/__init__.py
  purchase_order_line_price_history/__manifest__.py
  purchase_order_line_price_history/i18n/de.po
  purchase_order_line_price_history/i18n/es.po
  purchase_order_line_price_history/i18n/fr.po
  purchase_order_line_price_history/i18n/nl_NL.po
  purchase_order_line_price_history/i18n/purchase_order_line_price_history.pot
  purchase_order_line_price_history/readme/CONTRIBUTORS.rst
  purchase_order_line_price_history/readme/DESCRIPTION.rst
  purchase_order_line_price_history/readme/ROADMAP.rst
  purchase_order_line_price_history/readme/USAGE.rst
  purchase_order_line_price_history/security/ir.model.access.csv
  purchase_order_line_price_history/static/description/icon.png
  purchase_order_line_price_history/static/description/index.html
  purchase_order_line_price_history/tests/__init__.py
  purchase_order_line_price_history/tests/test_purchase_order_line_price_history.py
  purchase_order_line_price_history/views/purchase_views.xml
  purchase_order_line_price_history/wizards/__init__.py
  purchase_order_line_price_history/wizards/purchase_order_line_price_history.py
  purchase_order_line_price_history/wizards/purchase_order_line_price_history.xml
  setup/purchase_order_line_price_history/odoo/addons/purchase_order_line_price_history
  setup/purchase_order_line_price_history/setup.py
Labels: approved, bot is merging ⏳
