Repository OCA/purchase-workflow, pull requests merged in 2022-07, with the labels that each got.

#1511 [15.0][IMP] purchase_blanket_order: Add partner_ref field + order blanket orders from date_start desc field.
  purchase_blanket_order/models/blanket_orders.py
  purchase_blanket_order/tests/test_purchase_blanket_order.py
  purchase_blanket_order/views/purchase_blanket_order_views.xml
  purchase_blanket_order/wizard/create_purchase_orders.py
Labels: bot is merging ⏳

#1512 [15.0][FIX] purchase_blanket_order: Set name by sequence only if is necessary.
  purchase_blanket_order/models/blanket_orders.py
  purchase_blanket_order/tests/test_purchase_blanket_order.py
Labels: bot is merging ⏳

#1480 [13.0][IMP] purchase_discount: flag discount hack
  purchase_discount/models/purchase_order.py
  purchase_stock_price_unit_sync/models/purchase_order.py
Labels: approved, bot is merging ⏳

#1520 [UPD] Switch to Github Actions
  .copier-answers.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
  purchase_minimum_amount/__init__.py
  purchase_minimum_amount/__manifest__.py
  purchase_minimum_amount/data/purchase_block_reason_data.xml
  purchase_minimum_amount/models/__init__.py
  purchase_minimum_amount/models/partner.py
  purchase_minimum_amount/models/purchase_order.py
  purchase_minimum_amount/tests/__init__.py
  purchase_minimum_amount/tests/test_po_minimum_amount_block.py
  purchase_minimum_amount/views/purchase_order_view.xml
  purchase_minimum_amount/views/res_partner_view.xml
  purchase_order_approval_block/__init__.py
  purchase_order_approval_block/__manifest__.py
  purchase_order_approval_block/models/purchase_approval_block_reason.py
  purchase_order_approval_block/models/purchase_order.py
  purchase_order_approval_block/security/purchase_order_approval_block_security.xml
  purchase_order_approval_block/tests/__init__.py
  purchase_order_approval_block/tests/test_po_approval_block_reason.py
  purchase_order_approval_block/tests/test_purchase_order_approval_block.py
  purchase_order_approval_block/views/purchase_approval_block_reason_view.xml
  purchase_order_approval_block/views/purchase_order_view.xml
  purchase_order_approval_block/wizard/__init__.py
  purchase_order_approval_block/wizard/purchase_exception_confirm.py
  purchase_order_line_sequence/__manifest__.py
  setup/purchase_order_line_sequence/odoo/addons/purchase_order_line_sequence
  setup/purchase_order_line_sequence/setup.py
Labels: bot is merging ⏳

#854 [IMP] purchase_order_approved: Allows to activate the two-step approv…
  purchase_order_approved/README.rst
  purchase_order_approved/__manifest__.py
  purchase_order_approved/models/__init__.py
  purchase_order_approved/models/purchase_order.py
  purchase_order_approved/models/res_partner.py
  purchase_order_approved/tests/__init__.py
  purchase_order_approved/tests/test_purchase_order.py
  purchase_order_approved/views/res_partner.xml
Labels: bot is merging ⏳

#1523 [13.0][FIX] purchase_blanket_order: multi company rules not migrated
  purchase_blanket_order/models/blanket_orders.py
  purchase_blanket_order/security/security.xml
Labels: approved, bot is merging ⏳

#1525 [15.0][FIX] purchase_blanket_order: multi company rules not migrated
  purchase_blanket_order/models/blanket_orders.py
  purchase_blanket_order/security/security.xml
Labels: bot is merging ⏳

#1524 [14.0][FIX] purchase_blanket_order: multi company rules not migrated
  purchase_blanket_order/models/blanket_orders.py
  purchase_blanket_order/security/security.xml
Labels: bot is merging ⏳

#1447 [14.0][ADD] sale_purchase_force_vendor: New addon.
  purchase_order_line_invoicing/models/res_partner.py
  sale_purchase_force_vendor/README.rst
  sale_purchase_force_vendor/__init__.py
  sale_purchase_force_vendor/__manifest__.py
  sale_purchase_force_vendor/i18n/es.po
  sale_purchase_force_vendor/i18n/sale_purchase_force_vendor.pot
  sale_purchase_force_vendor/models/__init__.py
  sale_purchase_force_vendor/models/res_company.py
  sale_purchase_force_vendor/models/res_config_settings.py
  sale_purchase_force_vendor/models/sale_order_line.py
  sale_purchase_force_vendor/models/stock_move.py
  sale_purchase_force_vendor/readme/CONFIGURE.rst
  sale_purchase_force_vendor/readme/CONTRIBUTORS.rst
  sale_purchase_force_vendor/readme/DESCRIPTION.st
  sale_purchase_force_vendor/readme/USAGE.rst
  sale_purchase_force_vendor/static/description/icon.png
  sale_purchase_force_vendor/static/description/index.html
  sale_purchase_force_vendor/tests/__init__.py
  sale_purchase_force_vendor/tests/common.py
  sale_purchase_force_vendor/tests/test_sale_purchase_force_vendor.py
  sale_purchase_force_vendor/views/res_config_settings_view.xml
  sale_purchase_force_vendor/views/sale_order_view.xml
  setup/sale_purchase_force_vendor/odoo/addons/sale_purchase_force_vendor
  setup/sale_purchase_force_vendor/setup.py
Labels: approved, bot is merging ⏳

#1519 [15.0][MIG] purchase_order_qty_change_no_recompute: Migration to 15.0
  purchase_order_qty_change_no_recompute/README.rst
  purchase_order_qty_change_no_recompute/__init__.py
  purchase_order_qty_change_no_recompute/__manifest__.py
  purchase_order_qty_change_no_recompute/i18n/purchase_order_qty_change_no_recompute.pot
  purchase_order_qty_change_no_recompute/models/__init__.py
  purchase_order_qty_change_no_recompute/models/purchase_order.py
  purchase_order_qty_change_no_recompute/readme/CONTRIBUTORS.rst
  purchase_order_qty_change_no_recompute/readme/DESCRIPTION.rst
  purchase_order_qty_change_no_recompute/readme/USAGE.rst
  purchase_order_qty_change_no_recompute/static/description/icon.png
  purchase_order_qty_change_no_recompute/static/description/index.html
  purchase_order_qty_change_no_recompute/tests/__init__.py
  purchase_order_qty_change_no_recompute/tests/test_purchase_order_qty_change.py
  setup/purchase_order_qty_change_no_recompute/odoo/addons/purchase_order_qty_change_no_recompute
  setup/purchase_order_qty_change_no_recompute/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1528 [13.0][FIX] purchase_blanket_order: Don't compare with translatable string
  purchase_blanket_order/models/blanket_orders.py
Labels: approved, bot is merging ⏳

#1518 [15.0][MIG] purchase_order_product_recommendation: Migration to 15.0
  purchase_order_product_recommendation/README.rst
  purchase_order_product_recommendation/__init__.py
  purchase_order_product_recommendation/__manifest__.py
  purchase_order_product_recommendation/i18n/es.po
  purchase_order_product_recommendation/i18n/purchase_order_product_recommendation.pot
  purchase_order_product_recommendation/readme/CONTRIBUTORS.rst
  purchase_order_product_recommendation/readme/DESCRIPTION.rst
  purchase_order_product_recommendation/readme/USAGE.rst
  purchase_order_product_recommendation/security/ir.model.access.csv
  purchase_order_product_recommendation/static/description/icon.png
  purchase_order_product_recommendation/static/description/index.html
  purchase_order_product_recommendation/tests/__init__.py
  purchase_order_product_recommendation/tests/test_recommendation.py
  purchase_order_product_recommendation/views/purchase_order_view.xml
  purchase_order_product_recommendation/wizards/__init__.py
  purchase_order_product_recommendation/wizards/purchase_order_recommendation.py
  purchase_order_product_recommendation/wizards/purchase_order_recommendation_view.xml
  setup/purchase_order_product_recommendation/odoo/addons/purchase_order_product_recommendation
  setup/purchase_order_product_recommendation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1526 [15.0][MIG] procurement_purchase_no_grouping: Migration to 15.0
  procurement_purchase_no_grouping/README.rst
  procurement_purchase_no_grouping/__init__.py
  procurement_purchase_no_grouping/__manifest__.py
  procurement_purchase_no_grouping/i18n/de.po
  procurement_purchase_no_grouping/i18n/es.po
  procurement_purchase_no_grouping/i18n/es_ES.po
  procurement_purchase_no_grouping/i18n/es_MX.po
  procurement_purchase_no_grouping/i18n/es_PE.po
  procurement_purchase_no_grouping/i18n/fi.po
  procurement_purchase_no_grouping/i18n/fr.po
  procurement_purchase_no_grouping/i18n/fr_BE.po
  procurement_purchase_no_grouping/i18n/fr_FR.po
  procurement_purchase_no_grouping/i18n/gl.po
  procurement_purchase_no_grouping/i18n/hr.po
  procurement_purchase_no_grouping/i18n/it.po
  procurement_purchase_no_grouping/i18n/nl.po
  procurement_purchase_no_grouping/i18n/nl_NL.po
  procurement_purchase_no_grouping/i18n/procurement_purchase_no_grouping.pot
  procurement_purchase_no_grouping/i18n/pt_BR.po
  procurement_purchase_no_grouping/i18n/pt_PT.po
  procurement_purchase_no_grouping/i18n/ro.po
  procurement_purchase_no_grouping/i18n/sl.po
  procurement_purchase_no_grouping/i18n/tr_TR.po
  procurement_purchase_no_grouping/i18n/vi_VN.po
  procurement_purchase_no_grouping/i18n/zh_CN.po
  procurement_purchase_no_grouping/models/__init__.py
  procurement_purchase_no_grouping/models/product_category.py
  procurement_purchase_no_grouping/models/purchase_order.py
  procurement_purchase_no_grouping/models/res_company.py
  procurement_purchase_no_grouping/models/res_config_settings.py
  procurement_purchase_no_grouping/models/stock_rule.py
  procurement_purchase_no_grouping/readme/CONFIGURE.rst
  procurement_purchase_no_grouping/readme/CONTRIBUTORS.rst
  procurement_purchase_no_grouping/readme/DESCRIPTION.rst
  procurement_purchase_no_grouping/readme/ROADMAP.rst
  procurement_purchase_no_grouping/static/description/icon.png
  procurement_purchase_no_grouping/static/description/index.html
  procurement_purchase_no_grouping/tests/__init__.py
  procurement_purchase_no_grouping/tests/test_procurement_purchase_no_grouping.py
  procurement_purchase_no_grouping/views/product_category_view.xml
  procurement_purchase_no_grouping/views/res_config_settings_views.xml
  setup/procurement_purchase_no_grouping/odoo/addons/procurement_purchase_no_grouping
  setup/procurement_purchase_no_grouping/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1515 [15.0] [IMP] purchase_receipt_expectation_manual_split: set split PO line's planned date
  purchase_receipt_expectation_manual_split/wizards/purchase_order_manual_receipt_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1431 [FIX] [15.0] `purchase_receipt_exceptation_manual_split`: Revert quantities with partial pickings
  purchase_receipt_expectation_manual_split/models/__init__.py
  purchase_receipt_expectation_manual_split/models/purchase_order_line.py
  purchase_receipt_expectation_manual_split/models/stock_move.py
  purchase_receipt_expectation_manual_split/models/stock_picking.py
  purchase_receipt_expectation_manual_split/tests/test_purchase_receipt_expectation_manual_split.py
Labels: approved, ready to merge, bot is merging ⏳

#1336 [14.0][FIX] purchase_rfq_number : Keep po name from action cancel po > reset to draft > confirm order
  purchase_rfq_number/models/purchase_order.py
  purchase_rfq_number/views/purchase_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1500 [12.0][ADD] purchase_start_end_dates
  purchase_start_end_dates/__init__.py
  purchase_start_end_dates/__manifest__.py
  purchase_start_end_dates/i18n/de.po
  purchase_start_end_dates/i18n/purchase_start_end_dates.pot
  purchase_start_end_dates/models/__init__.py
  purchase_start_end_dates/models/account_invoice.py
  purchase_start_end_dates/models/purchase_order.py
  purchase_start_end_dates/tests/__init__.py
  purchase_start_end_dates/tests/test_purchase_start_end_dates.py
  purchase_start_end_dates/views/purchase_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#1420 [15.0] [ADD] purchase_order_no_zero_price
  purchase_delivery_split_date/tests/test_purchase_delivery.py
  purchase_order_no_zero_price/README.rst
  purchase_order_no_zero_price/__init__.py
  purchase_order_no_zero_price/__manifest__.py
  purchase_order_no_zero_price/models/__init__.py
  purchase_order_no_zero_price/models/purchase_order_line.py
  purchase_order_no_zero_price/readme/CONTRIBUTORS.rst
  purchase_order_no_zero_price/readme/DESCRIPTION.rst
  purchase_order_no_zero_price/readme/USAGE.rst
  purchase_order_no_zero_price/tests/__init__.py
  purchase_order_no_zero_price/tests/test_purchase_order_no_zero_price.py
  purchase_request/tests/test_purchase_request_allocation.py
  purchase_request/tests/test_purchase_request_to_rfq.py
  setup/purchase_order_no_zero_price/odoo/addons/purchase_order_no_zero_price
  setup/purchase_order_no_zero_price/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1517 [15.0][MIG] purchase_partner_selectable_option: Migration to 15.0
  purchase_partner_selectable_option/README.rst
  purchase_partner_selectable_option/__init__.py
  purchase_partner_selectable_option/__manifest__.py
  purchase_partner_selectable_option/i18n/es.po
  purchase_partner_selectable_option/i18n/purchase_partner_selectable_option.pot
  purchase_partner_selectable_option/models/__init__.py
  purchase_partner_selectable_option/models/purchase_order.py
  purchase_partner_selectable_option/models/res_partner.py
  purchase_partner_selectable_option/readme/CONFIGURE.rst
  purchase_partner_selectable_option/readme/CONTRIBUTORS.rst
  purchase_partner_selectable_option/readme/DESCRIPTION.rst
  purchase_partner_selectable_option/readme/USAGE.rst
  purchase_partner_selectable_option/static/description/icon.png
  purchase_partner_selectable_option/static/description/index.html
  purchase_partner_selectable_option/tests/__init__.py
  purchase_partner_selectable_option/tests/test_purchase_partner_selectable_option.py
  purchase_partner_selectable_option/views/res_partner_view.xml
  setup/purchase_partner_selectable_option/odoo/addons/purchase_partner_selectable_option
  setup/purchase_partner_selectable_option/setup.py
Labels: approved, bot is merging ⏳
