Repository OCA/purchase-workflow, pull requests merged in 2022-11, with the labels that each got.

#1590 [13.0][ADD] purchase_origin_link_sale: add a link to the Sale Order
  purchase_origin_link_sale/__init__.py
  purchase_origin_link_sale/__manifest__.py
  purchase_origin_link_sale/models/__init__.py
  purchase_origin_link_sale/models/purchase.py
  purchase_origin_link_sale/readme/CONTRIBUTORS.rst
  purchase_origin_link_sale/readme/DESCRIPTION.rst
  purchase_origin_link_sale/tests/__init__.py
  purchase_origin_link_sale/tests/test_purchase_origin_link_sale.py
  setup/purchase_origin_link_sale/odoo/addons/purchase_origin_link_sale
  setup/purchase_origin_link_sale/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1621 [15.0] Updated from template
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: bot is merging ⏳

#1424 15.0 mig purchase request department
  purchase_request_department/README.rst
  purchase_request_department/__init__.py
  purchase_request_department/__manifest__.py
  purchase_request_department/hooks.py
  purchase_request_department/i18n/de.po
  purchase_request_department/i18n/es.po
  purchase_request_department/i18n/es_EC.po
  purchase_request_department/i18n/fr.po
  purchase_request_department/i18n/hr.po
  purchase_request_department/i18n/it.po
  purchase_request_department/i18n/nb.po
  purchase_request_department/i18n/nb_NO.po
  purchase_request_department/i18n/nl_NL.po
  purchase_request_department/i18n/pt_BR.po
  purchase_request_department/i18n/purchase_request_department.pot
  purchase_request_department/i18n/sl.po
  purchase_request_department/i18n/tr.po
  purchase_request_department/i18n/zh_CN.po
  purchase_request_department/models/__init__.py
  purchase_request_department/models/purchase_request.py
  purchase_request_department/readme/CONTRIBUTORS.rst
  purchase_request_department/readme/CREDITS.rst
  purchase_request_department/readme/DESCRIPTION.rst
  purchase_request_department/readme/USAGE.rst
  purchase_request_department/static/description/icon.png
  purchase_request_department/static/description/index.html
  purchase_request_department/tests/__init__.py
  purchase_request_department/tests/test_purchase_request_department.py
  purchase_request_department/views/purchase_request_department_view.xml
  setup/purchase_request_department/odoo/addons/purchase_request_department
  setup/purchase_request_department/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1607 [15.0][MIG] purchase_order_line_price_history_discount: Migration to version 15.0
  purchase_order_line_price_history_discount/README.rst
  purchase_order_line_price_history_discount/__init__.py
  purchase_order_line_price_history_discount/__manifest__.py
  purchase_order_line_price_history_discount/i18n/es.po
  purchase_order_line_price_history_discount/i18n/purchase_order_line_price_history_discount.pot
  purchase_order_line_price_history_discount/readme/CONTRIBUTORS.rst
  purchase_order_line_price_history_discount/readme/DESCRIPTION.rst
  purchase_order_line_price_history_discount/readme/USAGE.rst
  purchase_order_line_price_history_discount/static/description/icon.png
  purchase_order_line_price_history_discount/static/description/index.html
  purchase_order_line_price_history_discount/tests/__init__.py
  purchase_order_line_price_history_discount/tests/test_purchase_order_line_price_history_discount.py
  purchase_order_line_price_history_discount/wizards/__init__.py
  purchase_order_line_price_history_discount/wizards/purchase_order_line_price_history.py
  purchase_order_line_price_history_discount/wizards/purchase_order_line_price_history.xml
  setup/purchase_order_line_price_history_discount/odoo/addons/purchase_order_line_price_history_discount
  setup/purchase_order_line_price_history_discount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1623 [14.0] Updated from template
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#1618 [14.0] purchase_request: fix done purchase_request_line
  purchase_request/models/purchase_request.py
  purchase_request/models/purchase_request_line.py
  purchase_request/tests/__init__.py
  purchase_request/tests/test_purchase_request_dest_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1609 [15.0][MIG] purchase_order_uninvoiced_amount: Migration to version 15.0
  purchase_order_uninvoiced_amount/README.rst
  purchase_order_uninvoiced_amount/__init__.py
  purchase_order_uninvoiced_amount/__manifest__.py
  purchase_order_uninvoiced_amount/i18n/en_US.po
  purchase_order_uninvoiced_amount/i18n/es.po
  purchase_order_uninvoiced_amount/i18n/purchase_order_uninvoiced_amount.pot
  purchase_order_uninvoiced_amount/models/__init__.py
  purchase_order_uninvoiced_amount/models/purchase_order.py
  purchase_order_uninvoiced_amount/readme/CONTRIBUTORS.rst
  purchase_order_uninvoiced_amount/readme/DESCRIPTION.rst
  purchase_order_uninvoiced_amount/static/description/icon.png
  purchase_order_uninvoiced_amount/static/description/index.html
  purchase_order_uninvoiced_amount/tests/__init__.py
  purchase_order_uninvoiced_amount/tests/test_purchase_order_uninvoiced_amount.py
  purchase_order_uninvoiced_amount/views/purchase_order_view.xml
  setup/purchase_order_uninvoiced_amount/odoo/addons/purchase_order_uninvoiced_amount
  setup/purchase_order_uninvoiced_amount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1608 [15.0][MIG] purchase_order_product_recommendation_xlsx: Migration to version 15.0
  purchase_order_product_recommendation_xlsx/README.rst
  purchase_order_product_recommendation_xlsx/__init__.py
  purchase_order_product_recommendation_xlsx/__manifest__.py
  purchase_order_product_recommendation_xlsx/i18n/es.po
  purchase_order_product_recommendation_xlsx/i18n/purchase_order_product_recommendation_xlsx.pot
  purchase_order_product_recommendation_xlsx/readme/CONTRIBUTORS.rst
  purchase_order_product_recommendation_xlsx/readme/DESCRIPTION.rst
  purchase_order_product_recommendation_xlsx/readme/USAGE.rst
  purchase_order_product_recommendation_xlsx/report/__init__.py
  purchase_order_product_recommendation_xlsx/report/recommendation_xlsx.py
  purchase_order_product_recommendation_xlsx/report/recommendation_xlsx.xml
  purchase_order_product_recommendation_xlsx/static/description/icon.png
  purchase_order_product_recommendation_xlsx/static/description/index.html
  purchase_order_product_recommendation_xlsx/tests/__init__.py
  purchase_order_product_recommendation_xlsx/tests/test_recommendation.py
  purchase_order_product_recommendation_xlsx/wizards/__init__.py
  purchase_order_product_recommendation_xlsx/wizards/purchase_order_recommendation.py
  purchase_order_product_recommendation_xlsx/wizards/purchase_order_recommendation_view.xml
  setup/purchase_order_product_recommendation_xlsx/odoo/addons/purchase_order_product_recommendation_xlsx
  setup/purchase_order_product_recommendation_xlsx/setup.py
Labels: approved, bot is merging ⏳

#1625 [13.0][IMP] purchase_open_qty: Quantity returned without credit note is pending to bill
  purchase_open_qty/i18n/es.po
  purchase_open_qty/i18n/purchase_open_qty.pot
  purchase_open_qty/models/purchase_order.py
  purchase_open_qty/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#1626 [FIX] purchase_blanket_order: fix blanket order automatically setting…
  purchase_blanket_order/models/blanket_orders.py
Labels: bot is merging ⏳

#1627 [15.0][FIX] purchase_blanket_order: fix blanket order automatically s…
  purchase_blanket_order/models/blanket_orders.py
Labels: bot is merging ⏳

#1628 [13.0][FIX] purchase_open_qty: Quantity to invoice less than 0 has to be to invoice in purchase.order.lines too
  purchase_open_qty/models/purchase_order.py
  purchase_open_qty/views/purchase_view.xml
Labels: bot is merging ⏳

#1616 [FIX] purchase_order_approved: Allow to receive products when in 'Purchase' state
  purchase_order_approved/views/purchase_order_view.xml
Labels: bot is merging ⏳

#1554 [14.0][ADD] purchase_supplierinfo_product_breakdown
  purchase_supplierinfo_product_breakdown/README.rst
  purchase_supplierinfo_product_breakdown/__init__.py
  purchase_supplierinfo_product_breakdown/__manifest__.py
  purchase_supplierinfo_product_breakdown/data/demo.xml
  purchase_supplierinfo_product_breakdown/models/__init__.py
  purchase_supplierinfo_product_breakdown/models/product_supplierinfo.py
  purchase_supplierinfo_product_breakdown/models/product_supplierinfo_component.py
  purchase_supplierinfo_product_breakdown/models/product_template.py
  purchase_supplierinfo_product_breakdown/models/res_partner.py
  purchase_supplierinfo_product_breakdown/readme/CONTRIBUTORS.rst
  purchase_supplierinfo_product_breakdown/readme/DESCRIPTION.rst
  purchase_supplierinfo_product_breakdown/readme/USAGE.rst
  purchase_supplierinfo_product_breakdown/security/ir.model.access.csv
  purchase_supplierinfo_product_breakdown/tests/__init__.py
  purchase_supplierinfo_product_breakdown/tests/common.py
  purchase_supplierinfo_product_breakdown/tests/test_product_supplierinfo_component.py
  purchase_supplierinfo_product_breakdown/tests/test_supplierinfo.py
  purchase_supplierinfo_product_breakdown/views/product_supplierinfo_views.xml
  purchase_supplierinfo_product_breakdown/views/product_template_views.xml
  purchase_supplierinfo_product_breakdown/views/res_partner_views.xml
  setup/purchase_supplierinfo_product_breakdown/odoo/addons/purchase_supplierinfo_product_breakdown
  setup/purchase_supplierinfo_product_breakdown/setup.py
Labels: approved, bot is merging ⏳

#1619 [ADD] purchase_order_weight_volume
  purchase_order_weight_volume/README.rst
  purchase_order_weight_volume/__init__.py
  purchase_order_weight_volume/__manifest__.py
  purchase_order_weight_volume/models/__init__.py
  purchase_order_weight_volume/models/purchase_order.py
  purchase_order_weight_volume/models/res_company.py
  purchase_order_weight_volume/models/res_config_settings.py
  purchase_order_weight_volume/readme/CONTRIBUTORS.rst
  purchase_order_weight_volume/readme/DESCRIPTION.rst
  purchase_order_weight_volume/readme/USAGE.rst
  purchase_order_weight_volume/report/purchase_report_templates.xml
  purchase_order_weight_volume/static/description/icon.png
  purchase_order_weight_volume/views/purchase_order_view.xml
  purchase_order_weight_volume/views/res_config_settings_views.xml
  setup/purchase_order_weight_volume/odoo/addons/purchase_order_weight_volume
  setup/purchase_order_weight_volume/setup.py
Labels: approved, bot is merging ⏳

#1631 [15.0][mig] purchase_fop_shipping: Migration to 15.0
  purchase_fop_shipping/README.rst
  purchase_fop_shipping/__init__.py
  purchase_fop_shipping/__manifest__.py
  purchase_fop_shipping/i18n/de.po
  purchase_fop_shipping/i18n/es.po
  purchase_fop_shipping/i18n/es_PE.po
  purchase_fop_shipping/i18n/fr.po
  purchase_fop_shipping/i18n/fr_BE.po
  purchase_fop_shipping/i18n/gl.po
  purchase_fop_shipping/i18n/hr.po
  purchase_fop_shipping/i18n/it.po
  purchase_fop_shipping/i18n/nl.po
  purchase_fop_shipping/i18n/nl_NL.po
  purchase_fop_shipping/i18n/pt_BR.po
  purchase_fop_shipping/i18n/purchase_fop_shipping.pot
  purchase_fop_shipping/i18n/ro.po
  purchase_fop_shipping/i18n/sl.po
  purchase_fop_shipping/i18n/vi_VN.po
  purchase_fop_shipping/models/__init__.py
  purchase_fop_shipping/models/partner.py
  purchase_fop_shipping/models/purchase.py
  purchase_fop_shipping/security/res_groups.xml
  purchase_fop_shipping/static/description/icon.png
  purchase_fop_shipping/tests/__init__.py
  purchase_fop_shipping/tests/test_fop_shipping.py
  purchase_fop_shipping/views/purchase_order.xml
  purchase_fop_shipping/views/res_partner.xml
  setup/purchase_fop_shipping/odoo/addons/purchase_fop_shipping
  setup/purchase_fop_shipping/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1588 [15.0][MIG] purchase_order_approved
  purchase_order_approved/README.rst
  purchase_order_approved/__init__.py
  purchase_order_approved/__manifest__.py
  purchase_order_approved/i18n/am.po
  purchase_order_approved/i18n/ar.po
  purchase_order_approved/i18n/ca.po
  purchase_order_approved/i18n/da.po
  purchase_order_approved/i18n/de.po
  purchase_order_approved/i18n/el_GR.po
  purchase_order_approved/i18n/es.po
  purchase_order_approved/i18n/es_ES.po
  purchase_order_approved/i18n/es_MX.po
  purchase_order_approved/i18n/eu.po
  purchase_order_approved/i18n/fi.po
  purchase_order_approved/i18n/fr.po
  purchase_order_approved/i18n/fr_CA.po
  purchase_order_approved/i18n/fr_FR.po
  purchase_order_approved/i18n/gl.po
  purchase_order_approved/i18n/hr.po
  purchase_order_approved/i18n/hr_HR.po
  purchase_order_approved/i18n/it.po
  purchase_order_approved/i18n/nb.po
  purchase_order_approved/i18n/nb_NO.po
  purchase_order_approved/i18n/nl.po
  purchase_order_approved/i18n/nl_BE.po
  purchase_order_approved/i18n/nl_NL.po
  purchase_order_approved/i18n/pt_BR.po
  purchase_order_approved/i18n/purchase_order_approved.pot
  purchase_order_approved/i18n/ro.po
  purchase_order_approved/i18n/sk.po
  purchase_order_approved/i18n/sl.po
  purchase_order_approved/i18n/tr.po
  purchase_order_approved/i18n/vi_VN.po
  purchase_order_approved/i18n/zh_CN.po
  purchase_order_approved/models/__init__.py
  purchase_order_approved/models/purchase_order.py
  purchase_order_approved/models/res_company.py
  purchase_order_approved/models/res_config.py
  purchase_order_approved/models/res_partner.py
  purchase_order_approved/readme/CONFIGURE.rst
  purchase_order_approved/readme/CONTRIBUTORS.rst
  purchase_order_approved/readme/DESCRIPTION.rst
  purchase_order_approved/readme/HISTORY.rst
  purchase_order_approved/readme/USAGE.rst
  purchase_order_approved/static/description/icon.png
  purchase_order_approved/static/description/index.html
  purchase_order_approved/static/description/schema.png
  purchase_order_approved/tests/__init__.py
  purchase_order_approved/tests/test_purchase_order.py
  purchase_order_approved/tests/test_purchase_order_approved.py
  purchase_order_approved/views/purchase_order_view.xml
  purchase_order_approved/views/res_config_view.xml
  purchase_order_approved/views/res_partner.xml
  setup/purchase_order_approved/odoo/addons/purchase_order_approved
  setup/purchase_order_approved/setup.py
Labels: bot is merging ⏳

#1642 [14.0][FIX] purchase_order_type tests lint fixing
  purchase_manual_currency/tests/test_purchase_manual_currency.py
  purchase_stock_secondary_unit/tests/test_purchase_stock_secondary_unit.py
Labels: bot is merging ⏳

#1635 [ADD][14.0] purchase_order_shipping_date
  purchase_order_shipping_date/README.rst
  purchase_order_shipping_date/__init__.py
  purchase_order_shipping_date/__manifest__.py
  purchase_order_shipping_date/models/__init__.py
  purchase_order_shipping_date/models/purchase_order.py
  purchase_order_shipping_date/readme/CONTRIBUTORS.rst
  purchase_order_shipping_date/readme/DESCRIPTION.rst
  purchase_order_shipping_date/reports/report_purchase_order.xml
  purchase_order_shipping_date/views/purchase_order.xml
  setup/purchase_order_shipping_date/odoo/addons/purchase_order_shipping_date
  setup/purchase_order_shipping_date/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1654 [16.0][UPD] Run copier to include https://github.com/OCA/server-tools/pull/2467
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: approved

#1659 [15.0][FW-PORT] purchase_open_qty
  purchase_open_qty/i18n/es.po
  purchase_open_qty/i18n/purchase_open_qty.pot
  purchase_open_qty/models/purchase_order.py
  purchase_open_qty/readme/CONTRIBUTORS.rst
  purchase_open_qty/views/purchase_view.xml
Labels: approved, bot is merging ⏳

#1658 [14.0][FW-PORT] purchase_open_qty
  purchase_open_qty/i18n/es.po
  purchase_open_qty/i18n/purchase_open_qty.pot
  purchase_open_qty/models/purchase_order.py
  purchase_open_qty/readme/CONTRIBUTORS.rst
  purchase_open_qty/views/purchase_view.xml
Labels: approved, bot is merging ⏳

#1649 [14.0] [FIX] product_form_purchase_link: purchase_lines_count label
  product_form_purchase_link/models/product_template.py
Labels: approved, ready to merge, bot is merging ⏳

#1216 [14.0][ADD] purchase_work_acceptance_tier_validation
  purchase_work_acceptance_tier_validation/README.rst
  purchase_work_acceptance_tier_validation/__init__.py
  purchase_work_acceptance_tier_validation/__manifest__.py
  purchase_work_acceptance_tier_validation/models/__init__.py
  purchase_work_acceptance_tier_validation/models/tier_definition.py
  purchase_work_acceptance_tier_validation/models/work_acceptance.py
  purchase_work_acceptance_tier_validation/readme/CONFIGURE.rst
  purchase_work_acceptance_tier_validation/readme/CONTRIBUTORS.rst
  purchase_work_acceptance_tier_validation/readme/DESCRIPTION.rst
  purchase_work_acceptance_tier_validation/readme/INSTALL.rst
  purchase_work_acceptance_tier_validation/readme/USAGE.rst
  purchase_work_acceptance_tier_validation/static/description/icon.png
  purchase_work_acceptance_tier_validation/static/description/index.html
  purchase_work_acceptance_tier_validation/tests/__init__.py
  purchase_work_acceptance_tier_validation/tests/test_purchast_work_acceptance_tier_validation.py
  purchase_work_acceptance_tier_validation/views/work_acceptance_view.xml
  setup/purchase_work_acceptance_tier_validation/odoo/addons/purchase_work_acceptance_tier_validation
  setup/purchase_work_acceptance_tier_validation/setup.py
Labels: approved, bot is merging ⏳

#1655 [15.0][MIG] purchase_v12_control_menu: Migration to 15.0
  purchase_v12_control_menu/README.rst
  purchase_v12_control_menu/__init__.py
  purchase_v12_control_menu/__manifest__.py
  purchase_v12_control_menu/i18n/es.po
  purchase_v12_control_menu/i18n/purchase_v12_control_menu.pot
  purchase_v12_control_menu/readme/CONTRIBUTORS.rst
  purchase_v12_control_menu/readme/DESCRIPTION.rst
  purchase_v12_control_menu/static/description/icon.png
  purchase_v12_control_menu/static/description/index.html
  purchase_v12_control_menu/views/purchase_views.xml
  setup/purchase_v12_control_menu/odoo/addons/purchase_v12_control_menu
  setup/purchase_v12_control_menu/setup.py
Labels: approved, bot is merging ⏳

#1662 [14.0][IMP] purchase_force_invoiced: Add filter by company to avoid errors with inconsistent data
  purchase_force_invoiced/tests/test_purchase_force_invoiced.py
Labels: bot is merging ⏳

#1663 [15.0][IMP] purchase_force_invoiced: Add filter by company to avoid errors with inconsistent data
  purchase_force_invoiced/tests/test_purchase_force_invoiced.py
Labels: bot is merging ⏳
