Repository OCA/purchase-workflow, pull requests merged in 2022-04, with the labels that each got.

#1392 [14.0][FIX] vendor_transport_lead_time: fix error
  vendor_transport_lead_time/models/purchase_order_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1407 [14.0] purchase_request: Fix wrong method name
  purchase_request/models/stock_picking.py
Labels: bot is merging ⏳

#1324 [14.0][FIX] purchase_advance_payment: do not count twice reconciled pre-payments in PO residual amount.
  purchase_advance_payment/models/purchase_order.py
  purchase_advance_payment/tests/test_purchase_advance_payment.py
Labels: approved, ready to merge, bot is merging ⏳

#1405 [15.0][PORT] purchase_request: 1398 from 14.0
  purchase_request/models/purchase_request_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1200 [14.0][MIG] - purchase_order_line_invoicing
  purchase_order_line_invoicing/README.rst
  purchase_order_line_invoicing/__init__.py
  purchase_order_line_invoicing/__manifest__.py
  purchase_order_line_invoicing/models/__init__.py
  purchase_order_line_invoicing/models/res_partner.py
  purchase_order_line_invoicing/readme/CONTRIBUTORS.rst
  purchase_order_line_invoicing/readme/DESCRIPTION.rst
  purchase_order_line_invoicing/readme/USAGE.rst
  purchase_order_line_invoicing/security/purchase_order_line_invoice_details.xml
  purchase_order_line_invoicing/security/purchase_order_line_invoice_wizard.xml
  purchase_order_line_invoicing/tests/__init__.py
  purchase_order_line_invoicing/tests/test_purchase_order_line_invoicing_wizard.py
  purchase_order_line_invoicing/views/res_partner_views.xml
  purchase_order_line_invoicing/wizards/__init__.py
  purchase_order_line_invoicing/wizards/purchase_order_line_invoice_details.py
  purchase_order_line_invoicing/wizards/purchase_order_line_invoicing_wizard.py
  purchase_order_line_invoicing/wizards/purchase_order_line_invoicing_wizard.xml
  setup/purchase_order_line_invoicing/odoo/addons/purchase_order_line_invoicing
  setup/purchase_order_line_invoicing/setup.py
Labels: approved, bot is merging ⏳

#1408 [14.0][IMP] purchase_order_line_sequence: delete unused file
  purchase_order_line_sequence/models/invoice.py
Labels: approved, ready to merge, bot is merging ⏳

#1411 [15.0][MIG] purchase_default_terms_conditions
  purchase_default_terms_conditions/README.rst
  purchase_default_terms_conditions/__init__.py
  purchase_default_terms_conditions/__manifest__.py
  purchase_default_terms_conditions/i18n/pt_BR.po
  purchase_default_terms_conditions/i18n/purchase_default_terms_conditions.pot
  purchase_default_terms_conditions/models/__init__.py
  purchase_default_terms_conditions/models/purchase.py
  purchase_default_terms_conditions/models/res_company.py
  purchase_default_terms_conditions/models/res_config_settings.py
  purchase_default_terms_conditions/models/res_partner.py
  purchase_default_terms_conditions/readme/CONFIGURE.rst
  purchase_default_terms_conditions/readme/CONTRIBUTORS.rst
  purchase_default_terms_conditions/readme/CREDITS.rst
  purchase_default_terms_conditions/readme/DESCRIPTION.rst
  purchase_default_terms_conditions/readme/USAGE.rst
  purchase_default_terms_conditions/static/description/banner.png
  purchase_default_terms_conditions/static/description/icon.png
  purchase_default_terms_conditions/static/description/index.html
  purchase_default_terms_conditions/static/index.html
  purchase_default_terms_conditions/tests/__init__.py
  purchase_default_terms_conditions/tests/test_purchase_order.py
  purchase_default_terms_conditions/views/res_config_settings.xml
  purchase_default_terms_conditions/views/res_partner_views.xml
  setup/purchase_default_terms_conditions/odoo/addons/purchase_default_terms_conditions
  setup/purchase_default_terms_conditions/setup.py
Labels: approved, bot is merging ⏳

#1351 [15.0] [MIG] purchase_request_tier_validation
  purchase_request_tier_validation/README.rst
  purchase_request_tier_validation/__init__.py
  purchase_request_tier_validation/__manifest__.py
  purchase_request_tier_validation/data/purchase_request_tier_definition.xml
  purchase_request_tier_validation/i18n/es.po
  purchase_request_tier_validation/i18n/es_EC.po
  purchase_request_tier_validation/i18n/it.po
  purchase_request_tier_validation/i18n/nl_NL.po
  purchase_request_tier_validation/i18n/purchase_request_tier_validation.pot
  purchase_request_tier_validation/i18n/zh_CN.po
  purchase_request_tier_validation/models/__init__.py
  purchase_request_tier_validation/models/purchase_request.py
  purchase_request_tier_validation/models/tier_definition.py
  purchase_request_tier_validation/readme/CONFIGURE.rst
  purchase_request_tier_validation/readme/CONTRIBUTORS.rst
  purchase_request_tier_validation/readme/CREDITS.rst
  purchase_request_tier_validation/readme/DESCRIPTION.rst
  purchase_request_tier_validation/readme/INSTALL.rst
  purchase_request_tier_validation/readme/USAGE.rst
  purchase_request_tier_validation/static/description/icon.png
  purchase_request_tier_validation/static/description/index.html
  purchase_request_tier_validation/tests/__init__.py
  purchase_request_tier_validation/tests/test_purchase_request_tier_validation.py
  purchase_request_tier_validation/views/purchase_request_view.xml
  setup/purchase_request_tier_validation/odoo/addons/purchase_request_tier_validation
  setup/purchase_request_tier_validation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1416 [14.0][ADD] purchase_tag
  purchase_tag/README.rst
  purchase_tag/__init__.py
  purchase_tag/__manifest__.py
  purchase_tag/models/__init__.py
  purchase_tag/models/purchase_order.py
  purchase_tag/models/purchase_tag.py
  purchase_tag/readme/CONTRIBUTORS.rst
  purchase_tag/readme/DESCRIPTION.rst
  purchase_tag/readme/USAGE.rst
  purchase_tag/security/ir.model.access.csv
  purchase_tag/static/description/icon.png
  purchase_tag/views/purchase_tag_view.xml
  purchase_tag/views/purchase_view.xml
  setup/purchase_tag/odoo/addons/purchase_tag
  setup/purchase_tag/setup.py
Labels: approved, bot is merging ⏳

#1423 [15.0] [IMP] purchase_default_terms_conditions: changed field type Text to Html on note
  purchase_default_terms_conditions/models/res_company.py
  purchase_default_terms_conditions/models/res_config_settings.py
  purchase_default_terms_conditions/models/res_partner.py
Labels: bot is merging ⏳

#1359 [15.0] [MIG] purchase_delivery_split_date
  purchase_delivery_split_date/README.rst
  purchase_delivery_split_date/__init__.py
  purchase_delivery_split_date/__manifest__.py
  purchase_delivery_split_date/i18n/ca.po
  purchase_delivery_split_date/i18n/de.po
  purchase_delivery_split_date/i18n/es.po
  purchase_delivery_split_date/i18n/es_MX.po
  purchase_delivery_split_date/i18n/es_PE.po
  purchase_delivery_split_date/i18n/fi.po
  purchase_delivery_split_date/i18n/fr.po
  purchase_delivery_split_date/i18n/gl.po
  purchase_delivery_split_date/i18n/hr.po
  purchase_delivery_split_date/i18n/it.po
  purchase_delivery_split_date/i18n/nl_NL.po
  purchase_delivery_split_date/i18n/pt_BR.po
  purchase_delivery_split_date/i18n/pt_PT.po
  purchase_delivery_split_date/i18n/purchase_delivery_split_date.pot
  purchase_delivery_split_date/i18n/ro.po
  purchase_delivery_split_date/i18n/sl.po
  purchase_delivery_split_date/i18n/zh_CN.po
  purchase_delivery_split_date/models/__init__.py
  purchase_delivery_split_date/models/purchase.py
  purchase_delivery_split_date/readme/CONTRIBUTORS.rst
  purchase_delivery_split_date/readme/DESCRIPTION.rst
  purchase_delivery_split_date/readme/HISTORY.rst
  purchase_delivery_split_date/readme/USAGE.rst
  purchase_delivery_split_date/static/description/icon.png
  purchase_delivery_split_date/static/description/index.html
  purchase_delivery_split_date/static/description/split_delivery.png
  purchase_delivery_split_date/tests/__init__.py
  purchase_delivery_split_date/tests/test_purchase_delivery.py
  setup/purchase_delivery_split_date/odoo/addons/purchase_delivery_split_date
  setup/purchase_delivery_split_date/setup.py
Labels: approved, bot is merging ⏳

#1425 [14.0][FIX] purchase_picking_state: Add post_install tag in tests to prevent test errors
  purchase_picking_state/tests/test_purchase_picking_state.py
Labels: bot is merging ⏳

#1429 [14.0][ADD] purchase_order_vendor_product
  purchase_order_vendor_product/README.rst
  purchase_order_vendor_product/__init__.py
  purchase_order_vendor_product/__manifest__.py
  purchase_order_vendor_product/readme/CONTRIBUTORS.rst
  purchase_order_vendor_product/readme/DESCRIPTION.rst
  purchase_order_vendor_product/readme/HISTORY.rst
  purchase_order_vendor_product/readme/USAGE.rst
  purchase_order_vendor_product/static/description/icon.png
  purchase_order_vendor_product/views/purchase_order.xml
  setup/purchase_order_vendor_product/odoo/addons/purchase_order_vendor_product
  setup/purchase_order_vendor_product/setup.py
Labels: approved, bot is merging ⏳

#1433 [FIX]purchase_request: change name field in purchase_request_line
  purchase_request/models/purchase_request_line.py
Labels: bot is merging ⏳

#1434 [14.0][FIX] purchase_order_vendor_product, fix pre-commit error
  purchase_order_vendor_product/README.rst
  purchase_order_vendor_product/readme/DESCRIPTION.rst
  purchase_order_vendor_product/readme/HISTORY.rst
  purchase_order_vendor_product/static/description/index.html
Labels: bot is merging ⏳

#1365 [14.0][MIG] purchase_manual_delivery
  purchase_manual_delivery/README.rst
  purchase_manual_delivery/__init__.py
  purchase_manual_delivery/__manifest__.py
  purchase_manual_delivery/i18n/purchase_manual_delivery.pot
  purchase_manual_delivery/i18n/sl.po
  purchase_manual_delivery/models/__init__.py
  purchase_manual_delivery/models/purchase_order.py
  purchase_manual_delivery/models/res_company.py
  purchase_manual_delivery/models/res_config.py
  purchase_manual_delivery/readme/CONTRIBUTORS.rst
  purchase_manual_delivery/readme/DESCRIPTION.rst
  purchase_manual_delivery/readme/USAGE.rst
  purchase_manual_delivery/security/ir.model.access.csv
  purchase_manual_delivery/static/description/create_incoming_shipment_button.png
  purchase_manual_delivery/static/description/create_incoming_shipment_wizard.png
  purchase_manual_delivery/static/description/icon.png
  purchase_manual_delivery/static/description/index.html
  purchase_manual_delivery/tests/__init__.py
  purchase_manual_delivery/tests/test_purchase_manual_delivery.py
  purchase_manual_delivery/views/purchase_order_views.xml
  purchase_manual_delivery/views/res_config_view.xml
  purchase_manual_delivery/wizard/__init__.py
  purchase_manual_delivery/wizard/create_manual_stock_picking.py
  purchase_manual_delivery/wizard/create_manual_stock_picking.xml
  setup/purchase_manual_delivery/odoo/addons/purchase_manual_delivery
  setup/purchase_manual_delivery/setup.py
Labels: approved, bot is merging ⏳

#1329 Add _prepare_advance_purchase_line for hook function
  purchase_deposit/wizard/purchase_make_invoice_advance.py
Labels: approved, bot is merging ⏳

#1243 [14.0][IMP] purchase_invoice_plan, misc improvements to be more accurate.
  purchase_invoice_plan/__manifest__.py
  purchase_invoice_plan/data/purchase_data.xml
  purchase_invoice_plan/models/purchase.py
  purchase_invoice_plan/views/purchase_view.xml
Labels: approved, bot is merging ⏳
