Repository OCA/purchase-workflow, pull requests merged in 2022-10, with the labels that each got.

#1571 [15.0][MIG]purchase_partner_incoterm
  purchase_partner_incoterm/README.rst
  purchase_partner_incoterm/__init__.py
  purchase_partner_incoterm/__manifest__.py
  purchase_partner_incoterm/i18n/purchase_partner_incoterm.pot
  purchase_partner_incoterm/models/__init__.py
  purchase_partner_incoterm/models/purchase_order.py
  purchase_partner_incoterm/models/res_partner.py
  purchase_partner_incoterm/readme/CONTRIBUTORS.rst
  purchase_partner_incoterm/readme/CREDITS.rst
  purchase_partner_incoterm/readme/DESCRIPTION.rst
  purchase_partner_incoterm/static/description/icon.png
  purchase_partner_incoterm/static/description/index.html
  purchase_partner_incoterm/views/partner_view.xml
  purchase_partner_incoterm/views/purchase_view.xml
  setup/purchase_partner_incoterm/odoo/addons/purchase_partner_incoterm
  setup/purchase_partner_incoterm/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1587 [14.0][IMP] purchase_triple_discount: Display discount2 and discount3 field…
  purchase_triple_discount/__manifest__.py
  purchase_triple_discount/views/purchase_order_report.xml
Labels: approved, bot is merging ⏳

#1499 [15.0][MIG] purchase_open_qty
  purchase_open_qty/README.rst
  purchase_open_qty/__init__.py
  purchase_open_qty/__manifest__.py
  purchase_open_qty/i18n/de.po
  purchase_open_qty/i18n/es.po
  purchase_open_qty/i18n/es_MX.po
  purchase_open_qty/i18n/es_PE.po
  purchase_open_qty/i18n/fi.po
  purchase_open_qty/i18n/fr.po
  purchase_open_qty/i18n/fr_BE.po
  purchase_open_qty/i18n/gl.po
  purchase_open_qty/i18n/hr.po
  purchase_open_qty/i18n/it.po
  purchase_open_qty/i18n/nl.po
  purchase_open_qty/i18n/nl_NL.po
  purchase_open_qty/i18n/pt_BR.po
  purchase_open_qty/i18n/pt_PT.po
  purchase_open_qty/i18n/purchase_open_qty.pot
  purchase_open_qty/i18n/ro.po
  purchase_open_qty/i18n/sl.po
  purchase_open_qty/i18n/vi_VN.po
  purchase_open_qty/i18n/zh_CN.po
  purchase_open_qty/init_hook.py
  purchase_open_qty/models/__init__.py
  purchase_open_qty/models/purchase_order.py
  purchase_open_qty/readme/CONTRIBUTORS.rst
  purchase_open_qty/readme/DESCRIPTION.rst
  purchase_open_qty/readme/USAGE.rst
  purchase_open_qty/static/description/icon.png
  purchase_open_qty/static/description/index.html
  purchase_open_qty/tests/__init__.py
  purchase_open_qty/tests/test_purchase_open_qty.py
  purchase_open_qty/views/purchase_view.xml
  setup/purchase_open_qty/odoo/addons/purchase_open_qty
  setup/purchase_open_qty/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1589 [13][ADD] purchase_origin_link: add a link to the Source Document
  purchase_origin_link/__init__.py
  purchase_origin_link/__manifest__.py
  purchase_origin_link/models/__init__.py
  purchase_origin_link/models/purchase.py
  purchase_origin_link/readme/CONTRIBUTORS.rst
  purchase_origin_link/readme/DESCRIPTION.rst
  purchase_origin_link/views/purchase_views.xml
  setup/purchase_origin_link/odoo/addons/purchase_origin_link
  setup/purchase_origin_link/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1578 [14.0][FIX] sale_purchase_force_vendor: Display the vendor_id field only 1 time so that it is always displayed and apply the correct domain in both use cases
  sale_purchase_force_vendor/__manifest__.py
  sale_purchase_force_vendor/models/sale_order_line.py
  sale_purchase_force_vendor/tests/test_sale_purchase_force_vendor.py
  sale_purchase_force_vendor/views/sale_order_view.xml
Labels: approved, bot is merging ⏳

#1598 [FIX] purchase_analytic_global: saving the purchase mustn't remove the analytic accounts on lines when lines have different analytic accounts
  purchase_analytic_global/models/purchase.py
Labels: bot is merging ⏳

#1516 [15.0][MIG] purchase_force_invoiced: Migration to 15.0
  purchase_force_invoiced/README.rst
  purchase_force_invoiced/__init__.py
  purchase_force_invoiced/__manifest__.py
  purchase_force_invoiced/i18n/purchase_force_invoiced.pot
  purchase_force_invoiced/i18n/zh_CN.po
  purchase_force_invoiced/model/__init__.py
  purchase_force_invoiced/model/purchase.py
  purchase_force_invoiced/readme/CONTRIBUTORS.rst
  purchase_force_invoiced/readme/DESCRIPTION.rst
  purchase_force_invoiced/readme/USAGE.rst
  purchase_force_invoiced/reports/__init__.py
  purchase_force_invoiced/reports/purchase_report.py
  purchase_force_invoiced/static/description/icon.png
  purchase_force_invoiced/static/description/index.html
  purchase_force_invoiced/tests/__init__.py
  purchase_force_invoiced/tests/test_purchase_force_invoiced.py
  purchase_force_invoiced/view/purchase_view.xml
  setup/purchase_force_invoiced/odoo/addons/purchase_force_invoiced
  setup/purchase_force_invoiced/setup.py
Labels: approved, bot is merging ⏳

#1539 [15.0][MIG] purchase_order_supplierinfo_update: Migration to version 15.0
  purchase_order_supplierinfo_update/README.rst
  purchase_order_supplierinfo_update/__init__.py
  purchase_order_supplierinfo_update/__manifest__.py
  purchase_order_supplierinfo_update/i18n/purchase_order_supplierinfo_update.pot
  purchase_order_supplierinfo_update/models/__init__.py
  purchase_order_supplierinfo_update/models/purchase_order.py
  purchase_order_supplierinfo_update/readme/CONTRIBUTORS.rst
  purchase_order_supplierinfo_update/readme/DESCRIPTION.rst
  purchase_order_supplierinfo_update/readme/ROADMAP.rst
  purchase_order_supplierinfo_update/readme/USAGE.rst
  purchase_order_supplierinfo_update/static/description/icon.png
  purchase_order_supplierinfo_update/static/description/index.html
  purchase_order_supplierinfo_update/tests/__init__.py
  purchase_order_supplierinfo_update/tests/test_purchase_order_supplierinfo_update.py
  setup/purchase_order_supplierinfo_update/odoo/addons/purchase_order_supplierinfo_update
  setup/purchase_order_supplierinfo_update/setup.py
Labels: approved, bot is merging ⏳

#1610 [15.0][FIX] Misc changes
  procurement_purchase_no_grouping/tests/test_procurement_purchase_no_grouping.py
  purchase_order_product_recommendation/tests/test_recommendation.py
  purchase_order_qty_change_no_recompute/tests/test_purchase_order_qty_change.py
  purchase_partner_selectable_option/tests/test_purchase_partner_selectable_option.py
  test-requirements.txt
Labels: bot is merging ⏳

#1602 [16.0][MIG] purchase_discount: Migration to 16.0
  purchase_discount/README.rst
  purchase_discount/__init__.py
  purchase_discount/__manifest__.py
  purchase_discount/i18n/de.po
  purchase_discount/i18n/el_GR.po
  purchase_discount/i18n/es.po
  purchase_discount/i18n/es_MX.po
  purchase_discount/i18n/fr.po
  purchase_discount/i18n/fr_CH.po
  purchase_discount/i18n/fr_FR.po
  purchase_discount/i18n/hr.po
  purchase_discount/i18n/it.po
  purchase_discount/i18n/nl.po
  purchase_discount/i18n/pt_BR.po
  purchase_discount/i18n/pt_PT.po
  purchase_discount/i18n/purchase_discount.pot
  purchase_discount/i18n/sl.po
  purchase_discount/i18n/zh_CN.po
  purchase_discount/images/purchase_discount.png
  purchase_discount/models/__init__.py
  purchase_discount/models/product_supplierinfo.py
  purchase_discount/models/purchase_order.py
  purchase_discount/models/res_partner.py
  purchase_discount/models/stock_move.py
  purchase_discount/readme/CONTRIBUTORS.rst
  purchase_discount/readme/DESCRIPTION.rst
  purchase_discount/readme/ROADMAP.rst
  purchase_discount/readme/USAGE.rst
  purchase_discount/report/__init__.py
  purchase_discount/report/purchase_report.py
  purchase_discount/static/description/icon.png
  purchase_discount/static/description/icon.svg
  purchase_discount/static/description/index.html
  purchase_discount/static/description/product_supplierinfo_form.png
  purchase_discount/static/description/res_partner_company_form.png
  purchase_discount/static/description/res_partner_individual_form.png
  purchase_discount/tests/__init__.py
  purchase_discount/tests/test_product_supplierinfo_discount.py
  purchase_discount/tests/test_purchase_discount.py
  purchase_discount/views/product_supplierinfo_view.xml
  purchase_discount/views/purchase_discount_view.xml
  purchase_discount/views/report_purchaseorder.xml
  purchase_discount/views/res_partner_view.xml
  setup/purchase_discount/odoo/addons/purchase_discount
  setup/purchase_discount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1604 purchase_request: fix cancel purchase_request_line
  purchase_request/models/purchase_request_line.py
Labels: approved, bot is merging ⏳

#1613 [14.0][MIG] purchase_order_line_stock_available: Migration to 14.0
  purchase_order_line_stock_available/README.rst
  purchase_order_line_stock_available/__init__.py
  purchase_order_line_stock_available/__manifest__.py
  purchase_order_line_stock_available/i18n/es.po
  purchase_order_line_stock_available/i18n/pt_BR.po
  purchase_order_line_stock_available/i18n/purchase_order_line_stock_available.pot
  purchase_order_line_stock_available/i18n/sl.po
  purchase_order_line_stock_available/i18n/zh_CN.po
  purchase_order_line_stock_available/models/__init__.py
  purchase_order_line_stock_available/models/purchase.py
  purchase_order_line_stock_available/readme/CONTRIBUTORS.rst
  purchase_order_line_stock_available/readme/DESCRIPTION.rst
  purchase_order_line_stock_available/readme/USAGE.rst
  purchase_order_line_stock_available/static/description/icon.png
  purchase_order_line_stock_available/static/description/index.html
  purchase_order_line_stock_available/tests/__init__.py
  purchase_order_line_stock_available/tests/test_purchase.py
  purchase_order_line_stock_available/views/purchase_view.xml
  setup/purchase_order_line_stock_available/odoo/addons/purchase_order_line_stock_available
  setup/purchase_order_line_stock_available/setup.py
Labels: approved, bot is merging ⏳

#1614 [15.0][MIG] purchase_order_line_stock_available: Migration to 15.0
  purchase_order_line_stock_available/README.rst
  purchase_order_line_stock_available/__init__.py
  purchase_order_line_stock_available/__manifest__.py
  purchase_order_line_stock_available/i18n/es.po
  purchase_order_line_stock_available/i18n/pt_BR.po
  purchase_order_line_stock_available/i18n/purchase_order_line_stock_available.pot
  purchase_order_line_stock_available/i18n/sl.po
  purchase_order_line_stock_available/i18n/zh_CN.po
  purchase_order_line_stock_available/models/__init__.py
  purchase_order_line_stock_available/models/purchase.py
  purchase_order_line_stock_available/readme/CONTRIBUTORS.rst
  purchase_order_line_stock_available/readme/DESCRIPTION.rst
  purchase_order_line_stock_available/readme/USAGE.rst
  purchase_order_line_stock_available/static/description/icon.png
  purchase_order_line_stock_available/static/description/index.html
  purchase_order_line_stock_available/tests/__init__.py
  purchase_order_line_stock_available/tests/test_purchase.py
  purchase_order_line_stock_available/views/purchase_view.xml
  setup/purchase_order_line_stock_available/odoo/addons/purchase_order_line_stock_available
  setup/purchase_order_line_stock_available/setup.py
Labels: approved, bot is merging ⏳
