Repository OCA/purchase-workflow, pull requests merged in 2022-08, with the labels that each got.

#1542 [13.0][FIX] purchase_propagate_qty: CI error due to upstream change
  purchase_propagate_qty/README.rst
  purchase_propagate_qty/readme/DESCRIPTION.rst
  purchase_propagate_qty/static/description/index.html
  purchase_propagate_qty/tests/test_purchase_delivery.py
Labels: approved, bot is merging ⏳

#1535 [14.0][FIX] purchase_discount: Prevent price_unit recursion error since https://github.com/odoo/odoo/commit/87ffe5983be7f0f4a926b458c4bd1f13001048ec
  purchase_discount/models/purchase_order.py
  purchase_propagate_qty/README.rst
  purchase_propagate_qty/readme/DESCRIPTION.rst
  purchase_propagate_qty/static/description/index.html
  purchase_propagate_qty/tests/test_purchase_delivery.py
Labels: approved, bot is merging ⏳

#1507 [FIX]purchase_request: add product_uom_id domain
  purchase_request/models/purchase_request_line.py
  purchase_request/views/purchase_request_line_view.xml
  purchase_request/views/purchase_request_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1545 [15.0] [MIG] purchase_requisition_tier_validation: Migration to 15.0
  purchase_requisition_tier_validation/README.rst
  purchase_requisition_tier_validation/__init__.py
  purchase_requisition_tier_validation/__manifest__.py
  purchase_requisition_tier_validation/i18n/purchase_requisition_tier_validation.pot
  purchase_requisition_tier_validation/i18n/zh_CN.po
  purchase_requisition_tier_validation/models/__init__.py
  purchase_requisition_tier_validation/models/purchase_requisition.py
  purchase_requisition_tier_validation/models/tier_definition.py
  purchase_requisition_tier_validation/readme/CONFIGURE.rst
  purchase_requisition_tier_validation/readme/CONTRIBUTORS.rst
  purchase_requisition_tier_validation/readme/DESCRIPTION.rst
  purchase_requisition_tier_validation/readme/INSTALL.rst
  purchase_requisition_tier_validation/readme/USAGE.rst
  purchase_requisition_tier_validation/static/description/icon.png
  purchase_requisition_tier_validation/static/description/index.html
  purchase_requisition_tier_validation/tests/__init__.py
  purchase_requisition_tier_validation/tests/test_purchase_requisition_tier_validation.py
  purchase_requisition_tier_validation/views/purchase_requisition_view.xml
  setup/purchase_requisition_tier_validation/odoo/addons/purchase_requisition_tier_validation
  setup/purchase_requisition_tier_validation/setup.py
Labels: approved, bot is merging ⏳

#1319 [15.0][MIG] purchase_tier_validation
  purchase_tier_validation/README.rst
  purchase_tier_validation/__init__.py
  purchase_tier_validation/__manifest__.py
  purchase_tier_validation/i18n/es.po
  purchase_tier_validation/i18n/purchase_tier_validation.pot
  purchase_tier_validation/i18n/zh_CN.po
  purchase_tier_validation/models/__init__.py
  purchase_tier_validation/models/purchase_order.py
  purchase_tier_validation/models/tier_definition.py
  purchase_tier_validation/readme/CONFIGURE.rst
  purchase_tier_validation/readme/CONTRIBUTORS.rst
  purchase_tier_validation/readme/DESCRIPTION.rst
  purchase_tier_validation/readme/INSTALL.rst
  purchase_tier_validation/readme/USAGE.rst
  purchase_tier_validation/static/description/icon.png
  purchase_tier_validation/static/description/index.html
  purchase_tier_validation/tests/__init__.py
  purchase_tier_validation/tests/test_tier_validation.py
  purchase_tier_validation/tests/tier_validation_tester.py
  purchase_tier_validation/views/purchase_order_view.xml
  setup/purchase_tier_validation/odoo/addons/purchase_tier_validation
  setup/purchase_tier_validation/setup.py
Labels: approved, bot is merging ⏳

#1549 [FW][FIX]purchase_request: add product_uom_id domain
  purchase_request/models/purchase_request_line.py
  purchase_request/views/purchase_request_line_view.xml
  purchase_request/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳

#1550 [IMP] purchase_order_approved: Allows to activate the two-step approv…
  purchase_order_approved/README.rst
  purchase_order_approved/__manifest__.py
  purchase_order_approved/models/__init__.py
  purchase_order_approved/models/purchase_order.py
  purchase_order_approved/models/res_partner.py
  purchase_order_approved/readme/CONFIGURE.rst
  purchase_order_approved/readme/CONTRIBUTORS.rst
  purchase_order_approved/readme/DESCRIPTION.rst
  purchase_order_approved/static/description/index.html
  purchase_order_approved/tests/__init__.py
  purchase_order_approved/tests/test_purchase_order.py
  purchase_order_approved/views/res_partner.xml
Labels: approved, bot is merging ⏳

#1548 [FW][FIX]purchase_request: add product_uom_id domain
  purchase_request/models/purchase_request_line.py
  purchase_request/views/purchase_request_line_view.xml
  purchase_request/views/purchase_request_view.xml
Labels: bot is merging ⏳
