Repository OCA/purchase-workflow, pull requests merged in 2022-05, with the labels that each got.

#1360 [15.0][MIG] purchase_deposit
  purchase_deposit/README.rst
  purchase_deposit/__init__.py
  purchase_deposit/__manifest__.py
  purchase_deposit/i18n/fr.po
  purchase_deposit/i18n/purchase_deposit.pot
  purchase_deposit/models/__init__.py
  purchase_deposit/models/purchase.py
  purchase_deposit/models/res_config_settings.py
  purchase_deposit/readme/CONFIGURATION.rst
  purchase_deposit/readme/CONTRIBUTORS.rst
  purchase_deposit/readme/DESCRIPTION.rst
  purchase_deposit/readme/USAGE.rst
  purchase_deposit/security/ir.model.access.csv
  purchase_deposit/static/description/icon.png
  purchase_deposit/static/description/index.html
  purchase_deposit/tests/__init__.py
  purchase_deposit/tests/test_purchase_deposit.py
  purchase_deposit/views/purchase_view.xml
  purchase_deposit/views/res_config_settings_views.xml
  purchase_deposit/wizard/__init__.py
  purchase_deposit/wizard/purchase_make_invoice_advance.py
  purchase_deposit/wizard/purchase_make_invoice_advance_views.xml
  setup/purchase_deposit/odoo/addons/purchase_deposit
  setup/purchase_deposit/setup.py
Labels: approved, bot is merging ⏳

#1442 14.0[FIX] purchase_order_vendor_product
  purchase_order_vendor_product/__init__.py
  purchase_order_vendor_product/models/__init__.py
  purchase_order_vendor_product/models/product_product.py
  purchase_order_vendor_product/readme/HISTORY.rst
  purchase_order_vendor_product/tests/__init__.py
  purchase_order_vendor_product/tests/test_purchase_order_vendor_product.py
  purchase_order_vendor_product/views/purchase_order.xml
Labels: approved, bot is merging ⏳

#1446 [14.0][FIX] purchase_triple_discount: decimal_precision is obsolete
  purchase_triple_discount/report/purchase_report.py
Labels: bot is merging ⏳

#1410 [14.0][ADD] purchase_order_price_recalculation: New addon.
  purchase_order_price_recalculation/README.rst
  purchase_order_price_recalculation/__init__.py
  purchase_order_price_recalculation/__manifest__.py
  purchase_order_price_recalculation/i18n/es.po
  purchase_order_price_recalculation/i18n/purchase_order_price_recalculation.pot
  purchase_order_price_recalculation/models/__init__.py
  purchase_order_price_recalculation/models/purchase_order.py
  purchase_order_price_recalculation/readme/CONTRIBUTORS.rst
  purchase_order_price_recalculation/readme/DESCRIPTION.rst
  purchase_order_price_recalculation/readme/USAGE.rst
  purchase_order_price_recalculation/static/description/icon.png
  purchase_order_price_recalculation/static/description/index.html
  purchase_order_price_recalculation/tests/__init__.py
  purchase_order_price_recalculation/tests/test_purchase_order_price_recalculation.py
  purchase_order_price_recalculation/views/purchase_order_view.xml
  setup/purchase_order_price_recalculation/odoo/addons/purchase_order_price_recalculation
  setup/purchase_order_price_recalculation/setup.py
Labels: bot is merging ⏳

#1142 [MIG] product_supplier_code_purchase: Migration to 14.0
  product_supplier_code_purchase/README.rst
  product_supplier_code_purchase/__init__.py
  product_supplier_code_purchase/__manifest__.py
  product_supplier_code_purchase/i18n/de.po
  product_supplier_code_purchase/i18n/es.po
  product_supplier_code_purchase/i18n/es_MX.po
  product_supplier_code_purchase/i18n/fi.po
  product_supplier_code_purchase/i18n/fr.po
  product_supplier_code_purchase/i18n/it.po
  product_supplier_code_purchase/i18n/nl_NL.po
  product_supplier_code_purchase/i18n/product_supplier_code_purchase.pot
  product_supplier_code_purchase/i18n/pt_BR.po
  product_supplier_code_purchase/i18n/pt_PT.po
  product_supplier_code_purchase/i18n/ro.po
  product_supplier_code_purchase/i18n/sl.po
  product_supplier_code_purchase/models/__init__.py
  product_supplier_code_purchase/models/purchase_order.py
  product_supplier_code_purchase/readme/CONTRIBUTORS.rst
  product_supplier_code_purchase/readme/DESCRIPTION.rst
  product_supplier_code_purchase/readme/USAGE.rst
  product_supplier_code_purchase/static/description/icon.png
  product_supplier_code_purchase/static/description/index.html
  product_supplier_code_purchase/tests/__init__.py
  product_supplier_code_purchase/tests/test_product_supplier_code_purchase.py
  product_supplier_code_purchase/views/purchase_order_view.xml
  setup/product_supplier_code_purchase/odoo/addons/product_supplier_code_purchase
  setup/product_supplier_code_purchase/setup.py
Labels: bot is merging ⏳

#1461 [13.0][FIX] CI problems after switching to GH
  purchase_minimum_amount/README.rst
  purchase_minimum_amount/__manifest__.py
  purchase_minimum_amount/static/description/index.html
  purchase_order_approval_block/README.rst
  purchase_order_approval_block/__manifest__.py
  purchase_order_approval_block/static/description/index.html
  purchase_request_order_approved/README.rst
  purchase_request_order_approved/__manifest__.py
  purchase_request_order_approved/static/description/index.html
  purchase_stock_secondary_unit/README.rst
  purchase_stock_secondary_unit/__manifest__.py
  purchase_stock_secondary_unit/static/description/index.html
  purchase_tier_validation_forward/README.rst
  purchase_tier_validation_forward/__manifest__.py
  purchase_tier_validation_forward/static/description/index.html
Labels: bot is merging ⏳

#1428 [13.0][ADD] purchase_v12_control_menu: New module
  purchase_v12_control_menu/README.rst
  purchase_v12_control_menu/__init__.py
  purchase_v12_control_menu/__manifest__.py
  purchase_v12_control_menu/readme/CONTRIBUTORS.rst
  purchase_v12_control_menu/readme/DESCRIPTION.rst
  purchase_v12_control_menu/static/description/index.html
  purchase_v12_control_menu/views/purchase_views.xml
  setup/purchase_v12_control_menu/odoo/addons/purchase_v12_control_menu
  setup/purchase_v12_control_menu/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1066 [13.0][IMP] purchase_order_secondary_unit: Less code. Use product_secondary _unit mixin model from product-attribute repository.
  purchase_order_secondary_unit/models/purchase_order.py
  purchase_order_secondary_unit/tests/test_purchase_order_secondary_unit.py
  purchase_order_secondary_unit/views/purchase_order_views.xml
Labels: needs fixing, bot is merging ⏳

#1464 [14.0][FIX] po_secondary_unit: Drop 0 qty test assert on POL with secondary UoM
  purchase_order_secondary_unit/tests/test_purchase_order_secondary_unit.py
Labels: needs review, bot is merging ⏳

#1422 [14.0][FIX] purchase_request _compute_open_product_qty
  purchase_request/models/purchase_request_allocation.py
Labels: approved, bot is merging ⏳

#1466 [14.0][FIX] purchase_invoice_plan, clean recompute tax dr/cr
  purchase_invoice_plan/models/purchase.py
Labels: bot is merging ⏳

#1470 [13.0][FIX] purchase_blanket_order: Use purchasing UoM.
  purchase_blanket_order/models/blanket_orders.py
Labels: approved, bot is merging ⏳

#1441 [14.0][MIG] purchase_blanket_order
  purchase_blanket_order/README.rst
  purchase_blanket_order/__init__.py
  purchase_blanket_order/__manifest__.py
  purchase_blanket_order/data/ir_cron.xml
  purchase_blanket_order/data/sequence.xml
  purchase_blanket_order/i18n/purchase_blanket_order.pot
  purchase_blanket_order/models/__init__.py
  purchase_blanket_order/models/blanket_orders.py
  purchase_blanket_order/models/purchase_config_settings.py
  purchase_blanket_order/models/purchase_order.py
  purchase_blanket_order/readme/CONTRIBUTORS.rst
  purchase_blanket_order/readme/DESCRIPTION.rst
  purchase_blanket_order/readme/USAGE.rst
  purchase_blanket_order/report/report.xml
  purchase_blanket_order/report/templates.xml
  purchase_blanket_order/security/ir.model.access.csv
  purchase_blanket_order/security/security.xml
  purchase_blanket_order/static/description/BO_actions.png
  purchase_blanket_order/static/description/BO_form.png
  purchase_blanket_order/static/description/BO_lines.png
  purchase_blanket_order/static/description/BO_menu.png
  purchase_blanket_order/static/description/PO_BOLine.png
  purchase_blanket_order/static/description/PO_from_BO.png
  purchase_blanket_order/static/description/icon.png
  purchase_blanket_order/static/description/index.html
  purchase_blanket_order/tests/__init__.py
  purchase_blanket_order/tests/test_purchase_blanket_order.py
  purchase_blanket_order/tests/test_purchase_order.py
  purchase_blanket_order/views/purchase_blanket_order_views.xml
  purchase_blanket_order/views/purchase_config_settings.xml
  purchase_blanket_order/views/purchase_order_views.xml
  purchase_blanket_order/wizard/__init__.py
  purchase_blanket_order/wizard/create_purchase_orders.py
  purchase_blanket_order/wizard/create_purchase_orders.xml
  setup/purchase_blanket_order/odoo/addons/purchase_blanket_order
  setup/purchase_blanket_order/setup.py
Labels: approved, bot is merging ⏳

#1462 [14.0][ENH] purchase_invoice_plan, freeze plan amount if already invoiced
  purchase_invoice_plan/models/purchase.py
  purchase_invoice_plan/tests/test_purchase_invoice_plan.py
  purchase_invoice_plan/views/purchase_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1457 [14.0][IMP] added optional on field existing_qty
  purchase_manual_delivery/views/purchase_order_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1474 [15.0][MIG] purchase_blanket_order
  purchase_blanket_order/README.rst
  purchase_blanket_order/__init__.py
  purchase_blanket_order/__manifest__.py
  purchase_blanket_order/data/ir_cron.xml
  purchase_blanket_order/data/sequence.xml
  purchase_blanket_order/i18n/purchase_blanket_order.pot
  purchase_blanket_order/models/__init__.py
  purchase_blanket_order/models/blanket_orders.py
  purchase_blanket_order/models/purchase_config_settings.py
  purchase_blanket_order/models/purchase_order.py
  purchase_blanket_order/readme/CONTRIBUTORS.rst
  purchase_blanket_order/readme/DESCRIPTION.rst
  purchase_blanket_order/readme/USAGE.rst
  purchase_blanket_order/report/report.xml
  purchase_blanket_order/report/templates.xml
  purchase_blanket_order/security/ir.model.access.csv
  purchase_blanket_order/security/security.xml
  purchase_blanket_order/static/description/BO_actions.png
  purchase_blanket_order/static/description/BO_form.png
  purchase_blanket_order/static/description/BO_lines.png
  purchase_blanket_order/static/description/BO_menu.png
  purchase_blanket_order/static/description/PO_BOLine.png
  purchase_blanket_order/static/description/PO_from_BO.png
  purchase_blanket_order/static/description/icon.png
  purchase_blanket_order/static/description/index.html
  purchase_blanket_order/tests/__init__.py
  purchase_blanket_order/tests/test_purchase_blanket_order.py
  purchase_blanket_order/tests/test_purchase_order.py
  purchase_blanket_order/views/purchase_blanket_order_views.xml
  purchase_blanket_order/views/purchase_config_settings.xml
  purchase_blanket_order/views/purchase_order_views.xml
  purchase_blanket_order/wizard/__init__.py
  purchase_blanket_order/wizard/create_purchase_orders.py
  purchase_blanket_order/wizard/create_purchase_orders.xml
  setup/purchase_blanket_order/odoo/addons/purchase_blanket_order
  setup/purchase_blanket_order/setup.py
Labels: approved, bot is merging ⏳

#1473 [FIX] check if filtered moves are not empty
  purchase_propagate_qty/models/stock_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1475 [13.0][PORT] 1473 from 14.0 -> [FIX] check if filtered moves are not empty
  purchase_propagate_qty/models/stock_move.py
Labels: approved, bot is merging ⏳

#1449 [15.0][MIG] purchase_analytic_global
  purchase_analytic_global/README.rst
  purchase_analytic_global/__init__.py
  purchase_analytic_global/__manifest__.py
  purchase_analytic_global/i18n/fr.po
  purchase_analytic_global/i18n/purchase_analytic_global.pot
  purchase_analytic_global/models/__init__.py
  purchase_analytic_global/models/purchase.py
  purchase_analytic_global/readme/CONTRIBUTORS.rst
  purchase_analytic_global/readme/CREDITS.rst
  purchase_analytic_global/readme/DESCRIPTION.rst
  purchase_analytic_global/static/description/icon.png
  purchase_analytic_global/static/description/index.html
  purchase_analytic_global/tests/__init__.py
  purchase_analytic_global/tests/test_purchase_analytic_global.py
  purchase_analytic_global/views/purchase.xml
  setup/purchase_analytic_global/odoo/addons/purchase_analytic_global
  setup/purchase_analytic_global/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1445 [ADD] module: purchase_lot
  purchase_lot/__init__.py
  purchase_lot/__manifest__.py
  purchase_lot/models/__init__.py
  purchase_lot/models/purchase_order_line.py
  purchase_lot/models/stock_rule.py
  purchase_lot/readme/CONTRIBUTORS.rst
  purchase_lot/readme/DESCRIPTION.rst
  purchase_lot/tests/__init__.py
  purchase_lot/tests/test_purchase_lot.py
  purchase_lot/views/purchase_order_view.xml
  setup/purchase_lot/odoo/addons/purchase_lot
  setup/purchase_lot/setup.py
Labels: approved, bot is merging ⏳
