Repository OCA/purchase-workflow, pull requests merged in 2022-03, with the labels that each got.

#1370 [13.0][MIG] purchase_order_product_recommendation_secondary_unit: Migration to 13.0
  purchase_order_product_recommendation_secondary_unit/README.rst
  purchase_order_product_recommendation_secondary_unit/__init__.py
  purchase_order_product_recommendation_secondary_unit/__manifest__.py
  purchase_order_product_recommendation_secondary_unit/i18n/es.po
  purchase_order_product_recommendation_secondary_unit/i18n/purchase_order_product_recommendation_secondary_unit.pot
  purchase_order_product_recommendation_secondary_unit/readme/CONTRIBUTORS.rst
  purchase_order_product_recommendation_secondary_unit/readme/DESCRIPTION.rst
  purchase_order_product_recommendation_secondary_unit/readme/USAGE.rst
  purchase_order_product_recommendation_secondary_unit/static/description/icon.png
  purchase_order_product_recommendation_secondary_unit/static/description/index.html
  purchase_order_product_recommendation_secondary_unit/wizards/__init__.py
  purchase_order_product_recommendation_secondary_unit/wizards/purchase_order_recommendation.py
  purchase_order_product_recommendation_secondary_unit/wizards/purchase_order_recommendation_view.xml
  setup/purchase_order_product_recommendation_secondary_unit/odoo/addons/purchase_order_product_recommendation_secondary_unit
  setup/purchase_order_product_recommendation_secondary_unit/setup.py
Labels: approved, bot is merging ⏳

#1373 [13.0] [MIG] purchase_order_product_recommendation_classification: Migration to 13.0
  purchase_order_product_recommendation_classification/README.rst
  purchase_order_product_recommendation_classification/__init__.py
  purchase_order_product_recommendation_classification/__manifest__.py
  purchase_order_product_recommendation_classification/readme/CONTRIBUTORS.rst
  purchase_order_product_recommendation_classification/readme/DESCRIPTION.rst
  purchase_order_product_recommendation_classification/readme/USAGE.rst
  purchase_order_product_recommendation_classification/static/description/icon.png
  purchase_order_product_recommendation_classification/static/description/index.html
  purchase_order_product_recommendation_classification/tests/__init__.py
  purchase_order_product_recommendation_classification/tests/test_recommendation.py
  purchase_order_product_recommendation_classification/wizard/__init__.py
  purchase_order_product_recommendation_classification/wizard/purchase_order_recommendation.py
  purchase_order_product_recommendation_classification/wizard/purchase_order_recommendation_view.xml
  setup/purchase_order_product_recommendation_classification/odoo/addons/purchase_order_product_recommendation_classification
  setup/purchase_order_product_recommendation_classification/setup.py
Labels: approved, bot is merging ⏳

#1204 [14.0][REF] purchase_work_acceptance, code refactor
  purchase_work_acceptance/__manifest__.py
  purchase_work_acceptance/models/account_move.py
  purchase_work_acceptance/models/purchase.py
  purchase_work_acceptance/models/stock_picking.py
  purchase_work_acceptance/models/work_acceptance.py
  purchase_work_acceptance/readme/CONFIGURE.rst
  purchase_work_acceptance/security/ir.model.access.csv
  purchase_work_acceptance/tests/test_purchase_work_acceptance.py
  purchase_work_acceptance/views/purchase_views.xml
  purchase_work_acceptance/views/stock_picking_type_views.xml
  purchase_work_acceptance/views/stock_picking_views.xml
  purchase_work_acceptance/views/work_acceptance_views.xml
  purchase_work_acceptance/wizard/__init__.py
  purchase_work_acceptance/wizard/select_work_acceptance_wizard.py
  purchase_work_acceptance/wizard/select_work_acceptance_wizard_views.xml
  purchase_work_acceptance/wizard/work_accepted_date_wizard.py
  purchase_work_acceptance/wizard/work_accepted_date_wizard.xml
Labels: approved, bot is merging ⏳

#1354 [15.0][ADD] purchase_receipt_expectation_manual
  purchase_receipt_expectation/README.rst
  purchase_receipt_expectation/__init__.py
  purchase_receipt_expectation/__manifest__.py
  purchase_receipt_expectation/i18n/fr.po
  purchase_receipt_expectation/i18n/purchase_receipt_expectation.pot
  purchase_receipt_expectation/models/__init__.py
  purchase_receipt_expectation/models/purchase_order.py
  purchase_receipt_expectation/readme/CONTRIBUTORS.rst
  purchase_receipt_expectation/readme/DESCRIPTION.rst
  purchase_receipt_expectation/readme/USAGE.rst
  purchase_receipt_expectation/static/description/index.html
  purchase_receipt_expectation/tests/__init__.py
  purchase_receipt_expectation/tests/test_purchase_receipt_expectation.py
  purchase_receipt_expectation/views/purchase_order.xml
  purchase_receipt_expectation_manual/README.rst
  purchase_receipt_expectation_manual/__init__.py
  purchase_receipt_expectation_manual/__manifest__.py
  purchase_receipt_expectation_manual/i18n/fr.po
  purchase_receipt_expectation_manual/i18n/purchase_receipt_expectation_manual.pot
  purchase_receipt_expectation_manual/models/__init__.py
  purchase_receipt_expectation_manual/models/purchase_order.py
  purchase_receipt_expectation_manual/models/purchase_order_line.py
  purchase_receipt_expectation_manual/models/stock_move.py
  purchase_receipt_expectation_manual/readme/CONTRIBUTORS.rst
  purchase_receipt_expectation_manual/readme/DESCRIPTION.rst
  purchase_receipt_expectation_manual/readme/USAGE.rst
  purchase_receipt_expectation_manual/security/ir.model.access.csv
  purchase_receipt_expectation_manual/static/description/index.html
  purchase_receipt_expectation_manual/tests/__init__.py
  purchase_receipt_expectation_manual/tests/test_purchase_receipt_expectation_manual.py
  purchase_receipt_expectation_manual/views/purchase_order.xml
  purchase_receipt_expectation_manual/wizards/__init__.py
  purchase_receipt_expectation_manual/wizards/purchase_order_manual_receipt.py
  purchase_receipt_expectation_manual/wizards/purchase_order_manual_receipt.xml
  purchase_receipt_expectation_manual/wizards/purchase_order_manual_receipt_line.py
  setup/purchase_receipt_expectation/odoo/addons/purchase_receipt_expectation
  setup/purchase_receipt_expectation/setup.py
  setup/purchase_receipt_expectation_manual/odoo/addons/purchase_receipt_expectation_manual
  setup/purchase_receipt_expectation_manual/setup.py
Labels: work in progress, approved

#1125 [14.0][ADD] purchase_cancel_confirm
  .copier-answers.yml
  .travis.yml
  purchase_cancel_confirm/__init__.py
  purchase_cancel_confirm/__manifest__.py
  purchase_cancel_confirm/model/__init__.py
  purchase_cancel_confirm/model/purchase.py
  purchase_cancel_confirm/readme/CONTRIBUTORS.rst
  purchase_cancel_confirm/readme/DESCRIPTION.rst
  purchase_cancel_confirm/static/description/icon.png
  purchase_cancel_confirm/static/description/index.html
  purchase_cancel_confirm/tests/__init__.py
  purchase_cancel_confirm/tests/test_purchase_cancel_confirm.py
  setup/purchase_cancel_confirm/odoo/addons/purchase_cancel_confirm
  setup/purchase_cancel_confirm/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1376 [14.0][MIG] purchase_picking_state: Migration to 14.0
  purchase_picking_state/README.rst
  purchase_picking_state/__init__.py
  purchase_picking_state/__manifest__.py
  purchase_picking_state/i18n/de.po
  purchase_picking_state/i18n/es.po
  purchase_picking_state/i18n/es_PE.po
  purchase_picking_state/i18n/fr.po
  purchase_picking_state/i18n/fr_BE.po
  purchase_picking_state/i18n/gl.po
  purchase_picking_state/i18n/hr.po
  purchase_picking_state/i18n/it.po
  purchase_picking_state/i18n/ja.po
  purchase_picking_state/i18n/ja_JP.po
  purchase_picking_state/i18n/nl.po
  purchase_picking_state/i18n/nl_NL.po
  purchase_picking_state/i18n/pt_BR.po
  purchase_picking_state/i18n/purchase_picking_state.pot
  purchase_picking_state/i18n/ro.po
  purchase_picking_state/i18n/sl.po
  purchase_picking_state/i18n/vi_VN.po
  purchase_picking_state/models/__init__.py
  purchase_picking_state/models/purchase.py
  purchase_picking_state/readme/CONTRIBUTORS.rst
  purchase_picking_state/readme/DESCRIPTION.rst
  purchase_picking_state/readme/USAGE.rst
  purchase_picking_state/static/description/icon.png
  purchase_picking_state/static/description/index.html
  purchase_picking_state/tests/__init__.py
  purchase_picking_state/tests/test_purchase_picking_state.py
  purchase_picking_state/views/purchase_view.xml
  setup/purchase_picking_state/odoo/addons/purchase_picking_state
  setup/purchase_picking_state/setup.py
Labels: approved, bot is merging ⏳

#1382 [FIX] purchase_discount: Use TransactionCase in tests
  purchase_discount/tests/test_product_supplierinfo_discount.py
  purchase_discount/tests/test_purchase_discount.py
Labels: approved, bot is merging ⏳

#1321 [14.0] [MIG] purchase_analytic_global: Migrate to version 14.0
  purchase_analytic_global/README.rst
  purchase_analytic_global/__init__.py
  purchase_analytic_global/__manifest__.py
  purchase_analytic_global/i18n/fr.po
  purchase_analytic_global/i18n/purchase_analytic_global.pot
  purchase_analytic_global/models/__init__.py
  purchase_analytic_global/models/purchase.py
  purchase_analytic_global/readme/CONTRIBUTORS.rst
  purchase_analytic_global/readme/CREDITS.rst
  purchase_analytic_global/readme/DESCRIPTION.rst
  purchase_analytic_global/static/description/icon.png
  purchase_analytic_global/static/description/index.html
  purchase_analytic_global/tests/__init__.py
  purchase_analytic_global/tests/test_purchase_analytic_global.py
  purchase_analytic_global/views/purchase.xml
  setup/purchase_analytic_global/odoo/addons/purchase_analytic_global
  setup/purchase_analytic_global/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1402 [14.0] [MIG] purchase_representative
  purchase_representative/README.rst
  purchase_representative/__init__.py
  purchase_representative/__manifest__.py
  purchase_representative/i18n/purchase_representative.pot
  purchase_representative/models/__init__.py
  purchase_representative/models/stock_rule.py
  purchase_representative/readme/CONTRIBUTORS.rst
  purchase_representative/readme/DESCRIPTION.rst
  purchase_representative/readme/USAGE.rst
  purchase_representative/static/description/icon.png
  purchase_representative/static/description/index.html
  setup/purchase_representative/odoo/addons/purchase_representative
  setup/purchase_representative/setup.py
Labels: approved, bot is merging ⏳

#1388 [14.0][ADD] purchase_partner_approval
  purchase_partner_approval/README.rst
  purchase_partner_approval/__init__.py
  purchase_partner_approval/__manifest__.py
  purchase_partner_approval/data/exception_rule.xml
  purchase_partner_approval/data/init_puchase_ok.xml
  purchase_partner_approval/models/__init__.py
  purchase_partner_approval/models/purchase_order.py
  purchase_partner_approval/models/res_partner.py
  purchase_partner_approval/models/res_partner_stage.py
  purchase_partner_approval/readme/CONFIGURE.rst
  purchase_partner_approval/readme/CONTRIBUTORS.rst
  purchase_partner_approval/readme/DESCRIPTION.rst
  purchase_partner_approval/readme/USAGE.rst
  purchase_partner_approval/static/description/icon.png
  purchase_partner_approval/static/description/index.html
  purchase_partner_approval/tests/__init__.py
  purchase_partner_approval/tests/test_product_approval.py
  purchase_partner_approval/views/res_partner.xml
  purchase_partner_approval/views/res_partner_stage.xml
  setup/purchase_partner_approval/odoo/addons/purchase_partner_approval
  setup/purchase_partner_approval/setup.py
Labels: approved, bot is merging ⏳
