Repository OCA/purchase-workflow, pull requests merged in 2022-02, with the labels that each got.

#1345 [13.0][ADD] purchase_requisition_grouped_by_procurement: This module allows you to group procurements in the same purchase requisitions according to procurement group.
  purchase_requisition_grouped_by_procurement/README.rst
  purchase_requisition_grouped_by_procurement/__init__.py
  purchase_requisition_grouped_by_procurement/__manifest__.py
  purchase_requisition_grouped_by_procurement/i18n/es.po
  purchase_requisition_grouped_by_procurement/i18n/purchase_requisition_grouped_by_procurement.pot
  purchase_requisition_grouped_by_procurement/models/__init__.py
  purchase_requisition_grouped_by_procurement/models/purchase_requisition.py
  purchase_requisition_grouped_by_procurement/models/stock_rule.py
  purchase_requisition_grouped_by_procurement/readme/CONFIGURE.rst
  purchase_requisition_grouped_by_procurement/readme/CONTRIBUTORS.rst
  purchase_requisition_grouped_by_procurement/readme/DESCRIPTION.rst
  purchase_requisition_grouped_by_procurement/readme/USAGE.rst
  purchase_requisition_grouped_by_procurement/static/description/icon.png
  purchase_requisition_grouped_by_procurement/static/description/index.html
  purchase_requisition_grouped_by_procurement/tests/__init__.py
  purchase_requisition_grouped_by_procurement/tests/test_purchase_requisition_grouped_by_procurement.py
  setup/purchase_requisition_grouped_by_procurement/odoo/addons/purchase_requisition_grouped_by_procurement
  setup/purchase_requisition_grouped_by_procurement/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1346 [13.0][ADD] purchase_requisition_order_remaining_qty: This module allows you to define agreement types to use the remaining quantity of the agreement compared with the already proposed RfQs quantity.
  purchase_requisition_order_remaining_qty/README.rst
  purchase_requisition_order_remaining_qty/__init__.py
  purchase_requisition_order_remaining_qty/__manifest__.py
  purchase_requisition_order_remaining_qty/i18n/es.po
  purchase_requisition_order_remaining_qty/i18n/purchase_requisition_order_remaining_qty.pot
  purchase_requisition_order_remaining_qty/models/__init__.py
  purchase_requisition_order_remaining_qty/models/purchase_order.py
  purchase_requisition_order_remaining_qty/models/purchase_requisition_line.py
  purchase_requisition_order_remaining_qty/models/purchase_requisition_type.py
  purchase_requisition_order_remaining_qty/readme/CONFIGURE.rst
  purchase_requisition_order_remaining_qty/readme/CONTRIBUTORS.rst
  purchase_requisition_order_remaining_qty/readme/DESCRIPTION.rst
  purchase_requisition_order_remaining_qty/readme/USAGE.rst
  purchase_requisition_order_remaining_qty/static/description/icon.png
  purchase_requisition_order_remaining_qty/static/description/index.html
  purchase_requisition_order_remaining_qty/tests/__init__.py
  purchase_requisition_order_remaining_qty/tests/test_purchase_requisition_order_remaining_qty.py
  purchase_requisition_order_remaining_qty/views/purchase_requisition_view.xml
  setup/purchase_requisition_order_remaining_qty/odoo/addons/purchase_requisition_order_remaining_qty
  setup/purchase_requisition_order_remaining_qty/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1274 [12.0][IMP] purchase_order_line_packaging_qty: default without warning
  purchase_order_line_packaging_qty/models/product_product.py
  purchase_order_line_packaging_qty/models/purchase_order_line.py
  purchase_order_line_packaging_qty/views/product_product.xml
Labels: approved, bot is merging ⏳

#1323 [14.0][MIG] purchase_triple_discount
  purchase_triple_discount/README.rst
  purchase_triple_discount/__init__.py
  purchase_triple_discount/__manifest__.py
  purchase_triple_discount/i18n/de.po
  purchase_triple_discount/i18n/es.po
  purchase_triple_discount/i18n/es_MX.po
  purchase_triple_discount/i18n/es_PE.po
  purchase_triple_discount/i18n/fi.po
  purchase_triple_discount/i18n/fr.po
  purchase_triple_discount/i18n/hr.po
  purchase_triple_discount/i18n/it.po
  purchase_triple_discount/i18n/nl_NL.po
  purchase_triple_discount/i18n/pt_BR.po
  purchase_triple_discount/i18n/pt_PT.po
  purchase_triple_discount/i18n/purchase_triple_discount.pot
  purchase_triple_discount/i18n/ro.po
  purchase_triple_discount/i18n/sl.po
  purchase_triple_discount/i18n/zh_CN.po
  purchase_triple_discount/models/__init__.py
  purchase_triple_discount/models/product_supplierinfo.py
  purchase_triple_discount/models/purchase_order.py
  purchase_triple_discount/models/res_partner.py
  purchase_triple_discount/readme/CONTRIBUTORS.rst
  purchase_triple_discount/readme/DESCRIPTION.rst
  purchase_triple_discount/readme/USAGE.rst
  purchase_triple_discount/report/__init__.py
  purchase_triple_discount/report/purchase_report.py
  purchase_triple_discount/static/description/icon.png
  purchase_triple_discount/static/description/index.html
  purchase_triple_discount/tests/__init__.py
  purchase_triple_discount/tests/test_purchase_discount.py
  purchase_triple_discount/views/product_supplierinfo_view.xml
  purchase_triple_discount/views/purchase_view.xml
  purchase_triple_discount/views/res_partner_view.xml
  setup/purchase_triple_discount/odoo/addons/purchase_triple_discount
  setup/purchase_triple_discount/setup.py
Labels: approved, bot is merging ⏳

#1352 [13.0] [MIG] purchase_order_general_discount: Migration to 13.0
  purchase_order_general_discount/README.rst
  purchase_order_general_discount/__init__.py
  purchase_order_general_discount/__manifest__.py
  purchase_order_general_discount/i18n/es.po
  purchase_order_general_discount/i18n/pt.po
  purchase_order_general_discount/i18n/purchase_order_general_discount.pot
  purchase_order_general_discount/models/__init__.py
  purchase_order_general_discount/models/purchase_order.py
  purchase_order_general_discount/models/res_company.py
  purchase_order_general_discount/models/res_config_settings.py
  purchase_order_general_discount/models/res_partner.py
  purchase_order_general_discount/readme/CONFIGURE.rst
  purchase_order_general_discount/readme/CONTRIBUTORS.rst
  purchase_order_general_discount/readme/DESCRIPTION.rst
  purchase_order_general_discount/readme/USAGE.rst
  purchase_order_general_discount/static/description/icon.png
  purchase_order_general_discount/static/description/index.html
  purchase_order_general_discount/tests/__init__.py
  purchase_order_general_discount/tests/test_purchase_order_general_discount.py
  purchase_order_general_discount/views/purchase_order_view.xml
  purchase_order_general_discount/views/res_config_view.xml
  purchase_order_general_discount/views/res_partner_view.xml
  setup/purchase_order_general_discount/odoo/addons/purchase_order_general_discount
  setup/purchase_order_general_discount/setup.py
Labels: approved, bot is merging ⏳

#1353 [14.0][FIX] purchase_order_line_packaging_qty:
  purchase_order_line_packaging_qty/models/__init__.py
  purchase_order_line_packaging_qty/models/purchase_order_line.py
  purchase_order_line_packaging_qty/models/stock_rule.py
Labels: approved, bot is merging ⏳

#1363 [13.0] [MIG] purchase_triple_discount: Migration to 13.0
  oca_dependencies.txt
  purchase_triple_discount/README.rst
  purchase_triple_discount/__init__.py
  purchase_triple_discount/__manifest__.py
  purchase_triple_discount/i18n/de.po
  purchase_triple_discount/i18n/es.po
  purchase_triple_discount/i18n/es_MX.po
  purchase_triple_discount/i18n/es_PE.po
  purchase_triple_discount/i18n/fi.po
  purchase_triple_discount/i18n/fr.po
  purchase_triple_discount/i18n/hr.po
  purchase_triple_discount/i18n/it.po
  purchase_triple_discount/i18n/nl_NL.po
  purchase_triple_discount/i18n/pt_BR.po
  purchase_triple_discount/i18n/pt_PT.po
  purchase_triple_discount/i18n/purchase_triple_discount.pot
  purchase_triple_discount/i18n/ro.po
  purchase_triple_discount/i18n/sl.po
  purchase_triple_discount/i18n/zh_CN.po
  purchase_triple_discount/models/__init__.py
  purchase_triple_discount/models/product_supplierinfo.py
  purchase_triple_discount/models/purchase_order_line.py
  purchase_triple_discount/models/res_partner.py
  purchase_triple_discount/models/stock_rule.py
  purchase_triple_discount/readme/CONTRIBUTORS.rst
  purchase_triple_discount/readme/DESCRIPTION.rst
  purchase_triple_discount/readme/USAGE.rst
  purchase_triple_discount/report/__init__.py
  purchase_triple_discount/report/purchase_report.py
  purchase_triple_discount/report/report_purchase_order.xml
  purchase_triple_discount/static/description/icon.png
  purchase_triple_discount/static/description/index.html
  purchase_triple_discount/tests/__init__.py
  purchase_triple_discount/tests/test_purchase_discount.py
  purchase_triple_discount/views/product_supplierinfo.xml
  purchase_triple_discount/views/purchase_order.xml
  purchase_triple_discount/views/res_partner.xml
  setup/purchase_triple_discount/odoo/addons/purchase_triple_discount
  setup/purchase_triple_discount/setup.py
Labels: approved, bot is merging ⏳

#1364 [13.0] [MIG] purchase_stock_return_request: Migration to 13.0
  purchase_stock_return_request/README.rst
  purchase_stock_return_request/__init__.py
  purchase_stock_return_request/__manifest__.py
  purchase_stock_return_request/i18n/es.po
  purchase_stock_return_request/i18n/fr.po
  purchase_stock_return_request/i18n/purchase_stock_return_request.pot
  purchase_stock_return_request/models/__init__.py
  purchase_stock_return_request/models/stock_return_request.py
  purchase_stock_return_request/readme/CONTRIBUTORS.rst
  purchase_stock_return_request/readme/DESCRIPTION.rst
  purchase_stock_return_request/readme/USAGE.rst
  purchase_stock_return_request/report/stock_return_report.xml
  purchase_stock_return_request/static/description/icon.png
  purchase_stock_return_request/static/description/index.html
  purchase_stock_return_request/tests/__init__.py
  purchase_stock_return_request/tests/test_stock_return_request.py
  purchase_stock_return_request/views/purchase_return_request_views.xml
  setup/purchase_stock_return_request/odoo/addons/purchase_stock_return_request
  setup/purchase_stock_return_request/setup.py
Labels: approved, bot is merging ⏳

#1357 [13.0][FIX] purchase_requisition_order_remaining_qty: Use all purchase orders (except canceled orders) to get the value of the proposed_qty field.
  purchase_requisition_order_remaining_qty/models/purchase_requisition_line.py
  purchase_requisition_order_remaining_qty/tests/test_purchase_requisition_order_remaining_qty.py
Labels: bot is merging ⏳
