Repository OCA/purchase-workflow, pull requests merged in 2022-01, with the labels that each got.

#1327 [MIG][15.0] product_form_purchase_link
  product_form_purchase_link/README.rst
  product_form_purchase_link/__init__.py
  product_form_purchase_link/__manifest__.py
  product_form_purchase_link/i18n/fr.po
  product_form_purchase_link/i18n/product_form_purchase_link.pot
  product_form_purchase_link/readme/CONTRIBUTORS.rst
  product_form_purchase_link/readme/DESCRIPTION.rst
  product_form_purchase_link/readme/USAGE.rst
  product_form_purchase_link/static/description/icon.png
  product_form_purchase_link/static/description/index.html
  product_form_purchase_link/views/product_product.xml
  product_form_purchase_link/views/product_template.xml
  product_form_purchase_link/views/purchase_order_line.xml
  setup/product_form_purchase_link/odoo/addons/product_form_purchase_link
  setup/product_form_purchase_link/setup.py
Labels: approved, bot is merging ⏳

#1325 [14.0][FIX] purchase_discount: Misc changes: tracking + assertEqual
  purchase_discount/models/res_partner.py
  purchase_discount/tests/test_product_supplierinfo_discount.py
  purchase_quick/models/product_product.py
  purchase_quick/tests/test_quick_purchase.py
Labels: approved, ready to merge, bot is merging ⏳

#1335 [12.0][FIX] purchase_discount: Search for rates of relevant company
  purchase_discount/tests/test_purchase_discount.py
Labels: approved, bot is merging ⏳

#1328 [14.0][IMP] purchase_tier_validation: Simplify the tests.
  purchase_tier_validation/tests/__init__.py
  purchase_tier_validation/tests/common.py
  purchase_tier_validation/tests/test_tier_validation.py
  purchase_tier_validation/tests/tier_validation_tester.py
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#1338 [14.0][FIX] purchase_delivery_split_date: fix date_planned can be False
  purchase_delivery_split_date/models/purchase.py
Labels: bot is merging ⏳

#1339 [13.0][IMP] purchase_partner_selectable_option: Improve purchase button in contact form to show only if "Selectable in orders" is checked.
  purchase_partner_selectable_option/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#1340 [IMP][14.0] Purchase_deposit:added button create_deposit
  purchase_deposit/README.rst
  purchase_deposit/models/purchase.py
  purchase_deposit/readme/CONFIGURATION.rst
  purchase_deposit/readme/CONTRIBUTORS.rst
  purchase_deposit/readme/USAGE.rst
  purchase_deposit/tests/test_purchase_deposit.py
  purchase_deposit/wizard/purchase_make_invoice_advance.py
  purchase_deposit/wizard/purchase_make_invoice_advance_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1270 [14.0][MIG] purchase_force_invoiced: Migration to 14.0
  purchase_force_invoiced/README.rst
  purchase_force_invoiced/__init__.py
  purchase_force_invoiced/__manifest__.py
  purchase_force_invoiced/i18n/purchase_force_invoiced.pot
  purchase_force_invoiced/i18n/zh_CN.po
  purchase_force_invoiced/model/__init__.py
  purchase_force_invoiced/model/purchase.py
  purchase_force_invoiced/readme/CONTRIBUTORS.rst
  purchase_force_invoiced/readme/DESCRIPTION.rst
  purchase_force_invoiced/readme/USAGE.rst
  purchase_force_invoiced/static/description/icon.png
  purchase_force_invoiced/static/description/index.html
  purchase_force_invoiced/tests/__init__.py
  purchase_force_invoiced/tests/test_purchase_force_invoiced.py
  purchase_force_invoiced/view/purchase_view.xml
  setup/purchase_force_invoiced/odoo/addons/purchase_force_invoiced
  setup/purchase_force_invoiced/setup.py
Labels: approved, bot is merging ⏳

#1332 [14.0][FIX] purchase_request_tier_validation, can't approve after validated
  purchase_request_tier_validation/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳

#1341 [14.0][ADD] purchase_order_line_description_picking
  purchase_order_line_description_picking/__init__.py
  purchase_order_line_description_picking/__manifest__.py
  purchase_order_line_description_picking/models/__init__.py
  purchase_order_line_description_picking/models/purchase_order_line.py
  purchase_order_line_description_picking/readme/CONTRIBUTORS.rst
  purchase_order_line_description_picking/readme/DESCRIPTION.rst
  purchase_order_line_description_picking/readme/USAGE.rst
  purchase_order_line_description_picking/static/description/icon.png
  purchase_order_line_description_picking/tests/__init__.py
  purchase_order_line_description_picking/tests/test_purchase_order_line_description_picking.py
  setup/purchase_order_line_description_picking/odoo/addons/purchase_order_line_description_picking
  setup/purchase_order_line_description_picking/setup.py
Labels: approved, bot is merging ⏳

#1347 [14.0][FIX] Fix access right issues when using actions
  purchase_request/models/purchase_request.py
  purchase_work_acceptance/wizard/select_work_acceptance_wizard.py
  purchase_work_acceptance_late_fines/models/work_acceptance.py
Labels: approved, bot is merging ⏳
