Repository OCA/purchase-workflow, pull requests merged in 2023-08, with the labels that each got.

#1945 [15.0] [FIX] purchase_request: invalid field
  purchase_request/models/stock_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1962 [13.0][FIX]purchase_origin_link_sale: properly get the SO from Source Document
  purchase_origin_link_sale/models/purchase.py
  purchase_origin_link_sale/readme/CONTRIBUTORS.rst
  purchase_origin_link_sale/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#1933 [14.0][IMP] purchase_order_line_sequence: module refactor, new sequence fields for orders and invoices
  .pre-commit-config.yaml
  purchase_order_line_sequence/README.rst
  purchase_order_line_sequence/__init__.py
  purchase_order_line_sequence/__manifest__.py
  purchase_order_line_sequence/hooks.py
  purchase_order_line_sequence/models/__init__.py
  purchase_order_line_sequence/models/account_move_line.py
  purchase_order_line_sequence/models/purchase.py
  purchase_order_line_sequence/models/purchase_line.py
  purchase_order_line_sequence/models/stock_move.py
  purchase_order_line_sequence/readme/CONTRIBUTORS.rst
  purchase_order_line_sequence/tests/test_po_lines_sequence.py
  purchase_order_line_sequence/views/account_move_view.xml
  purchase_order_line_sequence/views/purchase_view.xml
  purchase_order_line_sequence/views/report_invoice.xml
  purchase_order_line_sequence/views/report_purchaseorder.xml
  purchase_order_line_sequence/views/report_purchasequotation.xml
  setup/purchase_order_line_sequence/odoo/addons/purchase_order_line_sequence
  setup/purchase_order_line_sequence/setup.py
Labels: approved, bot is merging ⏳

#1964 [15.0][IMP] purchase_order_line_menu: added invoice line in tree view
  purchase_order_line_menu/__manifest__.py
  purchase_order_line_menu/readme/CONTRIBUTORS.rst
  purchase_order_line_menu/views/purchase_order_line_views.xml
Labels: approved, bot is merging ⏳

#1967 [15.0][MIG] purchase_order_line_sequence
  purchase_order_line_sequence/README.rst
  purchase_order_line_sequence/__init__.py
  purchase_order_line_sequence/__manifest__.py
  purchase_order_line_sequence/i18n/de.po
  purchase_order_line_sequence/i18n/es.po
  purchase_order_line_sequence/i18n/fr.po
  purchase_order_line_sequence/i18n/purchase_order_line_sequence.pot
  purchase_order_line_sequence/models/__init__.py
  purchase_order_line_sequence/models/account_move_line.py
  purchase_order_line_sequence/models/purchase.py
  purchase_order_line_sequence/models/purchase_line.py
  purchase_order_line_sequence/models/stock_move.py
  purchase_order_line_sequence/readme/CONTRIBUTORS.rst
  purchase_order_line_sequence/readme/DESCRIPTION.rst
  purchase_order_line_sequence/readme/ROADMAP.rst
  purchase_order_line_sequence/readme/USAGE.rst
  purchase_order_line_sequence/static/description/icon.png
  purchase_order_line_sequence/static/description/index.html
  purchase_order_line_sequence/tests/__init__.py
  purchase_order_line_sequence/tests/test_po_lines_sequence.py
  purchase_order_line_sequence/views/account_move_view.xml
  purchase_order_line_sequence/views/purchase_view.xml
  purchase_order_line_sequence/views/report_invoice.xml
  purchase_order_line_sequence/views/report_purchaseorder.xml
  purchase_order_line_sequence/views/report_purchasequotation.xml
  setup/purchase_order_line_sequence/odoo/addons/purchase_order_line_sequence
  setup/purchase_order_line_sequence/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1958 Fix sequence usage considering company
  purchase_rfq_number/models/purchase_order.py
Labels: approved, bot is merging ⏳

#1730 [15.0][MIG] purchase_order_weight_volume: Migration to 15.0
  purchase_order_weight_volume/README.rst
  purchase_order_weight_volume/__init__.py
  purchase_order_weight_volume/__manifest__.py
  purchase_order_weight_volume/i18n/it.po
  purchase_order_weight_volume/i18n/purchase_order_weight_volume.pot
  purchase_order_weight_volume/models/__init__.py
  purchase_order_weight_volume/models/purchase_order.py
  purchase_order_weight_volume/models/res_company.py
  purchase_order_weight_volume/models/res_config_settings.py
  purchase_order_weight_volume/readme/CONTRIBUTORS.rst
  purchase_order_weight_volume/readme/DESCRIPTION.rst
  purchase_order_weight_volume/readme/USAGE.rst
  purchase_order_weight_volume/report/purchase_report_templates.xml
  purchase_order_weight_volume/static/description/icon.png
  purchase_order_weight_volume/static/description/index.html
  purchase_order_weight_volume/views/purchase_order_view.xml
  purchase_order_weight_volume/views/res_config_settings_views.xml
  setup/purchase_order_weight_volume/odoo/addons/purchase_order_weight_volume
  setup/purchase_order_weight_volume/setup.py
Labels: approved, bot is merging ⏳

#1974 [14.0][FIX] purchase_order_uninvoiced_amount: fix the deprecationWarning for test case
  purchase_order_uninvoiced_amount/tests/test_purchase_order_uninvoiced_amount.py
Labels: approved, bot is merging ⏳

#1978 [IMP] purchase_order_weight_volume: added license
  purchase_order_weight_volume/__manifest__.py
  purchase_order_weight_volume/models/purchase_order.py
  purchase_order_weight_volume/models/res_company.py
  purchase_order_weight_volume/models/res_config_settings.py
Labels: bot is merging ⏳

#1979 [IMP] purchase_order_weight_volume: added license
  purchase_order_weight_volume/__manifest__.py
  purchase_order_weight_volume/models/purchase_order.py
  purchase_order_weight_volume/models/res_company.py
  purchase_order_weight_volume/models/res_config_settings.py
Labels: bot is merging ⏳

#1977 [14.0][IMP] purchase_blanket_order: add blanket order line form
  purchase_blanket_order/views/purchase_blanket_order_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1984 [12.0][FIX] purchase_work_acceptance: fix xpath config view
  purchase_work_acceptance/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳
