Repository OCA/purchase-workflow, pull requests merged in 2023-10, with the labels that each got.

#2023 [15.0][FIX] purchase_discount: ocb compatibility
  purchase_discount/models/purchase_order.py
  purchase_discount/models/stock_move.py
Labels: approved, bot is merging ⏳

#1972 [16.0][MIG] purchase_order_weight_volume: Migrate to version 16.0
  purchase_order_weight_volume/README.rst
  purchase_order_weight_volume/__init__.py
  purchase_order_weight_volume/__manifest__.py
  purchase_order_weight_volume/i18n/it.po
  purchase_order_weight_volume/i18n/purchase_order_weight_volume.pot
  purchase_order_weight_volume/models/__init__.py
  purchase_order_weight_volume/models/purchase_order.py
  purchase_order_weight_volume/models/res_company.py
  purchase_order_weight_volume/models/res_config_settings.py
  purchase_order_weight_volume/readme/CONTRIBUTORS.rst
  purchase_order_weight_volume/readme/CREDITS.rst
  purchase_order_weight_volume/readme/DESCRIPTION.rst
  purchase_order_weight_volume/readme/USAGE.rst
  purchase_order_weight_volume/report/purchase_report_templates.xml
  purchase_order_weight_volume/static/description/icon.png
  purchase_order_weight_volume/static/description/index.html
  purchase_order_weight_volume/tests/__init__.py
  purchase_order_weight_volume/tests/test_purchase_order_weight_volume.py
  purchase_order_weight_volume/views/purchase_order_view.xml
  purchase_order_weight_volume/views/res_config_settings_views.xml
  setup/purchase_order_weight_volume/odoo/addons/purchase_order_weight_volume
  setup/purchase_order_weight_volume/setup.py
Labels: needs review, approved, bot is merging ⏳

#2021 [14.0][FIX] purchase_discount: ocb compatibility
  purchase_discount/models/purchase_order.py
  purchase_discount/models/stock_move.py
Labels: approved, bot is merging ⏳

#2022 [13.0][FIX] purchase_discount: ocb compatibility
  purchase_discount/models/purchase_order.py
  purchase_discount/models/stock_move.py
Labels: approved, bot is merging ⏳

#2026 [IMP] purchase_order_weight_volume: Display weight and volume
  purchase_order_weight_volume/views/purchase_order_view.xml
Labels: bot is merging ⏳

#2029 [15.0][FIX] purchase_stock_return_request: `_for_xml_id()` retrieving action
  purchase_stock_return_request/models/stock_return_request.py
  purchase_stock_return_request/tests/test_stock_return_request.py
Labels: approved, bot is merging ⏳

#1990 [15.0][IMP] purchase_order_line_sequence: Show only PO related sequence in Vendor Bills
  purchase_order_line_sequence/views/report_invoice.xml
Labels: approved, ready to merge, bot is merging ⏳

#1873 [15.0][ADD] sale_purchase_secondary_unit: New module
  sale_purchase_secondary_unit/README.rst
  sale_purchase_secondary_unit/__init__.py
  sale_purchase_secondary_unit/__manifest__.py
  sale_purchase_secondary_unit/models/__init__.py
  sale_purchase_secondary_unit/models/purchase_order_line.py
  sale_purchase_secondary_unit/models/sale_order.py
  sale_purchase_secondary_unit/models/stock_move.py
  sale_purchase_secondary_unit/models/stock_rule.py
  sale_purchase_secondary_unit/readme/CONTRIBUTORS.rst
  sale_purchase_secondary_unit/readme/DESCRIPTION.rst
  sale_purchase_secondary_unit/readme/USAGE.rst
  sale_purchase_secondary_unit/static/description/icon.png
  sale_purchase_secondary_unit/static/description/index.html
  sale_purchase_secondary_unit/tests/__init__.py
  sale_purchase_secondary_unit/tests/test_sale_purchase_secondary_unit.py
  setup/sale_purchase_secondary_unit/odoo/addons/sale_purchase_secondary_unit
  setup/sale_purchase_secondary_unit/setup.py
Labels: bot is merging ⏳

#2031 [13.0][IMP] purchase_blanket_order: avoid overwrite context in views inherited
  purchase_blanket_order/__manifest__.py
  purchase_blanket_order/views/purchase_order_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2043 [16.0][MIG] purchase_invoice_method: Migration to 16.0
  purchase_invoice_method/README.rst
  purchase_invoice_method/__init__.py
  purchase_invoice_method/__manifest__.py
  purchase_invoice_method/i18n/es_MX.po
  purchase_invoice_method/i18n/purchase_invoice_method.pot
  purchase_invoice_method/models/__init__.py
  purchase_invoice_method/models/purchase_order.py
  purchase_invoice_method/readme/CONTRIBUTORS.rst
  purchase_invoice_method/readme/DESCRIPTION.rst
  purchase_invoice_method/readme/USAGE.rst
  purchase_invoice_method/static/description/icon.png
  purchase_invoice_method/static/description/index.html
  purchase_invoice_method/tests/__init__.py
  purchase_invoice_method/tests/test_purchase_invoice_method.py
  purchase_invoice_method/views/purchase_order.xml
  setup/purchase_invoice_method/odoo/addons/purchase_invoice_method
  setup/purchase_invoice_method/setup.py
Labels: approved, bot is merging ⏳

#2048 [15.0][IMP] purchase_blanket_order: avoid overwrite context in views inherited
  purchase_blanket_order/__manifest__.py
  purchase_blanket_order/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#2047 [14.0][IMP] purchase_blanket_order: avoid overwrite context in views inherited
  purchase_blanket_order/__manifest__.py
  purchase_blanket_order/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#2036 [IMP] Purchase order total weight volume in UOM company
  purchase_order_weight_volume/models/purchase_order.py
  purchase_order_weight_volume/report/purchase_report_templates.xml
  purchase_order_weight_volume/tests/test_purchase_order_weight_volume.py
  purchase_order_weight_volume/views/purchase_order_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1440 [14.0][IMP] purchase_tier_validation: Add decoration to purchase tree view when orders have been rejected or approved.
  purchase_tier_validation/views/purchase_order_view.xml
Labels: approved, bot is merging ⏳

#2053 [15.0][FIX] sale_purchase_secondary_unit: When a so is cancelled the secondary_uom_qty on po lines is not updated
  sale_purchase_secondary_unit/models/sale_order.py
  sale_purchase_secondary_unit/models/stock_rule.py
Labels: approved, bot is merging ⏳

#2054 [15.0][IMP] purchase-workflow : test performance improvement
  procurement_purchase_no_grouping/tests/test_procurement_purchase_no_grouping.py
  purchase_discount/tests/test_product_supplierinfo_discount.py
  purchase_discount/tests/test_purchase_discount.py
  purchase_force_invoiced/tests/test_purchase_force_invoiced.py
  purchase_order_line_price_history/tests/test_purchase_order_line_price_history.py
  purchase_order_line_price_history_discount/tests/test_purchase_order_line_price_history_discount.py
  purchase_order_product_recommendation/tests/test_recommendation.py
  purchase_order_product_recommendation_brand/tests/test_recommendation.py
  purchase_order_product_recommendation_xlsx/tests/test_recommendation.py
  purchase_order_qty_change_no_recompute/tests/test_purchase_order_qty_change.py
  purchase_order_supplierinfo_update/tests/test_purchase_order_supplierinfo_update.py
  purchase_order_uninvoiced_amount/tests/test_purchase_order_uninvoiced_amount.py
  purchase_partner_selectable_option/tests/test_purchase_partner_selectable_option.py
  purchase_stock_price_unit_sync/tests/test_purchase_stock_price_unit_sync.py
  sale_purchase_force_vendor/tests/common.py
Labels: approved, bot is merging ⏳

#2056 [15.0][IMP] purchase_tier_validation: Add decoration to purchase tree view when orders have been rejected or approved.
  purchase_tier_validation/views/purchase_order_view.xml
  test-requirements.txt
Labels: approved, bot is merging ⏳

#2057 [16.0][IMP] purchase_tier_validation: Add decoration to purchase tree view when orders have been rejected or approved.
  purchase_tier_validation/views/purchase_order_view.xml
Labels: approved, bot is merging ⏳

#2066 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  purchase_blanket_order/i18n/purchase_blanket_order.pot
  purchase_merge/i18n/purchase_merge.pot
  purchase_merge/wizard/purchase_merge.py
  purchase_quick/i18n/es.po
  purchase_quick/i18n/purchase_quick.pot
  purchase_quick/models/purchase_order.py
  purchase_request/i18n/purchase_request.pot
  purchase_request_to_requisition/i18n/purchase_request_to_requisition.pot
  purchase_request_to_requisition/models/purchase_requisition.py
  purchase_rfq_number/reports/purchase_report_templates.xml
  purchase_work_acceptance/i18n/purchase_work_acceptance.pot
  purchase_work_acceptance_invoice_plan/i18n/purchase_work_acceptance_invoice_plan.pot
  purchase_work_acceptance_invoice_plan/wizard/select_work_acceptance_invoice_plan_wizard.py
Labels: help wanted, needs review, bot is merging ⏳

#2072 [16.0][IMP] purchase-workflow : test performance improvement
  purchase_discount/tests/test_product_supplierinfo_discount.py
  purchase_discount/tests/test_purchase_discount.py
  purchase_force_invoiced/tests/test_purchase_force_invoiced.py
  purchase_order_product_recommendation/tests/test_recommendation.py
  purchase_order_supplierinfo_update/tests/test_purchase_order_supplierinfo_update.py
  purchase_order_uninvoiced_amount/tests/test_purchase_order_uninvoiced_amount.py
  purchase_partner_selectable_option/tests/test_purchase_partner_selectable_option.py
Labels: bot is merging ⏳

#2074 [16.0][FIX] purchase_allowed_product: use correct field name
  purchase_allowed_product/models/product_supplierinfo.py
Labels: approved, bot is merging ⏳

#2075 [14.0] Update dotfiles
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  purchase_blanket_order/i18n/purchase_blanket_order.pot
  purchase_blanket_order/views/purchase_blanket_order_views.xml
  purchase_cancel_reason/i18n/purchase_cancel_reason.pot
  purchase_cancel_reason/views/purchase_order.xml
  purchase_delivery_split_date/tests/test_purchase_delivery.py
  purchase_order_approval_block/i18n/purchase_order_approval_block.pot
  purchase_order_approval_block/views/purchase_approval_block_reason_view.xml
  purchase_order_line_image/views/purchase_order_view.xml
  purchase_order_line_image/views/res_config_settings.xml
  purchase_order_payment_term_report/views/purchase_order.xml
  purchase_order_shipping_date/views/purchase_order.xml
  purchase_order_type/i18n/purchase_order_type.pot
  purchase_order_type/views/view_purchase_order_type.xml
  purchase_product_usage/i18n/purchase_product_usage.pot
  purchase_product_usage/views/purchase_product_usage_view.xml
  purchase_quick/i18n/purchase_quick.pot
  purchase_quick/views/product_view.xml
  purchase_request/i18n/de.po
  purchase_request/i18n/es_PE.po
  purchase_request/i18n/hr.po
  purchase_request/i18n/nl_NL.po
  purchase_request/i18n/pt_BR.po
  purchase_request/i18n/purchase_request.pot
  purchase_request/i18n/sl.po
  purchase_request/views/purchase_request_line_view.xml
  purchase_request/views/purchase_request_view.xml
  purchase_request/views/stock_move_views.xml
  purchase_request/wizard/purchase_request_line_make_purchase_order_view.xml
  purchase_request_to_requisition/i18n/purchase_request_to_requisition.pot
  purchase_request_to_requisition/views/purchase_request_view.xml
  purchase_request_to_requisition/wizard/purchase_request_line_make_purchase_requisition_view.xml
  purchase_request_type/i18n/purchase_request_type.pot
  purchase_request_type/views/purchase_request_type_view.xml
  purchase_requisition_auto_rfq/demo/product_product.xml
  purchase_requisition_auto_rfq/tests/test_purchase_requisition.py
  purchase_rfq_number/reports/purchase_report_templates.xml
  purchase_supplierinfo_product_breakdown/views/product_supplierinfo_views.xml
  purchase_tag/i18n/purchase_tag.pot
  purchase_tag/views/purchase_tag_view.xml
  purchase_vendor_bill_breakdown/i18n/purchase_vendor_bill_breakdown.pot
  purchase_vendor_bill_breakdown/views/purchase_order_views.xml
  purchase_work_acceptance/data/work_acceptance_sequence.xml
  purchase_work_acceptance/i18n/purchase_work_acceptance.pot
  purchase_work_acceptance/views/work_acceptance_views.xml
  purchase_work_acceptance_evaluation/demo/evaluation_data.xml
  purchase_work_acceptance_evaluation/i18n/purchase_work_acceptance_evaluation.pot
  purchase_work_acceptance_evaluation/views/work_acceptance_evaluation_views.xml
  purchase_work_acceptance_evaluation/views/work_acceptance_views.xml
Labels: approved, bot is merging ⏳
