Repository OCA/purchase-workflow, pull requests merged in 2023-02, with the labels that each got.

#1555 [15.0][MIG] purchase_work_acceptance: Migration to 15.0
  purchase_work_acceptance/README.rst
  purchase_work_acceptance/__init__.py
  purchase_work_acceptance/__manifest__.py
  purchase_work_acceptance/data/work_acceptance_sequence.xml
  purchase_work_acceptance/i18n/purchase_work_acceptance.pot
  purchase_work_acceptance/models/__init__.py
  purchase_work_acceptance/models/account_move.py
  purchase_work_acceptance/models/purchase.py
  purchase_work_acceptance/models/res_config_settings.py
  purchase_work_acceptance/models/stock_picking.py
  purchase_work_acceptance/models/work_acceptance.py
  purchase_work_acceptance/readme/CONFIGURE.rst
  purchase_work_acceptance/readme/CONTRIBUTORS.rst
  purchase_work_acceptance/readme/DESCRIPTION.rst
  purchase_work_acceptance/readme/USAGE.rst
  purchase_work_acceptance/security/ir.model.access.csv
  purchase_work_acceptance/security/security.xml
  purchase_work_acceptance/static/description/icon.png
  purchase_work_acceptance/static/description/index.html
  purchase_work_acceptance/tests/__init__.py
  purchase_work_acceptance/tests/test_purchase_work_acceptance.py
  purchase_work_acceptance/views/account_move_views.xml
  purchase_work_acceptance/views/purchase_views.xml
  purchase_work_acceptance/views/res_config_settings_views.xml
  purchase_work_acceptance/views/stock_picking_type_views.xml
  purchase_work_acceptance/views/stock_picking_views.xml
  purchase_work_acceptance/views/work_acceptance_views.xml
  purchase_work_acceptance/wizard/__init__.py
  purchase_work_acceptance/wizard/select_work_acceptance_wizard.py
  purchase_work_acceptance/wizard/select_work_acceptance_wizard_views.xml
  purchase_work_acceptance/wizard/work_accepted_date_wizard.py
  purchase_work_acceptance/wizard/work_accepted_date_wizard.xml
  setup/purchase_work_acceptance/odoo/addons/purchase_work_acceptance
  setup/purchase_work_acceptance/setup.py
Labels: approved, bot is merging ⏳

#1188 [14.0][ADD] purchase_invoice_plan_retention
  purchase_invoice_plan_retention/README.rst
  purchase_invoice_plan_retention/__init__.py
  purchase_invoice_plan_retention/__manifest__.py
  purchase_invoice_plan_retention/models/__init__.py
  purchase_invoice_plan_retention/models/purchase.py
  purchase_invoice_plan_retention/readme/CONTRIBUTORS.rst
  purchase_invoice_plan_retention/readme/DESCRIPTION.rst
  purchase_invoice_plan_retention/readme/USAGE.rst
  purchase_invoice_plan_retention/static/description/icon.png
  purchase_invoice_plan_retention/static/description/index.html
  purchase_invoice_plan_retention/tests/__init__.py
  purchase_invoice_plan_retention/tests/test_purchase_invoice_plan_retention.py
  purchase_invoice_plan_retention/views/purchase_view.xml
  setup/purchase_invoice_plan_retention/odoo/addons/purchase_invoice_plan_retention
  setup/purchase_invoice_plan_retention/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1752 [15.0][IMP] purchase_discount*: Improve qweb xpath
  purchase_discount/views/report_purchaseorder.xml
  purchase_triple_discount/views/purchase_order_report.xml
Labels: bot is merging ⏳

#1596 [15.0][MIG] purchase_invoice_plan: Migration to 15.0
  purchase_invoice_plan/README.rst
  purchase_invoice_plan/__init__.py
  purchase_invoice_plan/__manifest__.py
  purchase_invoice_plan/data/purchase_data.xml
  purchase_invoice_plan/i18n/purchase_invoice_plan.pot
  purchase_invoice_plan/models/__init__.py
  purchase_invoice_plan/models/purchase.py
  purchase_invoice_plan/readme/CONTRIBUTORS.rst
  purchase_invoice_plan/readme/DESCRIPTION.rst
  purchase_invoice_plan/readme/USAGE.rst
  purchase_invoice_plan/security/ir.model.access.csv
  purchase_invoice_plan/static/description/icon.png
  purchase_invoice_plan/static/description/index.html
  purchase_invoice_plan/tests/__init__.py
  purchase_invoice_plan/tests/test_purchase_invoice_plan.py
  purchase_invoice_plan/views/purchase_view.xml
  purchase_invoice_plan/wizard/__init__.py
  purchase_invoice_plan/wizard/purchase_create_invoice_plan.py
  purchase_invoice_plan/wizard/purchase_create_invoice_plan_view.xml
  purchase_invoice_plan/wizard/purchase_make_planned_invoice.py
  purchase_invoice_plan/wizard/purchase_make_planned_invoice_view.xml
  setup/purchase_invoice_plan/odoo/addons/purchase_invoice_plan
  setup/purchase_invoice_plan/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1733 [15.0][MIG] purchase_work_acceptance_evaluation
  purchase_work_acceptance_evaluation/README.rst
  purchase_work_acceptance_evaluation/__init__.py
  purchase_work_acceptance_evaluation/__manifest__.py
  purchase_work_acceptance_evaluation/demo/evaluation_data.xml
  purchase_work_acceptance_evaluation/i18n/purchase_work_acceptance_evaluation.pot
  purchase_work_acceptance_evaluation/models/__init__.py
  purchase_work_acceptance_evaluation/models/res_config_settings.py
  purchase_work_acceptance_evaluation/models/work_acceptance.py
  purchase_work_acceptance_evaluation/models/work_acceptance_evaluation.py
  purchase_work_acceptance_evaluation/readme/CONFIGURE.rst
  purchase_work_acceptance_evaluation/readme/CONTRIBUTORS.rst
  purchase_work_acceptance_evaluation/readme/DESCRIPTION.rst
  purchase_work_acceptance_evaluation/readme/USAGE.rst
  purchase_work_acceptance_evaluation/report/__init__.py
  purchase_work_acceptance_evaluation/report/work_acceptance_evaluation_report.py
  purchase_work_acceptance_evaluation/report/work_acceptance_evaluation_report.xml
  purchase_work_acceptance_evaluation/security/ir.model.access.csv
  purchase_work_acceptance_evaluation/security/security.xml
  purchase_work_acceptance_evaluation/static/description/icon.png
  purchase_work_acceptance_evaluation/static/description/index.html
  purchase_work_acceptance_evaluation/tests/__init__.py
  purchase_work_acceptance_evaluation/tests/test_purchase_work_acceptance_evaluation.py
  purchase_work_acceptance_evaluation/views/res_config_settings_views.xml
  purchase_work_acceptance_evaluation/views/work_acceptance_evaluation_views.xml
  purchase_work_acceptance_evaluation/views/work_acceptance_views.xml
  setup/purchase_work_acceptance_evaluation/odoo/addons/purchase_work_acceptance_evaluation
  setup/purchase_work_acceptance_evaluation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1723 [15.0][FIX] purchase_request: analytic_tag widget many2many_tags
  purchase_request/views/purchase_request_view.xml
Labels: approved, ready to merge, merged 🎉

#1749 [15.0][MIG] purchase_work_acceptance_tier_validation
  purchase_work_acceptance_tier_validation/README.rst
  purchase_work_acceptance_tier_validation/__init__.py
  purchase_work_acceptance_tier_validation/__manifest__.py
  purchase_work_acceptance_tier_validation/i18n/purchase_work_acceptance_tier_validation.pot
  purchase_work_acceptance_tier_validation/models/__init__.py
  purchase_work_acceptance_tier_validation/models/tier_definition.py
  purchase_work_acceptance_tier_validation/models/work_acceptance.py
  purchase_work_acceptance_tier_validation/readme/CONFIGURE.rst
  purchase_work_acceptance_tier_validation/readme/CONTRIBUTORS.rst
  purchase_work_acceptance_tier_validation/readme/DESCRIPTION.rst
  purchase_work_acceptance_tier_validation/readme/INSTALL.rst
  purchase_work_acceptance_tier_validation/readme/USAGE.rst
  purchase_work_acceptance_tier_validation/static/description/icon.png
  purchase_work_acceptance_tier_validation/static/description/index.html
  purchase_work_acceptance_tier_validation/tests/__init__.py
  purchase_work_acceptance_tier_validation/tests/test_purchast_work_acceptance_tier_validation.py
  purchase_work_acceptance_tier_validation/views/work_acceptance_view.xml
  setup/purchase_work_acceptance_tier_validation/odoo/addons/purchase_work_acceptance_tier_validation
  setup/purchase_work_acceptance_tier_validation/setup.py
Labels: approved, bot is merging ⏳

#1734 [15.0][MIG] purchase_work_acceptance_late_fines
  purchase_work_acceptance_late_fines/README.rst
  purchase_work_acceptance_late_fines/__init__.py
  purchase_work_acceptance_late_fines/__manifest__.py
  purchase_work_acceptance_late_fines/i18n/purchase_work_acceptance_late_fines.pot
  purchase_work_acceptance_late_fines/models/__init__.py
  purchase_work_acceptance_late_fines/models/account_move.py
  purchase_work_acceptance_late_fines/models/res_company.py
  purchase_work_acceptance_late_fines/models/res_config_settings.py
  purchase_work_acceptance_late_fines/models/work_acceptance.py
  purchase_work_acceptance_late_fines/readme/CONFIGURE.rst
  purchase_work_acceptance_late_fines/readme/CONTRIBUTORS.rst
  purchase_work_acceptance_late_fines/readme/DESCRIPTION.rst
  purchase_work_acceptance_late_fines/readme/USAGE.rst
  purchase_work_acceptance_late_fines/security/security.xml
  purchase_work_acceptance_late_fines/static/description/icon.png
  purchase_work_acceptance_late_fines/static/description/index.html
  purchase_work_acceptance_late_fines/tests/__init__.py
  purchase_work_acceptance_late_fines/tests/test_work_acceptance_late_fine.py
  purchase_work_acceptance_late_fines/views/account_move_views.xml
  purchase_work_acceptance_late_fines/views/res_config_settings_views.xml
  purchase_work_acceptance_late_fines/views/work_acceptance_views.xml
  setup/purchase_work_acceptance_late_fines/odoo/addons/purchase_work_acceptance_late_fines
  setup/purchase_work_acceptance_late_fines/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1753 [13.0][IMP] purchase_open_qty: consider services
  purchase_open_qty/models/purchase_order.py
  purchase_open_qty/tests/test_purchase_open_qty.py
Labels: approved, bot is merging ⏳

#1755 [15.0][IMP] purchase_open_qty: consider services
  purchase_open_qty/models/purchase_order.py
  purchase_open_qty/tests/test_purchase_open_qty.py
Labels: bot is merging ⏳

#1754 [14.0][IMP] purchase_open_qty: consider services
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  purchase_open_qty/models/purchase_order.py
  purchase_open_qty/tests/test_purchase_open_qty.py
Labels: bot is merging ⏳

#1704 [14.0][ADD] purchase_order_line_image
  purchase_order_line_image/README.rst
  purchase_order_line_image/__init__.py
  purchase_order_line_image/__manifest__.py
  purchase_order_line_image/models/__init__.py
  purchase_order_line_image/models/purchase_order.py
  purchase_order_line_image/models/res_config_settings.py
  purchase_order_line_image/readme/DESCRIPTION.rst
  purchase_order_line_image/reports/purchase_order_report.xml
  purchase_order_line_image/tests/__init__.py
  purchase_order_line_image/tests/test_purchase_order.py
  purchase_order_line_image/views/purchase_order_view.xml
  purchase_order_line_image/views/res_config_settings.xml
  setup/purchase_order_line_image/odoo/addons/purchase_order_line_image
  setup/purchase_order_line_image/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1390 [15.0][MIG] product_supplier_code_purchase
  product_supplier_code_purchase/README.rst
  product_supplier_code_purchase/__init__.py
  product_supplier_code_purchase/__manifest__.py
  product_supplier_code_purchase/i18n/de.po
  product_supplier_code_purchase/i18n/es.po
  product_supplier_code_purchase/i18n/es_MX.po
  product_supplier_code_purchase/i18n/fi.po
  product_supplier_code_purchase/i18n/fr.po
  product_supplier_code_purchase/i18n/it.po
  product_supplier_code_purchase/i18n/nl_NL.po
  product_supplier_code_purchase/i18n/product_supplier_code_purchase.pot
  product_supplier_code_purchase/i18n/pt_BR.po
  product_supplier_code_purchase/i18n/pt_PT.po
  product_supplier_code_purchase/i18n/ro.po
  product_supplier_code_purchase/i18n/sl.po
  product_supplier_code_purchase/models/__init__.py
  product_supplier_code_purchase/models/purchase_order.py
  product_supplier_code_purchase/readme/CONTRIBUTORS.rst
  product_supplier_code_purchase/readme/DESCRIPTION.rst
  product_supplier_code_purchase/readme/USAGE.rst
  product_supplier_code_purchase/static/description/icon.png
  product_supplier_code_purchase/static/description/index.html
  product_supplier_code_purchase/tests/__init__.py
  product_supplier_code_purchase/tests/test_product_supplier_code_purchase.py
  product_supplier_code_purchase/views/purchase_order_view.xml
  setup/product_supplier_code_purchase/odoo/addons/product_supplier_code_purchase
  setup/product_supplier_code_purchase/setup.py
Labels: approved, bot is merging ⏳

#1757 [14.0][FIX] purchase-workflow: xmlids
  purchase_blanket_order/models/blanket_orders.py
  purchase_order_product_attachment_mgmt/models/purchase_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1736 [15.0][ADD] purchase_order_line_qty_to_receive
  purchase_order_line_qty_to_receive/README.rst
  purchase_order_line_qty_to_receive/__init__.py
  purchase_order_line_qty_to_receive/__manifest__.py
  purchase_order_line_qty_to_receive/i18n/fr.po
  purchase_order_line_qty_to_receive/i18n/purchase_order_line_qty_to_receive.pot
  purchase_order_line_qty_to_receive/models/__init__.py
  purchase_order_line_qty_to_receive/models/purchase_order_line.py
  purchase_order_line_qty_to_receive/readme/CONTRIBUTORS.rst
  purchase_order_line_qty_to_receive/readme/DESCRIPTION.rst
  purchase_order_line_qty_to_receive/static/description/index.html
  purchase_order_line_qty_to_receive/tests/__init__.py
  purchase_order_line_qty_to_receive/tests/test_purchase_order_line_qty_to_receive.py
  purchase_order_line_qty_to_receive/views/purchase_order.xml
  setup/purchase_order_line_qty_to_receive/odoo/addons/purchase_order_line_qty_to_receive
  setup/purchase_order_line_qty_to_receive/setup.py
Labels: approved, bot is merging ⏳

#1703 [15.0] [FIX] `purchase_receipt_expectation_manual`: wizard lines overflow
  purchase_receipt_expectation_manual/wizards/purchase_order_manual_receipt.xml
Labels: approved, ready to merge, bot is merging ⏳

#1764 [14.0][ADD] purchase_invoice_method
  purchase_invoice_method/__init__.py
  purchase_invoice_method/__manifest__.py
  purchase_invoice_method/models/__init__.py
  purchase_invoice_method/models/purchase_order.py
  purchase_invoice_method/readme/CONTRIBUTORS.rst
  purchase_invoice_method/readme/DESCRIPTION.rst
  purchase_invoice_method/readme/USAGE.rst
  purchase_invoice_method/static/description/icon.png
  purchase_invoice_method/tests/__init__.py
  purchase_invoice_method/tests/test_purchase_invoice_method.py
  purchase_invoice_method/views/purchase_order.xml
  setup/purchase_invoice_method/odoo/addons/purchase_invoice_method
  setup/purchase_invoice_method/setup.py
Labels: approved, bot is merging ⏳

#1681 [16.0][MIG] purchase_force_invoiced
  purchase_force_invoiced/README.rst
  purchase_force_invoiced/__init__.py
  purchase_force_invoiced/__manifest__.py
  purchase_force_invoiced/i18n/purchase_force_invoiced.pot
  purchase_force_invoiced/i18n/zh_CN.po
  purchase_force_invoiced/model/__init__.py
  purchase_force_invoiced/model/purchase_order.py
  purchase_force_invoiced/readme/CONTRIBUTORS.rst
  purchase_force_invoiced/readme/DESCRIPTION.rst
  purchase_force_invoiced/readme/USAGE.rst
  purchase_force_invoiced/reports/__init__.py
  purchase_force_invoiced/reports/purchase_report.py
  purchase_force_invoiced/static/description/icon.png
  purchase_force_invoiced/static/description/index.html
  purchase_force_invoiced/tests/__init__.py
  purchase_force_invoiced/tests/test_purchase_force_invoiced.py
  purchase_force_invoiced/view/purchase_order.xml
  setup/purchase_force_invoiced/odoo/addons/purchase_force_invoiced
  setup/purchase_force_invoiced/setup.py
Labels: approved, bot is merging ⏳

#1727 [15.0][IMP] purchase_request - multi currency
  purchase_request/models/purchase_request.py
  purchase_request/models/purchase_request_line.py
  purchase_request/views/purchase_request_view.xml
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1179 [14.0][ADD] purchase_invoice_plan_deposit
  purchase_invoice_plan_deposit/README.rst
  purchase_invoice_plan_deposit/__init__.py
  purchase_invoice_plan_deposit/__manifest__.py
  purchase_invoice_plan_deposit/models/__init__.py
  purchase_invoice_plan_deposit/models/purchase.py
  purchase_invoice_plan_deposit/readme/CONTRIBUTORS.rst
  purchase_invoice_plan_deposit/readme/DESCRIPTION.rst
  purchase_invoice_plan_deposit/readme/USAGE.rst
  purchase_invoice_plan_deposit/static/description/icon.png
  purchase_invoice_plan_deposit/static/description/index.html
  purchase_invoice_plan_deposit/tests/__init__.py
  purchase_invoice_plan_deposit/tests/test_purchase_invoice_plan.py
  purchase_invoice_plan_deposit/views/purchase_view.xml
  purchase_invoice_plan_deposit/wizard/__init__.py
  purchase_invoice_plan_deposit/wizard/purchase_create_invoice_plan.py
  purchase_invoice_plan_deposit/wizard/purchase_create_invoice_plan_view.xml
  purchase_invoice_plan_deposit/wizard/purchase_make_invoice_advance.py
  purchase_invoice_plan_deposit/wizard/purchase_make_planned_invoice.py
  setup/purchase_invoice_plan_deposit/odoo/addons/purchase_invoice_plan_deposit
  setup/purchase_invoice_plan_deposit/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1771 [15.0][MIG] purchase_requisition_grouped_by_procurement: Migration to version 15.0
  purchase_requisition_grouped_by_procurement/README.rst
  purchase_requisition_grouped_by_procurement/__init__.py
  purchase_requisition_grouped_by_procurement/__manifest__.py
  purchase_requisition_grouped_by_procurement/i18n/es.po
  purchase_requisition_grouped_by_procurement/i18n/purchase_requisition_grouped_by_procurement.pot
  purchase_requisition_grouped_by_procurement/models/__init__.py
  purchase_requisition_grouped_by_procurement/models/purchase_requisition.py
  purchase_requisition_grouped_by_procurement/models/stock_rule.py
  purchase_requisition_grouped_by_procurement/readme/CONFIGURE.rst
  purchase_requisition_grouped_by_procurement/readme/CONTRIBUTORS.rst
  purchase_requisition_grouped_by_procurement/readme/DESCRIPTION.rst
  purchase_requisition_grouped_by_procurement/readme/USAGE.rst
  purchase_requisition_grouped_by_procurement/static/description/icon.png
  purchase_requisition_grouped_by_procurement/static/description/index.html
  purchase_requisition_grouped_by_procurement/tests/__init__.py
  purchase_requisition_grouped_by_procurement/tests/test_purchase_requisition_grouped_by_procurement.py
  setup/purchase_requisition_grouped_by_procurement/odoo/addons/purchase_requisition_grouped_by_procurement
  setup/purchase_requisition_grouped_by_procurement/setup.py
Labels: approved, bot is merging ⏳

#1669 [MIG] purchase_tier_validation: Migration to 16.0
  purchase_tier_validation/README.rst
  purchase_tier_validation/__init__.py
  purchase_tier_validation/__manifest__.py
  purchase_tier_validation/i18n/es.po
  purchase_tier_validation/i18n/purchase_tier_validation.pot
  purchase_tier_validation/i18n/zh_CN.po
  purchase_tier_validation/models/__init__.py
  purchase_tier_validation/models/purchase_order.py
  purchase_tier_validation/models/tier_definition.py
  purchase_tier_validation/readme/CONFIGURE.rst
  purchase_tier_validation/readme/CONTRIBUTORS.rst
  purchase_tier_validation/readme/DESCRIPTION.rst
  purchase_tier_validation/readme/INSTALL.rst
  purchase_tier_validation/readme/USAGE.rst
  purchase_tier_validation/static/description/icon.png
  purchase_tier_validation/static/description/index.html
  purchase_tier_validation/tests/__init__.py
  purchase_tier_validation/tests/test_tier_validation.py
  purchase_tier_validation/tests/tier_validation_tester.py
  purchase_tier_validation/views/purchase_order_view.xml
  setup/purchase_tier_validation/odoo/addons/purchase_tier_validation
  setup/purchase_tier_validation/setup.py
  test-requirements.txt
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#1769 [15.0][MIG] purchase_requisition_order_remaining_qty: Migration to version 15.0
  purchase_requisition_order_remaining_qty/README.rst
  purchase_requisition_order_remaining_qty/__init__.py
  purchase_requisition_order_remaining_qty/__manifest__.py
  purchase_requisition_order_remaining_qty/i18n/es.po
  purchase_requisition_order_remaining_qty/i18n/purchase_requisition_order_remaining_qty.pot
  purchase_requisition_order_remaining_qty/models/__init__.py
  purchase_requisition_order_remaining_qty/models/purchase_order.py
  purchase_requisition_order_remaining_qty/models/purchase_requisition_line.py
  purchase_requisition_order_remaining_qty/models/purchase_requisition_type.py
  purchase_requisition_order_remaining_qty/readme/CONFIGURE.rst
  purchase_requisition_order_remaining_qty/readme/CONTRIBUTORS.rst
  purchase_requisition_order_remaining_qty/readme/DESCRIPTION.rst
  purchase_requisition_order_remaining_qty/readme/USAGE.rst
  purchase_requisition_order_remaining_qty/static/description/icon.png
  purchase_requisition_order_remaining_qty/static/description/index.html
  purchase_requisition_order_remaining_qty/tests/__init__.py
  purchase_requisition_order_remaining_qty/tests/test_purchase_requisition_order_remaining_qty.py
  purchase_requisition_order_remaining_qty/views/purchase_requisition_view.xml
  setup/purchase_requisition_order_remaining_qty/odoo/addons/purchase_requisition_order_remaining_qty
  setup/purchase_requisition_order_remaining_qty/setup.py
Labels: approved, bot is merging ⏳

#1738 [MIG] purchase_requisition_tier_validation: Migration to 16.0
  purchase_requisition_tier_validation/README.rst
  purchase_requisition_tier_validation/__init__.py
  purchase_requisition_tier_validation/__manifest__.py
  purchase_requisition_tier_validation/i18n/purchase_requisition_tier_validation.pot
  purchase_requisition_tier_validation/i18n/zh_CN.po
  purchase_requisition_tier_validation/models/__init__.py
  purchase_requisition_tier_validation/models/purchase_requisition.py
  purchase_requisition_tier_validation/models/tier_definition.py
  purchase_requisition_tier_validation/readme/CONFIGURE.rst
  purchase_requisition_tier_validation/readme/CONTRIBUTORS.rst
  purchase_requisition_tier_validation/readme/CREDITS.rst
  purchase_requisition_tier_validation/readme/DESCRIPTION.rst
  purchase_requisition_tier_validation/readme/INSTALL.rst
  purchase_requisition_tier_validation/readme/USAGE.rst
  purchase_requisition_tier_validation/static/description/icon.png
  purchase_requisition_tier_validation/static/description/index.html
  purchase_requisition_tier_validation/tests/__init__.py
  purchase_requisition_tier_validation/tests/test_purchase_requisition_tier_validation.py
  purchase_requisition_tier_validation/views/purchase_requisition_view.xml
  setup/purchase_requisition_tier_validation/odoo/addons/purchase_requisition_tier_validation
  setup/purchase_requisition_tier_validation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1702 [16.0] [MIG] purchase_advance_payment: Migrate to version 16.0
  purchase_advance_payment/README.rst
  purchase_advance_payment/__init__.py
  purchase_advance_payment/__manifest__.py
  purchase_advance_payment/i18n/fr.po
  purchase_advance_payment/i18n/purchase_advance_payment.pot
  purchase_advance_payment/models/__init__.py
  purchase_advance_payment/models/payment.py
  purchase_advance_payment/models/purchase_order.py
  purchase_advance_payment/readme/CONTRIBUTORS.rst
  purchase_advance_payment/readme/CREDITS.rst
  purchase_advance_payment/readme/DESCRIPTION.rst
  purchase_advance_payment/readme/USAGE.rst
  purchase_advance_payment/security/ir.model.access.csv
  purchase_advance_payment/static/description/icon.png
  purchase_advance_payment/static/description/index.html
  purchase_advance_payment/tests/__init__.py
  purchase_advance_payment/tests/test_purchase_advance_payment.py
  purchase_advance_payment/views/purchase_view.xml
  purchase_advance_payment/wizard/__init__.py
  purchase_advance_payment/wizard/purchase_advance_payment_wizard.py
  purchase_advance_payment/wizard/purchase_advance_payment_wizard_view.xml
  setup/purchase_advance_payment/odoo/addons/purchase_advance_payment
  setup/purchase_advance_payment/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1746 [15.0][MIG] purchase_order_product_recommendation_classification: Migration to version 15.0
  purchase_order_product_recommendation_classification/README.rst
  purchase_order_product_recommendation_classification/__init__.py
  purchase_order_product_recommendation_classification/__manifest__.py
  purchase_order_product_recommendation_classification/i18n/purchase_order_product_recommendation_classification.pot
  purchase_order_product_recommendation_classification/readme/CONTRIBUTORS.rst
  purchase_order_product_recommendation_classification/readme/DESCRIPTION.rst
  purchase_order_product_recommendation_classification/readme/USAGE.rst
  purchase_order_product_recommendation_classification/static/description/icon.png
  purchase_order_product_recommendation_classification/static/description/index.html
  purchase_order_product_recommendation_classification/tests/__init__.py
  purchase_order_product_recommendation_classification/tests/test_recommendation.py
  purchase_order_product_recommendation_classification/wizard/__init__.py
  purchase_order_product_recommendation_classification/wizard/purchase_order_recommendation.py
  purchase_order_product_recommendation_classification/wizard/purchase_order_recommendation_view.xml
  setup/purchase_order_product_recommendation_classification/odoo/addons/purchase_order_product_recommendation_classification
  setup/purchase_order_product_recommendation_classification/setup.py
Labels: approved, bot is merging ⏳
