Repository OCA/purchase-workflow, pull requests merged in 2023-01, with the labels that each got.

#1697 [15.0][MIG] purchase_stock_return_request: Migration to version 15.0
  purchase_stock_return_request/README.rst
  purchase_stock_return_request/__init__.py
  purchase_stock_return_request/__manifest__.py
  purchase_stock_return_request/i18n/es.po
  purchase_stock_return_request/i18n/fr.po
  purchase_stock_return_request/i18n/purchase_stock_return_request.pot
  purchase_stock_return_request/models/__init__.py
  purchase_stock_return_request/models/stock_return_request.py
  purchase_stock_return_request/readme/CONTRIBUTORS.rst
  purchase_stock_return_request/readme/DESCRIPTION.rst
  purchase_stock_return_request/readme/USAGE.rst
  purchase_stock_return_request/report/stock_return_report.xml
  purchase_stock_return_request/static/description/icon.png
  purchase_stock_return_request/static/description/index.html
  purchase_stock_return_request/tests/__init__.py
  purchase_stock_return_request/tests/test_stock_return_request.py
  purchase_stock_return_request/views/purchase_return_request_views.xml
  setup/purchase_stock_return_request/odoo/addons/purchase_stock_return_request
  setup/purchase_stock_return_request/setup.py
Labels: approved, bot is merging ⏳

#1705 [13.0][MIG] purchase_analytic_global
  purchase_analytic_global/README.rst
  purchase_analytic_global/__init__.py
  purchase_analytic_global/__manifest__.py
  purchase_analytic_global/i18n/fr.po
  purchase_analytic_global/i18n/purchase_analytic_global.pot
  purchase_analytic_global/models/__init__.py
  purchase_analytic_global/models/purchase.py
  purchase_analytic_global/readme/CONTRIBUTORS.rst
  purchase_analytic_global/readme/DESCRIPTION.rst
  purchase_analytic_global/static/description/icon.png
  purchase_analytic_global/static/description/index.html
  purchase_analytic_global/tests/__init__.py
  purchase_analytic_global/tests/test_purchase_analytic_global.py
  purchase_analytic_global/views/purchase.xml
  setup/purchase_analytic_global/odoo/addons/purchase_analytic_global
  setup/purchase_analytic_global/setup.py
Labels: bot is merging ⏳

#1700 [13.0][MIG] purchase_order_line_sequence
  purchase_order_line_sequence/README.rst
  purchase_order_line_sequence/__init__.py
  purchase_order_line_sequence/__manifest__.py
  purchase_order_line_sequence/hooks.py
  purchase_order_line_sequence/i18n/de.po
  purchase_order_line_sequence/i18n/fr.po
  purchase_order_line_sequence/i18n/purchase_order_line_sequence.pot
  purchase_order_line_sequence/models/__init__.py
  purchase_order_line_sequence/models/purchase.py
  purchase_order_line_sequence/models/purchase_line.py
  purchase_order_line_sequence/readme/CONTRIBUTORS.rst
  purchase_order_line_sequence/readme/DESCRIPTION.rst
  purchase_order_line_sequence/readme/ROADMAP.rst
  purchase_order_line_sequence/readme/USAGE.rst
  purchase_order_line_sequence/static/description/icon.png
  purchase_order_line_sequence/static/description/index.html
  purchase_order_line_sequence/tests/__init__.py
  purchase_order_line_sequence/tests/test_po_lines_sequence.py
  purchase_order_line_sequence/views/purchase_view.xml
  purchase_order_line_sequence/views/report_purchaseorder.xml
  purchase_order_line_sequence/views/report_purchasequotation.xml
  setup/purchase_order_line_sequence/odoo/addons/purchase_order_line_sequence
  setup/purchase_order_line_sequence/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1671 [MIG] purchase_request_tier_validation: Migration to 16.0
  purchase_request_tier_validation/README.rst
  purchase_request_tier_validation/__init__.py
  purchase_request_tier_validation/__manifest__.py
  purchase_request_tier_validation/data/purchase_request_tier_definition.xml
  purchase_request_tier_validation/i18n/es.po
  purchase_request_tier_validation/i18n/es_EC.po
  purchase_request_tier_validation/i18n/it.po
  purchase_request_tier_validation/i18n/nl_NL.po
  purchase_request_tier_validation/i18n/purchase_request_tier_validation.pot
  purchase_request_tier_validation/i18n/zh_CN.po
  purchase_request_tier_validation/models/__init__.py
  purchase_request_tier_validation/models/purchase_request.py
  purchase_request_tier_validation/models/tier_definition.py
  purchase_request_tier_validation/readme/CONFIGURE.rst
  purchase_request_tier_validation/readme/CONTRIBUTORS.rst
  purchase_request_tier_validation/readme/CREDITS.rst
  purchase_request_tier_validation/readme/DESCRIPTION.rst
  purchase_request_tier_validation/readme/INSTALL.rst
  purchase_request_tier_validation/readme/USAGE.rst
  purchase_request_tier_validation/static/description/icon.png
  purchase_request_tier_validation/static/description/index.html
  purchase_request_tier_validation/tests/__init__.py
  purchase_request_tier_validation/tests/test_purchase_request_tier_validation.py
  purchase_request_tier_validation/views/purchase_request_view.xml
  setup/purchase_request_tier_validation/odoo/addons/purchase_request_tier_validation
  setup/purchase_request_tier_validation/setup.py
Labels: approved, bot is merging ⏳

#1713 [IMP] purchase_order_general_discount: Make the tests compatible with other modules
  purchase_order_general_discount/tests/test_purchase_order_general_discount.py
Labels: approved, ready to merge, bot is merging ⏳

#1707 [15.0][MIG] purchase_order_product_recommendation_forecast: Migration to version 15.0
  purchase_order_product_recommendation_forecast/README.rst
  purchase_order_product_recommendation_forecast/__init__.py
  purchase_order_product_recommendation_forecast/__manifest__.py
  purchase_order_product_recommendation_forecast/i18n/es.po
  purchase_order_product_recommendation_forecast/i18n/purchase_order_product_recommendation_forecast.pot
  purchase_order_product_recommendation_forecast/readme/CONTRIBUTORS.rst
  purchase_order_product_recommendation_forecast/readme/DESCRIPTION.rst
  purchase_order_product_recommendation_forecast/readme/USAGE.rst
  purchase_order_product_recommendation_forecast/static/description/icon.png
  purchase_order_product_recommendation_forecast/static/description/index.html
  purchase_order_product_recommendation_forecast/tests/__init__.py
  purchase_order_product_recommendation_forecast/tests/test_recommendation_forecast.py
  purchase_order_product_recommendation_forecast/wizards/__init__.py
  purchase_order_product_recommendation_forecast/wizards/purchase_order_recommendation.py
  purchase_order_product_recommendation_forecast/wizards/purchase_order_recommendation_view.xml
  setup/purchase_order_product_recommendation_forecast/odoo/addons/purchase_order_product_recommendation_forecast
  setup/purchase_order_product_recommendation_forecast/setup.py
Labels: approved, bot is merging ⏳

#1593 [14.0][ADD] purchase_stock_vendor_bill_breakdown
  purchase_stock_vendor_bill_breakdown/README.rst
  purchase_stock_vendor_bill_breakdown/__init__.py
  purchase_stock_vendor_bill_breakdown/__manifest__.py
  purchase_stock_vendor_bill_breakdown/models/__init__.py
  purchase_stock_vendor_bill_breakdown/models/purchase_order_line.py
  purchase_stock_vendor_bill_breakdown/readme/CONTRIBUTORS.rst
  purchase_stock_vendor_bill_breakdown/readme/DESCRIPTION.rst
  purchase_stock_vendor_bill_breakdown/tests/__init__.py
  purchase_stock_vendor_bill_breakdown/tests/test_stock_purchase_order_line.py
  setup/purchase_stock_vendor_bill_breakdown/odoo/addons/purchase_stock_vendor_bill_breakdown
  setup/purchase_stock_vendor_bill_breakdown/setup.py
Labels: approved, ready to merge, bot is merging ⏳
