Repository OCA/purchase-workflow, pull requests merged in 2023-09, with the labels that each got.

#1939 [15.0][ENH] purchase_deposit, add advance return option
  purchase_deposit/README.rst
  purchase_deposit/__manifest__.py
  purchase_deposit/models/__init__.py
  purchase_deposit/models/account_move.py
  purchase_deposit/models/purchase.py
  purchase_deposit/security/ir.model.access.csv
  purchase_deposit/tests/test_purchase_deposit.py
  purchase_deposit/wizard/__init__.py
  purchase_deposit/wizard/purchase_advance_deduct_option.py
  purchase_deposit/wizard/purchase_advance_deduct_option_views.xml
Labels: approved, bot is merging ⏳

#1854 [14.0][ADD] purchase_mass_mail
  purchase_mass_mail/README.rst
  purchase_mass_mail/__init__.py
  purchase_mass_mail/__manifest__.py
  purchase_mass_mail/models/__init__.py
  purchase_mass_mail/models/purchase_order.py
  purchase_mass_mail/readme/CONTRIBUTORS.rst
  purchase_mass_mail/readme/DESCRIPTION.rst
  purchase_mass_mail/readme/USAGE.rst
  purchase_mass_mail/static/description/icon.png
  purchase_mass_mail/tests/__init__.py
  purchase_mass_mail/tests/test_send_mass_mail.py
  purchase_mass_mail/view/purchase_order.xml
  purchase_mass_mail/wizards/__init__.py
  purchase_mass_mail/wizards/mail_compose_message.py
  setup/purchase_mass_mail/odoo/addons/purchase_mass_mail
  setup/purchase_mass_mail/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1991 [13.0][IMP] purchase_stock_price_unit_sync: Propagate change to stock move price_unit
  purchase_stock_price_unit_sync/models/purchase_order.py
Labels: approved, bot is merging ⏳

#1995 [FIX][15.0] purchase_stock_secondary_unit: update secondary uom on stock moves correctly
  purchase_order_secondary_unit/views/purchase_order_views.xml
  purchase_stock_secondary_unit/models/__init__.py
  purchase_stock_secondary_unit/models/purchase_order_line.py
  purchase_stock_secondary_unit/models/stock_move.py
Labels: approved, bot is merging ⏳

#1997 [14.0][FIX] purchase_stock_price_unit_sync: Apply sudo() to avoid access errors when accessing stock.valuation.layer
  purchase_stock_price_unit_sync/models/purchase_order.py
  purchase_stock_price_unit_sync/tests/test_purchase_stock_price_unit_sync.py
Labels: approved, bot is merging ⏳

#2000 [14.0][FIX] purchase_stock_price_unit_sync: Change to the appropriate context used in purchase_discount v14
  purchase_stock_price_unit_sync/models/purchase_order.py
Labels: bot is merging ⏳

#2001 [16.0] update dotfiles
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  purchase_merge/wizard/purchase_merge.py
Labels: bot is merging ⏳

#2005 [16.0][IMP] purchase_request: pre-commit stuff
  purchase_request/README.rst
  purchase_request/static/description/index.html
Labels: bot is merging ⏳

#2006 Update dotfiles
  .copier-answers.yml
  .github/workflows/pre-commit.yml
Labels: bot is merging ⏳

#1999 [15.0][FIX] purchase_stock_price_unit_sync: Apply sudo() to avoid access errors when accessing stock.valuation.layer
  purchase_stock_price_unit_sync/models/purchase_order.py
  purchase_stock_price_unit_sync/tests/test_purchase_stock_price_unit_sync.py
Labels: approved, bot is merging ⏳

#1993 [MIG] purchase_order_archive: Migration to 16.0
  purchase_order_archive/README.rst
  purchase_order_archive/__init__.py
  purchase_order_archive/__manifest__.py
  purchase_order_archive/i18n/es.po
  purchase_order_archive/i18n/purchase_order_archive.pot
  purchase_order_archive/i18n/zh_CN.po
  purchase_order_archive/models/__init__.py
  purchase_order_archive/models/purchase_order.py
  purchase_order_archive/readme/CONTRIBUTORS.rst
  purchase_order_archive/readme/DESCRIPTION.rst
  purchase_order_archive/readme/USAGE.rst
  purchase_order_archive/setup/purchase_order_archive/odoo/addons/purchase_order_archive
  purchase_order_archive/setup/purchase_order_archive/setup.py
  purchase_order_archive/static/description/icon.png
  purchase_order_archive/static/description/index.html
  purchase_order_archive/tests/__init__.py
  purchase_order_archive/tests/test_purchase_order_archive.py
  purchase_order_archive/views/purchase_order.xml
  setup/purchase_order_archive/odoo/addons/purchase_order_archive
  setup/purchase_order_archive/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1986 [12.0][MIG] purchase_work_acceptance_evaluation: Migrate to 12.0
  purchase_work_acceptance_evaluation/README.rst
  purchase_work_acceptance_evaluation/__init__.py
  purchase_work_acceptance_evaluation/__manifest__.py
  purchase_work_acceptance_evaluation/demo/evaluation_data.xml
  purchase_work_acceptance_evaluation/i18n/purchase_work_acceptance_evaluation.pot
  purchase_work_acceptance_evaluation/models/__init__.py
  purchase_work_acceptance_evaluation/models/res_config_settings.py
  purchase_work_acceptance_evaluation/models/work_acceptance.py
  purchase_work_acceptance_evaluation/models/work_acceptance_evaluation.py
  purchase_work_acceptance_evaluation/readme/CONFIGURE.rst
  purchase_work_acceptance_evaluation/readme/CONTRIBUTORS.rst
  purchase_work_acceptance_evaluation/readme/DESCRIPTION.rst
  purchase_work_acceptance_evaluation/readme/USAGE.rst
  purchase_work_acceptance_evaluation/report/__init__.py
  purchase_work_acceptance_evaluation/report/work_acceptance_evaluation_report.py
  purchase_work_acceptance_evaluation/report/work_acceptance_evaluation_report.xml
  purchase_work_acceptance_evaluation/security/ir.model.access.csv
  purchase_work_acceptance_evaluation/security/security.xml
  purchase_work_acceptance_evaluation/static/description/icon.png
  purchase_work_acceptance_evaluation/static/description/index.html
  purchase_work_acceptance_evaluation/tests/__init__.py
  purchase_work_acceptance_evaluation/tests/test_purchase_work_acceptance_evaluation.py
  purchase_work_acceptance_evaluation/views/res_config_settings_views.xml
  purchase_work_acceptance_evaluation/views/work_acceptance_evaluation_views.xml
  purchase_work_acceptance_evaluation/views/work_acceptance_views.xml
  setup/purchase_work_acceptance_evaluation/odoo/addons/purchase_work_acceptance_evaluation
  setup/purchase_work_acceptance_evaluation/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1460 [14.0][MIG] purchase_default_terms_conditions
  purchase_default_terms_conditions/README.rst
  purchase_default_terms_conditions/__init__.py
  purchase_default_terms_conditions/__manifest__.py
  purchase_default_terms_conditions/i18n/pt_BR.po
  purchase_default_terms_conditions/i18n/purchase_default_terms_conditions.pot
  purchase_default_terms_conditions/models/__init__.py
  purchase_default_terms_conditions/models/purchase.py
  purchase_default_terms_conditions/models/res_company.py
  purchase_default_terms_conditions/models/res_config_settings.py
  purchase_default_terms_conditions/models/res_partner.py
  purchase_default_terms_conditions/readme/CONFIGURE.rst
  purchase_default_terms_conditions/readme/CONTRIBUTORS.rst
  purchase_default_terms_conditions/readme/CREDITS.rst
  purchase_default_terms_conditions/readme/DESCRIPTION.rst
  purchase_default_terms_conditions/readme/USAGE.rst
  purchase_default_terms_conditions/static/description/banner.png
  purchase_default_terms_conditions/static/description/icon.png
  purchase_default_terms_conditions/static/description/index.html
  purchase_default_terms_conditions/static/index.html
  purchase_default_terms_conditions/tests/__init__.py
  purchase_default_terms_conditions/tests/test_purchase_order.py
  purchase_default_terms_conditions/views/res_config_settings.xml
  purchase_default_terms_conditions/views/res_partner_views.xml
  setup/purchase_default_terms_conditions/odoo/addons/purchase_default_terms_conditions
  setup/purchase_default_terms_conditions/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1982 [16.0][MIG] purchase_invoice_plan: Migration to 16.0
  purchase_invoice_plan/README.rst
  purchase_invoice_plan/__init__.py
  purchase_invoice_plan/__manifest__.py
  purchase_invoice_plan/data/purchase_data.xml
  purchase_invoice_plan/i18n/purchase_invoice_plan.pot
  purchase_invoice_plan/models/__init__.py
  purchase_invoice_plan/models/purchase.py
  purchase_invoice_plan/readme/CONTRIBUTORS.rst
  purchase_invoice_plan/readme/DESCRIPTION.rst
  purchase_invoice_plan/readme/USAGE.rst
  purchase_invoice_plan/security/ir.model.access.csv
  purchase_invoice_plan/static/description/icon.png
  purchase_invoice_plan/static/description/index.html
  purchase_invoice_plan/tests/__init__.py
  purchase_invoice_plan/tests/test_purchase_invoice_plan.py
  purchase_invoice_plan/views/purchase_view.xml
  purchase_invoice_plan/wizard/__init__.py
  purchase_invoice_plan/wizard/purchase_create_invoice_plan.py
  purchase_invoice_plan/wizard/purchase_create_invoice_plan_view.xml
  purchase_invoice_plan/wizard/purchase_make_planned_invoice.py
  purchase_invoice_plan/wizard/purchase_make_planned_invoice_view.xml
  setup/purchase_invoice_plan/odoo/addons/purchase_invoice_plan
  setup/purchase_invoice_plan/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2008 [15.0][FIX] purchase_order_secondary_unit: Set product unit of measure for purchases
  purchase_order_secondary_unit/models/purchase_order.py
Labels: approved, bot is merging ⏳

#2012 [16.0][FIX] purchase_discount: Apply always seller discount
  purchase_discount/models/purchase_order.py
  purchase_order_product_recommendation/wizards/purchase_order_recommendation.py
Labels: approved, bot is merging ⏳

#2015 [16.0][FIX] purchase_discount: Don't call _select_seller without product
  purchase_discount/models/purchase_order.py
  purchase_discount/tests/test_purchase_discount.py
Labels: bot is merging ⏳

#2013 [16.0][IMP] purchase_order_line_menu: Remove form in action
  purchase_order_line_menu/views/purchase_order_line_views.xml
Labels: approved, bot is merging ⏳

#1774 [15.0][ADD] purchase_deposit_analytic
  purchase_deposit_analytic/README.rst
  purchase_deposit_analytic/__init__.py
  purchase_deposit_analytic/__manifest__.py
  purchase_deposit_analytic/readme/CONTRIBUTORS.rst
  purchase_deposit_analytic/readme/DESCRIPTION.rst
  purchase_deposit_analytic/static/description/index.html
  purchase_deposit_analytic/tests/__init__.py
  purchase_deposit_analytic/tests/test_purchase_deposit_analytic.py
  purchase_deposit_analytic/wizard/__init__.py
  purchase_deposit_analytic/wizard/purchase_make_invoice_advance.py
  purchase_deposit_analytic/wizard/purchase_make_invoice_advance_views.xml
  setup/purchase_deposit_analytic/odoo/addons/purchase_deposit_analytic
  setup/purchase_deposit_analytic/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1919 [16.0][mig] purchase_fop_shipping: Migration to 16.0
  purchase_fop_shipping/README.rst
  purchase_fop_shipping/__init__.py
  purchase_fop_shipping/__manifest__.py
  purchase_fop_shipping/i18n/de.po
  purchase_fop_shipping/i18n/es.po
  purchase_fop_shipping/i18n/es_PE.po
  purchase_fop_shipping/i18n/fr.po
  purchase_fop_shipping/i18n/fr_BE.po
  purchase_fop_shipping/i18n/gl.po
  purchase_fop_shipping/i18n/hr.po
  purchase_fop_shipping/i18n/it.po
  purchase_fop_shipping/i18n/nl.po
  purchase_fop_shipping/i18n/nl_NL.po
  purchase_fop_shipping/i18n/pt_BR.po
  purchase_fop_shipping/i18n/purchase_fop_shipping.pot
  purchase_fop_shipping/i18n/ro.po
  purchase_fop_shipping/i18n/sl.po
  purchase_fop_shipping/i18n/vi_VN.po
  purchase_fop_shipping/models/__init__.py
  purchase_fop_shipping/models/partner.py
  purchase_fop_shipping/models/purchase.py
  purchase_fop_shipping/security/res_groups.xml
  purchase_fop_shipping/static/description/icon.png
  purchase_fop_shipping/tests/__init__.py
  purchase_fop_shipping/tests/test_fop_shipping.py
  purchase_fop_shipping/views/purchase_order.xml
  purchase_fop_shipping/views/res_partner.xml
  setup/purchase_fop_shipping/odoo/addons/purchase_fop_shipping
  setup/purchase_fop_shipping/setup.py
Labels: approved, bot is merging ⏳

#1266 [12.0][NEW] Module purchase_add_products_from_bom.
  purchase_add_products_from_bom/README.rst
  purchase_add_products_from_bom/__init__.py
  purchase_add_products_from_bom/__manifest__.py
  purchase_add_products_from_bom/i18n/fr.po
  purchase_add_products_from_bom/i18n/pt_BR.po
  purchase_add_products_from_bom/models/__init__.py
  purchase_add_products_from_bom/models/product_product.py
  purchase_add_products_from_bom/readme/CONTRIBUTORS.rst
  purchase_add_products_from_bom/readme/DESCRIPTION.rst
  purchase_add_products_from_bom/readme/HISTORY.rst
  purchase_add_products_from_bom/readme/INSTALL.rst
  purchase_add_products_from_bom/readme/USAGE.rst
  purchase_add_products_from_bom/static/description/index.html
  purchase_add_products_from_bom/tests/__init__.py
  purchase_add_products_from_bom/tests/test_purchase_add_products_from_bom.py
  purchase_add_products_from_bom/views/purchase_order_view.xml
  purchase_add_products_from_bom/wizard/__init__.py
  purchase_add_products_from_bom/wizard/add_products_from_bom.py
  purchase_add_products_from_bom/wizard/add_products_from_bom_view.xml
  setup/purchase_add_products_from_bom/odoo/addons/purchase_add_products_from_bom
  setup/purchase_add_products_from_bom/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1942 [FIX] purchase_request: fix datetime from request to order
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: approved, bot is merging ⏳
