Repository OCA/purchase-workflow, pull requests merged in 2023-06, with the labels that each got.

#1775 [15.0][FIX] purchase_invoice_plan: change qty after create invoiced will error
  purchase_invoice_plan/models/purchase.py
Labels: approved, bot is merging ⏳

#1878 [15.0][MIG] purchase_order_type_dashboard
  purchase_order_type_dashboard/README.rst
  purchase_order_type_dashboard/__init__.py
  purchase_order_type_dashboard/__manifest__.py
  purchase_order_type_dashboard/demo/purchase_order_type_dashboard.xml
  purchase_order_type_dashboard/i18n/es.po
  purchase_order_type_dashboard/i18n/purchase_order_type_dashboard.pot
  purchase_order_type_dashboard/models/__init__.py
  purchase_order_type_dashboard/models/purchase_order_type.py
  purchase_order_type_dashboard/readme/CONTRIBUTORS.rst
  purchase_order_type_dashboard/readme/DESCRIPTION.rst
  purchase_order_type_dashboard/static/description/icon.png
  purchase_order_type_dashboard/static/description/index.html
  purchase_order_type_dashboard/tests/__init__.py
  purchase_order_type_dashboard/tests/test_purchase_order_type_dashboard.py
  purchase_order_type_dashboard/views/menu_purchase_order.xml
  purchase_order_type_dashboard/views/view_purchase_order.xml
  purchase_order_type_dashboard/views/view_purchase_order_type.xml
  setup/purchase_order_type_dashboard/odoo/addons/purchase_order_type_dashboard
  setup/purchase_order_type_dashboard/setup.py
Labels: bot is merging ⏳

#1719 [15.0][MIG]purchase_cancel_confirm: Migration to 15.0
  purchase_cancel_confirm/README.rst
  purchase_cancel_confirm/__init__.py
  purchase_cancel_confirm/__manifest__.py
  purchase_cancel_confirm/i18n/purchase_cancel_confirm.pot
  purchase_cancel_confirm/model/__init__.py
  purchase_cancel_confirm/model/purchase.py
  purchase_cancel_confirm/readme/CONTRIBUTORS.rst
  purchase_cancel_confirm/readme/DESCRIPTION.rst
  purchase_cancel_confirm/static/description/icon.png
  purchase_cancel_confirm/static/description/index.html
  purchase_cancel_confirm/tests/__init__.py
  purchase_cancel_confirm/tests/test_purchase_cancel_confirm.py
  setup/purchase_cancel_confirm/odoo/addons/purchase_cancel_confirm
  setup/purchase_cancel_confirm/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1696 [15.0][MIG]purchase_last_price_info: Migration to 15.0
  purchase_last_price_info/README.rst
  purchase_last_price_info/__init__.py
  purchase_last_price_info/__manifest__.py
  purchase_last_price_info/i18n/ca.po
  purchase_last_price_info/i18n/de.po
  purchase_last_price_info/i18n/el_GR.po
  purchase_last_price_info/i18n/es.po
  purchase_last_price_info/i18n/es_ES.po
  purchase_last_price_info/i18n/eu.po
  purchase_last_price_info/i18n/fi.po
  purchase_last_price_info/i18n/fr.po
  purchase_last_price_info/i18n/fr_CH.po
  purchase_last_price_info/i18n/fr_FR.po
  purchase_last_price_info/i18n/gl.po
  purchase_last_price_info/i18n/hr.po
  purchase_last_price_info/i18n/hr_HR.po
  purchase_last_price_info/i18n/it.po
  purchase_last_price_info/i18n/nl.po
  purchase_last_price_info/i18n/nl_NL.po
  purchase_last_price_info/i18n/pt.po
  purchase_last_price_info/i18n/pt_BR.po
  purchase_last_price_info/i18n/purchase_last_price_info.pot
  purchase_last_price_info/i18n/ro.po
  purchase_last_price_info/i18n/ru.po
  purchase_last_price_info/i18n/sk.po
  purchase_last_price_info/i18n/sl.po
  purchase_last_price_info/i18n/tr.po
  purchase_last_price_info/i18n/tr_TR.po
  purchase_last_price_info/i18n/vi_VN.po
  purchase_last_price_info/i18n/zh_CN.po
  purchase_last_price_info/models/__init__.py
  purchase_last_price_info/models/product_product.py
  purchase_last_price_info/models/product_template.py
  purchase_last_price_info/readme/CONTRIBUTORS.rst
  purchase_last_price_info/readme/DESCRIPTION.rst
  purchase_last_price_info/readme/USAGE.rst
  purchase_last_price_info/static/description/icon.png
  purchase_last_price_info/static/description/index.html
  purchase_last_price_info/static/description/purchase_last_price.png
  purchase_last_price_info/tests/__init__.py
  purchase_last_price_info/tests/test_purchase_last_price_info.py
  purchase_last_price_info/views/product_views.xml
  setup/purchase_last_price_info/odoo/addons/purchase_last_price_info
  setup/purchase_last_price_info/setup.py
Labels: approved, bot is merging ⏳

#1840 [15.0][ENH] purchase_work_acceptance: compute search wa_acceted field for filter
  purchase_work_acceptance/models/purchase.py
  purchase_work_acceptance/tests/test_purchase_work_acceptance.py
  purchase_work_acceptance/views/purchase_views.xml
  purchase_work_acceptance/views/work_acceptance_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1887 [16.0][MIG] purchase_merge: Migration to 16.0
  purchase_merge/README.rst
  purchase_merge/__init__.py
  purchase_merge/__manifest__.py
  purchase_merge/i18n/purchase_merge.pot
  purchase_merge/readme/CONTRIBUTORS.rst
  purchase_merge/readme/DESCRIPTION.rst
  purchase_merge/readme/USAGE.rst
  purchase_merge/security/ir.model.access.csv
  purchase_merge/static/description/icon.png
  purchase_merge/static/description/index.html
  purchase_merge/tests/__init__.py
  purchase_merge/tests/test_purchase_merge.py
  purchase_merge/wizard/__init__.py
  purchase_merge/wizard/purchase_merge.py
  purchase_merge/wizard/purchase_merge_views.xml
  requirements.txt
  setup/purchase_merge/odoo/addons/purchase_merge
  setup/purchase_merge/setup.py
Labels: approved, bot is merging ⏳

#1759 [15.0][FIX] purchase_invoice_plan: full path with tree_view_ref
  purchase_invoice_plan/views/purchase_view.xml
Labels: bot is merging ⏳

#1684 [15.0][FW][IMP] product_form_purchase_link: do not filter out rfq
  product_form_purchase_link/views/purchase_order_line.xml
Labels: approved, bot is merging ⏳

#1683 [14.0][FW][IMP] product_form_purchase_link: do not filter out rfq
  product_form_purchase_link/views/purchase_order_line.xml
Labels: approved, bot is merging ⏳

#1893 [16.0][MIG] purchase_partner_selectable_option
  purchase_partner_selectable_option/README.rst
  purchase_partner_selectable_option/__init__.py
  purchase_partner_selectable_option/__manifest__.py
  purchase_partner_selectable_option/i18n/es.po
  purchase_partner_selectable_option/i18n/purchase_partner_selectable_option.pot
  purchase_partner_selectable_option/models/__init__.py
  purchase_partner_selectable_option/models/purchase_order.py
  purchase_partner_selectable_option/models/res_partner.py
  purchase_partner_selectable_option/readme/CONFIGURE.rst
  purchase_partner_selectable_option/readme/CONTRIBUTORS.rst
  purchase_partner_selectable_option/readme/DESCRIPTION.rst
  purchase_partner_selectable_option/readme/USAGE.rst
  purchase_partner_selectable_option/static/description/icon.png
  purchase_partner_selectable_option/static/description/index.html
  purchase_partner_selectable_option/tests/__init__.py
  purchase_partner_selectable_option/tests/test_purchase_partner_selectable_option.py
  purchase_partner_selectable_option/views/res_partner_view.xml
  setup/purchase_partner_selectable_option/odoo/addons/purchase_partner_selectable_option
  setup/purchase_partner_selectable_option/setup.py
Labels: approved, bot is merging ⏳

#1904 [16.0][FIX] purchase_partner_selectable_option: change deprecated method fi…
  purchase_partner_selectable_option/tests/test_purchase_partner_selectable_option.py
Labels: approved, bot is merging ⏳

#1853 [16.0][MIG] purchase_deposit: Migration to 16.0
  purchase_deposit/README.rst
  purchase_deposit/__init__.py
  purchase_deposit/__manifest__.py
  purchase_deposit/i18n/arp.po
  purchase_deposit/i18n/es.po
  purchase_deposit/i18n/fr.po
  purchase_deposit/i18n/purchase_deposit.pot
  purchase_deposit/models/__init__.py
  purchase_deposit/models/account_move.py
  purchase_deposit/models/purchase.py
  purchase_deposit/models/res_company.py
  purchase_deposit/models/res_config_settings.py
  purchase_deposit/readme/CONFIGURATION.rst
  purchase_deposit/readme/CONTRIBUTORS.rst
  purchase_deposit/readme/DESCRIPTION.rst
  purchase_deposit/readme/USAGE.rst
  purchase_deposit/security/ir.model.access.csv
  purchase_deposit/static/description/icon.png
  purchase_deposit/static/description/index.html
  purchase_deposit/tests/__init__.py
  purchase_deposit/tests/test_purchase_deposit.py
  purchase_deposit/views/purchase_view.xml
  purchase_deposit/views/res_config_settings_views.xml
  purchase_deposit/wizard/__init__.py
  purchase_deposit/wizard/purchase_make_invoice_advance.py
  purchase_deposit/wizard/purchase_make_invoice_advance_views.xml
  setup/purchase_deposit/odoo/addons/purchase_deposit
  setup/purchase_deposit/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1902 [16.0][MIG] purchase_security
  purchase_security/README.rst
  purchase_security/__init__.py
  purchase_security/__manifest__.py
  purchase_security/i18n/it.po
  purchase_security/i18n/purchase_security.pot
  purchase_security/models/__init__.py
  purchase_security/models/purchase_order.py
  purchase_security/readme/CONFIGURATION.rst
  purchase_security/readme/CONTRIBUTORS.rst
  purchase_security/readme/DESCRIPTION.rst
  purchase_security/readme/USAGE.rst
  purchase_security/security/security.xml
  purchase_security/static/description/icon.png
  purchase_security/static/description/index.html
  purchase_security/tests/__init__.py
  purchase_security/tests/test_access_rights.py
  purchase_security/views/purchase_order_views.xml
  setup/purchase_security/odoo/addons/purchase_security
  setup/purchase_security/setup.py
Labels: approved, bot is merging ⏳

#1137 [13.0][mig][purchase_manual_delivery]
  purchase_manual_delivery/README.rst
  purchase_manual_delivery/__init__.py
  purchase_manual_delivery/__manifest__.py
  purchase_manual_delivery/i18n/purchase_manual_delivery.pot
  purchase_manual_delivery/i18n/sl.po
  purchase_manual_delivery/models/__init__.py
  purchase_manual_delivery/models/purchase_order.py
  purchase_manual_delivery/models/res_company.py
  purchase_manual_delivery/models/res_config.py
  purchase_manual_delivery/readme/CONTRIBUTORS.rst
  purchase_manual_delivery/readme/DESCRIPTION.rst
  purchase_manual_delivery/readme/USAGE.rst
  purchase_manual_delivery/static/description/create_incoming_shipment_button.png
  purchase_manual_delivery/static/description/create_incoming_shipment_wizard.png
  purchase_manual_delivery/static/description/icon.png
  purchase_manual_delivery/static/description/index.html
  purchase_manual_delivery/tests/__init__.py
  purchase_manual_delivery/tests/test_purchase_manual_delivery.py
  purchase_manual_delivery/views/purchase_order_views.xml
  purchase_manual_delivery/views/res_config_view.xml
  purchase_manual_delivery/wizard/__init__.py
  purchase_manual_delivery/wizard/create_manual_stock_picking.py
  purchase_manual_delivery/wizard/create_manual_stock_picking_views.xml
  setup/purchase_manual_delivery/odoo/addons/purchase_manual_delivery
  setup/purchase_manual_delivery/setup.py
Labels: approved, bot is merging ⏳, stale

#1925 [16.0][MIG]purchase_location_by_line
  purchase_location_by_line/README.rst
  purchase_location_by_line/__init__.py
  purchase_location_by_line/__manifest__.py
  purchase_location_by_line/i18n/ca.po
  purchase_location_by_line/i18n/de.po
  purchase_location_by_line/i18n/es.po
  purchase_location_by_line/i18n/es_MX.po
  purchase_location_by_line/i18n/es_PE.po
  purchase_location_by_line/i18n/fi.po
  purchase_location_by_line/i18n/fr.po
  purchase_location_by_line/i18n/gl.po
  purchase_location_by_line/i18n/hr.po
  purchase_location_by_line/i18n/it.po
  purchase_location_by_line/i18n/nl_NL.po
  purchase_location_by_line/i18n/pt_BR.po
  purchase_location_by_line/i18n/pt_PT.po
  purchase_location_by_line/i18n/purchase_location_by_line.pot
  purchase_location_by_line/i18n/ro.po
  purchase_location_by_line/i18n/sl.po
  purchase_location_by_line/models/__init__.py
  purchase_location_by_line/models/purchase.py
  purchase_location_by_line/models/stock_picking.py
  purchase_location_by_line/readme/CONTRIBUTORS.rst
  purchase_location_by_line/readme/DESCRIPTION.rst
  purchase_location_by_line/static/description/icon.png
  purchase_location_by_line/static/description/index.html
  purchase_location_by_line/tests/__init__.py
  purchase_location_by_line/tests/test_purchase_delivery.py
  purchase_location_by_line/views/purchase_views.xml
  setup/purchase_location_by_line/odoo/addons/purchase_location_by_line
  setup/purchase_location_by_line/setup.py
Labels: approved, bot is merging ⏳

#1767 [13.0][FIX] purchase_stock_price_unit_sync: Don't write on children SVLs
  purchase_stock_price_unit_sync/models/purchase_order.py
Labels: approved, bot is merging ⏳

#1924 [13.0][IMP] purchase_order_line_sequence: use correct sequence in moves when section or notes in purchase order
  purchase_order_line_sequence/models/purchase.py
  purchase_order_line_sequence/tests/test_po_lines_sequence.py
Labels: approved, bot is merging ⏳

#1881 16.0 mig purchase_open_qty
  purchase_open_qty/README.rst
  purchase_open_qty/__init__.py
  purchase_open_qty/__manifest__.py
  purchase_open_qty/i18n/de.po
  purchase_open_qty/i18n/es.po
  purchase_open_qty/i18n/es_MX.po
  purchase_open_qty/i18n/es_PE.po
  purchase_open_qty/i18n/fi.po
  purchase_open_qty/i18n/fr.po
  purchase_open_qty/i18n/fr_BE.po
  purchase_open_qty/i18n/gl.po
  purchase_open_qty/i18n/hr.po
  purchase_open_qty/i18n/it.po
  purchase_open_qty/i18n/nl.po
  purchase_open_qty/i18n/nl_NL.po
  purchase_open_qty/i18n/pt_BR.po
  purchase_open_qty/i18n/pt_PT.po
  purchase_open_qty/i18n/purchase_open_qty.pot
  purchase_open_qty/i18n/ro.po
  purchase_open_qty/i18n/sl.po
  purchase_open_qty/i18n/vi_VN.po
  purchase_open_qty/i18n/zh_CN.po
  purchase_open_qty/init_hook.py
  purchase_open_qty/models/__init__.py
  purchase_open_qty/models/purchase_order.py
  purchase_open_qty/readme/CONTRIBUTORS.rst
  purchase_open_qty/readme/DESCRIPTION.rst
  purchase_open_qty/readme/USAGE.rst
  purchase_open_qty/static/description/icon.png
  purchase_open_qty/static/description/index.html
  purchase_open_qty/tests/__init__.py
  purchase_open_qty/tests/test_purchase_open_qty.py
  purchase_open_qty/views/purchase_view.xml
  setup/purchase_open_qty/odoo/addons/purchase_open_qty
  setup/purchase_open_qty/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1835 [16.0][mig] purchase_partner_incoterm: Migration to 16.0
  README.md
  purchase_partner_incoterm/README.rst
  purchase_partner_incoterm/__init__.py
  purchase_partner_incoterm/__manifest__.py
  purchase_partner_incoterm/i18n/purchase_partner_incoterm.pot
  purchase_partner_incoterm/models/__init__.py
  purchase_partner_incoterm/models/purchase_order.py
  purchase_partner_incoterm/models/res_partner.py
  purchase_partner_incoterm/readme/CONTRIBUTORS.rst
  purchase_partner_incoterm/readme/CREDITS.rst
  purchase_partner_incoterm/readme/DESCRIPTION.rst
  purchase_partner_incoterm/static/description/icon.png
  purchase_partner_incoterm/static/description/index.html
  purchase_partner_incoterm/views/partner_view.xml
  purchase_partner_incoterm/views/purchase_view.xml
  setup/purchase_partner_incoterm/odoo/addons/purchase_partner_incoterm
  setup/purchase_partner_incoterm/setup.py
Labels: approved, bot is merging ⏳

#1926 [14.0][IMP] purchase_order_line_sequence: use correct sequence in moves when section or notes in purchase order
  purchase_order_line_sequence/models/purchase.py
  purchase_order_line_sequence/tests/test_po_lines_sequence.py
Labels: bot is merging ⏳

#1917 [15.0][FIX] purchase_deposit: allow register deposit when state done (Locked)
  purchase_deposit/wizard/purchase_make_invoice_advance.py
Labels: approved, bot is merging ⏳
