Repository OCA/purchase-workflow, pull requests merged in 2023-05, with the labels that each got.

#1859 [15.0][IMP] purchase_order_secondary_unit: Add secondary units to purchase order reports
  purchase_order_secondary_unit/__manifest__.py
  purchase_order_secondary_unit/i18n/es.po
  purchase_order_secondary_unit/i18n/purchase_order_secondary_unit.pot
  purchase_order_secondary_unit/reports/purchase_order_templates.xml
  purchase_order_secondary_unit/reports/purchase_quotation_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#1844 [14.0][IMP] purchase_requisition_auto_rfq
  purchase_requisition_auto_rfq/demo/product_product.xml
  purchase_requisition_auto_rfq/models/purchase_requisition.py
  purchase_requisition_auto_rfq/view/purchase_requisition.xml
Labels: bot is merging ⏳

#1861 [16.0][MIG] purchase_order_product_recommendation: Migration to version 16.0
  purchase_order_product_recommendation/README.rst
  purchase_order_product_recommendation/__init__.py
  purchase_order_product_recommendation/__manifest__.py
  purchase_order_product_recommendation/i18n/es.po
  purchase_order_product_recommendation/i18n/purchase_order_product_recommendation.pot
  purchase_order_product_recommendation/readme/CONTRIBUTORS.rst
  purchase_order_product_recommendation/readme/DESCRIPTION.rst
  purchase_order_product_recommendation/readme/USAGE.rst
  purchase_order_product_recommendation/security/ir.model.access.csv
  purchase_order_product_recommendation/static/description/icon.png
  purchase_order_product_recommendation/static/description/index.html
  purchase_order_product_recommendation/tests/__init__.py
  purchase_order_product_recommendation/tests/test_recommendation.py
  purchase_order_product_recommendation/views/purchase_order_view.xml
  purchase_order_product_recommendation/wizards/__init__.py
  purchase_order_product_recommendation/wizards/purchase_order_recommendation.py
  purchase_order_product_recommendation/wizards/purchase_order_recommendation_view.xml
  setup/purchase_order_product_recommendation/odoo/addons/purchase_order_product_recommendation
  setup/purchase_order_product_recommendation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1865 [16.0][MIG] purchase_order_uninvoiced_amount: Migration to version 16.0
  purchase_order_uninvoiced_amount/README.rst
  purchase_order_uninvoiced_amount/__init__.py
  purchase_order_uninvoiced_amount/__manifest__.py
  purchase_order_uninvoiced_amount/i18n/en_US.po
  purchase_order_uninvoiced_amount/i18n/es.po
  purchase_order_uninvoiced_amount/i18n/purchase_order_uninvoiced_amount.pot
  purchase_order_uninvoiced_amount/models/__init__.py
  purchase_order_uninvoiced_amount/models/purchase_order.py
  purchase_order_uninvoiced_amount/readme/CONTRIBUTORS.rst
  purchase_order_uninvoiced_amount/readme/DESCRIPTION.rst
  purchase_order_uninvoiced_amount/static/description/icon.png
  purchase_order_uninvoiced_amount/static/description/index.html
  purchase_order_uninvoiced_amount/tests/__init__.py
  purchase_order_uninvoiced_amount/tests/test_purchase_order_uninvoiced_amount.py
  purchase_order_uninvoiced_amount/views/purchase_order_view.xml
  setup/purchase_order_uninvoiced_amount/odoo/addons/purchase_order_uninvoiced_amount
  setup/purchase_order_uninvoiced_amount/setup.py
Labels: approved, bot is merging ⏳

#1867 [15.0][MIG] purchase_stock_secondary_unit: Migration to version 15.0
  purchase_stock_secondary_unit/README.rst
  purchase_stock_secondary_unit/__init__.py
  purchase_stock_secondary_unit/__manifest__.py
  purchase_stock_secondary_unit/i18n/de.po
  purchase_stock_secondary_unit/i18n/es.po
  purchase_stock_secondary_unit/i18n/purchase_stock_secondary_unit.pot
  purchase_stock_secondary_unit/models/__init__.py
  purchase_stock_secondary_unit/models/purchase_order_line.py
  purchase_stock_secondary_unit/models/stock_move.py
  purchase_stock_secondary_unit/readme/CONTRIBUTORS.rst
  purchase_stock_secondary_unit/readme/DESCRIPTION.rst
  purchase_stock_secondary_unit/readme/USAGE.rst
  purchase_stock_secondary_unit/static/description/icon.png
  purchase_stock_secondary_unit/static/description/index.html
  purchase_stock_secondary_unit/tests/__init__.py
  purchase_stock_secondary_unit/tests/test_purchase_stock_secondary_unit.py
  setup/purchase_stock_secondary_unit/odoo/addons/purchase_stock_secondary_unit
  setup/purchase_stock_secondary_unit/setup.py
Labels: approved, bot is merging ⏳

#1869 [IMP] purchase_order_line_price_history: shrink button
  purchase_order_line_price_history/views/purchase_views.xml
Labels: approved, bot is merging ⏳

#1218 [14.0][MIG] purchase_substate
  purchase_substate/__init__.py
  purchase_substate/__manifest__.py
  purchase_substate/data/purchase_substate_data.xml
  purchase_substate/data/purchase_substate_demo.xml
  purchase_substate/data/purchase_substate_mail_template_data.xml
  purchase_substate/i18n/purchase_substate.pot
  purchase_substate/models/__init__.py
  purchase_substate/models/purchase_order.py
  purchase_substate/readme/CONTRIBUTORS.rst
  purchase_substate/readme/DESCRIPTION.rst
  purchase_substate/readme/USAGE.rst
  purchase_substate/static/description/icon.png
  purchase_substate/tests/__init__.py
  purchase_substate/tests/test_purchase_substate.py
  purchase_substate/views/purchase_views.xml
  setup/purchase_substate/odoo/addons/purchase_substate
  setup/purchase_substate/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1864 [16.0][MIG] purchase_order_supplierinfo_update: Migration to version 16.0
  purchase_order_supplierinfo_update/README.rst
  purchase_order_supplierinfo_update/__init__.py
  purchase_order_supplierinfo_update/__manifest__.py
  purchase_order_supplierinfo_update/i18n/purchase_order_supplierinfo_update.pot
  purchase_order_supplierinfo_update/models/__init__.py
  purchase_order_supplierinfo_update/models/purchase_order.py
  purchase_order_supplierinfo_update/readme/CONTRIBUTORS.rst
  purchase_order_supplierinfo_update/readme/DESCRIPTION.rst
  purchase_order_supplierinfo_update/readme/ROADMAP.rst
  purchase_order_supplierinfo_update/readme/USAGE.rst
  purchase_order_supplierinfo_update/static/description/icon.png
  purchase_order_supplierinfo_update/static/description/index.html
  purchase_order_supplierinfo_update/tests/__init__.py
  purchase_order_supplierinfo_update/tests/test_purchase_order_supplierinfo_update.py
  setup/purchase_order_supplierinfo_update/odoo/addons/purchase_order_supplierinfo_update
  setup/purchase_order_supplierinfo_update/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1836 [16.0][mig] purchase_order_no_zero_price: Migration to 16.0
  README.md
  purchase_order_no_zero_price/README.rst
  purchase_order_no_zero_price/__init__.py
  purchase_order_no_zero_price/__manifest__.py
  purchase_order_no_zero_price/i18n/purchase_order_no_zero_price.pot
  purchase_order_no_zero_price/models/__init__.py
  purchase_order_no_zero_price/models/purchase_order_line.py
  purchase_order_no_zero_price/readme/CONTRIBUTORS.rst
  purchase_order_no_zero_price/readme/DESCRIPTION.rst
  purchase_order_no_zero_price/readme/USAGE.rst
  purchase_order_no_zero_price/static/description/icon.png
  purchase_order_no_zero_price/static/description/index.html
  purchase_order_no_zero_price/tests/__init__.py
  purchase_order_no_zero_price/tests/test_purchase_order_no_zero_price.py
  setup/purchase_order_no_zero_price/odoo/addons/purchase_order_no_zero_price
  setup/purchase_order_no_zero_price/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1641 [14.0][IMP] purchase_reception_status: Add KPI Purchase tree inherits + :rainbow: column
  purchase_reception_status/views/purchase_order.xml
Labels: approved, bot is merging ⏳

#1566 [14.0][MIG] purchase_order_type_dashboard
  .github/workflows/test.yml
  purchase_order_type_dashboard/README.rst
  purchase_order_type_dashboard/__init__.py
  purchase_order_type_dashboard/__manifest__.py
  purchase_order_type_dashboard/demo/purchase_order_type_dashboard.xml
  purchase_order_type_dashboard/i18n/es.po
  purchase_order_type_dashboard/i18n/purchase_order_type_dashboard.pot
  purchase_order_type_dashboard/models/__init__.py
  purchase_order_type_dashboard/models/purchase_order_type.py
  purchase_order_type_dashboard/readme/CONTRIBUTORS.rst
  purchase_order_type_dashboard/readme/DESCRIPTION.rst
  purchase_order_type_dashboard/static/description/icon.png
  purchase_order_type_dashboard/static/description/index.html
  purchase_order_type_dashboard/tests/__init__.py
  purchase_order_type_dashboard/tests/test_purchase_order_type_dashboard.py
  purchase_order_type_dashboard/views/menu_purchase_order.xml
  purchase_order_type_dashboard/views/view_purchase_order.xml
  purchase_order_type_dashboard/views/view_purchase_order_type.xml
  setup/purchase_order_type_dashboard/odoo/addons/purchase_order_type_dashboard
  setup/purchase_order_type_dashboard/setup.py
Labels: approved, ready to merge, bot is merging ⏳
