Repository OCA/purchase-workflow, pull requests merged in 2023-04, with the labels that each got.

#1828 [14.0] product_form_purchase_link: label on purchase_lines_count different from Odoo SA
  product_form_purchase_link/i18n/fr.po
  product_form_purchase_link/i18n/product_form_purchase_link.pot
  product_form_purchase_link/models/product_product.py
  product_form_purchase_link/models/product_template.py
Labels: approved, bot is merging ⏳

#1817 [14.0][MIG]purchase_requisition_auto_rfq
  purchase_requisition_auto_rfq/README.rst
  purchase_requisition_auto_rfq/__init__.py
  purchase_requisition_auto_rfq/__manifest__.py
  purchase_requisition_auto_rfq/demo/product_product.xml
  purchase_requisition_auto_rfq/i18n/fr.po
  purchase_requisition_auto_rfq/i18n/purchase_requisition_auto_rfq.pot
  purchase_requisition_auto_rfq/models/__init__.py
  purchase_requisition_auto_rfq/models/purchase_requisition.py
  purchase_requisition_auto_rfq/readme/CONTRIBUTORS.rst
  purchase_requisition_auto_rfq/readme/DESCRIPTION.rst
  purchase_requisition_auto_rfq/readme/USAGE.rst
  purchase_requisition_auto_rfq/static/description/icon.png
  purchase_requisition_auto_rfq/static/description/index.html
  purchase_requisition_auto_rfq/tests/__init__.py
  purchase_requisition_auto_rfq/tests/test_purchase_requisition.py
  purchase_requisition_auto_rfq/view/purchase_requisition.xml
  setup/purchase_requisition_auto_rfq/odoo/addons/purchase_requisition_auto_rfq
  setup/purchase_requisition_auto_rfq/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1810 [16.0][ADD] purchase_order_owner
  purchase_order_owner/README.rst
  purchase_order_owner/__init__.py
  purchase_order_owner/__manifest__.py
  purchase_order_owner/models/__init__.py
  purchase_order_owner/models/purchase_order.py
  purchase_order_owner/readme/CONTRIBUTORS.rst
  purchase_order_owner/readme/DESCRIPTION.rst
  purchase_order_owner/static/description/index.html
  purchase_order_owner/tests/__init__.py
  purchase_order_owner/tests/test_purchase_order_owner.py
  purchase_order_owner/views/purchase_order_views.xml
  setup/purchase_order_owner/odoo/addons/purchase_order_owner
  setup/purchase_order_owner/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1807 [15.0][IMP] purchase_work_acceptance: add purchase in wa view
  purchase_work_acceptance/views/work_acceptance_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1656 [13.0][ADD] purchase_stock_tier_validation: Exclude RFQs pending to v…
  purchase_stock_tier_validation/__init__.py
  purchase_stock_tier_validation/__manifest__.py
  purchase_stock_tier_validation/models/__init__.py
  purchase_stock_tier_validation/models/stock_rule.py
  purchase_stock_tier_validation/readme/CONTRIBUTORS.rst
  purchase_stock_tier_validation/readme/DESCRIPTION.rst
  purchase_stock_tier_validation/static/description/icon.png
  purchase_stock_tier_validation/static/description/index.html
  purchase_stock_tier_validation/tests/__init__.py
  purchase_stock_tier_validation/tests/test_purchase_stock_tier_validation.py
  setup/purchase_stock_tier_validation/odoo/addons/purchase_stock_tier_validation
  setup/purchase_stock_tier_validation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1806 [16.0][MIG] purchase_line_procurement_group: Migration to 16.0
  purchase_line_procurement_group/README.rst
  purchase_line_procurement_group/__init__.py
  purchase_line_procurement_group/__manifest__.py
  purchase_line_procurement_group/i18n/fr.po
  purchase_line_procurement_group/i18n/purchase_line_procurement_group.pot
  purchase_line_procurement_group/i18n/zh_CN.po
  purchase_line_procurement_group/models/__init__.py
  purchase_line_procurement_group/models/purchase_order_line.py
  purchase_line_procurement_group/models/stock_move.py
  purchase_line_procurement_group/readme/CONTRIBUTORS.rst
  purchase_line_procurement_group/readme/CREDITS.rst
  purchase_line_procurement_group/readme/DESCRIPTION.rst
  purchase_line_procurement_group/static/description/icon.png
  purchase_line_procurement_group/static/description/index.html
  purchase_line_procurement_group/tests/__init__.py
  purchase_line_procurement_group/tests/test_po_line_proc_group.py
  purchase_line_procurement_group/views/purchase.xml
  setup/purchase_line_procurement_group/odoo/addons/purchase_line_procurement_group
  setup/purchase_line_procurement_group/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1168 [ADD] 12.0 : new module purchase_no_rfq that remove request for quotation concept in purchase workflow
  purchase_no_rfq/README.rst
  purchase_no_rfq/__init__.py
  purchase_no_rfq/__manifest__.py
  purchase_no_rfq/hooks.py
  purchase_no_rfq/i18n/fr.po
  purchase_no_rfq/models/__init__.py
  purchase_no_rfq/models/purchase_order.py
  purchase_no_rfq/readme/CONTRIBUTORS.rst
  purchase_no_rfq/readme/DESCRIPTION.rst
  purchase_no_rfq/readme/ROADMAP.rst
  purchase_no_rfq/reports/ir_actions_report.xml
  purchase_no_rfq/reports/purchase_order_template.xml
  purchase_no_rfq/static/description/purchase_order_form.png
  purchase_no_rfq/static/description/purchase_order_tree.png
  purchase_no_rfq/views/view_purchase_order.xml
  setup/purchase_no_rfq/odoo/addons/purchase_no_rfq
  setup/purchase_no_rfq/setup.py
Labels: approved, bot is merging ⏳, stale

#1845 [16.0][IMP] purchase_order_line_menu: remove the form view to prevent the user from making uncontrolled modifications
  purchase_order_line_menu/views/purchase_order_line_views.xml
Labels: approved, bot is merging ⏳

#1666 [16][MIG] purchase_lot
  purchase_lot/README.rst
  purchase_lot/__init__.py
  purchase_lot/__manifest__.py
  purchase_lot/i18n/purchase_lot.pot
  purchase_lot/models/__init__.py
  purchase_lot/models/purchase_order_line.py
  purchase_lot/models/stock_rule.py
  purchase_lot/readme/CONTRIBUTORS.rst
  purchase_lot/readme/DESCRIPTION.rst
  purchase_lot/static/description/icon.png
  purchase_lot/static/description/index.html
  purchase_lot/tests/__init__.py
  purchase_lot/tests/test_purchase_lot.py
  purchase_lot/views/purchase_order_view.xml
  setup/purchase_lot/odoo/addons/purchase_lot
  setup/purchase_lot/setup.py
Labels: approved, bot is merging ⏳

#1848 [14.0][MIG] purchase_stock_tier_validation
  purchase_stock_tier_validation/README.rst
  purchase_stock_tier_validation/__init__.py
  purchase_stock_tier_validation/__manifest__.py
  purchase_stock_tier_validation/i18n/purchase_stock_tier_validation.pot
  purchase_stock_tier_validation/models/__init__.py
  purchase_stock_tier_validation/models/stock_rule.py
  purchase_stock_tier_validation/readme/CONTRIBUTORS.rst
  purchase_stock_tier_validation/readme/DESCRIPTION.rst
  purchase_stock_tier_validation/static/description/icon.png
  purchase_stock_tier_validation/static/description/index.html
  purchase_stock_tier_validation/tests/__init__.py
  purchase_stock_tier_validation/tests/test_purchase_stock_tier_validation.py
  setup/purchase_stock_tier_validation/odoo/addons/purchase_stock_tier_validation
  setup/purchase_stock_tier_validation/setup.py
Labels: approved, bot is merging ⏳

#1850 [16.0][FIX] purchase_allowed_product: cannot find the vendor's products.
  purchase_allowed_product/__manifest__.py
  purchase_allowed_product/models/product.py
  purchase_allowed_product/tests/test_purchase_allowed_product.py
  purchase_allowed_product/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#1849 [16.0] MIG purchase_no_rfq
  purchase_no_rfq/README.rst
  purchase_no_rfq/__init__.py
  purchase_no_rfq/__manifest__.py
  purchase_no_rfq/hooks.py
  purchase_no_rfq/i18n/fr.po
  purchase_no_rfq/i18n/purchase_no_rfq.pot
  purchase_no_rfq/models/__init__.py
  purchase_no_rfq/models/purchase_order.py
  purchase_no_rfq/readme/CONTRIBUTORS.rst
  purchase_no_rfq/readme/DESCRIPTION.rst
  purchase_no_rfq/reports/ir_actions_report.xml
  purchase_no_rfq/reports/purchase_order_template.xml
  purchase_no_rfq/static/description/icon.png
  purchase_no_rfq/static/description/index.html
  purchase_no_rfq/static/description/purchase_order_form.png
  purchase_no_rfq/static/description/purchase_order_tree.png
  purchase_no_rfq/views/view_purchase_order.xml
  setup/purchase_no_rfq/odoo/addons/purchase_no_rfq
  setup/purchase_no_rfq/setup.py
Labels: approved, bot is merging ⏳

#1572 [FIX] Adding tags to unittests for purchase_deposit and purchase_order_line_sequence
  purchase_deposit/tests/test_purchase_deposit.py
  purchase_order_line_sequence/tests/test_po_lines_sequence.py
Labels: approved, ready to merge, bot is merging ⏳

#1856 [FIX] purchase_order_secondary_unit: Split tests that modifies Form new lines from edit
  purchase_order_secondary_unit/tests/test_purchase_order_secondary_unit.py
Labels: bot is merging ⏳

#1735 [15.0][ADD] purchase_order_qty_by_product_category
  purchase_order_qty_by_product_category/README.rst
  purchase_order_qty_by_product_category/__init__.py
  purchase_order_qty_by_product_category/__manifest__.py
  purchase_order_qty_by_product_category/i18n/fr.po
  purchase_order_qty_by_product_category/i18n/purchase_order_qty_by_product_category.pot
  purchase_order_qty_by_product_category/models/__init__.py
  purchase_order_qty_by_product_category/models/purchase_order.py
  purchase_order_qty_by_product_category/models/purchase_order_line.py
  purchase_order_qty_by_product_category/models/purchase_order_qty_by_product_category.py
  purchase_order_qty_by_product_category/models/res_company.py
  purchase_order_qty_by_product_category/models/res_config_settings.py
  purchase_order_qty_by_product_category/readme/CONTRIBUTORS.rst
  purchase_order_qty_by_product_category/readme/DESCRIPTION.rst
  purchase_order_qty_by_product_category/readme/USAGE.rst
  purchase_order_qty_by_product_category/security/ir.model.access.csv
  purchase_order_qty_by_product_category/static/description/index.html
  purchase_order_qty_by_product_category/tests/__init__.py
  purchase_order_qty_by_product_category/tests/test_purchase_order_qty_by_product_category.py
  purchase_order_qty_by_product_category/views/purchase_order.xml
  purchase_order_qty_by_product_category/views/res_config_settings.xml
  setup/purchase_order_qty_by_product_category/odoo/addons/purchase_order_qty_by_product_category
  setup/purchase_order_qty_by_product_category/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1851 [15.0][MIG] purchase_stock_tier_validation
  purchase_stock_tier_validation/README.rst
  purchase_stock_tier_validation/__init__.py
  purchase_stock_tier_validation/__manifest__.py
  purchase_stock_tier_validation/i18n/purchase_stock_tier_validation.pot
  purchase_stock_tier_validation/models/__init__.py
  purchase_stock_tier_validation/models/stock_rule.py
  purchase_stock_tier_validation/readme/CONTRIBUTORS.rst
  purchase_stock_tier_validation/readme/DESCRIPTION.rst
  purchase_stock_tier_validation/static/description/icon.png
  purchase_stock_tier_validation/static/description/index.html
  purchase_stock_tier_validation/tests/__init__.py
  purchase_stock_tier_validation/tests/test_purchase_stock_tier_validation.py
  setup/purchase_stock_tier_validation/odoo/addons/purchase_stock_tier_validation
  setup/purchase_stock_tier_validation/setup.py
Labels: approved, ready to merge, bot is merging ⏳
