Repository OCA/purchase-workflow, pull requests merged in 2023-03, with the labels that each got.

#1599 [16.0] [MIG] purchase_last_price_info
  purchase_last_price_info/README.rst
  purchase_last_price_info/__init__.py
  purchase_last_price_info/__manifest__.py
  purchase_last_price_info/i18n/ca.po
  purchase_last_price_info/i18n/de.po
  purchase_last_price_info/i18n/el_GR.po
  purchase_last_price_info/i18n/es.po
  purchase_last_price_info/i18n/es_ES.po
  purchase_last_price_info/i18n/eu.po
  purchase_last_price_info/i18n/fi.po
  purchase_last_price_info/i18n/fr.po
  purchase_last_price_info/i18n/fr_CH.po
  purchase_last_price_info/i18n/fr_FR.po
  purchase_last_price_info/i18n/gl.po
  purchase_last_price_info/i18n/hr.po
  purchase_last_price_info/i18n/hr_HR.po
  purchase_last_price_info/i18n/it.po
  purchase_last_price_info/i18n/nl.po
  purchase_last_price_info/i18n/nl_NL.po
  purchase_last_price_info/i18n/pt.po
  purchase_last_price_info/i18n/pt_BR.po
  purchase_last_price_info/i18n/purchase_last_price_info.pot
  purchase_last_price_info/i18n/ro.po
  purchase_last_price_info/i18n/ru.po
  purchase_last_price_info/i18n/sk.po
  purchase_last_price_info/i18n/sl.po
  purchase_last_price_info/i18n/tr.po
  purchase_last_price_info/i18n/tr_TR.po
  purchase_last_price_info/i18n/vi_VN.po
  purchase_last_price_info/i18n/zh_CN.po
  purchase_last_price_info/models/__init__.py
  purchase_last_price_info/models/product_product.py
  purchase_last_price_info/models/product_template.py
  purchase_last_price_info/readme/CONTRIBUTORS.rst
  purchase_last_price_info/readme/DESCRIPTION.rst
  purchase_last_price_info/readme/USAGE.rst
  purchase_last_price_info/static/description/icon.png
  purchase_last_price_info/static/description/index.html
  purchase_last_price_info/static/description/purchase_last_price.png
  purchase_last_price_info/tests/__init__.py
  purchase_last_price_info/tests/test_purchase_last_price_info.py
  purchase_last_price_info/views/product_views.xml
  setup/purchase_last_price_info/odoo/addons/purchase_last_price_info
  setup/purchase_last_price_info/setup.py
Labels: bot is merging ⏳

#1451 [IMP] purchase_request: update existing line if any
  purchase_request/models/stock_rule.py
  purchase_request/tests/test_purchase_request_procurement.py
Labels: bot is merging ⏳

#1797 [15.0][FIX]purchase_allowed_product: search product by vendor reference
  purchase_allowed_product/__manifest__.py
  purchase_allowed_product/views/purchase_order_view.xml
Labels: approved, bot is merging ⏳

#1773 [15.0][FIX] purchase_deposit: split function _prepare_advance_purchase_line for hook
  purchase_deposit/wizard/purchase_make_invoice_advance.py
Labels: approved, ready to merge, bot is merging ⏳

#1766 [14.0][FIX] purchase_request : supplier can be an individual
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1637 [15.0][MIG] purchase_request_exception
  purchase_request_exception/README.rst
  purchase_request_exception/__init__.py
  purchase_request_exception/__manifest__.py
  purchase_request_exception/data/purchase_request_exception_data.xml
  purchase_request_exception/i18n/fr.po
  purchase_request_exception/i18n/purchase_request_exception.pot
  purchase_request_exception/models/__init__.py
  purchase_request_exception/models/exception_rule.py
  purchase_request_exception/models/purchase_request.py
  purchase_request_exception/models/purchase_request_line.py
  purchase_request_exception/readme/CONTRIBUTORS.rst
  purchase_request_exception/readme/DESCRIPTION.rst
  purchase_request_exception/security/ir.model.access.csv
  purchase_request_exception/static/description/icon.png
  purchase_request_exception/static/description/index.html
  purchase_request_exception/tests/__init__.py
  purchase_request_exception/tests/test_purchase_request_exception.py
  purchase_request_exception/views/purchase_request_view.xml
  purchase_request_exception/wizard/__init__.py
  purchase_request_exception/wizard/purchase_request_exception_confirm.py
  purchase_request_exception/wizard/purchase_request_exception_confirm_view.xml
  setup/purchase_request_exception/odoo/addons/purchase_request_exception
  setup/purchase_request_exception/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1805 [16.0]purchase_request add new icon with svg file.
  purchase_request/static/description/icon.png
  purchase_request/static/description/icon.svg
Labels: approved, bot is merging ⏳

#1307 [14.0][ENH] purchase_work_acceptance_late_fines, option to create fines as refund
  purchase_work_acceptance_late_fines/__init__.py
  purchase_work_acceptance_late_fines/__manifest__.py
  purchase_work_acceptance_late_fines/models/account_move.py
  purchase_work_acceptance_late_fines/models/work_acceptance.py
  purchase_work_acceptance_late_fines/security/ir.model.access.csv
  purchase_work_acceptance_late_fines/tests/test_work_acceptance_late_fine.py
  purchase_work_acceptance_late_fines/views/account_move_views.xml
  purchase_work_acceptance_late_fines/views/work_acceptance_views.xml
  purchase_work_acceptance_late_fines/wizards/__init__.py
  purchase_work_acceptance_late_fines/wizards/work_acceptance_create_fines.py
  purchase_work_acceptance_late_fines/wizards/work_acceptance_create_fines_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1763 [15.0][ENH] purchase_work_acceptance_late_fines, option to create fines as refund
  purchase_work_acceptance_late_fines/__init__.py
  purchase_work_acceptance_late_fines/__manifest__.py
  purchase_work_acceptance_late_fines/models/account_move.py
  purchase_work_acceptance_late_fines/models/work_acceptance.py
  purchase_work_acceptance_late_fines/security/ir.model.access.csv
  purchase_work_acceptance_late_fines/tests/test_work_acceptance_late_fine.py
  purchase_work_acceptance_late_fines/views/account_move_views.xml
  purchase_work_acceptance_late_fines/views/work_acceptance_views.xml
  purchase_work_acceptance_late_fines/wizards/__init__.py
  purchase_work_acceptance_late_fines/wizards/work_acceptance_create_fines.py
  purchase_work_acceptance_late_fines/wizards/work_acceptance_create_fines_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1638 [15.0][MIG] purchase_request_substate
  purchase_request_substate/README.rst
  purchase_request_substate/__init__.py
  purchase_request_substate/__manifest__.py
  purchase_request_substate/data/purchase_request_substate_data.xml
  purchase_request_substate/data/purchase_substate_mail_template_data.xml
  purchase_request_substate/demo/purchase_request_substate_demo.xml
  purchase_request_substate/i18n/purchase_request_substate.pot
  purchase_request_substate/models/__init__.py
  purchase_request_substate/models/purchase_request.py
  purchase_request_substate/readme/CONTRIBUTORS.rst
  purchase_request_substate/readme/DESCRIPTION.rst
  purchase_request_substate/readme/USAGE.rst
  purchase_request_substate/static/description/icon.png
  purchase_request_substate/static/description/index.html
  purchase_request_substate/tests/__init__.py
  purchase_request_substate/tests/test_purchase_request_substate.py
  purchase_request_substate/views/purchase_request_views.xml
  setup/purchase_request_substate/odoo/addons/purchase_request_substate
  setup/purchase_request_substate/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1779 [MIG] purchase_order_approved: Migration to 16.0
  purchase_order_approved/README.rst
  purchase_order_approved/__init__.py
  purchase_order_approved/__manifest__.py
  purchase_order_approved/i18n/am.po
  purchase_order_approved/i18n/ar.po
  purchase_order_approved/i18n/ca.po
  purchase_order_approved/i18n/da.po
  purchase_order_approved/i18n/de.po
  purchase_order_approved/i18n/el_GR.po
  purchase_order_approved/i18n/es.po
  purchase_order_approved/i18n/es_ES.po
  purchase_order_approved/i18n/es_MX.po
  purchase_order_approved/i18n/eu.po
  purchase_order_approved/i18n/fi.po
  purchase_order_approved/i18n/fr.po
  purchase_order_approved/i18n/fr_CA.po
  purchase_order_approved/i18n/fr_FR.po
  purchase_order_approved/i18n/gl.po
  purchase_order_approved/i18n/hr.po
  purchase_order_approved/i18n/hr_HR.po
  purchase_order_approved/i18n/it.po
  purchase_order_approved/i18n/nb.po
  purchase_order_approved/i18n/nb_NO.po
  purchase_order_approved/i18n/nl.po
  purchase_order_approved/i18n/nl_BE.po
  purchase_order_approved/i18n/nl_NL.po
  purchase_order_approved/i18n/pt_BR.po
  purchase_order_approved/i18n/purchase_order_approved.pot
  purchase_order_approved/i18n/ro.po
  purchase_order_approved/i18n/sk.po
  purchase_order_approved/i18n/sl.po
  purchase_order_approved/i18n/tr.po
  purchase_order_approved/i18n/vi_VN.po
  purchase_order_approved/i18n/zh_CN.po
  purchase_order_approved/models/__init__.py
  purchase_order_approved/models/purchase_order.py
  purchase_order_approved/models/res_company.py
  purchase_order_approved/models/res_config.py
  purchase_order_approved/models/res_partner.py
  purchase_order_approved/readme/CONFIGURE.rst
  purchase_order_approved/readme/CONTRIBUTORS.rst
  purchase_order_approved/readme/DESCRIPTION.rst
  purchase_order_approved/readme/HISTORY.rst
  purchase_order_approved/readme/USAGE.rst
  purchase_order_approved/static/description/icon.png
  purchase_order_approved/static/description/index.html
  purchase_order_approved/static/description/schema.png
  purchase_order_approved/tests/__init__.py
  purchase_order_approved/tests/test_purchase_order.py
  purchase_order_approved/tests/test_purchase_order_approved.py
  purchase_order_approved/views/purchase_order_view.xml
  purchase_order_approved/views/res_config_view.xml
  purchase_order_approved/views/res_partner.xml
  setup/purchase_order_approved/odoo/addons/purchase_order_approved
  setup/purchase_order_approved/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1687 [16.0][MIG] purchase_delivery_split_date: Migration to 16.0
  purchase_delivery_split_date/README.rst
  purchase_delivery_split_date/__init__.py
  purchase_delivery_split_date/__manifest__.py
  purchase_delivery_split_date/i18n/ca.po
  purchase_delivery_split_date/i18n/de.po
  purchase_delivery_split_date/i18n/es.po
  purchase_delivery_split_date/i18n/es_MX.po
  purchase_delivery_split_date/i18n/es_PE.po
  purchase_delivery_split_date/i18n/fi.po
  purchase_delivery_split_date/i18n/fr.po
  purchase_delivery_split_date/i18n/gl.po
  purchase_delivery_split_date/i18n/hr.po
  purchase_delivery_split_date/i18n/it.po
  purchase_delivery_split_date/i18n/nl_NL.po
  purchase_delivery_split_date/i18n/pt_BR.po
  purchase_delivery_split_date/i18n/pt_PT.po
  purchase_delivery_split_date/i18n/purchase_delivery_split_date.pot
  purchase_delivery_split_date/i18n/ro.po
  purchase_delivery_split_date/i18n/sl.po
  purchase_delivery_split_date/i18n/zh_CN.po
  purchase_delivery_split_date/models/__init__.py
  purchase_delivery_split_date/models/purchase_order.py
  purchase_delivery_split_date/models/purchase_order_line.py
  purchase_delivery_split_date/models/stock_picking.py
  purchase_delivery_split_date/readme/CONTRIBUTORS.rst
  purchase_delivery_split_date/readme/DESCRIPTION.rst
  purchase_delivery_split_date/readme/HISTORY.rst
  purchase_delivery_split_date/readme/USAGE.rst
  purchase_delivery_split_date/static/description/icon.png
  purchase_delivery_split_date/static/description/index.html
  purchase_delivery_split_date/static/description/split_delivery.png
  purchase_delivery_split_date/tests/__init__.py
  purchase_delivery_split_date/tests/test_purchase_delivery.py
  setup/purchase_delivery_split_date/odoo/addons/purchase_delivery_split_date
  setup/purchase_delivery_split_date/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1601 [16.0][MIG] purchase_triple_discount: Migration to 16.0
  purchase_triple_discount/README.rst
  purchase_triple_discount/__init__.py
  purchase_triple_discount/__manifest__.py
  purchase_triple_discount/i18n/de.po
  purchase_triple_discount/i18n/es.po
  purchase_triple_discount/i18n/es_MX.po
  purchase_triple_discount/i18n/es_PE.po
  purchase_triple_discount/i18n/fi.po
  purchase_triple_discount/i18n/fr.po
  purchase_triple_discount/i18n/hr.po
  purchase_triple_discount/i18n/it.po
  purchase_triple_discount/i18n/nl_NL.po
  purchase_triple_discount/i18n/pt_BR.po
  purchase_triple_discount/i18n/pt_PT.po
  purchase_triple_discount/i18n/purchase_triple_discount.pot
  purchase_triple_discount/i18n/ro.po
  purchase_triple_discount/i18n/sl.po
  purchase_triple_discount/i18n/zh_CN.po
  purchase_triple_discount/models/__init__.py
  purchase_triple_discount/models/product_supplierinfo.py
  purchase_triple_discount/models/purchase_order.py
  purchase_triple_discount/models/res_partner.py
  purchase_triple_discount/readme/CONTRIBUTORS.rst
  purchase_triple_discount/readme/DESCRIPTION.rst
  purchase_triple_discount/readme/USAGE.rst
  purchase_triple_discount/report/__init__.py
  purchase_triple_discount/report/purchase_report.py
  purchase_triple_discount/static/description/icon.png
  purchase_triple_discount/static/description/index.html
  purchase_triple_discount/tests/__init__.py
  purchase_triple_discount/tests/test_purchase_discount.py
  purchase_triple_discount/views/product_supplierinfo_view.xml
  purchase_triple_discount/views/purchase_order_report.xml
  purchase_triple_discount/views/purchase_view.xml
  purchase_triple_discount/views/res_partner_view.xml
  setup/purchase_triple_discount/odoo/addons/purchase_triple_discount
  setup/purchase_triple_discount/setup.py
Labels: bot is merging ⏳

#1811 [13.0][FIX][purchase_discount] discount are readonly when invoice state is fully billed
  purchase_discount/views/purchase_discount_view.xml
Labels: approved, bot is merging ⏳

#1689 15.0 fix default note purchase order
  purchase_default_terms_conditions/models/purchase.py
Labels: approved, bot is merging ⏳

#1709 [16.0] [MIG] purchase default terms conditions
  purchase_default_terms_conditions/README.rst
  purchase_default_terms_conditions/__init__.py
  purchase_default_terms_conditions/__manifest__.py
  purchase_default_terms_conditions/i18n/pt_BR.po
  purchase_default_terms_conditions/i18n/purchase_default_terms_conditions.pot
  purchase_default_terms_conditions/models/__init__.py
  purchase_default_terms_conditions/models/purchase.py
  purchase_default_terms_conditions/models/res_company.py
  purchase_default_terms_conditions/models/res_config_settings.py
  purchase_default_terms_conditions/models/res_partner.py
  purchase_default_terms_conditions/readme/CONFIGURE.rst
  purchase_default_terms_conditions/readme/CONTRIBUTORS.rst
  purchase_default_terms_conditions/readme/CREDITS.rst
  purchase_default_terms_conditions/readme/DESCRIPTION.rst
  purchase_default_terms_conditions/readme/USAGE.rst
  purchase_default_terms_conditions/static/description/banner.png
  purchase_default_terms_conditions/static/description/icon.png
  purchase_default_terms_conditions/static/description/index.html
  purchase_default_terms_conditions/static/index.html
  purchase_default_terms_conditions/tests/__init__.py
  purchase_default_terms_conditions/tests/test_purchase_order.py
  purchase_default_terms_conditions/views/res_config_settings.xml
  purchase_default_terms_conditions/views/res_partner_views.xml
  setup/purchase_default_terms_conditions/odoo/addons/purchase_default_terms_conditions
  setup/purchase_default_terms_conditions/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1679 [15.0][ADD] Purchase Order Merge
  purchase_merge/README.rst
  purchase_merge/__init__.py
  purchase_merge/__manifest__.py
  purchase_merge/readme/CONTRIBUTORS.rst
  purchase_merge/readme/DESCRIPTION.rst
  purchase_merge/readme/USAGE.rst
  purchase_merge/security/ir.model.access.csv
  purchase_merge/static/description/index.html
  purchase_merge/tests/__init__.py
  purchase_merge/tests/test_purchase_merge.py
  purchase_merge/wizard/__init__.py
  purchase_merge/wizard/purchase_merge.py
  purchase_merge/wizard/purchase_merge_views.xml
  requirements.txt
  setup/purchase_merge/odoo/addons/purchase_merge
  setup/purchase_merge/setup.py
Labels: approved, merged 🎉

#1617 [15.0] purchase_tag: Migration to 15.0
  purchase_tag/README.rst
  purchase_tag/__init__.py
  purchase_tag/__manifest__.py
  purchase_tag/i18n/purchase_tag.pot
  purchase_tag/models/__init__.py
  purchase_tag/models/purchase_order.py
  purchase_tag/models/purchase_tag.py
  purchase_tag/readme/CONTRIBUTORS.rst
  purchase_tag/readme/DESCRIPTION.rst
  purchase_tag/readme/USAGE.rst
  purchase_tag/security/ir.model.access.csv
  purchase_tag/static/description/icon.png
  purchase_tag/static/description/index.html
  purchase_tag/views/purchase_tag_view.xml
  purchase_tag/views/purchase_view.xml
  setup/purchase_tag/odoo/addons/purchase_tag
  setup/purchase_tag/setup.py
Labels: approved, bot is merging ⏳

#1732 [15.0][ADD] purchase_receipt_percentage
  purchase_receipt_percentage/README.rst
  purchase_receipt_percentage/__init__.py
  purchase_receipt_percentage/__manifest__.py
  purchase_receipt_percentage/i18n/fr.po
  purchase_receipt_percentage/i18n/purchase_receipt_percentage.pot
  purchase_receipt_percentage/models/__init__.py
  purchase_receipt_percentage/models/purchase_order.py
  purchase_receipt_percentage/models/purchase_order_line.py
  purchase_receipt_percentage/readme/CONTRIBUTORS.rst
  purchase_receipt_percentage/readme/DESCRIPTION.rst
  purchase_receipt_percentage/static/description/index.html
  purchase_receipt_percentage/tests/__init__.py
  purchase_receipt_percentage/tests/test_purchase_receipt_percentage.py
  purchase_receipt_percentage/views/purchase_order.xml
  setup/purchase_receipt_percentage/odoo/addons/purchase_receipt_percentage
  setup/purchase_receipt_percentage/setup.py
Labels: approved, ready to merge, merged 🎉

#1731 [15.0][ADD] purchase_total_ordered_qty
  purchase_total_ordered_qty/README.rst
  purchase_total_ordered_qty/__init__.py
  purchase_total_ordered_qty/__manifest__.py
  purchase_total_ordered_qty/i18n/fr.po
  purchase_total_ordered_qty/i18n/purchase_total_ordered_qty.pot
  purchase_total_ordered_qty/models/__init__.py
  purchase_total_ordered_qty/models/purchase_order.py
  purchase_total_ordered_qty/readme/CONTRIBUTORS.rst
  purchase_total_ordered_qty/readme/DESCRIPTION.rst
  purchase_total_ordered_qty/static/description/icon.png
  purchase_total_ordered_qty/static/description/index.html
  purchase_total_ordered_qty/tests/__init__.py
  purchase_total_ordered_qty/tests/test_purchase_total_ordered_qty.py
  purchase_total_ordered_qty/views/purchase_order.xml
  setup/purchase_total_ordered_qty/odoo/addons/purchase_total_ordered_qty
  setup/purchase_total_ordered_qty/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1821 [14.0][FIX][purchase_discount] discount are readonly when invoice state is fully billed
  purchase_discount/views/purchase_discount_view.xml
Labels: bot is merging ⏳

#1826 [15.0][FIX] purchase_discount: price_unit update recursion failure
  purchase_discount/models/purchase_order.py
  purchase_discount/models/stock_move.py
  purchase_discount/tests/test_product_supplierinfo_discount.py
Labels: approved, bot is merging ⏳

#1708 [15.0][MIG] purchase_order_secondary_unit: Migration to version 15.0
  oca_dependencies.txt
  purchase_order_secondary_unit/README.rst
  purchase_order_secondary_unit/__init__.py
  purchase_order_secondary_unit/__manifest__.py
  purchase_order_secondary_unit/i18n/de.po
  purchase_order_secondary_unit/i18n/es.po
  purchase_order_secondary_unit/i18n/fr.po
  purchase_order_secondary_unit/i18n/ja.po
  purchase_order_secondary_unit/i18n/purchase_order_secondary_unit.pot
  purchase_order_secondary_unit/models/__init__.py
  purchase_order_secondary_unit/models/product_product.py
  purchase_order_secondary_unit/models/product_template.py
  purchase_order_secondary_unit/models/purchase_order.py
  purchase_order_secondary_unit/readme/CONTRIBUTORS.rst
  purchase_order_secondary_unit/readme/DESCRIPTION.rst
  purchase_order_secondary_unit/readme/USAGE.rst
  purchase_order_secondary_unit/static/description/icon.png
  purchase_order_secondary_unit/static/description/index.html
  purchase_order_secondary_unit/tests/__init__.py
  purchase_order_secondary_unit/tests/test_purchase_order_secondary_unit.py
  purchase_order_secondary_unit/views/product_views.xml
  purchase_order_secondary_unit/views/purchase_order_views.xml
  setup/purchase_order_secondary_unit/odoo/addons/purchase_order_secondary_unit
  setup/purchase_order_secondary_unit/setup.py
Labels: approved, bot is merging ⏳

#1790 [15.0][MIG]sale_purchase_force_vendor: Migration to V15
  sale_purchase_force_vendor/README.rst
  sale_purchase_force_vendor/__init__.py
  sale_purchase_force_vendor/__manifest__.py
  sale_purchase_force_vendor/i18n/es.po
  sale_purchase_force_vendor/i18n/sale_purchase_force_vendor.pot
  sale_purchase_force_vendor/models/__init__.py
  sale_purchase_force_vendor/models/res_company.py
  sale_purchase_force_vendor/models/res_config_settings.py
  sale_purchase_force_vendor/models/sale_order_line.py
  sale_purchase_force_vendor/models/stock_move.py
  sale_purchase_force_vendor/readme/CONFIGURE.rst
  sale_purchase_force_vendor/readme/CONTRIBUTORS.rst
  sale_purchase_force_vendor/readme/DESCRIPTION.rst
  sale_purchase_force_vendor/readme/USAGE.rst
  sale_purchase_force_vendor/static/description/icon.png
  sale_purchase_force_vendor/static/description/index.html
  sale_purchase_force_vendor/tests/__init__.py
  sale_purchase_force_vendor/tests/common.py
  sale_purchase_force_vendor/tests/test_sale_purchase_force_vendor.py
  sale_purchase_force_vendor/views/res_config_settings_view.xml
  sale_purchase_force_vendor/views/sale_order_view.xml
  setup/sale_purchase_force_vendor/odoo/addons/sale_purchase_force_vendor
  setup/sale_purchase_force_vendor/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1823 [16.0][FIX][purchase_discount] discount are readonly when invoice state is fully billed
  purchase_discount/models/purchase_order.py
  purchase_discount/models/stock_move.py
  purchase_discount/tests/test_product_supplierinfo_discount.py
  purchase_discount/views/purchase_discount_view.xml
Labels: approved, bot is merging ⏳
