Repository OCA/purchase-workflow, pull requests merged in 2023-11, with the labels that each got.

#2084 [FIX] purchase_order_product_recommendation: fix abs missing error
  purchase_order_product_recommendation/wizards/purchase_order_recommendation_view.xml
Labels: bug, bot is merging ⏳

#2062 [14.0] [ADD] purchase_order_partner_manual_rank
  purchase_order_partner_manual_rank/README.rst
  purchase_order_partner_manual_rank/__init__.py
  purchase_order_partner_manual_rank/__manifest__.py
  purchase_order_partner_manual_rank/readme/CONTRIBUTORS.rst
  purchase_order_partner_manual_rank/readme/DESCRIPTION.rst
  purchase_order_partner_manual_rank/readme/USAGE.rst
  purchase_order_partner_manual_rank/static/description/index.html
  purchase_order_partner_manual_rank/views/purchase_order_views.xml
  setup/purchase_order_partner_manual_rank/odoo/addons/purchase_order_partner_manual_rank
  setup/purchase_order_partner_manual_rank/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2085 [IMP] purchase_discount: allow hiding discount column
  purchase_discount/views/purchase_discount_view.xml
Labels: enhancement, approved, bot is merging ⏳

#2069 [FIX] purchase_quick: price_unit when qty_to_process is less than seller’s qty_min
  purchase_quick/models/purchase_order.py
  purchase_quick/tests/test_quick_purchase.py
Labels: approved, ready to merge, bot is merging ⏳

#1783 12.0 mig product supplierinfo qty multiplier
  product_supplierinfo_qty_multiplier/README.rst
  product_supplierinfo_qty_multiplier/__init__.py
  product_supplierinfo_qty_multiplier/__manifest__.py
  product_supplierinfo_qty_multiplier/i18n/fr.po
  product_supplierinfo_qty_multiplier/i18n/product_supplierinfo_qty_multiplier.pot
  product_supplierinfo_qty_multiplier/models/__init__.py
  product_supplierinfo_qty_multiplier/models/product_supplierinfo.py
  product_supplierinfo_qty_multiplier/models/purchase_order_line.py
  product_supplierinfo_qty_multiplier/readme/CONTRIBUTORS.rst
  product_supplierinfo_qty_multiplier/readme/DESCRIPTION.rst
  product_supplierinfo_qty_multiplier/readme/USAGE.rst
  product_supplierinfo_qty_multiplier/static/description/icon.png
  product_supplierinfo_qty_multiplier/static/description/index.html
  product_supplierinfo_qty_multiplier/tests/__init__.py
  product_supplierinfo_qty_multiplier/tests/test_purchase_order.py
  product_supplierinfo_qty_multiplier/views/product_supplierinfo_view.xml
  setup/product_supplierinfo_qty_multiplier/odoo/addons/product_supplierinfo_qty_multiplier
  setup/product_supplierinfo_qty_multiplier/setup.py
Labels: approved, bot is merging ⏳

#1992 [15.0][FIX] purchase_request: default payment_terms when create RFQ
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1748 [15.0][MIG] purchase_request_cancel_confirm
  purchase_request_cancel_confirm/README.rst
  purchase_request_cancel_confirm/__init__.py
  purchase_request_cancel_confirm/__manifest__.py
  purchase_request_cancel_confirm/i18n/purchase_request_cancel_confirm.pot
  purchase_request_cancel_confirm/model/__init__.py
  purchase_request_cancel_confirm/model/purchase_request.py
  purchase_request_cancel_confirm/readme/CONTRIBUTORS.rst
  purchase_request_cancel_confirm/readme/DESCRIPTION.rst
  purchase_request_cancel_confirm/static/description/icon.png
  purchase_request_cancel_confirm/static/description/index.html
  purchase_request_cancel_confirm/tests/__init__.py
  purchase_request_cancel_confirm/tests/test_purchase_request_cancel_confirm.py
  setup/purchase_request_cancel_confirm/odoo/addons/purchase_request_cancel_confirm
  setup/purchase_request_cancel_confirm/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2082 [16.0] purchase_deposit: fix string
  purchase_deposit/models/purchase.py
Labels: approved, bot is merging ⏳

#2079 [15.0][FIX] purchase_discount: allow creating without product_tmpl_id
  purchase_discount/models/product_supplierinfo.py
  purchase_discount/tests/test_product_supplierinfo_discount.py
Labels: bug, approved, bot is merging ⏳

#2058 [16.0][FIX] purchase_request: default payment_terms when create RFQ
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: bot is merging ⏳

#2091 [15.0][FIX] sale_purchase_force_vendor: Users with salesman security group can not confirm sale orders
  sale_purchase_force_vendor/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#1831 [16.0][MIG] purchase_reception_status
  purchase_reception_status/README.rst
  purchase_reception_status/__init__.py
  purchase_reception_status/__manifest__.py
  purchase_reception_status/i18n/fr.po
  purchase_reception_status/i18n/it.po
  purchase_reception_status/i18n/ja.po
  purchase_reception_status/i18n/purchase_reception_status.pot
  purchase_reception_status/models/__init__.py
  purchase_reception_status/models/purchase_order.py
  purchase_reception_status/readme/CONTRIBUTORS.rst
  purchase_reception_status/readme/DESCRIPTION.rst
  purchase_reception_status/readme/USAGE.rst
  purchase_reception_status/static/description/icon.png
  purchase_reception_status/static/description/index.html
  purchase_reception_status/views/purchase_order.xml
  setup/purchase_reception_status/odoo/addons/purchase_reception_status
  setup/purchase_reception_status/setup.py
Labels: approved, bot is merging ⏳

#1883 [16.0][ADD] purchase_order_hide_receipt_status
  purchase_order_hide_receipt_status/README.rst
  purchase_order_hide_receipt_status/__init__.py
  purchase_order_hide_receipt_status/__manifest__.py
  purchase_order_hide_receipt_status/readme/DESCRIPTION.rst
  purchase_order_hide_receipt_status/static/description/index.html
  purchase_order_hide_receipt_status/views/purchase_order.xml
  setup/purchase_order_hide_receipt_status/odoo/addons/purchase_order_hide_receipt_status
  setup/purchase_order_hide_receipt_status/setup.py
Labels: approved, bot is merging ⏳

#2092 [16.0][MIG] purchase_warn_message: Migration to version 16.0
  purchase_warn_message/README.rst
  purchase_warn_message/__init__.py
  purchase_warn_message/__manifest__.py
  purchase_warn_message/i18n/purchase_warn_message.pot
  purchase_warn_message/models/__init__.py
  purchase_warn_message/models/purchase_order.py
  purchase_warn_message/readme/CONTRIBUTORS.rst
  purchase_warn_message/readme/DESCRIPTION.rst
  purchase_warn_message/static/description/icon.png
  purchase_warn_message/static/description/index.html
  purchase_warn_message/tests/__init__.py
  purchase_warn_message/tests/test_purchase_warn_message.py
  purchase_warn_message/views/purchase_order_views.xml
  setup/purchase_warn_message/odoo/addons/purchase_warn_message
  setup/purchase_warn_message/setup.py
Labels: approved, bot is merging ⏳

#2070 [IMP] purchase_discount: checkbox to use real purchase supplier discount
  purchase_discount/README.rst
  purchase_discount/__manifest__.py
  purchase_discount/models/__init__.py
  purchase_discount/models/purchase_order.py
  purchase_discount/models/res_company.py
  purchase_discount/models/res_config_settings.py
  purchase_discount/readme/CONTRIBUTORS.rst
  purchase_discount/readme/DESCRIPTION.rst
  purchase_discount/static/description/index.html
  purchase_discount/static/description/res_config_settings_form.png
  purchase_discount/tests/test_product_supplierinfo_discount.py
  purchase_discount/views/res_config_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2060 [IMP] purchase_order_weight_volume store total weight volume store
  purchase_order_weight_volume/models/purchase_order.py
Labels: approved, ready to merge, bot is merging ⏳

#2095 [14.0] [FIX] procurement_purchase_no_grouping: Remove duplicated purchase tab in settings
  procurement_purchase_no_grouping/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#2089 [14.0] [FIX] purchase_allowed_product: search product by vendor reference
  purchase_allowed_product/README.rst
  purchase_allowed_product/__manifest__.py
  purchase_allowed_product/static/description/index.html
  purchase_allowed_product/views/purchase_order_view.xml
Labels: approved, bot is merging ⏳

#1985 [16.0][MIG] purchase_manual_delivery: Migration to 16.0
  purchase_manual_delivery/README.rst
  purchase_manual_delivery/__init__.py
  purchase_manual_delivery/__manifest__.py
  purchase_manual_delivery/i18n/purchase_manual_delivery.pot
  purchase_manual_delivery/i18n/sl.po
  purchase_manual_delivery/models/__init__.py
  purchase_manual_delivery/models/purchase_order.py
  purchase_manual_delivery/models/res_company.py
  purchase_manual_delivery/models/res_config.py
  purchase_manual_delivery/readme/CONTRIBUTORS.rst
  purchase_manual_delivery/readme/DESCRIPTION.rst
  purchase_manual_delivery/readme/USAGE.rst
  purchase_manual_delivery/security/ir.model.access.csv
  purchase_manual_delivery/static/description/create_incoming_shipment_button.png
  purchase_manual_delivery/static/description/create_incoming_shipment_wizard.png
  purchase_manual_delivery/static/description/icon.png
  purchase_manual_delivery/static/description/index.html
  purchase_manual_delivery/tests/__init__.py
  purchase_manual_delivery/tests/test_purchase_manual_delivery.py
  purchase_manual_delivery/views/purchase_order_views.xml
  purchase_manual_delivery/views/res_config_view.xml
  purchase_manual_delivery/wizard/__init__.py
  purchase_manual_delivery/wizard/create_manual_stock_picking.py
  purchase_manual_delivery/wizard/create_manual_stock_picking.xml
  setup/purchase_manual_delivery/odoo/addons/purchase_manual_delivery
  setup/purchase_manual_delivery/setup.py
Labels: needs review, approved, bot is merging ⏳

#2094 [16.0][FIX] purchase_order_weight_volume: disable display on PO if settings display = False
  purchase_order_weight_volume/models/purchase_order.py
  purchase_order_weight_volume/views/purchase_order_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2051 [16.0][ADD] purchase_only_by_packaging
  purchase_only_by_packaging/README.rst
  purchase_only_by_packaging/__init__.py
  purchase_only_by_packaging/__manifest__.py
  purchase_only_by_packaging/models/__init__.py
  purchase_only_by_packaging/models/product_packaging.py
  purchase_only_by_packaging/models/product_packaging_level.py
  purchase_only_by_packaging/models/product_product.py
  purchase_only_by_packaging/models/product_template.py
  purchase_only_by_packaging/models/purchase_order_line.py
  purchase_only_by_packaging/readme/CONFIGURE.rst
  purchase_only_by_packaging/readme/CONTRIBUTORS.rst
  purchase_only_by_packaging/readme/CREDITS.rst
  purchase_only_by_packaging/readme/DESCRIPTION.rst
  purchase_only_by_packaging/static/description/icon.png
  purchase_only_by_packaging/static/description/index.html
  purchase_only_by_packaging/tests/__init__.py
  purchase_only_by_packaging/tests/common.py
  purchase_only_by_packaging/tests/test_minimum_purchasable_qty.py
  purchase_only_by_packaging/tests/test_purchase_line_onchanges.py
  purchase_only_by_packaging/tests/test_purchase_only_by_packaging.py
  purchase_only_by_packaging/views/product_packaging.xml
  purchase_only_by_packaging/views/product_product.xml
  purchase_only_by_packaging/views/product_template.xml
  setup/purchase_only_by_packaging/odoo/addons/purchase_only_by_packaging
  setup/purchase_only_by_packaging/setup.py
Labels: approved, bot is merging ⏳

#2088 [14.0] [IMP] purchase_allowed_product: global setting and access rights
  purchase_allowed_product/README.rst
  purchase_allowed_product/__manifest__.py
  purchase_allowed_product/models/__init__.py
  purchase_allowed_product/models/res_config_settings.py
  purchase_allowed_product/models/supplied_product_mixin.py
  purchase_allowed_product/readme/CONTRIBUTORS.rst
  purchase_allowed_product/security/purchase_security.xml
  purchase_allowed_product/static/description/index.html
  purchase_allowed_product/views/purchase_order_view.xml
  purchase_allowed_product/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1966 [16.0][MIG] sale_purchase_force_vendor: Migration to 16.0
  sale_purchase_force_vendor/README.rst
  sale_purchase_force_vendor/__init__.py
  sale_purchase_force_vendor/__manifest__.py
  sale_purchase_force_vendor/i18n/es.po
  sale_purchase_force_vendor/i18n/nl.po
  sale_purchase_force_vendor/i18n/sale_purchase_force_vendor.pot
  sale_purchase_force_vendor/models/__init__.py
  sale_purchase_force_vendor/models/res_company.py
  sale_purchase_force_vendor/models/res_config_settings.py
  sale_purchase_force_vendor/models/sale_order_line.py
  sale_purchase_force_vendor/models/stock_move.py
  sale_purchase_force_vendor/readme/CONFIGURE.rst
  sale_purchase_force_vendor/readme/CONTRIBUTORS.rst
  sale_purchase_force_vendor/readme/DESCRIPTION.rst
  sale_purchase_force_vendor/readme/USAGE.rst
  sale_purchase_force_vendor/static/description/icon.png
  sale_purchase_force_vendor/static/description/index.html
  sale_purchase_force_vendor/tests/__init__.py
  sale_purchase_force_vendor/tests/common.py
  sale_purchase_force_vendor/tests/test_sale_purchase_force_vendor.py
  sale_purchase_force_vendor/views/res_config_settings_view.xml
  sale_purchase_force_vendor/views/sale_order_view.xml
  setup/sale_purchase_force_vendor/odoo/addons/sale_purchase_force_vendor
  setup/sale_purchase_force_vendor/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2098 [15.0][FIX] purchase_order_product_recommendation: product recommendation button is hide for purchase state
  purchase_order_product_recommendation/views/purchase_order_view.xml
Labels: bot is merging ⏳
