Repository OCA/purchase-workflow, pull requests merged in 2024-02, with the labels that each got.

#2164 [17.0][IMP] `purchase_tag`: add parent tags
  purchase_tag/models/purchase_tag.py
  purchase_tag/views/purchase_tag_view.xml
Labels: approved, bot is merging ⏳

#2163 [16.0][IMP] `purchase_tag`: add parent tags
  purchase_tag/models/purchase_tag.py
  purchase_tag/views/purchase_tag_view.xml
Labels: approved, bot is merging ⏳

#2161 [15.0][IMP] `purchase_tag`: add parent tags
  purchase_tag/models/purchase_tag.py
  purchase_tag/views/purchase_tag_view.xml
Labels: approved, bot is merging ⏳

#2149 [16.0][MIG] purchase_blanket_order
  purchase_blanket_order/README.rst
  purchase_blanket_order/__init__.py
  purchase_blanket_order/__manifest__.py
  purchase_blanket_order/data/ir_cron.xml
  purchase_blanket_order/data/sequence.xml
  purchase_blanket_order/i18n/purchase_blanket_order.pot
  purchase_blanket_order/models/__init__.py
  purchase_blanket_order/models/blanket_orders.py
  purchase_blanket_order/models/purchase_config_settings.py
  purchase_blanket_order/models/purchase_order.py
  purchase_blanket_order/readme/CONTRIBUTORS.rst
  purchase_blanket_order/readme/DESCRIPTION.rst
  purchase_blanket_order/readme/USAGE.rst
  purchase_blanket_order/report/report.xml
  purchase_blanket_order/report/templates.xml
  purchase_blanket_order/security/ir.model.access.csv
  purchase_blanket_order/security/security.xml
  purchase_blanket_order/static/description/BO_actions.png
  purchase_blanket_order/static/description/BO_form.png
  purchase_blanket_order/static/description/BO_lines.png
  purchase_blanket_order/static/description/BO_menu.png
  purchase_blanket_order/static/description/PO_BOLine.png
  purchase_blanket_order/static/description/PO_from_BO.png
  purchase_blanket_order/static/description/icon.png
  purchase_blanket_order/static/description/index.html
  purchase_blanket_order/tests/__init__.py
  purchase_blanket_order/tests/test_purchase_blanket_order.py
  purchase_blanket_order/tests/test_purchase_order.py
  purchase_blanket_order/views/purchase_blanket_order_views.xml
  purchase_blanket_order/views/purchase_config_settings.xml
  purchase_blanket_order/views/purchase_order_views.xml
  purchase_blanket_order/wizard/__init__.py
  purchase_blanket_order/wizard/create_purchase_orders.py
  purchase_blanket_order/wizard/create_purchase_orders.xml
  setup/purchase_blanket_order/odoo/addons/purchase_blanket_order
  setup/purchase_blanket_order/setup.py
Labels: approved, bot is merging ⏳

#2166 [13.0] purchase_discount: use force company to select the seller
  purchase_discount/models/stock_rule.py
Labels: approved, ready to merge, bot is merging ⏳

#2170 [15.0][IMP] sale_purchase_force_vendor: Do not allow to change vendor in a sale order line in 'sale' state too.
  sale_purchase_force_vendor/views/sale_order_view.xml
Labels: approved, bot is merging ⏳

#2153 [15.0][IMP] purchase_security: Restrict partners according to purchase groups
  purchase_security/README.rst
  purchase_security/__manifest__.py
  purchase_security/i18n/es.po
  purchase_security/i18n/purchase_security.pot
  purchase_security/models/__init__.py
  purchase_security/models/ir_rule.py
  purchase_security/models/purchase_order.py
  purchase_security/models/purchase_team.py
  purchase_security/models/res_partner.py
  purchase_security/models/res_users.py
  purchase_security/static/description/index.html
  purchase_security/tests/test_access_rights.py
  purchase_security/views/res_partner_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2165 [17.0][MIG] purchase_invoice_plan: Migration to 17.0
  purchase_invoice_plan/README.rst
  purchase_invoice_plan/__init__.py
  purchase_invoice_plan/__manifest__.py
  purchase_invoice_plan/data/purchase_data.xml
  purchase_invoice_plan/i18n/es.po
  purchase_invoice_plan/i18n/it.po
  purchase_invoice_plan/i18n/purchase_invoice_plan.pot
  purchase_invoice_plan/models/__init__.py
  purchase_invoice_plan/models/purchase.py
  purchase_invoice_plan/pyproject.toml
  purchase_invoice_plan/readme/CONTRIBUTORS.md
  purchase_invoice_plan/readme/DESCRIPTION.md
  purchase_invoice_plan/readme/USAGE.md
  purchase_invoice_plan/security/ir.model.access.csv
  purchase_invoice_plan/static/description/icon.png
  purchase_invoice_plan/static/description/index.html
  purchase_invoice_plan/tests/__init__.py
  purchase_invoice_plan/tests/test_purchase_invoice_plan.py
  purchase_invoice_plan/views/purchase_view.xml
  purchase_invoice_plan/wizard/__init__.py
  purchase_invoice_plan/wizard/purchase_create_invoice_plan.py
  purchase_invoice_plan/wizard/purchase_create_invoice_plan_view.xml
  purchase_invoice_plan/wizard/purchase_make_planned_invoice.py
  purchase_invoice_plan/wizard/purchase_make_planned_invoice_view.xml
Labels: bot is merging ⏳

#2176 [16.0][IMP] purchase_security: Add groups to purchase orders and new group permission feature + Restrict partners according to purchase group
  purchase_security/README.rst
  purchase_security/__manifest__.py
  purchase_security/i18n/es.po
  purchase_security/i18n/purchase_security.pot
  purchase_security/models/__init__.py
  purchase_security/models/ir_rule.py
  purchase_security/models/purchase_order.py
  purchase_security/models/purchase_team.py
  purchase_security/models/res_partner.py
  purchase_security/models/res_users.py
  purchase_security/readme/CONTRIBUTORS.rst
  purchase_security/readme/DESCRIPTION.rst
  purchase_security/security/ir.model.access.csv
  purchase_security/security/security.xml
  purchase_security/static/description/index.html
  purchase_security/tests/test_access_rights.py
  purchase_security/views/purchase_order_views.xml
  purchase_security/views/purchase_team_views.xml
  purchase_security/views/res_partner_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2190 [16.0][MIG] purchase_order_product_attachment_mgmt: Migration to 16.0
  purchase_order_product_attachment_mgmt/README.rst
  purchase_order_product_attachment_mgmt/__init__.py
  purchase_order_product_attachment_mgmt/__manifest__.py
  purchase_order_product_attachment_mgmt/i18n/es.po
  purchase_order_product_attachment_mgmt/i18n/purchase_order_product_attachment_mgmt.pot
  purchase_order_product_attachment_mgmt/models/__init__.py
  purchase_order_product_attachment_mgmt/models/purchase_order.py
  purchase_order_product_attachment_mgmt/readme/CONTRIBUTORS.rst
  purchase_order_product_attachment_mgmt/readme/DESCRIPTION.rst
  purchase_order_product_attachment_mgmt/readme/USAGE.rst
  purchase_order_product_attachment_mgmt/static/description/icon.png
  purchase_order_product_attachment_mgmt/static/description/index.html
  purchase_order_product_attachment_mgmt/tests/__init__.py
  purchase_order_product_attachment_mgmt/tests/test_purchase_order_product_attachment_mgmt.py
  purchase_order_product_attachment_mgmt/views/purchase_order_view.xml
  setup/purchase_order_product_attachment_mgmt/odoo/addons/purchase_order_product_attachment_mgmt
  setup/purchase_order_product_attachment_mgmt/setup.py
Labels: approved, bot is merging ⏳

#2187 [16.0][MIG] purchase_order_price_recalculation: Migration to 16.0
  purchase_order_price_recalculation/README.rst
  purchase_order_price_recalculation/__init__.py
  purchase_order_price_recalculation/__manifest__.py
  purchase_order_price_recalculation/i18n/es.po
  purchase_order_price_recalculation/i18n/it.po
  purchase_order_price_recalculation/i18n/purchase_order_price_recalculation.pot
  purchase_order_price_recalculation/models/__init__.py
  purchase_order_price_recalculation/models/purchase_order.py
  purchase_order_price_recalculation/readme/CONTRIBUTORS.rst
  purchase_order_price_recalculation/readme/DESCRIPTION.rst
  purchase_order_price_recalculation/readme/USAGE.rst
  purchase_order_price_recalculation/static/description/icon.png
  purchase_order_price_recalculation/static/description/index.html
  purchase_order_price_recalculation/tests/__init__.py
  purchase_order_price_recalculation/tests/test_purchase_order_price_recalculation.py
  purchase_order_price_recalculation/views/purchase_order_view.xml
  setup/purchase_order_price_recalculation/odoo/addons/purchase_order_price_recalculation
  setup/purchase_order_price_recalculation/setup.py
Labels: approved, bot is merging ⏳

#2179 [17.0][FIX] purchase_request app icon adapted to the new milk style imperfectly
  purchase_request/static/description/icon.png
  purchase_request/static/description/icon.svg
Labels: approved, bot is merging ⏳

#2050 [15.0][FIX] purchase_request: activity assigned user upon procurement cancellation
  purchase_request/models/stock_move.py
Labels: approved, bot is merging ⏳

#2137 [16.0][MIG] purchase_stock_price_unit_sync: Migration to 16.0
  purchase_stock_price_unit_sync/README.rst
  purchase_stock_price_unit_sync/__init__.py
  purchase_stock_price_unit_sync/__manifest__.py
  purchase_stock_price_unit_sync/i18n/purchase_stock_price_unit_sync.pot
  purchase_stock_price_unit_sync/models/__init__.py
  purchase_stock_price_unit_sync/models/purchase_order.py
  purchase_stock_price_unit_sync/readme/CONTRIBUTORS.rst
  purchase_stock_price_unit_sync/readme/DESCRIPTION.rst
  purchase_stock_price_unit_sync/static/description/icon.png
  purchase_stock_price_unit_sync/static/description/index.html
  purchase_stock_price_unit_sync/tests/__init__.py
  purchase_stock_price_unit_sync/tests/test_purchase_stock_price_unit_sync.py
  setup/purchase_stock_price_unit_sync/odoo/addons/purchase_stock_price_unit_sync
  setup/purchase_stock_price_unit_sync/setup.py
Labels: approved, bot is merging ⏳

#2191 [16.0][FIX] purchase_request: activity assigned user upon procurement cancellation
  purchase_request/models/stock_move.py
Labels: approved, merged 🎉
