Repository OCA/purchase-workflow, pull requests merged in 2024-04, with the labels that each got.

#2221 [16.0][FIX] purchase_default_terms_conditions: error CI - Access denied to purchase.order.line model
  purchase_default_terms_conditions/tests/test_purchase_order.py
Labels: approved, bot is merging ⏳

#2223 [13.0][FIX] purchase_landed_cost: Remove ondelete from one2many fields
  purchase_landed_cost/models/purchase_cost_distribution.py
Labels: approved, bot is merging ⏳

#2073 [FIX] purchase_fop_shipping: purchase fop should not block negative PO
  purchase_fop_shipping/models/purchase.py
  purchase_fop_shipping/tests/test_fop_shipping.py
Labels: approved, bot is merging ⏳

#2228 [16.0][FIX] purchase_advance_payment: use commercial partner
  purchase_advance_payment/wizard/purchase_advance_payment_wizard.py
Labels: approved, bot is merging ⏳

#2207 [17.0][MIG] purchase_delivery_split_date: Migration to 17.0
  purchase_delivery_split_date/README.rst
  purchase_delivery_split_date/__init__.py
  purchase_delivery_split_date/__manifest__.py
  purchase_delivery_split_date/i18n/ca.po
  purchase_delivery_split_date/i18n/de.po
  purchase_delivery_split_date/i18n/es.po
  purchase_delivery_split_date/i18n/es_MX.po
  purchase_delivery_split_date/i18n/es_PE.po
  purchase_delivery_split_date/i18n/fi.po
  purchase_delivery_split_date/i18n/fr.po
  purchase_delivery_split_date/i18n/gl.po
  purchase_delivery_split_date/i18n/hr.po
  purchase_delivery_split_date/i18n/it.po
  purchase_delivery_split_date/i18n/nl_NL.po
  purchase_delivery_split_date/i18n/pt_BR.po
  purchase_delivery_split_date/i18n/pt_PT.po
  purchase_delivery_split_date/i18n/purchase_delivery_split_date.pot
  purchase_delivery_split_date/i18n/ro.po
  purchase_delivery_split_date/i18n/sl.po
  purchase_delivery_split_date/i18n/zh_CN.po
  purchase_delivery_split_date/models/__init__.py
  purchase_delivery_split_date/models/purchase_order.py
  purchase_delivery_split_date/models/purchase_order_line.py
  purchase_delivery_split_date/models/stock_picking.py
  purchase_delivery_split_date/pyproject.toml
  purchase_delivery_split_date/readme/CONTRIBUTORS.md
  purchase_delivery_split_date/readme/DESCRIPTION.md
  purchase_delivery_split_date/readme/HISTORY.md
  purchase_delivery_split_date/readme/USAGE.md
  purchase_delivery_split_date/static/description/icon.png
  purchase_delivery_split_date/static/description/index.html
  purchase_delivery_split_date/static/description/split_delivery.png
  purchase_delivery_split_date/tests/__init__.py
  purchase_delivery_split_date/tests/test_purchase_delivery.py
Labels: approved, ready to merge, bot is merging ⏳

#2219 [16.0][MIG] purchase_landed_cost: Migration to version 16.0
  purchase_landed_cost/README.rst
  purchase_landed_cost/__init__.py
  purchase_landed_cost/__manifest__.py
  purchase_landed_cost/data/purchase_cost_distribution_sequence.xml
  purchase_landed_cost/i18n/es.po
  purchase_landed_cost/i18n/fr.po
  purchase_landed_cost/i18n/it.po
  purchase_landed_cost/i18n/pt_BR.po
  purchase_landed_cost/i18n/purchase_landed_cost.pot
  purchase_landed_cost/i18n/ro.po
  purchase_landed_cost/i18n/sl.po
  purchase_landed_cost/i18n/zh_CN.po
  purchase_landed_cost/models/__init__.py
  purchase_landed_cost/models/account_move.py
  purchase_landed_cost/models/purchase_cost_distribution.py
  purchase_landed_cost/models/purchase_expense_type.py
  purchase_landed_cost/models/purchase_order.py
  purchase_landed_cost/models/stock_picking.py
  purchase_landed_cost/readme/CONTRIBUTORS.rst
  purchase_landed_cost/readme/DESCRIPTION.rst
  purchase_landed_cost/readme/ROADMAP.rst
  purchase_landed_cost/security/ir.model.access.csv
  purchase_landed_cost/security/purchase_landed_cost_security.xml
  purchase_landed_cost/static/description/icon.png
  purchase_landed_cost/static/description/images/expenses_types.png
  purchase_landed_cost/static/description/images/purchase_order_expense_line.png
  purchase_landed_cost/static/description/images/purchase_order_expense_main.png
  purchase_landed_cost/static/description/index.html
  purchase_landed_cost/tests/__init__.py
  purchase_landed_cost/tests/test_purchase_landed_cost.py
  purchase_landed_cost/views/account_move_view.xml
  purchase_landed_cost/views/purchase_cost_distribution_line_expense_view.xml
  purchase_landed_cost/views/purchase_cost_distribution_view.xml
  purchase_landed_cost/views/purchase_expense_type_view.xml
  purchase_landed_cost/views/purchase_order_view.xml
  purchase_landed_cost/views/stock_picking_view.xml
  purchase_landed_cost/wizard/__init__.py
  purchase_landed_cost/wizard/import_invoice_line.py
  purchase_landed_cost/wizard/import_invoice_line_wizard_view.xml
  purchase_landed_cost/wizard/import_landed_cost_pickings_wizard.py
  purchase_landed_cost/wizard/import_landed_cost_pickings_wizard_view.xml
  purchase_landed_cost/wizard/picking_import_wizard.py
  purchase_landed_cost/wizard/picking_import_wizard_view.xml
  setup/purchase_landed_cost/odoo/addons/purchase_landed_cost
  setup/purchase_landed_cost/setup.py
Labels: approved, bot is merging ⏳

#2238 [16.0][FIX] purchase_only_by_packaging: Rename method _convert_purchase_packaging_qty
  purchase_only_by_packaging/models/product_product.py
  purchase_only_by_packaging/models/purchase_order_line.py
Labels: approved, bot is merging ⏳

#2237 [IMP] purchase_request: add UTC time to scheduled_date
  purchase_request/tests/test_purchase_request_to_rfq.py
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: approved, ready to merge, bot is merging ⏳

#2245 [17.0][MIG] purchase_security
  purchase_security/README.rst
  purchase_security/__init__.py
  purchase_security/__manifest__.py
  purchase_security/i18n/es.po
  purchase_security/i18n/it.po
  purchase_security/i18n/purchase_security.pot
  purchase_security/models/__init__.py
  purchase_security/models/ir_rule.py
  purchase_security/models/purchase_order.py
  purchase_security/models/purchase_team.py
  purchase_security/models/res_partner.py
  purchase_security/models/res_users.py
  purchase_security/pyproject.toml
  purchase_security/readme/CONFIGURATION.rst
  purchase_security/readme/CONTRIBUTORS.md
  purchase_security/readme/DESCRIPTION.md
  purchase_security/readme/USAGE.md
  purchase_security/security/ir.model.access.csv
  purchase_security/security/security.xml
  purchase_security/static/description/icon.png
  purchase_security/static/description/index.html
  purchase_security/tests/__init__.py
  purchase_security/tests/test_access_rights.py
  purchase_security/views/purchase_order_views.xml
  purchase_security/views/purchase_team_views.xml
  purchase_security/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#2206 [16.0][FIX] purchase_request: not allow to edit an approved purchase request
  purchase_request/models/purchase_request.py
Labels: approved, ready to merge, bot is merging ⏳

#2236 [16.0][ADD] purchase_reorder_control
  purchase_reorder_control/README.rst
  purchase_reorder_control/__init__.py
  purchase_reorder_control/__manifest__.py
  purchase_reorder_control/i18n/fr.po
  purchase_reorder_control/i18n/purchase_reorder_control.pot
  purchase_reorder_control/models/__init__.py
  purchase_reorder_control/models/product_template.py
  purchase_reorder_control/models/stock_warehouse_orderpoint.py
  purchase_reorder_control/readme/CONTRIBUTORS.rst
  purchase_reorder_control/readme/CREDITS.rst
  purchase_reorder_control/readme/DESCRIPTION.rst
  purchase_reorder_control/static/description/index.html
  purchase_reorder_control/tests/__init__.py
  purchase_reorder_control/tests/test_unpurchaseable_product.py
  setup/purchase_reorder_control/odoo/addons/purchase_reorder_control
  setup/purchase_reorder_control/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2255 [16.0][IMP] supplier_calendar: robustness
  supplier_calendar/models/res_partner.py
Labels: approved, bot is merging ⏳

#2257 [14.0][IMP] supplier_calendar: robustness
  supplier_calendar/models/res_partner.py
Labels: bot is merging ⏳
