Repository OCA/purchase-workflow, pull requests merged in 2024-12, with the labels that each got.

#2475 [15.0][FIX] purchase_requisition_grouped_by_procurement: Correct grouping of purchase requisitions
  purchase_requisition_grouped_by_procurement/models/purchase_requisition.py
Labels: approved, bot is merging ⏳

#2479 [16.0][IMP]purchase_order_type: Automatically get partner purchase type on purchase creation.
  purchase_order_type/README.rst
  purchase_order_type/models/purchase_order.py
  purchase_order_type/readme/CONTRIBUTORS.rst
  purchase_order_type/static/description/index.html
  purchase_order_type/tests/test_purchase_order_type.py
Labels: bot is merging ⏳

#2409 [17.0][IMP] purchase_advance_payment: auto reconcile adv payments
  purchase_advance_payment/data/ir_config_parameter.xml
  purchase_advance_payment/models/__init__.py
  purchase_advance_payment/models/account_move.py
  purchase_advance_payment/models/res_config_settings.py
  purchase_advance_payment/tests/test_purchase_advance_payment.py
  purchase_advance_payment/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#2466 [16.0][IMP] purchase_transport_mode default
  purchase_transport_mode/models/purchase_order.py
  purchase_transport_mode/tests/test_purchase_transport_mode.py
Labels: approved, ready to merge, bot is merging ⏳

#2430 [18.0][MIG] purchase_order_line_menu: Migration to 18.0
  purchase_order_line_menu/README.rst
  purchase_order_line_menu/__init__.py
  purchase_order_line_menu/__manifest__.py
  purchase_order_line_menu/i18n/es.po
  purchase_order_line_menu/i18n/fr_FR.po
  purchase_order_line_menu/i18n/hr.po
  purchase_order_line_menu/i18n/it.po
  purchase_order_line_menu/i18n/ja.po
  purchase_order_line_menu/i18n/pt_BR.po
  purchase_order_line_menu/i18n/purchase_order_line_menu.pot
  purchase_order_line_menu/models/__init__.py
  purchase_order_line_menu/models/purchase_order_line.py
  purchase_order_line_menu/pyproject.toml
  purchase_order_line_menu/readme/CONTRIBUTORS.md
  purchase_order_line_menu/readme/DESCRIPTION.md
  purchase_order_line_menu/readme/USAGE.md
  purchase_order_line_menu/static/description/icon.png
  purchase_order_line_menu/static/description/index.html
  purchase_order_line_menu/views/purchase_order_line_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2055 [15.0][FIX] purchase_substate: split demo and fix template
  purchase_substate/__manifest__.py
  purchase_substate/data/purchase_substate_mail_template_data.xml
  purchase_substate/demo/purchase_substate_demo.xml
Labels: approved, bot is merging ⏳

#2150 [16.0][IMP] purchase_requisition_tier_validation: avoid error editing alternative
  purchase_requisition_tier_validation/models/__init__.py
  purchase_requisition_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#2492 [17.0][MIG] purchase_order_secondary_unit: Migration to 17.0
  purchase_order_secondary_unit/README.rst
  purchase_order_secondary_unit/__init__.py
  purchase_order_secondary_unit/__manifest__.py
  purchase_order_secondary_unit/i18n/de.po
  purchase_order_secondary_unit/i18n/es.po
  purchase_order_secondary_unit/i18n/fr.po
  purchase_order_secondary_unit/i18n/it.po
  purchase_order_secondary_unit/i18n/ja.po
  purchase_order_secondary_unit/i18n/purchase_order_secondary_unit.pot
  purchase_order_secondary_unit/models/__init__.py
  purchase_order_secondary_unit/models/product_product.py
  purchase_order_secondary_unit/models/product_template.py
  purchase_order_secondary_unit/models/purchase_order.py
  purchase_order_secondary_unit/pyproject.toml
  purchase_order_secondary_unit/readme/CONTRIBUTORS.md
  purchase_order_secondary_unit/readme/DESCRIPTION.md
  purchase_order_secondary_unit/readme/USAGE.md
  purchase_order_secondary_unit/reports/purchase_order_templates.xml
  purchase_order_secondary_unit/reports/purchase_quotation_templates.xml
  purchase_order_secondary_unit/static/description/icon.png
  purchase_order_secondary_unit/static/description/index.html
  purchase_order_secondary_unit/tests/__init__.py
  purchase_order_secondary_unit/tests/test_purchase_order_secondary_unit.py
  purchase_order_secondary_unit/views/product_views.xml
  purchase_order_secondary_unit/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#2481 [16.0][IMP] purchase_deposit: add advance section inside lines on advance creation
  purchase_deposit/tests/test_purchase_deposit.py
  purchase_deposit/wizard/purchase_make_invoice_advance.py
Labels: approved, bot is merging ⏳

#2358 [16.0][ADD] purchase_force_invoiced_quantity: add module
  purchase_force_invoiced_quantity/README.rst
  purchase_force_invoiced_quantity/__init__.py
  purchase_force_invoiced_quantity/__manifest__.py
  purchase_force_invoiced_quantity/demo/demo_product.xml
  purchase_force_invoiced_quantity/demo/demo_purchase_order.xml
  purchase_force_invoiced_quantity/models/__init__.py
  purchase_force_invoiced_quantity/models/purchase_order_line.py
  purchase_force_invoiced_quantity/readme/CONFIGURE.rst
  purchase_force_invoiced_quantity/readme/CONTEXT.rst
  purchase_force_invoiced_quantity/readme/CONTRIBUTORS.rst
  purchase_force_invoiced_quantity/readme/DESCRIPTION.rst
  purchase_force_invoiced_quantity/readme/USAGE.rst
  purchase_force_invoiced_quantity/static/description/index.html
  purchase_force_invoiced_quantity/tests/__init__.py
  purchase_force_invoiced_quantity/tests/test_purchase_force_invoiced_quantity.py
  purchase_force_invoiced_quantity/views/purchase_order.xml
  setup/purchase_force_invoiced_quantity/odoo/addons/purchase_force_invoiced_quantity
  setup/purchase_force_invoiced_quantity/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2467 [18.0][MIG] purchase_request_department: Migration to 18.0
  purchase_request_department/README.rst
  purchase_request_department/__init__.py
  purchase_request_department/__manifest__.py
  purchase_request_department/hooks.py
  purchase_request_department/i18n/de.po
  purchase_request_department/i18n/es.po
  purchase_request_department/i18n/es_EC.po
  purchase_request_department/i18n/fr.po
  purchase_request_department/i18n/hr.po
  purchase_request_department/i18n/it.po
  purchase_request_department/i18n/nb.po
  purchase_request_department/i18n/nb_NO.po
  purchase_request_department/i18n/nl_NL.po
  purchase_request_department/i18n/pt_BR.po
  purchase_request_department/i18n/purchase_request_department.pot
  purchase_request_department/i18n/sl.po
  purchase_request_department/i18n/tr.po
  purchase_request_department/i18n/zh_CN.po
  purchase_request_department/models/__init__.py
  purchase_request_department/models/purchase_request.py
  purchase_request_department/pyproject.toml
  purchase_request_department/readme/CONTRIBUTORS.md
  purchase_request_department/readme/CREDITS.md
  purchase_request_department/readme/DESCRIPTION.md
  purchase_request_department/readme/USAGE.md
  purchase_request_department/static/description/icon.png
  purchase_request_department/static/description/index.html
  purchase_request_department/tests/__init__.py
  purchase_request_department/tests/test_purchase_request_department.py
  purchase_request_department/views/purchase_request_department_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2497 [17.0][IMP] purchase_deposit: add advance section inside lines on advance creation
  purchase_deposit/tests/test_purchase_deposit.py
  purchase_deposit/wizard/purchase_make_invoice_advance.py
Labels: approved, bot is merging ⏳

#2410 [17.0][FIX] purchase_request: typo
  purchase_request/README.rst
  purchase_request/readme/CONTRIBUTORS.md
  purchase_request/static/description/index.html
  purchase_request/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳
