Repository OCA/purchase-workflow, pull requests merged in 2024-08, with the labels that each got.

#2384 [IMP] purchase_discount: remove discount compute hacks
  purchase_discount/models/purchase_order.py
  purchase_discount/models/stock_move.py
Labels: approved, bot is merging ⏳

#2381 [FIX] purchase_merge: add _description to purchase.merge.automatic.wizard
  purchase_merge/wizard/purchase_merge.py
Labels: approved, ready to merge, bot is merging ⏳

#2364 [17.0][MIG] purchase_invoice_method: Migration to 17.0
  purchase_invoice_method/README.rst
  purchase_invoice_method/__init__.py
  purchase_invoice_method/__manifest__.py
  purchase_invoice_method/i18n/es.po
  purchase_invoice_method/i18n/es_MX.po
  purchase_invoice_method/i18n/it.po
  purchase_invoice_method/i18n/purchase_invoice_method.pot
  purchase_invoice_method/models/__init__.py
  purchase_invoice_method/models/purchase_order.py
  purchase_invoice_method/pyproject.toml
  purchase_invoice_method/readme/CONTRIBUTORS.md
  purchase_invoice_method/readme/DESCRIPTION.md
  purchase_invoice_method/readme/USAGE.md
  purchase_invoice_method/static/description/icon.png
  purchase_invoice_method/static/description/index.html
  purchase_invoice_method/tests/__init__.py
  purchase_invoice_method/tests/test_purchase_invoice_method.py
  purchase_invoice_method/views/purchase_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#2377 [14.0] [ADD] purchase_line_service_qty_received
  purchase_line_service_qty_received/README.rst
  purchase_line_service_qty_received/__init__.py
  purchase_line_service_qty_received/__manifest__.py
  purchase_line_service_qty_received/models/__init__.py
  purchase_line_service_qty_received/models/purchase_order_line.py
  purchase_line_service_qty_received/readme/CONTRIBUTORS.rst
  purchase_line_service_qty_received/readme/DESCRIPTION.rst
  purchase_line_service_qty_received/static/description/icon.png
  purchase_line_service_qty_received/static/description/index.html
  purchase_line_service_qty_received/tests/__init__.py
  purchase_line_service_qty_received/tests/common.py
  purchase_line_service_qty_received/tests/test_service_line_qty_received.py
  setup/purchase_line_service_qty_received/odoo/addons/purchase_line_service_qty_received
  setup/purchase_line_service_qty_received/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2346 [17.0][MIG] purchase_no_rfq
  purchase_no_rfq/README.rst
  purchase_no_rfq/__init__.py
  purchase_no_rfq/__manifest__.py
  purchase_no_rfq/hooks.py
  purchase_no_rfq/i18n/es.po
  purchase_no_rfq/i18n/fr.po
  purchase_no_rfq/i18n/it.po
  purchase_no_rfq/i18n/pt_BR.po
  purchase_no_rfq/i18n/purchase_no_rfq.pot
  purchase_no_rfq/i18n/sv.po
  purchase_no_rfq/models/__init__.py
  purchase_no_rfq/models/purchase_order.py
  purchase_no_rfq/pyproject.toml
  purchase_no_rfq/readme/CONTRIBUTORS.md
  purchase_no_rfq/readme/DESCRIPTION.md
  purchase_no_rfq/reports/ir_actions_report.xml
  purchase_no_rfq/reports/purchase_order_template.xml
  purchase_no_rfq/static/description/icon.png
  purchase_no_rfq/static/description/index.html
  purchase_no_rfq/static/description/purchase_order_form.png
  purchase_no_rfq/static/description/purchase_order_tree.png
  purchase_no_rfq/views/view_purchase_order.xml
Labels: approved, bot is merging ⏳

#2339 [IMP] purchase_merge: Update chatter message
  purchase_merge/wizard/purchase_merge.py
Labels: approved, ready to merge, bot is merging ⏳

#2386 [17.0][MIG] purchase_partner_incoterm
  purchase_partner_incoterm/README.rst
  purchase_partner_incoterm/__init__.py
  purchase_partner_incoterm/__manifest__.py
  purchase_partner_incoterm/i18n/it.po
  purchase_partner_incoterm/i18n/purchase_partner_incoterm.pot
  purchase_partner_incoterm/models/__init__.py
  purchase_partner_incoterm/models/purchase_order.py
  purchase_partner_incoterm/models/res_partner.py
  purchase_partner_incoterm/pyproject.toml
  purchase_partner_incoterm/readme/CONTRIBUTORS.md
  purchase_partner_incoterm/readme/CREDITS.md
  purchase_partner_incoterm/readme/DESCRIPTION.md
  purchase_partner_incoterm/static/description/icon.png
  purchase_partner_incoterm/static/description/index.html
  purchase_partner_incoterm/views/partner_view.xml
  purchase_partner_incoterm/views/purchase_view.xml
Labels: bot is merging ⏳

#2389 [16.0][FIX] purchase_return: fix search view domain
  purchase_return/views/purchase_views.xml
Labels: approved, bot is merging ⏳

#2359 [17.0][MIG] purchase_order_qty_change_no_recompute: Migration to 17.0
  purchase_order_qty_change_no_recompute/README.rst
  purchase_order_qty_change_no_recompute/__init__.py
  purchase_order_qty_change_no_recompute/__manifest__.py
  purchase_order_qty_change_no_recompute/i18n/es.po
  purchase_order_qty_change_no_recompute/i18n/it.po
  purchase_order_qty_change_no_recompute/i18n/purchase_order_qty_change_no_recompute.pot
  purchase_order_qty_change_no_recompute/monkeypatching.py
  purchase_order_qty_change_no_recompute/pyproject.toml
  purchase_order_qty_change_no_recompute/readme/CONTRIBUTORS.md
  purchase_order_qty_change_no_recompute/readme/DESCRIPTION.md
  purchase_order_qty_change_no_recompute/readme/USAGE.md
  purchase_order_qty_change_no_recompute/static/description/icon.png
  purchase_order_qty_change_no_recompute/static/description/index.html
  purchase_order_qty_change_no_recompute/tests/__init__.py
  purchase_order_qty_change_no_recompute/tests/test_purchase_order_qty_change.py
Labels: approved, bot is merging ⏳

#2390 [16.0][IMP] purchase_discount: Use core hook
  purchase_discount/models/__init__.py
  purchase_discount/models/purchase_order.py
  purchase_discount/models/stock_move.py
  purchase_triple_discount/models/purchase_order.py
Labels: approved, ready to merge, bot is merging ⏳

#2380 [16.0][FIX]purchase_manual_delivery: qty compute fixes
  purchase_manual_delivery/models/purchase_order.py
  purchase_manual_delivery/tests/test_purchase_manual_delivery.py
Labels: bot is merging ⏳

#2382 [17.0][FIX] purchase_reception_notify: use markup when posting HTML message
  purchase_reception_notify/models/stock_picking.py
Labels: approved, ready to merge, bot is merging ⏳

#2391 [17.0][MIG] purchase_warn_message: Migration to 17.0
  purchase_warn_message/README.rst
  purchase_warn_message/__init__.py
  purchase_warn_message/__manifest__.py
  purchase_warn_message/i18n/es.po
  purchase_warn_message/i18n/it.po
  purchase_warn_message/i18n/purchase_warn_message.pot
  purchase_warn_message/models/__init__.py
  purchase_warn_message/models/purchase_order.py
  purchase_warn_message/pyproject.toml
  purchase_warn_message/readme/CONTRIBUTORS.md
  purchase_warn_message/readme/DESCRIPTION.md
  purchase_warn_message/static/description/icon.png
  purchase_warn_message/static/description/index.html
  purchase_warn_message/tests/__init__.py
  purchase_warn_message/tests/test_purchase_warn_message.py
  purchase_warn_message/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#2395 [16.0][IMP] sale_purchase_force_vendor: Add method for values to be used in product.supplierinfo record
  sale_purchase_force_vendor/models/sale_order_line.py
  sale_purchase_force_vendor/tests/common.py
  sale_purchase_force_vendor/tests/test_sale_purchase_force_vendor.py
Labels: approved, bot is merging ⏳

#2378 [17.0][MIG] purchase_order_line_menu
  purchase_order_line_menu/README.rst
  purchase_order_line_menu/__init__.py
  purchase_order_line_menu/__manifest__.py
  purchase_order_line_menu/i18n/es.po
  purchase_order_line_menu/i18n/fr_FR.po
  purchase_order_line_menu/i18n/hr.po
  purchase_order_line_menu/i18n/it.po
  purchase_order_line_menu/i18n/ja.po
  purchase_order_line_menu/i18n/pt_BR.po
  purchase_order_line_menu/i18n/purchase_order_line_menu.pot
  purchase_order_line_menu/models/__init__.py
  purchase_order_line_menu/models/purchase_order_line.py
  purchase_order_line_menu/pyproject.toml
  purchase_order_line_menu/readme/CONTRIBUTORS.md
  purchase_order_line_menu/readme/DESCRIPTION.md
  purchase_order_line_menu/readme/USAGE.md
  purchase_order_line_menu/static/description/icon.png
  purchase_order_line_menu/static/description/index.html
  purchase_order_line_menu/views/purchase_order_line_views.xml
Labels: approved, bot is merging ⏳

#2351 [16.0][MIG] purchase_request_exception
  purchase_request_exception/README.rst
  purchase_request_exception/__init__.py
  purchase_request_exception/__manifest__.py
  purchase_request_exception/data/purchase_request_exception_data.xml
  purchase_request_exception/i18n/es.po
  purchase_request_exception/i18n/fr.po
  purchase_request_exception/i18n/purchase_request_exception.pot
  purchase_request_exception/models/__init__.py
  purchase_request_exception/models/exception_rule.py
  purchase_request_exception/models/purchase_request.py
  purchase_request_exception/models/purchase_request_line.py
  purchase_request_exception/readme/CONTRIBUTORS.rst
  purchase_request_exception/readme/DESCRIPTION.rst
  purchase_request_exception/security/ir.model.access.csv
  purchase_request_exception/static/description/icon.png
  purchase_request_exception/static/description/index.html
  purchase_request_exception/tests/__init__.py
  purchase_request_exception/tests/test_purchase_request_exception.py
  purchase_request_exception/views/purchase_request_view.xml
  purchase_request_exception/wizard/__init__.py
  purchase_request_exception/wizard/purchase_request_exception_confirm.py
  purchase_request_exception/wizard/purchase_request_exception_confirm_view.xml
  setup/purchase_request_exception/odoo/addons/purchase_request_exception
  setup/purchase_request_exception/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2369 [16.0][IMP] purchase_request: add 'In Progress' state
  purchase_request/i18n/es.po
  purchase_request/i18n/purchase_request.pot
  purchase_request/models/orderpoint.py
  purchase_request/models/purchase_request.py
  purchase_request/models/purchase_request_line.py
  purchase_request/tests/test_purchase_request.py
  purchase_request/views/purchase_request_line_view.xml
  purchase_request/views/purchase_request_view.xml
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: approved, ready to merge, bot is merging ⏳

#2397 [17.0][IMP] purchase_open_qty: add purchase_order_line_menu dependency
  purchase_open_qty/__manifest__.py
  purchase_open_qty/views/purchase_view.xml
Labels: approved, bot is merging ⏳
