Repository OCA/purchase-workflow, pull requests merged in 2024-03, with the labels that each got.

#2193 [16.0][MIG] purchase_order_qty_change_no_recompute: Migration to 16.0
  .copier-answers.yml
  .github/workflows/test.yml
  purchase_order_qty_change_no_recompute/README.rst
  purchase_order_qty_change_no_recompute/__init__.py
  purchase_order_qty_change_no_recompute/__manifest__.py
  purchase_order_qty_change_no_recompute/i18n/es.po
  purchase_order_qty_change_no_recompute/monkeypatching.py
  purchase_order_qty_change_no_recompute/readme/CONTRIBUTORS.rst
  purchase_order_qty_change_no_recompute/readme/DESCRIPTION.rst
  purchase_order_qty_change_no_recompute/readme/USAGE.rst
  purchase_order_qty_change_no_recompute/static/description/icon.png
  purchase_order_qty_change_no_recompute/static/description/index.html
  purchase_order_qty_change_no_recompute/tests/__init__.py
  purchase_order_qty_change_no_recompute/tests/test_purchase_order_qty_change.py
  setup/purchase_order_qty_change_no_recompute/odoo/addons/purchase_order_qty_change_no_recompute
  setup/purchase_order_qty_change_no_recompute/setup.py
Labels: approved, bot is merging ⏳

#2186 [16.0][MIG] procurement_purchase_no_grouping: Migration to 16.0
  procurement_purchase_no_grouping/README.rst
  procurement_purchase_no_grouping/__init__.py
  procurement_purchase_no_grouping/__manifest__.py
  procurement_purchase_no_grouping/i18n/de.po
  procurement_purchase_no_grouping/i18n/es.po
  procurement_purchase_no_grouping/i18n/es_ES.po
  procurement_purchase_no_grouping/i18n/es_MX.po
  procurement_purchase_no_grouping/i18n/es_PE.po
  procurement_purchase_no_grouping/i18n/fi.po
  procurement_purchase_no_grouping/i18n/fr.po
  procurement_purchase_no_grouping/i18n/fr_BE.po
  procurement_purchase_no_grouping/i18n/fr_FR.po
  procurement_purchase_no_grouping/i18n/gl.po
  procurement_purchase_no_grouping/i18n/hr.po
  procurement_purchase_no_grouping/i18n/it.po
  procurement_purchase_no_grouping/i18n/nl.po
  procurement_purchase_no_grouping/i18n/nl_NL.po
  procurement_purchase_no_grouping/i18n/procurement_purchase_no_grouping.pot
  procurement_purchase_no_grouping/i18n/pt_BR.po
  procurement_purchase_no_grouping/i18n/pt_PT.po
  procurement_purchase_no_grouping/i18n/ro.po
  procurement_purchase_no_grouping/i18n/sl.po
  procurement_purchase_no_grouping/i18n/tr_TR.po
  procurement_purchase_no_grouping/i18n/vi_VN.po
  procurement_purchase_no_grouping/i18n/zh_CN.po
  procurement_purchase_no_grouping/models/__init__.py
  procurement_purchase_no_grouping/models/product_category.py
  procurement_purchase_no_grouping/models/purchase_order.py
  procurement_purchase_no_grouping/models/res_company.py
  procurement_purchase_no_grouping/models/res_config_settings.py
  procurement_purchase_no_grouping/models/stock_rule.py
  procurement_purchase_no_grouping/readme/CONFIGURE.rst
  procurement_purchase_no_grouping/readme/CONTRIBUTORS.rst
  procurement_purchase_no_grouping/readme/DESCRIPTION.rst
  procurement_purchase_no_grouping/readme/ROADMAP.rst
  procurement_purchase_no_grouping/static/description/icon.png
  procurement_purchase_no_grouping/static/description/index.html
  procurement_purchase_no_grouping/tests/__init__.py
  procurement_purchase_no_grouping/tests/test_procurement_purchase_no_grouping.py
  procurement_purchase_no_grouping/views/product_category_view.xml
  procurement_purchase_no_grouping/views/res_config_settings_views.xml
  setup/procurement_purchase_no_grouping/odoo/addons/procurement_purchase_no_grouping
  setup/procurement_purchase_no_grouping/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2157 [16.0][IMP] purchase_partner_selectable_option
  purchase_partner_selectable_option/README.rst
  purchase_partner_selectable_option/__manifest__.py
  purchase_partner_selectable_option/data/ir_config_parameter.xml
  purchase_partner_selectable_option/models/res_partner.py
  purchase_partner_selectable_option/readme/CONFIGURE.rst
  purchase_partner_selectable_option/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#2105 [16.0][MIG] purchase_work_acceptance
  purchase_work_acceptance/README.rst
  purchase_work_acceptance/__init__.py
  purchase_work_acceptance/__manifest__.py
  purchase_work_acceptance/data/work_acceptance_sequence.xml
  purchase_work_acceptance/i18n/es.po
  purchase_work_acceptance/i18n/purchase_work_acceptance.pot
  purchase_work_acceptance/models/__init__.py
  purchase_work_acceptance/models/account_move.py
  purchase_work_acceptance/models/purchase.py
  purchase_work_acceptance/models/res_config_settings.py
  purchase_work_acceptance/models/stock_picking.py
  purchase_work_acceptance/models/work_acceptance.py
  purchase_work_acceptance/readme/CONFIGURE.rst
  purchase_work_acceptance/readme/CONTRIBUTORS.rst
  purchase_work_acceptance/readme/DESCRIPTION.rst
  purchase_work_acceptance/readme/USAGE.rst
  purchase_work_acceptance/security/ir.model.access.csv
  purchase_work_acceptance/security/security.xml
  purchase_work_acceptance/static/description/icon.png
  purchase_work_acceptance/static/description/index.html
  purchase_work_acceptance/tests/__init__.py
  purchase_work_acceptance/tests/test_purchase_work_acceptance.py
  purchase_work_acceptance/views/account_move_views.xml
  purchase_work_acceptance/views/purchase_views.xml
  purchase_work_acceptance/views/res_config_settings_views.xml
  purchase_work_acceptance/views/stock_picking_type_views.xml
  purchase_work_acceptance/views/stock_picking_views.xml
  purchase_work_acceptance/views/work_acceptance_views.xml
  purchase_work_acceptance/wizard/__init__.py
  purchase_work_acceptance/wizard/select_work_acceptance_wizard.py
  purchase_work_acceptance/wizard/select_work_acceptance_wizard_views.xml
  purchase_work_acceptance/wizard/work_accepted_date_wizard.py
  purchase_work_acceptance/wizard/work_accepted_date_wizard.xml
  setup/purchase_work_acceptance/odoo/addons/purchase_work_acceptance
  setup/purchase_work_acceptance/setup.py
Labels: approved, bot is merging ⏳

#2154 [MIG] purchase_exception: Migrate to version 17.0
  purchase_exception/README.rst
  purchase_exception/__init__.py
  purchase_exception/__manifest__.py
  purchase_exception/data/purchase_exception_data.xml
  purchase_exception/i18n/es.po
  purchase_exception/i18n/fr.po
  purchase_exception/i18n/purchase_exception.pot
  purchase_exception/i18n/zh_CN.po
  purchase_exception/models/__init__.py
  purchase_exception/models/exception_rule.py
  purchase_exception/models/purchase.py
  purchase_exception/models/purchase_line.py
  purchase_exception/pyproject.toml
  purchase_exception/readme/CONTRIBUTORS.md
  purchase_exception/readme/CREDITS.md
  purchase_exception/readme/DESCRIPTION.md
  purchase_exception/security/ir.model.access.csv
  purchase_exception/static/description/icon.png
  purchase_exception/static/description/index.html
  purchase_exception/tests/__init__.py
  purchase_exception/tests/test_purchase_exception.py
  purchase_exception/views/purchase_view.xml
  purchase_exception/wizard/__init__.py
  purchase_exception/wizard/purchase_exception_confirm.py
  purchase_exception/wizard/purchase_exception_confirm_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2198 [16.0][ADD] purchase_order_downpayment
  purchase_order_downpayment/README.rst
  purchase_order_downpayment/__init__.py
  purchase_order_downpayment/__manifest__.py
  purchase_order_downpayment/models/__init__.py
  purchase_order_downpayment/models/account_payment.py
  purchase_order_downpayment/models/purchase_order.py
  purchase_order_downpayment/readme/CONTRIBUTORS.rst
  purchase_order_downpayment/readme/DESCRIPTION.rst
  purchase_order_downpayment/security/ir.model.access.csv
  purchase_order_downpayment/static/description/icon.png
  purchase_order_downpayment/static/description/index.html
  purchase_order_downpayment/tests/__init__.py
  purchase_order_downpayment/tests/test_purchase_order_downpayment.py
  purchase_order_downpayment/views/purchase_view.xml
  purchase_order_downpayment/wizard/__init__.py
  purchase_order_downpayment/wizard/purchase_order_downpayment_wiz_view.xml
  purchase_order_downpayment/wizard/purchase_order_downpayment_wizard.py
  setup/purchase_order_downpayment/odoo/addons/purchase_order_downpayment
  setup/purchase_order_downpayment/setup.py
Labels: enhancement, needs review, approved, ready to merge

#2178 [15.0][FIX] purchase_request: not allow to edit an approved purchase request
  purchase_request/models/purchase_request.py
Labels: approved, ready to merge, bot is merging ⏳

#2158 [16.0][FIX] purchase_exception
  purchase_exception/models/purchase.py
  purchase_exception/tests/test_purchase_exception.py
Labels: approved, ready to merge, bot is merging ⏳

#1944 [15.0] [FIX] purchase_delivery_split_date: Deadline and Scheduled Date
  purchase_delivery_split_date/models/purchase.py
  purchase_delivery_split_date/tests/test_purchase_delivery.py
Labels: approved, bot is merging ⏳

#2156 [16.0][IMP] purchase_blanket_order
  purchase_blanket_order/data/ir_cron.xml
  purchase_blanket_order/models/blanket_orders.py
  purchase_blanket_order/models/purchase_order.py
  purchase_blanket_order/views/purchase_blanket_order_views.xml
Labels: approved, bot is merging ⏳

#1983 [16.0][ADD] purchase_sale_link_by_origin
  purchase_sale_link_by_origin/README.rst
  purchase_sale_link_by_origin/__init__.py
  purchase_sale_link_by_origin/__manifest__.py
  purchase_sale_link_by_origin/models/__init__.py
  purchase_sale_link_by_origin/models/purchase_order.py
  purchase_sale_link_by_origin/models/sale_order.py
  purchase_sale_link_by_origin/readme/CONTRIBUTORS.rst
  purchase_sale_link_by_origin/readme/CREDITS.rst
  purchase_sale_link_by_origin/readme/DESCRIPTION.rst
  purchase_sale_link_by_origin/static/description/icon.png
  purchase_sale_link_by_origin/static/description/index.html
  purchase_sale_link_by_origin/tests/__init__.py
  purchase_sale_link_by_origin/tests/test_sale_purchase.py
  setup/purchase_sale_link_by_origin/odoo/addons/purchase_sale_link_by_origin
  setup/purchase_sale_link_by_origin/setup.py
Labels: needs review, approved, bot is merging ⏳

#2196 [15.0][FIX] purchase_requisition_grouped_by_procurement: Do not grouped from order point rules
  purchase_requisition_grouped_by_procurement/README.rst
  purchase_requisition_grouped_by_procurement/models/purchase_requisition.py
  purchase_requisition_grouped_by_procurement/readme/CONTRIBUTORS.rst
  purchase_requisition_grouped_by_procurement/static/description/index.html
Labels: approved, bot is merging ⏳

#2133 [16.0][ADD] purchase_order_line_receipt_status
  purchase_order_line_receipt_status/README.rst
  purchase_order_line_receipt_status/__init__.py
  purchase_order_line_receipt_status/__manifest__.py
  purchase_order_line_receipt_status/models/__init__.py
  purchase_order_line_receipt_status/models/purchase_order_line.py
  purchase_order_line_receipt_status/readme/CONTRIBUTORS.rst
  purchase_order_line_receipt_status/readme/DESCRIPTION.rst
  purchase_order_line_receipt_status/readme/USAGE.rst
  purchase_order_line_receipt_status/static/description/index.html
  purchase_order_line_receipt_status/views/purchase_order_line.xml
  setup/purchase_order_line_receipt_status/odoo/addons/purchase_order_line_receipt_status
  setup/purchase_order_line_receipt_status/setup.py
Labels: approved, bot is merging ⏳

#1597 [12.0][IMP] purchase_request: copy estimated cost to PO
  purchase_request/tests/test_purchase_request_to_rfq.py
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
  purchase_request/wizard/purchase_request_line_make_purchase_order_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2211 [FIX] CI tests: Add specific caompany to purchase order
  purchase_default_terms_conditions/tests/test_purchase_order.py
  purchase_picking_state/tests/test_purchase_picking_state.py
Labels: approved, bot is merging ⏳

#2197 [14.0][IMP] purchase_request: copy estimated cost to PO
  purchase_request/tests/test_purchase_request_to_rfq.py
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
  purchase_request/wizard/purchase_request_line_make_purchase_order_view.xml
Labels: approved, bot is merging ⏳
