Repository OCA/purchase-workflow, pull requests merged in 2024-06, with the labels that each got.

#2287 [16.0][ADD] product_supplierinfo_purchase_contact: Add Purchase contact in product supplier info
  product_supplierinfo_purchase_contact/README.rst
  product_supplierinfo_purchase_contact/__init__.py
  product_supplierinfo_purchase_contact/__manifest__.py
  product_supplierinfo_purchase_contact/i18n/es.po
  product_supplierinfo_purchase_contact/i18n/product_supplierinfo_purchase_contact.pot
  product_supplierinfo_purchase_contact/models/__init__.py
  product_supplierinfo_purchase_contact/models/product_supplierinfo.py
  product_supplierinfo_purchase_contact/models/stock_rule.py
  product_supplierinfo_purchase_contact/readme/CONTRIBUTORS.rst
  product_supplierinfo_purchase_contact/readme/DESCRIPTION.rst
  product_supplierinfo_purchase_contact/readme/USAGE.rst
  product_supplierinfo_purchase_contact/static/description/icon.png
  product_supplierinfo_purchase_contact/static/description/index.html
  product_supplierinfo_purchase_contact/tests/__init__.py
  product_supplierinfo_purchase_contact/tests/test_stock_rule.py
  product_supplierinfo_purchase_contact/views/product_supplierinfo_view.xml
  setup/product_supplierinfo_purchase_contact/odoo/addons/product_supplierinfo_purchase_contact
  setup/product_supplierinfo_purchase_contact/setup.py
Labels: approved, bot is merging ⏳

#2256 [15.0][IMP] supplier_calendar: robustness
  supplier_calendar/models/res_partner.py
Labels: approved, bot is merging ⏳

#2234 [17.0][MIG] purchase advance payment
  purchase_advance_payment/README.rst
  purchase_advance_payment/__init__.py
  purchase_advance_payment/__manifest__.py
  purchase_advance_payment/i18n/es.po
  purchase_advance_payment/i18n/fr.po
  purchase_advance_payment/i18n/pt_BR.po
  purchase_advance_payment/i18n/purchase_advance_payment.pot
  purchase_advance_payment/models/__init__.py
  purchase_advance_payment/models/payment.py
  purchase_advance_payment/models/purchase_order.py
  purchase_advance_payment/pyproject.toml
  purchase_advance_payment/readme/CONTRIBUTORS.md
  purchase_advance_payment/readme/CREDITS.md
  purchase_advance_payment/readme/DESCRIPTION.md
  purchase_advance_payment/readme/USAGE.md
  purchase_advance_payment/security/ir.model.access.csv
  purchase_advance_payment/static/description/icon.png
  purchase_advance_payment/static/description/index.html
  purchase_advance_payment/tests/__init__.py
  purchase_advance_payment/tests/test_purchase_advance_payment.py
  purchase_advance_payment/views/purchase_view.xml
  purchase_advance_payment/wizard/__init__.py
  purchase_advance_payment/wizard/purchase_advance_payment_wizard.py
  purchase_advance_payment/wizard/purchase_advance_payment_wizard_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2240 [ADD] [15.0] purchase_warn_option
  purchase_warn_option/README.rst
  purchase_warn_option/__init__.py
  purchase_warn_option/__manifest__.py
  purchase_warn_option/i18n/es.po
  purchase_warn_option/i18n/purchase_warn_option.pot
  purchase_warn_option/models/__init__.py
  purchase_warn_option/models/product_template.py
  purchase_warn_option/models/res_partner.py
  purchase_warn_option/models/warn_option.py
  purchase_warn_option/readme/CONTEXT.md
  purchase_warn_option/readme/CONTRIBUTORS.md
  purchase_warn_option/readme/DESCRIPTION.md
  purchase_warn_option/readme/USAGE.md
  purchase_warn_option/static/description/icon.png
  purchase_warn_option/static/description/index.html
  purchase_warn_option/tests/__init__.py
  purchase_warn_option/tests/test_warn_options.py
  purchase_warn_option/views/product_template_views.xml
  purchase_warn_option/views/res_partner_views.xml
  setup/purchase_warn_option/odoo/addons/purchase_warn_option
  setup/purchase_warn_option/setup.py
Labels: needs review, needs fixing, approved, bot is merging ⏳

#2296 [FIX] purchase_discount : transmits correctly discount value to account.move.line, if account_invoice_triple_discount is installed.
  purchase_discount/models/purchase_order.py
Labels: approved, bot is merging ⏳

#2270 [16.0] [ADD] purchase_sign
  purchase_sign/README.rst
  purchase_sign/__init__.py
  purchase_sign/__manifest__.py
  purchase_sign/controllers/__init__.py
  purchase_sign/controllers/main.py
  purchase_sign/models/__init__.py
  purchase_sign/models/purchase_order.py
  purchase_sign/models/res_company.py
  purchase_sign/models/res_config_settings.py
  purchase_sign/readme/CONTRIBUTORS.rst
  purchase_sign/readme/DESCRIPTION.rst
  purchase_sign/report/purchase_order_template.xml
  purchase_sign/static/description/index.html
  purchase_sign/static/tests/tours/purchase_signature.esm.js
  purchase_sign/templates/purchase_portal_templates.xml
  purchase_sign/tests/__init__.py
  purchase_sign/tests/test_purchase_sign.py
  purchase_sign/views/purchase_view.xml
  purchase_sign/views/res_config_settings_view.xml
  setup/purchase_sign/odoo/addons/purchase_sign
  setup/purchase_sign/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2251 [16.0][IMP] purchase_discount : Added discount field to purchase line history view
  purchase_discount/views/purchase_discount_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2248 [17.0][MIG] purchase_request_tier_validation: Migration to 17.0
  purchase_request_tier_validation/README.rst
  purchase_request_tier_validation/__init__.py
  purchase_request_tier_validation/__manifest__.py
  purchase_request_tier_validation/data/purchase_request_tier_definition.xml
  purchase_request_tier_validation/i18n/es.po
  purchase_request_tier_validation/i18n/es_EC.po
  purchase_request_tier_validation/i18n/it.po
  purchase_request_tier_validation/i18n/nl_NL.po
  purchase_request_tier_validation/i18n/purchase_request_tier_validation.pot
  purchase_request_tier_validation/i18n/zh_CN.po
  purchase_request_tier_validation/models/__init__.py
  purchase_request_tier_validation/models/purchase_request.py
  purchase_request_tier_validation/models/tier_definition.py
  purchase_request_tier_validation/pyproject.toml
  purchase_request_tier_validation/readme/CONFIGURE.md
  purchase_request_tier_validation/readme/CONTRIBUTORS.md
  purchase_request_tier_validation/readme/CREDITS.md
  purchase_request_tier_validation/readme/DESCRIPTION.md
  purchase_request_tier_validation/readme/INSTALL.md
  purchase_request_tier_validation/readme/USAGE.md
  purchase_request_tier_validation/static/description/icon.png
  purchase_request_tier_validation/static/description/index.html
  purchase_request_tier_validation/tests/__init__.py
  purchase_request_tier_validation/tests/test_purchase_request_tier_validation.py
  purchase_request_tier_validation/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳

#2285 [14.0][ADD] purchase_cancel_remaining_delivery
  purchase_cancel_remaining_delivery/README.rst
  purchase_cancel_remaining_delivery/__init__.py
  purchase_cancel_remaining_delivery/__manifest__.py
  purchase_cancel_remaining_delivery/models/__init__.py
  purchase_cancel_remaining_delivery/models/purchase_order.py
  purchase_cancel_remaining_delivery/readme/CONTRIBUTORS.rst
  purchase_cancel_remaining_delivery/readme/DESCRIPTION.rst
  purchase_cancel_remaining_delivery/static/description/index.html
  purchase_cancel_remaining_delivery/tests/__init__.py
  purchase_cancel_remaining_delivery/tests/test_purchase_cancel_remaining_delivery.py
  purchase_cancel_remaining_delivery/views/purchase_order.xml
  setup/purchase_cancel_remaining_delivery/odoo/addons/purchase_cancel_remaining_delivery
  setup/purchase_cancel_remaining_delivery/setup.py
Labels: approved, bot is merging ⏳

#2224 [15.0][IMP] sale_purchase_force_vendor: Allow set vendor for new sale order lines in a sale order in done state
  sale_purchase_force_vendor/views/sale_order_view.xml
Labels: approved, bot is merging ⏳

#2276 [16.0][ADD] purchase_vendor_promotion
  purchase_vendor_promotion/README.rst
  purchase_vendor_promotion/__init__.py
  purchase_vendor_promotion/__manifest__.py
  purchase_vendor_promotion/i18n/fr.po
  purchase_vendor_promotion/i18n/purchase_vendor_promotion.pot
  purchase_vendor_promotion/models/__init__.py
  purchase_vendor_promotion/models/product_supplierinfo.py
  purchase_vendor_promotion/models/purchase_order_line.py
  purchase_vendor_promotion/models/stock_warehouse_orderpoint.py
  purchase_vendor_promotion/readme/CONTRIBUTORS.rst
  purchase_vendor_promotion/readme/DESCRIPTION.rst
  purchase_vendor_promotion/static/description/index.html
  purchase_vendor_promotion/tests/__init__.py
  purchase_vendor_promotion/tests/test_vendor_promotion.py
  purchase_vendor_promotion/views/product_views.xml
  purchase_vendor_promotion/views/purchase_order_views.xml
  purchase_vendor_promotion/views/stock_orderpoint_views.xml
  setup/purchase_vendor_promotion/odoo/addons/purchase_vendor_promotion
  setup/purchase_vendor_promotion/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2281 [17.0][MIG] purchase_last_price_info
  purchase_last_price_info/README.rst
  purchase_last_price_info/__init__.py
  purchase_last_price_info/__manifest__.py
  purchase_last_price_info/i18n/ca.po
  purchase_last_price_info/i18n/de.po
  purchase_last_price_info/i18n/el_GR.po
  purchase_last_price_info/i18n/es.po
  purchase_last_price_info/i18n/es_ES.po
  purchase_last_price_info/i18n/eu.po
  purchase_last_price_info/i18n/fi.po
  purchase_last_price_info/i18n/fr.po
  purchase_last_price_info/i18n/fr_CH.po
  purchase_last_price_info/i18n/fr_FR.po
  purchase_last_price_info/i18n/gl.po
  purchase_last_price_info/i18n/hr.po
  purchase_last_price_info/i18n/hr_HR.po
  purchase_last_price_info/i18n/it.po
  purchase_last_price_info/i18n/nl.po
  purchase_last_price_info/i18n/nl_NL.po
  purchase_last_price_info/i18n/pt.po
  purchase_last_price_info/i18n/pt_BR.po
  purchase_last_price_info/i18n/purchase_last_price_info.pot
  purchase_last_price_info/i18n/ro.po
  purchase_last_price_info/i18n/ru.po
  purchase_last_price_info/i18n/sk.po
  purchase_last_price_info/i18n/sl.po
  purchase_last_price_info/i18n/tr.po
  purchase_last_price_info/i18n/tr_TR.po
  purchase_last_price_info/i18n/vi_VN.po
  purchase_last_price_info/i18n/zh_CN.po
  purchase_last_price_info/models/__init__.py
  purchase_last_price_info/models/product_product.py
  purchase_last_price_info/models/product_template.py
  purchase_last_price_info/pyproject.toml
  purchase_last_price_info/readme/CONTRIBUTORS.md
  purchase_last_price_info/readme/DESCRIPTION.md
  purchase_last_price_info/readme/USAGE.md
  purchase_last_price_info/static/description/icon.png
  purchase_last_price_info/static/description/index.html
  purchase_last_price_info/static/description/purchase_last_price.png
  purchase_last_price_info/tests/__init__.py
  purchase_last_price_info/tests/test_purchase_last_price_info.py
  purchase_last_price_info/views/product_views.xml
Labels: approved, bot is merging ⏳

#2311 [15.0][IMP] purchase_order_secondary_unit: make the secondary unit and secondary quantity fields optional
  purchase_order_secondary_unit/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#2310 [14.0][FIX] purchase_order_type: preserve order type when matches company
  purchase_order_type/models/purchase_order.py
  purchase_order_type/tests/test_purchase_order_type.py
Labels: approved, ready to merge, bot is merging ⏳

#2312 [15.0][IMP] purchase_order_product_recommendation_secondary_unit: make the secondary unit and secondary quantity fields optional
  purchase_order_product_recommendation_secondary_unit/wizards/purchase_order_recommendation_view.xml
Labels: approved, bot is merging ⏳

#2316 [17.0][FIX] purchase_order_type: preserve order type when matches company
  purchase_order_type/models/purchase_order.py
  purchase_order_type/tests/test_purchase_order_type.py
Labels: approved, bot is merging ⏳

#2039 [ADD] purchase_transport_mode
  purchase_transport_mode/README.rst
  purchase_transport_mode/__init__.py
  purchase_transport_mode/__manifest__.py
  purchase_transport_mode/data/purchase_exception_data.xml
  purchase_transport_mode/models/__init__.py
  purchase_transport_mode/models/purchase_order.py
  purchase_transport_mode/models/purchase_transport_mode.py
  purchase_transport_mode/models/purchase_transport_mode_constraint.py
  purchase_transport_mode/models/res_company.py
  purchase_transport_mode/models/res_config_settings.py
  purchase_transport_mode/models/res_partner.py
  purchase_transport_mode/readme/CONTRIBUTORS.rst
  purchase_transport_mode/readme/DESCRIPTION.rst
  purchase_transport_mode/readme/USAGE.rst
  purchase_transport_mode/security/ir.model.access.csv
  purchase_transport_mode/static/description/index.html
  purchase_transport_mode/templates/purchase_order_transport_mode_status.xml
  purchase_transport_mode/tests/__init__.py
  purchase_transport_mode/tests/test_purchase_transport_mode.py
  purchase_transport_mode/views/purchase_order_view.xml
  purchase_transport_mode/views/purchase_transport_mode_constraint_views.xml
  purchase_transport_mode/views/purchase_transport_mode_views.xml
  purchase_transport_mode/views/res_config_settings_views.xml
  purchase_transport_mode/views/res_partner_views.xml
  setup/purchase_transport_mode/odoo/addons/purchase_transport_mode
  setup/purchase_transport_mode/setup.py
Labels: approved, bot is merging ⏳
