Repository OCA/purchase-workflow, pull requests merged in 2024-10, with the labels that each got.

#2263 [FIX] purchase_request: message_post with html fixed
  purchase_request/models/purchase_order.py
  purchase_request/models/purchase_request_allocation.py
  purchase_request/models/stock_move_line.py
Labels: approved, bot is merging ⏳

#2418 [17.0][FIX] purchase_tag: fix _name_search signature
  purchase_tag/models/purchase_tag.py
Labels: approved, bot is merging ⏳

#2294 [16.0][IMP] purchase_delivery_split_date: change scheduled_date instead of date in pickings
  purchase_delivery_split_date/models/stock_picking.py
Labels: approved, bot is merging ⏳

#2226 [15.0][IMP] purchase_request: set requested_by to SO confirmer and set approver to False
  purchase_request/models/stock_rule.py
Labels: approved, bot is merging ⏳

#2413 [16.0][FIX] purchase_security: specify @api.onchange
  purchase_security/models/purchase_order.py
Labels: approved, bot is merging ⏳

#2429 [16.0][FIX] product_main_seller: correct import of pre_init_hook
  product_main_seller/migrations/16.0.1.0.0/pre-migration.py
Labels: approved, bot is merging ⏳

#2405 [15.0][ADD] stock_move_purchase_price_update: New module
  setup/stock_move_purchase_price_update/odoo/addons/stock_move_purchase_price_update
  setup/stock_move_purchase_price_update/setup.py
  setup/stock_picking_batch_purchase_price_update/odoo/addons/stock_picking_batch_purchase_price_update
  setup/stock_picking_batch_purchase_price_update/setup.py
  stock_move_purchase_price_update/README.rst
  stock_move_purchase_price_update/__init__.py
  stock_move_purchase_price_update/__manifest__.py
  stock_move_purchase_price_update/i18n/es.po
  stock_move_purchase_price_update/i18n/stock_move_purchase_price_update.pot
  stock_move_purchase_price_update/models/__init__.py
  stock_move_purchase_price_update/models/stock_move.py
  stock_move_purchase_price_update/models/stock_move_line.py
  stock_move_purchase_price_update/readme/CONFIGURE.md
  stock_move_purchase_price_update/readme/CONTRIBUTORS.md
  stock_move_purchase_price_update/readme/DESCRIPTION.md
  stock_move_purchase_price_update/readme/USAGE.md
  stock_move_purchase_price_update/static/description/icon.png
  stock_move_purchase_price_update/static/description/index.html
  stock_move_purchase_price_update/tests/__init__.py
  stock_move_purchase_price_update/tests/test_stock_move_purchase_price_update.py
  stock_move_purchase_price_update/views/stock_move_views.xml
  stock_picking_batch_purchase_price_update/README.rst
  stock_picking_batch_purchase_price_update/__init__.py
  stock_picking_batch_purchase_price_update/__manifest__.py
  stock_picking_batch_purchase_price_update/readme/CONFIGURE.md
  stock_picking_batch_purchase_price_update/readme/CONTRIBUTORS.md
  stock_picking_batch_purchase_price_update/readme/DESCRIPTION.md
  stock_picking_batch_purchase_price_update/readme/USAGE.md
  stock_picking_batch_purchase_price_update/static/description/icon.png
  stock_picking_batch_purchase_price_update/static/description/index.html
  stock_picking_batch_purchase_price_update/views/stock_move_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2442 [17.0][IMP] purchase_request: set requested_by to SO confirmer and set approver to False
  purchase_request/models/stock_rule.py
Labels: bot is merging ⏳

#2441 [16.0][IMP] purchase_request: set requested_by to SO confirmer and set approver to False
  purchase_request/models/stock_rule.py
Labels: bot is merging ⏳
