Repository OCA/purchase-workflow, pull requests merged in 2024-11, with the labels that each got.

#2439 [18.0][MIG] purchase_last_price_info: Migration to 18.0
  purchase_last_price_info/README.rst
  purchase_last_price_info/__init__.py
  purchase_last_price_info/__manifest__.py
  purchase_last_price_info/i18n/ca.po
  purchase_last_price_info/i18n/de.po
  purchase_last_price_info/i18n/el_GR.po
  purchase_last_price_info/i18n/es.po
  purchase_last_price_info/i18n/es_ES.po
  purchase_last_price_info/i18n/eu.po
  purchase_last_price_info/i18n/fi.po
  purchase_last_price_info/i18n/fr.po
  purchase_last_price_info/i18n/fr_CH.po
  purchase_last_price_info/i18n/fr_FR.po
  purchase_last_price_info/i18n/gl.po
  purchase_last_price_info/i18n/hr.po
  purchase_last_price_info/i18n/hr_HR.po
  purchase_last_price_info/i18n/it.po
  purchase_last_price_info/i18n/nl.po
  purchase_last_price_info/i18n/nl_NL.po
  purchase_last_price_info/i18n/pt.po
  purchase_last_price_info/i18n/pt_BR.po
  purchase_last_price_info/i18n/purchase_last_price_info.pot
  purchase_last_price_info/i18n/ro.po
  purchase_last_price_info/i18n/ru.po
  purchase_last_price_info/i18n/sk.po
  purchase_last_price_info/i18n/sl.po
  purchase_last_price_info/i18n/tr.po
  purchase_last_price_info/i18n/tr_TR.po
  purchase_last_price_info/i18n/vi_VN.po
  purchase_last_price_info/i18n/zh_CN.po
  purchase_last_price_info/models/__init__.py
  purchase_last_price_info/models/product_product.py
  purchase_last_price_info/models/product_template.py
  purchase_last_price_info/pyproject.toml
  purchase_last_price_info/readme/CONTRIBUTORS.md
  purchase_last_price_info/readme/DESCRIPTION.md
  purchase_last_price_info/readme/USAGE.md
  purchase_last_price_info/static/description/icon.png
  purchase_last_price_info/static/description/index.html
  purchase_last_price_info/static/description/purchase_last_price.png
  purchase_last_price_info/tests/__init__.py
  purchase_last_price_info/tests/test_purchase_last_price_info.py
  purchase_last_price_info/views/product_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2438 [18.0][MIG] purchase_commercial_partner: Migration to 18.0
  purchase_commercial_partner/README.rst
  purchase_commercial_partner/__init__.py
  purchase_commercial_partner/__manifest__.py
  purchase_commercial_partner/i18n/de.po
  purchase_commercial_partner/i18n/es.po
  purchase_commercial_partner/i18n/es_ES.po
  purchase_commercial_partner/i18n/es_PE.po
  purchase_commercial_partner/i18n/fr.po
  purchase_commercial_partner/i18n/fr_BE.po
  purchase_commercial_partner/i18n/gl.po
  purchase_commercial_partner/i18n/hr.po
  purchase_commercial_partner/i18n/it.po
  purchase_commercial_partner/i18n/nl.po
  purchase_commercial_partner/i18n/nl_NL.po
  purchase_commercial_partner/i18n/pt_BR.po
  purchase_commercial_partner/i18n/purchase_commercial_partner.pot
  purchase_commercial_partner/i18n/ro.po
  purchase_commercial_partner/i18n/sl.po
  purchase_commercial_partner/i18n/sv.po
  purchase_commercial_partner/i18n/vi_VN.po
  purchase_commercial_partner/models/__init__.py
  purchase_commercial_partner/models/purchase_order.py
  purchase_commercial_partner/pyproject.toml
  purchase_commercial_partner/readme/CONTRIBUTORS.md
  purchase_commercial_partner/readme/DESCRIPTION.md
  purchase_commercial_partner/readme/USAGE.md
  purchase_commercial_partner/static/description/icon.png
  purchase_commercial_partner/static/description/index.html
  purchase_commercial_partner/tests/__init__.py
  purchase_commercial_partner/tests/test_purchase_commercial_partner.py
  purchase_commercial_partner/views/purchase_order.xml
  purchase_commercial_partner/views/purchase_report.xml
Labels: approved, ready to merge, bot is merging ⏳

#2451 [17.0][IMP] purchase_delivery_split_date: change scheduled_date instead of date in pickings
  purchase_delivery_split_date/models/stock_picking.py
Labels: approved, bot is merging ⏳

#2453 [15.0][FIX] purchase_order_secondary_unit: Error when user try to select a secondary uom without product in sale order line
  purchase_order_secondary_unit/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#1326 [14.0] Refactor purchase_delivery_split_date (support new PO line or increased qty on a confirmed PO)
  purchase_delivery_split_date/README.rst
  purchase_delivery_split_date/__manifest__.py
  purchase_delivery_split_date/models/__init__.py
  purchase_delivery_split_date/models/purchase.py
  purchase_delivery_split_date/models/stock_picking.py
  purchase_delivery_split_date/readme/CONTRIBUTORS.rst
  purchase_delivery_split_date/readme/DESCRIPTION.rst
  purchase_delivery_split_date/readme/HISTORY.rst
  purchase_delivery_split_date/static/description/index.html
  purchase_delivery_split_date/tests/test_purchase_delivery.py
  purchase_location_by_line/README.rst
  purchase_location_by_line/__manifest__.py
  purchase_location_by_line/models/purchase.py
  purchase_location_by_line/readme/CONTRIBUTORS.rst
Labels: needs fixing, approved, bot is merging ⏳, stale

#2216 [16.0][MIG] purchase_order_secondary_unit
  purchase_order_secondary_unit/README.rst
  purchase_order_secondary_unit/__init__.py
  purchase_order_secondary_unit/__manifest__.py
  purchase_order_secondary_unit/i18n/de.po
  purchase_order_secondary_unit/i18n/es.po
  purchase_order_secondary_unit/i18n/fr.po
  purchase_order_secondary_unit/i18n/ja.po
  purchase_order_secondary_unit/i18n/purchase_order_secondary_unit.pot
  purchase_order_secondary_unit/models/__init__.py
  purchase_order_secondary_unit/models/product_product.py
  purchase_order_secondary_unit/models/product_template.py
  purchase_order_secondary_unit/models/purchase_order.py
  purchase_order_secondary_unit/readme/CONTRIBUTORS.rst
  purchase_order_secondary_unit/readme/DESCRIPTION.rst
  purchase_order_secondary_unit/readme/USAGE.rst
  purchase_order_secondary_unit/reports/purchase_order_templates.xml
  purchase_order_secondary_unit/reports/purchase_quotation_templates.xml
  purchase_order_secondary_unit/static/description/icon.png
  purchase_order_secondary_unit/static/description/index.html
  purchase_order_secondary_unit/tests/__init__.py
  purchase_order_secondary_unit/tests/test_purchase_order_secondary_unit.py
  purchase_order_secondary_unit/views/product_views.xml
  purchase_order_secondary_unit/views/purchase_order_views.xml
  setup/purchase_order_secondary_unit/odoo/addons/purchase_order_secondary_unit
  setup/purchase_order_secondary_unit/setup.py
Labels: bot is merging ⏳

#2461 [MIG][17.0] purchase_default_terms_conditions
  purchase_default_terms_conditions/README.rst
  purchase_default_terms_conditions/__init__.py
  purchase_default_terms_conditions/__manifest__.py
  purchase_default_terms_conditions/i18n/es.po
  purchase_default_terms_conditions/i18n/it.po
  purchase_default_terms_conditions/i18n/pt_BR.po
  purchase_default_terms_conditions/i18n/purchase_default_terms_conditions.pot
  purchase_default_terms_conditions/models/__init__.py
  purchase_default_terms_conditions/models/purchase.py
  purchase_default_terms_conditions/models/res_company.py
  purchase_default_terms_conditions/models/res_config_settings.py
  purchase_default_terms_conditions/models/res_partner.py
  purchase_default_terms_conditions/pyproject.toml
  purchase_default_terms_conditions/readme/CONFIGURE.md
  purchase_default_terms_conditions/readme/CONTRIBUTORS.md
  purchase_default_terms_conditions/readme/CREDITS.md
  purchase_default_terms_conditions/readme/DESCRIPTION.md
  purchase_default_terms_conditions/readme/USAGE.md
  purchase_default_terms_conditions/static/description/banner.png
  purchase_default_terms_conditions/static/description/icon.png
  purchase_default_terms_conditions/static/description/index.html
  purchase_default_terms_conditions/static/index.html
  purchase_default_terms_conditions/tests/__init__.py
  purchase_default_terms_conditions/tests/test_purchase_order.py
  purchase_default_terms_conditions/views/res_config_settings.xml
  purchase_default_terms_conditions/views/res_partner_views.xml
Labels: bot is merging ⏳

#2463 [15.0][IMP] purchase_stock_price_unit_sync: Avoid errors with cancelled stock moves
  purchase_stock_price_unit_sync/models/purchase_order.py
Labels: approved, bot is merging ⏳

#2464 [16.0][IMP] purchase_stock_price_unit_sync: Avoid errors with cancelled stock moves
  purchase_stock_price_unit_sync/models/purchase_order.py
Labels: approved, bot is merging ⏳

#2473 [13.0][FIX] purchase_requisition_grouped_by_procurement: Correct grouping of purchase requisitions
  purchase_requisition_grouped_by_procurement/models/purchase_requisition.py
Labels: bot is merging ⏳
