Repository OCA/purchase-workflow, pull requests merged in 2024-05, with the labels that each got.

#2261 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  purchase_invoice_plan/tests/test_purchase_invoice_plan.py
  purchase_request/models/stock_move.py
  purchase_request/models/stock_move_line.py
Labels: help wanted, needs review, bot is merging ⏳

#2132 [16][FIX] purchase_delivery_split_date: Access rights issue
  purchase_delivery_split_date/models/purchase_order.py
  purchase_delivery_split_date/models/purchase_order_line.py
Labels: approved, bot is merging ⏳

#1975 [16.0][MIG] purchase_return: Migration to 16.0.
  purchase_return/README.rst
  purchase_return/__init__.py
  purchase_return/__manifest__.py
  purchase_return/data/mail_template_data.xml
  purchase_return/data/purchase_data.xml
  purchase_return/models/__init__.py
  purchase_return/models/account_move.py
  purchase_return/models/account_move_line.py
  purchase_return/models/product_category.py
  purchase_return/models/product_template.py
  purchase_return/models/purchase_return_order.py
  purchase_return/models/purchase_return_order_line.py
  purchase_return/readme/CONTRIBUTORS.rst
  purchase_return/readme/DESCRIPTION.rst
  purchase_return/readme/USAGE.rst
  purchase_return/report/purchase_reports.xml
  purchase_return/report/purchase_return_order_templates.xml
  purchase_return/security/ir.model.access.csv
  purchase_return/security/purchase_security.xml
  purchase_return/tests/__init__.py
  purchase_return/tests/test_purchase_return_order.py
  purchase_return/tests/test_purchase_return_order_line.py
  purchase_return/views/account_move_views.xml
  purchase_return/views/product_category_views.xml
  purchase_return/views/product_template_views.xml
  purchase_return/views/purchase_return_template.xml
  purchase_return/views/purchase_views.xml
  setup/purchase_return/odoo/addons/purchase_return
  setup/purchase_return/setup.py
Labels: bot is merging ⏳

#2254 [17.0][MIG] purchase_reception_notify
  purchase_reception_notify/README.rst
  purchase_reception_notify/__init__.py
  purchase_reception_notify/__manifest__.py
  purchase_reception_notify/data/mail_data.xml
  purchase_reception_notify/hooks.py
  purchase_reception_notify/i18n/es.po
  purchase_reception_notify/i18n/it.po
  purchase_reception_notify/i18n/purchase_reception_notify.pot
  purchase_reception_notify/i18n/zh_CN.po
  purchase_reception_notify/models/__init__.py
  purchase_reception_notify/models/stock_picking.py
  purchase_reception_notify/pyproject.toml
  purchase_reception_notify/readme/CONTRIBUTORS.md
  purchase_reception_notify/readme/DESCRIPTION.md
  purchase_reception_notify/readme/USAGE.md
  purchase_reception_notify/static/description/icon.png
  purchase_reception_notify/static/description/index.html
  purchase_reception_notify/tests/__init__.py
  purchase_reception_notify/tests/test_purchase_reception_notify.py
Labels: approved, ready to merge, bot is merging ⏳

#2116 [16.0][ADD] purchase_order_supplier_return
  purchase_order_supplier_return/README.rst
  purchase_order_supplier_return/__init__.py
  purchase_order_supplier_return/__manifest__.py
  purchase_order_supplier_return/models/__init__.py
  purchase_order_supplier_return/models/stock_move.py
  purchase_order_supplier_return/readme/CONTRIBUTORS.rst
  purchase_order_supplier_return/readme/DESCRIPTION.rst
  purchase_order_supplier_return/readme/USAGE.rst
  purchase_order_supplier_return/static/description/index.html
  purchase_order_supplier_return/tests/__init__.py
  purchase_order_supplier_return/tests/test_purchase_order_supplier_return.py
  setup/purchase_order_supplier_return/odoo/addons/purchase_order_supplier_return
  setup/purchase_order_supplier_return/setup.py
Labels: approved, bot is merging ⏳

#2272 [16.0][FIX] purchase_discount: supplierinfo with no template
  purchase_discount/models/product_supplierinfo.py
Labels: bot is merging ⏳

#2174 [16.0][ADD] purchase_packaging_default
  purchase_packaging_default/README.rst
  purchase_packaging_default/__init__.py
  purchase_packaging_default/__manifest__.py
  purchase_packaging_default/models/__init__.py
  purchase_packaging_default/models/product_packaging.py
  purchase_packaging_default/models/purchase_order_line.py
  purchase_packaging_default/models/res_company.py
  purchase_packaging_default/models/res_config_settings.py
  purchase_packaging_default/readme/CONTRIBUTORS.rst
  purchase_packaging_default/readme/DESCRIPTION.rst
  purchase_packaging_default/static/description/index.html
  purchase_packaging_default/tests/__init__.py
  purchase_packaging_default/tests/test_purchase_packaging_default.py
  purchase_packaging_default/views/res_config_settings_views.xml
  setup/purchase_packaging_default/odoo/addons/purchase_packaging_default
  setup/purchase_packaging_default/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2227 [FIX]_request: Add products only in draft state
  purchase_request/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳

#2267 [17.0][MIG] purchase_order_archive
  purchase_order_archive/README.rst
  purchase_order_archive/__init__.py
  purchase_order_archive/__manifest__.py
  purchase_order_archive/i18n/es.po
  purchase_order_archive/i18n/it.po
  purchase_order_archive/i18n/purchase_order_archive.pot
  purchase_order_archive/i18n/zh_CN.po
  purchase_order_archive/models/__init__.py
  purchase_order_archive/models/purchase_order.py
  purchase_order_archive/pyproject.toml
  purchase_order_archive/readme/CONTRIBUTORS.md
  purchase_order_archive/readme/DESCRIPTION.md
  purchase_order_archive/readme/USAGE.md
  purchase_order_archive/setup/purchase_order_archive/odoo/addons/purchase_order_archive
  purchase_order_archive/setup/purchase_order_archive/setup.py
  purchase_order_archive/static/description/icon.png
  purchase_order_archive/static/description/index.html
  purchase_order_archive/tests/__init__.py
  purchase_order_archive/tests/test_purchase_order_archive.py
  purchase_order_archive/views/purchase_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#2277 [13.0] [ADD] Account Fiscal Position Allowed Journal Purchase
  account_fiscal_position_allowed_journal_purchase/README.rst
  account_fiscal_position_allowed_journal_purchase/__init__.py
  account_fiscal_position_allowed_journal_purchase/__manifest__.py
  account_fiscal_position_allowed_journal_purchase/models/__init__.py
  account_fiscal_position_allowed_journal_purchase/models/account_move.py
  account_fiscal_position_allowed_journal_purchase/readme/CONFIGURE.rst
  account_fiscal_position_allowed_journal_purchase/readme/CONTRIBUTORS.rst
  account_fiscal_position_allowed_journal_purchase/readme/DESCRIPTION.rst
  account_fiscal_position_allowed_journal_purchase/static/description/icon.png
  account_fiscal_position_allowed_journal_purchase/static/description/index.html
  account_fiscal_position_allowed_journal_purchase/tests/__init__.py
  account_fiscal_position_allowed_journal_purchase/tests/test_account_fiscal_position_allowed_journal_purchase.py
  account_fiscal_position_allowed_journal_sale_purchase/README.rst
  account_fiscal_position_allowed_journal_sale_purchase/__init__.py
  account_fiscal_position_allowed_journal_sale_purchase/__manifest__.py
  account_fiscal_position_allowed_journal_sale_purchase/models/__init__.py
  account_fiscal_position_allowed_journal_sale_purchase/models/account_move.py
  account_fiscal_position_allowed_journal_sale_purchase/readme/CONFIGURE.rst
  account_fiscal_position_allowed_journal_sale_purchase/readme/CONTRIBUTORS.rst
  account_fiscal_position_allowed_journal_sale_purchase/readme/DESCRIPTION.rst
  account_fiscal_position_allowed_journal_sale_purchase/static/description/icon.png
  account_fiscal_position_allowed_journal_sale_purchase/static/description/index.html
  account_fiscal_position_allowed_journal_sale_purchase/tests/__init__.py
  account_fiscal_position_allowed_journal_sale_purchase/tests/test_account_fiscal_position_allowed_journal_purchase.py
  oca_dependencies.txt
  setup/account_fiscal_position_allowed_journal_purchase/odoo/addons/account_fiscal_position_allowed_journal_purchase
  setup/account_fiscal_position_allowed_journal_purchase/setup.py
  setup/account_fiscal_position_allowed_journal_sale_purchase/odoo/addons/account_fiscal_position_allowed_journal_sale_purchase
  setup/account_fiscal_position_allowed_journal_sale_purchase/setup.py
Labels: bot is merging ⏳

#2266 [17.0][MIG] purchase_sale_link_by_origin: Migration to 17.0
  purchase_sale_link_by_origin/README.rst
  purchase_sale_link_by_origin/__init__.py
  purchase_sale_link_by_origin/__manifest__.py
  purchase_sale_link_by_origin/i18n/it.po
  purchase_sale_link_by_origin/i18n/purchase_sale_link_by_origin.pot
  purchase_sale_link_by_origin/models/__init__.py
  purchase_sale_link_by_origin/models/purchase_order.py
  purchase_sale_link_by_origin/models/sale_order.py
  purchase_sale_link_by_origin/pyproject.toml
  purchase_sale_link_by_origin/readme/CONTRIBUTORS.md
  purchase_sale_link_by_origin/readme/CREDITS.md
  purchase_sale_link_by_origin/readme/DESCRIPTION.md
  purchase_sale_link_by_origin/static/description/icon.png
  purchase_sale_link_by_origin/static/description/index.html
  purchase_sale_link_by_origin/tests/__init__.py
  purchase_sale_link_by_origin/tests/test_sale_purchase.py
Labels: approved, bot is merging ⏳

#2225 [FIX] purchase_request: changes in report layout
  purchase_request/reports/report_purchase_request.xml
Labels: approved, bot is merging ⏳

#2250 [17.0][FIX] purchase_request: changes in report layout
  purchase_request/reports/report_purchase_request.xml
Labels: bot is merging ⏳

#2264 [17.0] [MIG] supplier_calendar: Migration to 17.0
  supplier_calendar/README.rst
  supplier_calendar/__init__.py
  supplier_calendar/__manifest__.py
  supplier_calendar/i18n/es.po
  supplier_calendar/i18n/it.po
  supplier_calendar/i18n/supplier_calendar.pot
  supplier_calendar/models/__init__.py
  supplier_calendar/models/product.py
  supplier_calendar/models/purchase.py
  supplier_calendar/models/res_partner.py
  supplier_calendar/models/stock_rule.py
  supplier_calendar/pyproject.toml
  supplier_calendar/readme/CONFIGURE.md
  supplier_calendar/readme/CONTRIBUTORS.md
  supplier_calendar/readme/DESCRIPTION.md
  supplier_calendar/readme/USAGE.md
  supplier_calendar/static/description/icon.png
  supplier_calendar/static/description/index.html
  supplier_calendar/tests/__init__.py
  supplier_calendar/tests/test_supplier_calendar.py
  supplier_calendar/views/product_view.xml
  supplier_calendar/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#2286 [15.0][FIX] purchase_quick: fix CI error test
  purchase_default_terms_conditions/tests/test_purchase_order.py
  purchase_quick/models/purchase_order.py
  purchase_quick/tests/test_quick_purchase.py
Labels: bot is merging ⏳
