Repository OCA/purchase-workflow, pull requests merged in 2024-09, with the labels that each got.

#2396 [17.0][IMP]purchase_order_type: Automatically get partner purchase type on purchase creation.
  purchase_order_type/README.rst
  purchase_order_type/models/purchase_order.py
  purchase_order_type/readme/CONTRIBUTORS.md
  purchase_order_type/static/description/index.html
  purchase_order_type/tests/test_purchase_order_type.py
Labels: approved, ready to merge, bot is merging ⏳

#2350 [16.0][ADD] product_main_seller
  product_main_seller/README.rst
  product_main_seller/__init__.py
  product_main_seller/__manifest__.py
  product_main_seller/hooks.py
  product_main_seller/i18n/fr.po
  product_main_seller/migrations/16.0.1.0.0/pre-migration.py
  product_main_seller/models/__init__.py
  product_main_seller/models/product_template.py
  product_main_seller/readme/CONTRIBUTORS.rst
  product_main_seller/readme/DESCRIPTION.rst
  product_main_seller/static/description/icon.png
  product_main_seller/static/description/index.html
  product_main_seller/static/description/product_tree_view.png
  product_main_seller/tests/__init__.py
  product_main_seller/tests/test_seller.py
  product_main_seller/views/view_product_product.xml
  product_main_seller/views/view_product_template.xml
  setup/product_main_seller/odoo/addons/product_main_seller
  setup/product_main_seller/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1789 [15.0][MIG]purchase_order_price_recalculation: Migration to V15
  purchase_order_price_recalculation/README.rst
  purchase_order_price_recalculation/__init__.py
  purchase_order_price_recalculation/__manifest__.py
  purchase_order_price_recalculation/i18n/es.po
  purchase_order_price_recalculation/i18n/it.po
  purchase_order_price_recalculation/i18n/purchase_order_price_recalculation.pot
  purchase_order_price_recalculation/models/__init__.py
  purchase_order_price_recalculation/models/purchase_order.py
  purchase_order_price_recalculation/readme/CONTRIBUTORS.rst
  purchase_order_price_recalculation/readme/DESCRIPTION.rst
  purchase_order_price_recalculation/readme/USAGE.rst
  purchase_order_price_recalculation/static/description/icon.png
  purchase_order_price_recalculation/static/description/index.html
  purchase_order_price_recalculation/tests/__init__.py
  purchase_order_price_recalculation/tests/test_purchase_order_price_recalculation.py
  purchase_order_price_recalculation/views/purchase_order_view.xml
  setup/purchase_order_price_recalculation/odoo/addons/purchase_order_price_recalculation
  setup/purchase_order_price_recalculation/setup.py
Labels: approved, bot is merging ⏳, stale

#2402 [17.0][FIX] purchase_request: fix copying descriptions to new purchase order
  purchase_request/wizard/purchase_request_line_make_purchase_order_view.xml
Labels: bot is merging ⏳

#2373 [MIG] purchase_request_department: Migration to 16.0
  purchase_request/tests/test_purchase_request_procurement.py
  purchase_request_department/README.rst
  purchase_request_department/__init__.py
  purchase_request_department/__manifest__.py
  purchase_request_department/hooks.py
  purchase_request_department/i18n/de.po
  purchase_request_department/i18n/es.po
  purchase_request_department/i18n/es_EC.po
  purchase_request_department/i18n/fr.po
  purchase_request_department/i18n/hr.po
  purchase_request_department/i18n/it.po
  purchase_request_department/i18n/nb.po
  purchase_request_department/i18n/nb_NO.po
  purchase_request_department/i18n/nl_NL.po
  purchase_request_department/i18n/pt_BR.po
  purchase_request_department/i18n/purchase_request_department.pot
  purchase_request_department/i18n/sl.po
  purchase_request_department/i18n/tr.po
  purchase_request_department/i18n/zh_CN.po
  purchase_request_department/models/__init__.py
  purchase_request_department/models/purchase_request.py
  purchase_request_department/readme/CONTRIBUTORS.rst
  purchase_request_department/readme/CREDITS.rst
  purchase_request_department/readme/DESCRIPTION.rst
  purchase_request_department/readme/USAGE.rst
  purchase_request_department/static/description/icon.png
  purchase_request_department/static/description/index.html
  purchase_request_department/tests/__init__.py
  purchase_request_department/tests/test_purchase_request_department.py
  purchase_request_department/views/purchase_request_department_view.xml
  setup/purchase_request_department/odoo/addons/purchase_request_department
  setup/purchase_request_department/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1190 [13.0][MIG] - purchase_packaging
  .copier-answers.yml
  .github/workflows/test.yml
  purchase_packaging/README.rst
  purchase_packaging/__init__.py
  purchase_packaging/__manifest__.py
  purchase_packaging/hooks.py
  purchase_packaging/i18n/ca.po
  purchase_packaging/i18n/cs_CZ.po
  purchase_packaging/i18n/de.po
  purchase_packaging/i18n/es.po
  purchase_packaging/i18n/es_ES.po
  purchase_packaging/i18n/es_MX.po
  purchase_packaging/i18n/fi.po
  purchase_packaging/i18n/fr.po
  purchase_packaging/i18n/fr_CH.po
  purchase_packaging/i18n/hr.po
  purchase_packaging/i18n/hr_HR.po
  purchase_packaging/i18n/it.po
  purchase_packaging/i18n/nl.po
  purchase_packaging/i18n/nl_NL.po
  purchase_packaging/i18n/pt_BR.po
  purchase_packaging/i18n/pt_PT.po
  purchase_packaging/i18n/purchase_packaging.pot
  purchase_packaging/i18n/ro.po
  purchase_packaging/i18n/sk.po
  purchase_packaging/i18n/sl.po
  purchase_packaging/i18n/tr.po
  purchase_packaging/i18n/tr_TR.po
  purchase_packaging/i18n/vi_VN.po
  purchase_packaging/i18n/zh_CN.po
  purchase_packaging/models/__init__.py
  purchase_packaging/models/product_supplier_info.py
  purchase_packaging/models/purchase_order_line.py
  purchase_packaging/models/stock_rule.py
  purchase_packaging/models/stock_warehouse_orderpoint.py
  purchase_packaging/models/uom.py
  purchase_packaging/readme/CONFIGURE.rst
  purchase_packaging/readme/CONTRIBUTORS.rst
  purchase_packaging/readme/DESCRIPTION.rst
  purchase_packaging/static/description/icon.png
  purchase_packaging/static/description/index.html
  purchase_packaging/tests/__init__.py
  purchase_packaging/tests/test_procurement_order.py
  purchase_packaging/tests/test_product_supplier_info.py
  purchase_packaging/tests/test_purchase_order_line.py
  purchase_packaging/views/product_supplier_info_view.xml
  purchase_packaging/views/purchase_order_line_view.xml
  purchase_packaging/views/purchase_order_view.xml
  setup/purchase_packaging/odoo/addons/purchase_packaging
  setup/purchase_packaging/setup.py
Labels: approved, bot is merging ⏳, no stale

#2379 [17.0][MIG] purchase_blanket_order
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  purchase_blanket_order/README.rst
  purchase_blanket_order/__init__.py
  purchase_blanket_order/__manifest__.py
  purchase_blanket_order/data/ir_cron.xml
  purchase_blanket_order/data/sequence.xml
  purchase_blanket_order/i18n/es.po
  purchase_blanket_order/i18n/it.po
  purchase_blanket_order/i18n/purchase_blanket_order.pot
  purchase_blanket_order/models/__init__.py
  purchase_blanket_order/models/blanket_orders.py
  purchase_blanket_order/models/purchase_config_settings.py
  purchase_blanket_order/models/purchase_order.py
  purchase_blanket_order/pyproject.toml
  purchase_blanket_order/readme/CONTRIBUTORS.md
  purchase_blanket_order/readme/DESCRIPTION.md
  purchase_blanket_order/readme/USAGE.md
  purchase_blanket_order/report/report.xml
  purchase_blanket_order/report/templates.xml
  purchase_blanket_order/security/ir.model.access.csv
  purchase_blanket_order/security/security.xml
  purchase_blanket_order/static/description/BO_actions.png
  purchase_blanket_order/static/description/BO_form.png
  purchase_blanket_order/static/description/BO_lines.png
  purchase_blanket_order/static/description/BO_menu.png
  purchase_blanket_order/static/description/PO_BOLine.png
  purchase_blanket_order/static/description/PO_from_BO.png
  purchase_blanket_order/static/description/icon.png
  purchase_blanket_order/static/description/index.html
  purchase_blanket_order/tests/__init__.py
  purchase_blanket_order/tests/test_purchase_blanket_order.py
  purchase_blanket_order/tests/test_purchase_order.py
  purchase_blanket_order/views/purchase_blanket_order_views.xml
  purchase_blanket_order/views/purchase_config_settings.xml
  purchase_blanket_order/views/purchase_order_views.xml
  purchase_blanket_order/wizard/__init__.py
  purchase_blanket_order/wizard/create_purchase_orders.py
  purchase_blanket_order/wizard/create_purchase_orders.xml
Labels: approved, bot is merging ⏳

#2412 [17.0][FIX] purchase_security: specify @api.onchange
  purchase_security/models/purchase_order.py
Labels: bot is merging ⏳

#2401 [16.0][UPD] purchase_manual_delivery: do not show incoming shipment button
  purchase_manual_delivery/__manifest__.py
  purchase_manual_delivery/views/purchase_order_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2398 [16.0][REF] purchase_request: added hook after order line creation
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: approved, bot is merging ⏳
