Repository OCA/purchase-workflow, pull requests merged in 2025-02, with the labels that each got.

#2431 [18.0][MIG] purchase_open_qty: Migration to 18.0
  purchase_open_qty/README.rst
  purchase_open_qty/__init__.py
  purchase_open_qty/__manifest__.py
  purchase_open_qty/i18n/de.po
  purchase_open_qty/i18n/es.po
  purchase_open_qty/i18n/es_MX.po
  purchase_open_qty/i18n/es_PE.po
  purchase_open_qty/i18n/fi.po
  purchase_open_qty/i18n/fr.po
  purchase_open_qty/i18n/fr_BE.po
  purchase_open_qty/i18n/gl.po
  purchase_open_qty/i18n/hr.po
  purchase_open_qty/i18n/it.po
  purchase_open_qty/i18n/nl.po
  purchase_open_qty/i18n/nl_NL.po
  purchase_open_qty/i18n/pt_BR.po
  purchase_open_qty/i18n/pt_PT.po
  purchase_open_qty/i18n/purchase_open_qty.pot
  purchase_open_qty/i18n/ro.po
  purchase_open_qty/i18n/sl.po
  purchase_open_qty/i18n/vi_VN.po
  purchase_open_qty/i18n/zh_CN.po
  purchase_open_qty/init_hook.py
  purchase_open_qty/models/__init__.py
  purchase_open_qty/models/purchase_order.py
  purchase_open_qty/models/purchase_order_line.py
  purchase_open_qty/pyproject.toml
  purchase_open_qty/readme/CONTRIBUTORS.md
  purchase_open_qty/readme/CREDITS.md
  purchase_open_qty/readme/DESCRIPTION.md
  purchase_open_qty/readme/USAGE.md
  purchase_open_qty/static/description/icon.png
  purchase_open_qty/static/description/index.html
  purchase_open_qty/tests/__init__.py
  purchase_open_qty/tests/test_purchase_open_qty.py
  purchase_open_qty/views/purchase_order_line_views.xml
  purchase_open_qty/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#2162 [FIX] purchase_request: RFQ wizard copy description toggle
  purchase_request/wizard/purchase_request_line_make_purchase_order_view.xml
Labels: approved, bot is merging ⏳

#2540 [16.0][IMP]purchase_discount: add name in th for inheritance
  purchase_discount/views/report_purchaseorder.xml
Labels: approved, bot is merging ⏳

#2192 [17.0][FIX] purchase_request: activity assigned user upon procurement cancellation
  purchase_request/models/stock_move.py
Labels: approved, bot is merging ⏳

#2482 [18][MIG] purchase_request_tier_validation: Migration to 18
  purchase_request_tier_validation/README.rst
  purchase_request_tier_validation/__init__.py
  purchase_request_tier_validation/__manifest__.py
  purchase_request_tier_validation/data/purchase_request_tier_definition.xml
  purchase_request_tier_validation/i18n/es.po
  purchase_request_tier_validation/i18n/es_EC.po
  purchase_request_tier_validation/i18n/it.po
  purchase_request_tier_validation/i18n/nl_NL.po
  purchase_request_tier_validation/i18n/purchase_request_tier_validation.pot
  purchase_request_tier_validation/i18n/zh_CN.po
  purchase_request_tier_validation/models/__init__.py
  purchase_request_tier_validation/models/purchase_request.py
  purchase_request_tier_validation/models/tier_definition.py
  purchase_request_tier_validation/pyproject.toml
  purchase_request_tier_validation/readme/CONFIGURE.md
  purchase_request_tier_validation/readme/CONTRIBUTORS.md
  purchase_request_tier_validation/readme/CREDITS.md
  purchase_request_tier_validation/readme/DESCRIPTION.md
  purchase_request_tier_validation/readme/INSTALL.md
  purchase_request_tier_validation/readme/USAGE.md
  purchase_request_tier_validation/static/description/icon.png
  purchase_request_tier_validation/static/description/index.html
  purchase_request_tier_validation/tests/__init__.py
  purchase_request_tier_validation/tests/test_purchase_request_tier_validation.py
  purchase_request_tier_validation/views/purchase_request_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2549 [18.0][FIX] vendor_transport_lead_time: fix typo in `_get_supplier_date_planned`
  vendor_transport_lead_time/models/purchase_order_line.py
Labels: bug, bot is merging ⏳

#2548 [18.0][MIG] purchase_order_uninvoiced_amount: Migration to 18.0
  purchase_order_uninvoiced_amount/README.rst
  purchase_order_uninvoiced_amount/__init__.py
  purchase_order_uninvoiced_amount/__manifest__.py
  purchase_order_uninvoiced_amount/i18n/en_US.po
  purchase_order_uninvoiced_amount/i18n/es.po
  purchase_order_uninvoiced_amount/i18n/it.po
  purchase_order_uninvoiced_amount/i18n/purchase_order_uninvoiced_amount.pot
  purchase_order_uninvoiced_amount/models/__init__.py
  purchase_order_uninvoiced_amount/models/purchase_order.py
  purchase_order_uninvoiced_amount/pyproject.toml
  purchase_order_uninvoiced_amount/readme/CONTRIBUTORS.md
  purchase_order_uninvoiced_amount/readme/DESCRIPTION.md
  purchase_order_uninvoiced_amount/static/description/icon.png
  purchase_order_uninvoiced_amount/static/description/index.html
  purchase_order_uninvoiced_amount/tests/__init__.py
  purchase_order_uninvoiced_amount/tests/test_purchase_order_uninvoiced_amount.py
  purchase_order_uninvoiced_amount/views/purchase_order_view.xml
Labels: approved, bot is merging ⏳

#2447 [18.0][MIG] purchase_tier_validation: Migration to 18.0
  purchase_tier_validation/README.rst
  purchase_tier_validation/__init__.py
  purchase_tier_validation/__manifest__.py
  purchase_tier_validation/i18n/es.po
  purchase_tier_validation/i18n/it.po
  purchase_tier_validation/i18n/purchase_tier_validation.pot
  purchase_tier_validation/i18n/zh_CN.po
  purchase_tier_validation/models/__init__.py
  purchase_tier_validation/models/purchase_order.py
  purchase_tier_validation/models/tier_definition.py
  purchase_tier_validation/pyproject.toml
  purchase_tier_validation/readme/CONFIGURE.md
  purchase_tier_validation/readme/CONTRIBUTORS.md
  purchase_tier_validation/readme/DESCRIPTION.md
  purchase_tier_validation/readme/INSTALL.md
  purchase_tier_validation/readme/USAGE.md
  purchase_tier_validation/static/description/icon.png
  purchase_tier_validation/static/description/index.html
  purchase_tier_validation/tests/__init__.py
  purchase_tier_validation/tests/test_tier_validation.py
  purchase_tier_validation/views/purchase_order_view.xml
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#2546 [18.0][MIG] purchase_invoice_plan
  purchase_invoice_plan/README.rst
  purchase_invoice_plan/__init__.py
  purchase_invoice_plan/__manifest__.py
  purchase_invoice_plan/data/purchase_data.xml
  purchase_invoice_plan/i18n/es.po
  purchase_invoice_plan/i18n/it.po
  purchase_invoice_plan/i18n/purchase_invoice_plan.pot
  purchase_invoice_plan/models/__init__.py
  purchase_invoice_plan/models/purchase_invoice_plan.py
  purchase_invoice_plan/models/purchase_order.py
  purchase_invoice_plan/pyproject.toml
  purchase_invoice_plan/readme/CONTRIBUTORS.md
  purchase_invoice_plan/readme/DESCRIPTION.md
  purchase_invoice_plan/readme/USAGE.md
  purchase_invoice_plan/security/ir.model.access.csv
  purchase_invoice_plan/static/description/icon.png
  purchase_invoice_plan/static/description/index.html
  purchase_invoice_plan/tests/__init__.py
  purchase_invoice_plan/tests/test_purchase_invoice_plan.py
  purchase_invoice_plan/views/purchase_view.xml
  purchase_invoice_plan/wizard/__init__.py
  purchase_invoice_plan/wizard/purchase_create_invoice_plan.py
  purchase_invoice_plan/wizard/purchase_create_invoice_plan_view.xml
  purchase_invoice_plan/wizard/purchase_make_planned_invoice.py
  purchase_invoice_plan/wizard/purchase_make_planned_invoice_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2519 [18.0][MIG] purchase_delivery_split_date: Migration to 18.0
  purchase_delivery_split_date/README.rst
  purchase_delivery_split_date/__init__.py
  purchase_delivery_split_date/__manifest__.py
  purchase_delivery_split_date/i18n/ca.po
  purchase_delivery_split_date/i18n/de.po
  purchase_delivery_split_date/i18n/es.po
  purchase_delivery_split_date/i18n/es_MX.po
  purchase_delivery_split_date/i18n/es_PE.po
  purchase_delivery_split_date/i18n/fi.po
  purchase_delivery_split_date/i18n/fr.po
  purchase_delivery_split_date/i18n/gl.po
  purchase_delivery_split_date/i18n/hr.po
  purchase_delivery_split_date/i18n/it.po
  purchase_delivery_split_date/i18n/nl_NL.po
  purchase_delivery_split_date/i18n/pt_BR.po
  purchase_delivery_split_date/i18n/pt_PT.po
  purchase_delivery_split_date/i18n/purchase_delivery_split_date.pot
  purchase_delivery_split_date/i18n/ro.po
  purchase_delivery_split_date/i18n/sl.po
  purchase_delivery_split_date/i18n/zh_CN.po
  purchase_delivery_split_date/models/__init__.py
  purchase_delivery_split_date/models/purchase_order.py
  purchase_delivery_split_date/models/purchase_order_line.py
  purchase_delivery_split_date/models/stock_picking.py
  purchase_delivery_split_date/pyproject.toml
  purchase_delivery_split_date/readme/CONTRIBUTORS.md
  purchase_delivery_split_date/readme/DESCRIPTION.md
  purchase_delivery_split_date/readme/HISTORY.md
  purchase_delivery_split_date/readme/USAGE.md
  purchase_delivery_split_date/static/description/icon.png
  purchase_delivery_split_date/static/description/index.html
  purchase_delivery_split_date/static/description/split_delivery.png
  purchase_delivery_split_date/tests/__init__.py
  purchase_delivery_split_date/tests/test_purchase_delivery.py
Labels: approved, ready to merge, bot is merging ⏳

#2563 [15.0][FIX] sale_purchase_secondary_unit: _merge_procurements don't sum secondary_uom_qty
  sale_purchase_secondary_unit/models/stock_rule.py
Labels: approved, bot is merging ⏳

#2551 [17.0] [MIG] purchase_mass_mail
  purchase_mass_mail/README.rst
  purchase_mass_mail/__init__.py
  purchase_mass_mail/__manifest__.py
  purchase_mass_mail/i18n/es.po
  purchase_mass_mail/i18n/it.po
  purchase_mass_mail/i18n/purchase_mass_mail.pot
  purchase_mass_mail/models/__init__.py
  purchase_mass_mail/models/purchase_order.py
  purchase_mass_mail/pyproject.toml
  purchase_mass_mail/readme/CONTRIBUTORS.md
  purchase_mass_mail/readme/DESCRIPTION.md
  purchase_mass_mail/readme/USAGE.md
  purchase_mass_mail/static/description/icon.png
  purchase_mass_mail/static/description/index.html
  purchase_mass_mail/tests/__init__.py
  purchase_mass_mail/tests/test_send_mass_mail.py
  purchase_mass_mail/view/purchase_order.xml
  purchase_mass_mail/wizards/__init__.py
  purchase_mass_mail/wizards/mail_compose_message.py
Labels: approved, ready to merge, bot is merging ⏳

#2561 [17.0][FWD][IMP] purchase_order_line_menu: Improved accessibility
  purchase_order_line_menu/views/purchase_order_line_views.xml
Labels: approved, bot is merging ⏳

#2552 [17.0][ADD]purchase_requisition_multiple_vendor: Multiple purchase alternatives using one wizard
  purchase_requisition_multiple_vendor/README.rst
  purchase_requisition_multiple_vendor/__init__.py
  purchase_requisition_multiple_vendor/__manifest__.py
  purchase_requisition_multiple_vendor/pyproject.toml
  purchase_requisition_multiple_vendor/readme/CONTRIBUTORS.md
  purchase_requisition_multiple_vendor/readme/DESCRIPTION.md
  purchase_requisition_multiple_vendor/readme/USAGE.md
  purchase_requisition_multiple_vendor/static/description/icon.png
  purchase_requisition_multiple_vendor/static/description/index.html
  purchase_requisition_multiple_vendor/tests/__init__.py
  purchase_requisition_multiple_vendor/tests/test_purchase_requisition_multiple_vendors.py
  purchase_requisition_multiple_vendor/wizard/__init__.py
  purchase_requisition_multiple_vendor/wizard/purchase_requisition_create_alternative.py
  purchase_requisition_multiple_vendor/wizard/purchase_requisition_create_alternative.xml
Labels: approved, ready to merge, bot is merging ⏳

#2568 [17.0][ADD] procurement_purchase_requisition_generation: New module
  procurement_purchase_requisition_generation/README.rst
  procurement_purchase_requisition_generation/__init__.py
  procurement_purchase_requisition_generation/__manifest__.py
  procurement_purchase_requisition_generation/i18n/es.po
  procurement_purchase_requisition_generation/i18n/procurement_purchase_requisition_generation.pot
  procurement_purchase_requisition_generation/models/__init__.py
  procurement_purchase_requisition_generation/models/product_template.py
  procurement_purchase_requisition_generation/models/purchase_requisition.py
  procurement_purchase_requisition_generation/models/stock_rule.py
  procurement_purchase_requisition_generation/pyproject.toml
  procurement_purchase_requisition_generation/readme/CONFIGURE.md
  procurement_purchase_requisition_generation/readme/CONTEXT.md
  procurement_purchase_requisition_generation/readme/CONTRIBUTORS.md
  procurement_purchase_requisition_generation/readme/DESCRIPTION.md
  procurement_purchase_requisition_generation/readme/USAGE.md
  procurement_purchase_requisition_generation/static/description/icon.png
  procurement_purchase_requisition_generation/static/description/index.html
  procurement_purchase_requisition_generation/tests/__init__.py
  procurement_purchase_requisition_generation/tests/test_procurement_purchase_requisition_generation.py
  procurement_purchase_requisition_generation/views/product_template_views.xml
  procurement_purchase_requisition_generation/views/purchase_requisition_views.xml
  procurement_purchase_requisition_generation/wizards/__init__.py
  procurement_purchase_requisition_generation/wizards/product_replenish.py
Labels: approved, bot is merging ⏳

#2569 [17.0][FIX] purchase_request: Add Markup to messages
  purchase_request/models/purchase_order.py
  purchase_request/models/purchase_request_allocation.py
  purchase_request/models/stock_move_line.py
Labels: approved, bot is merging ⏳

#2566 [16.0][MIG] purchase_order_approval_block
  purchase_order_approval_block/README.rst
  purchase_order_approval_block/__init__.py
  purchase_order_approval_block/__manifest__.py
  purchase_order_approval_block/data/purchase_exception_data.xml
  purchase_order_approval_block/i18n/es.po
  purchase_order_approval_block/i18n/fr.po
  purchase_order_approval_block/i18n/purchase_order_approval_block.pot
  purchase_order_approval_block/models/__init__.py
  purchase_order_approval_block/models/purchase_approval_block_reason.py
  purchase_order_approval_block/models/purchase_order.py
  purchase_order_approval_block/readme/CONFIGURE.rst
  purchase_order_approval_block/readme/CONTRIBUTORS.rst
  purchase_order_approval_block/readme/DESCRIPTION.rst
  purchase_order_approval_block/readme/USAGE.rst
  purchase_order_approval_block/security/ir.model.access.csv
  purchase_order_approval_block/security/purchase_order_approval_block_security.xml
  purchase_order_approval_block/static/description/icon.png
  purchase_order_approval_block/static/description/index.html
  purchase_order_approval_block/tests/__init__.py
  purchase_order_approval_block/tests/test_po_approval_block_reason.py
  purchase_order_approval_block/tests/test_purchase_order_approval_block.py
  purchase_order_approval_block/views/purchase_approval_block_reason_view.xml
  purchase_order_approval_block/views/purchase_order_view.xml
  purchase_order_approval_block/wizard/__init__.py
  purchase_order_approval_block/wizard/purchase_exception_confirm.py
  setup/purchase_order_approval_block/odoo/addons/purchase_order_approval_block
  setup/purchase_order_approval_block/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2585 [18.0][MIG] purchase_force_invoiced
  purchase_force_invoiced/README.rst
  purchase_force_invoiced/__init__.py
  purchase_force_invoiced/__manifest__.py
  purchase_force_invoiced/i18n/es.po
  purchase_force_invoiced/i18n/fr.po
  purchase_force_invoiced/i18n/it.po
  purchase_force_invoiced/i18n/purchase_force_invoiced.pot
  purchase_force_invoiced/i18n/zh_CN.po
  purchase_force_invoiced/migrations/16.0.1.0.0/post-migrate.py
  purchase_force_invoiced/model/__init__.py
  purchase_force_invoiced/model/purchase_order.py
  purchase_force_invoiced/model/purchase_order_line.py
  purchase_force_invoiced/pyproject.toml
  purchase_force_invoiced/readme/CONTRIBUTORS.md
  purchase_force_invoiced/readme/DESCRIPTION.md
  purchase_force_invoiced/readme/USAGE.md
  purchase_force_invoiced/reports/__init__.py
  purchase_force_invoiced/reports/purchase_report.py
  purchase_force_invoiced/security/res_groups_data.xml
  purchase_force_invoiced/static/description/icon.png
  purchase_force_invoiced/static/description/index.html
  purchase_force_invoiced/tests/__init__.py
  purchase_force_invoiced/tests/test_purchase_force_invoiced.py
  purchase_force_invoiced/view/purchase_order.xml
Labels: approved, bot is merging ⏳
