Repository OCA/purchase-workflow, pull requests merged in 2025-01, with the labels that each got.

#1657 [16.0][ADD] purchase_order_revision
  purchase_order_revision/README.rst
  purchase_order_revision/__init__.py
  purchase_order_revision/__manifest__.py
  purchase_order_revision/models/__init__.py
  purchase_order_revision/models/purchase_order.py
  purchase_order_revision/readme/CONTRIBUTORS.rst
  purchase_order_revision/readme/DESCRIPTION.rst
  purchase_order_revision/readme/INSTALL.rst
  purchase_order_revision/static/description/icon.png
  purchase_order_revision/static/description/index.html
  purchase_order_revision/tests/__init__.py
  purchase_order_revision/tests/test_purchase_order_revision.py
  purchase_order_revision/view/purchase_order.xml
  purchase_receipt_expectation/tests/test_purchase_receipt_expectation.py
  setup/purchase_order_revision/odoo/addons/purchase_order_revision
  setup/purchase_order_revision/setup.py
Labels: needs review, approved, bot is merging ⏳

#2417 [17.0][MIG] purchase_manual_delivery
  purchase_manual_delivery/README.rst
  purchase_manual_delivery/__init__.py
  purchase_manual_delivery/__manifest__.py
  purchase_manual_delivery/i18n/es.po
  purchase_manual_delivery/i18n/it.po
  purchase_manual_delivery/i18n/purchase_manual_delivery.pot
  purchase_manual_delivery/i18n/sl.po
  purchase_manual_delivery/migrations/17.0.1.0.0/pre-migration.py
  purchase_manual_delivery/models/__init__.py
  purchase_manual_delivery/models/product_product.py
  purchase_manual_delivery/models/purchase_order.py
  purchase_manual_delivery/models/res_company.py
  purchase_manual_delivery/models/res_config.py
  purchase_manual_delivery/pyproject.toml
  purchase_manual_delivery/readme/CONFIGURE.md
  purchase_manual_delivery/readme/CONTRIBUTORS.md
  purchase_manual_delivery/readme/DESCRIPTION.md
  purchase_manual_delivery/readme/USAGE.md
  purchase_manual_delivery/report/__init__.py
  purchase_manual_delivery/report/stock_forecasted.py
  purchase_manual_delivery/security/ir.model.access.csv
  purchase_manual_delivery/static/description/create_incoming_shipment_button.png
  purchase_manual_delivery/static/description/create_incoming_shipment_wizard.png
  purchase_manual_delivery/static/description/icon.png
  purchase_manual_delivery/static/description/index.html
  purchase_manual_delivery/static/src/purchase_manual_delivery_forecasted/forecasted_details.xml
  purchase_manual_delivery/tests/__init__.py
  purchase_manual_delivery/tests/test_purchase_manual_delivery.py
  purchase_manual_delivery/tests/test_report_forecast.py
  purchase_manual_delivery/views/purchase_order_views.xml
  purchase_manual_delivery/views/res_config_view.xml
  purchase_manual_delivery/wizard/__init__.py
  purchase_manual_delivery/wizard/create_manual_stock_picking.py
  purchase_manual_delivery/wizard/create_manual_stock_picking.xml
  purchase_request/tests/test_purchase_request_procurement.py
Labels: approved, bot is merging ⏳

#2495 [18.0][MIG] purchase_order_archive: Migration to 18.0
  purchase_order_archive/README.rst
  purchase_order_archive/__init__.py
  purchase_order_archive/__manifest__.py
  purchase_order_archive/i18n/es.po
  purchase_order_archive/i18n/it.po
  purchase_order_archive/i18n/purchase_order_archive.pot
  purchase_order_archive/i18n/zh_CN.po
  purchase_order_archive/models/__init__.py
  purchase_order_archive/models/purchase_order.py
  purchase_order_archive/pyproject.toml
  purchase_order_archive/readme/CONTRIBUTORS.md
  purchase_order_archive/readme/DESCRIPTION.md
  purchase_order_archive/readme/USAGE.md
  purchase_order_archive/setup/purchase_order_archive/odoo/addons/purchase_order_archive
  purchase_order_archive/setup/purchase_order_archive/setup.py
  purchase_order_archive/static/description/icon.png
  purchase_order_archive/static/description/index.html
  purchase_order_archive/tests/__init__.py
  purchase_order_archive/tests/test_purchase_order_archive.py
  purchase_order_archive/views/purchase_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#2434 [15.0][ADD] purchase_reception_status_line
  purchase_reception_status_line/README.rst
  purchase_reception_status_line/__init__.py
  purchase_reception_status_line/__manifest__.py
  purchase_reception_status_line/models/__init__.py
  purchase_reception_status_line/models/purchase_order.py
  purchase_reception_status_line/models/purchase_order_line.py
  purchase_reception_status_line/readme/CONTRIBUTORS.rst
  purchase_reception_status_line/readme/DESCRIPTION.rst
  purchase_reception_status_line/readme/USAGE.rst
  purchase_reception_status_line/static/description/icon.png
  purchase_reception_status_line/static/description/index.html
  purchase_reception_status_line/tests/__init__.py
  purchase_reception_status_line/tests/test_purchase_receipt_status_line.py
  purchase_reception_status_line/views/purchase_order.xml
  setup/purchase_reception_status_line/odoo/addons/purchase_reception_status_line
  setup/purchase_reception_status_line/setup.py
Labels: approved, bot is merging ⏳

#2171 [16.0] MIG purchase_quick
  purchase_quick/README.rst
  purchase_quick/__init__.py
  purchase_quick/__manifest__.py
  purchase_quick/i18n/es.po
  purchase_quick/i18n/fr.po
  purchase_quick/i18n/it.po
  purchase_quick/i18n/purchase_quick.pot
  purchase_quick/models/__init__.py
  purchase_quick/models/product_product.py
  purchase_quick/models/purchase_order.py
  purchase_quick/readme/CONTRIBUTORS.rst
  purchase_quick/readme/DESCRIPTION.rst
  purchase_quick/readme/ROADMAP.rst
  purchase_quick/readme/USAGE.rst
  purchase_quick/static/description/01_purchase_order_create.png
  purchase_quick/static/description/02_purchase_order_add_product.png
  purchase_quick/static/description/03_purchase_order_updated.png
  purchase_quick/static/description/04_purchase_order_update_product_qty.png
  purchase_quick/static/description/filter.png
  purchase_quick/static/description/icon.png
  purchase_quick/static/description/index.html
  purchase_quick/static/description/po-product.png
  purchase_quick/static/description/po.png
  purchase_quick/tests/__init__.py
  purchase_quick/tests/test_quick_purchase.py
  purchase_quick/views/product_product_view.xml
  purchase_quick/views/purchase_order_view.xml
  setup/purchase_quick/odoo/addons/purchase_quick
  setup/purchase_quick/setup.py
Labels: approved, bot is merging ⏳

#2498 [18.0][MIG] vendor_transport_lead_time: Migration to 18.0
  vendor_transport_lead_time/README.rst
  vendor_transport_lead_time/__init__.py
  vendor_transport_lead_time/__manifest__.py
  vendor_transport_lead_time/i18n/es.po
  vendor_transport_lead_time/i18n/it.po
  vendor_transport_lead_time/i18n/vendor_transport_lead_time.pot
  vendor_transport_lead_time/models/__init__.py
  vendor_transport_lead_time/models/product_supplierinfo.py
  vendor_transport_lead_time/models/purchase_order_line.py
  vendor_transport_lead_time/pyproject.toml
  vendor_transport_lead_time/readme/CONTRIBUTORS.md
  vendor_transport_lead_time/readme/CREDITS.md
  vendor_transport_lead_time/readme/DESCRIPTION.md
  vendor_transport_lead_time/readme/HISTORY.md
  vendor_transport_lead_time/report/purchase_order_template.xml
  vendor_transport_lead_time/static/description/icon.png
  vendor_transport_lead_time/static/description/index.html
  vendor_transport_lead_time/tests/__init__.py
  vendor_transport_lead_time/tests/test_delay.py
  vendor_transport_lead_time/tests/test_purchase_order.py
  vendor_transport_lead_time/views/product_supplierinfo.xml
  vendor_transport_lead_time/views/purchase_order_line.xml
Labels: approved, bot is merging ⏳

#2189 [16.0][FIX] purchase_manual_delivery: manual delivery with double validation
  .github/workflows/test.yml
  purchase_manual_delivery/models/purchase_order.py
  purchase_manual_delivery/tests/test_purchase_manual_delivery.py
Labels: bot is merging ⏳

#2472 [18.0][MIG] purchase_all_shipments: Migration to 18.0
  purchase_all_shipments/README.rst
  purchase_all_shipments/__init__.py
  purchase_all_shipments/__manifest__.py
  purchase_all_shipments/i18n/es.po
  purchase_all_shipments/i18n/it.po
  purchase_all_shipments/i18n/purchase_all_shipments.pot
  purchase_all_shipments/models/__init__.py
  purchase_all_shipments/models/purchase_order.py
  purchase_all_shipments/pyproject.toml
  purchase_all_shipments/readme/CONTRIBUTORS.md
  purchase_all_shipments/readme/DESCRIPTION.md
  purchase_all_shipments/static/description/icon.png
  purchase_all_shipments/static/description/index.html
  purchase_all_shipments/tests/__init__.py
  purchase_all_shipments/tests/test_three_step_reception.py
  purchase_all_shipments/views/purchase_order_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2468 [18.0][MIG] purchase_deposit: Migration to 18.0
  purchase_deposit/README.rst
  purchase_deposit/__init__.py
  purchase_deposit/__manifest__.py
  purchase_deposit/i18n/arp.po
  purchase_deposit/i18n/es.po
  purchase_deposit/i18n/fr.po
  purchase_deposit/i18n/it.po
  purchase_deposit/i18n/purchase_deposit.pot
  purchase_deposit/models/__init__.py
  purchase_deposit/models/account_move.py
  purchase_deposit/models/purchase.py
  purchase_deposit/models/res_company.py
  purchase_deposit/models/res_config_settings.py
  purchase_deposit/pyproject.toml
  purchase_deposit/readme/CONFIGURATION.rst
  purchase_deposit/readme/CONTRIBUTORS.md
  purchase_deposit/readme/DESCRIPTION.md
  purchase_deposit/readme/USAGE.md
  purchase_deposit/security/ir.model.access.csv
  purchase_deposit/static/description/icon.png
  purchase_deposit/static/description/index.html
  purchase_deposit/tests/__init__.py
  purchase_deposit/tests/test_purchase_deposit.py
  purchase_deposit/views/purchase_view.xml
  purchase_deposit/views/res_config_settings_views.xml
  purchase_deposit/wizard/__init__.py
  purchase_deposit/wizard/purchase_make_invoice_advance.py
  purchase_deposit/wizard/purchase_make_invoice_advance_views.xml
Labels: approved, bot is merging ⏳

#2515 [17.0][MIG] purchase_order_line_deep_sort: Migration to 17.0
  purchase_order_line_deep_sort/README.rst
  purchase_order_line_deep_sort/__init__.py
  purchase_order_line_deep_sort/__manifest__.py
  purchase_order_line_deep_sort/i18n/es.po
  purchase_order_line_deep_sort/i18n/purchase_order_line_deep_sort.pot
  purchase_order_line_deep_sort/models/__init__.py
  purchase_order_line_deep_sort/models/purchase_order.py
  purchase_order_line_deep_sort/models/res_company.py
  purchase_order_line_deep_sort/models/res_config_settings.py
  purchase_order_line_deep_sort/pyproject.toml
  purchase_order_line_deep_sort/readme/CONFIGURE.md
  purchase_order_line_deep_sort/readme/CONTRIBUTORS.md
  purchase_order_line_deep_sort/readme/DESCRIPTION.md
  purchase_order_line_deep_sort/readme/ROADMAP.md
  purchase_order_line_deep_sort/readme/USAGE.md
  purchase_order_line_deep_sort/static/description/icon.png
  purchase_order_line_deep_sort/static/description/index.html
  purchase_order_line_deep_sort/tests/__init__.py
  purchase_order_line_deep_sort/tests/test_purchase_order_line_deep_sort.py
  purchase_order_line_deep_sort/views/purchase_order_views.xml
  purchase_order_line_deep_sort/views/res_config_settings_views.xml
Labels: bot is merging ⏳

#2507 [17.0][MIG] purchase_order_line_stock_available: Migration to version 17.0
  purchase_order_line_stock_available/README.rst
  purchase_order_line_stock_available/__init__.py
  purchase_order_line_stock_available/__manifest__.py
  purchase_order_line_stock_available/i18n/es.po
  purchase_order_line_stock_available/i18n/it.po
  purchase_order_line_stock_available/i18n/pt_BR.po
  purchase_order_line_stock_available/i18n/purchase_order_line_stock_available.pot
  purchase_order_line_stock_available/i18n/sl.po
  purchase_order_line_stock_available/i18n/zh_CN.po
  purchase_order_line_stock_available/models/__init__.py
  purchase_order_line_stock_available/models/purchase.py
  purchase_order_line_stock_available/pyproject.toml
  purchase_order_line_stock_available/readme/CONTRIBUTORS.md
  purchase_order_line_stock_available/readme/DESCRIPTION.md
  purchase_order_line_stock_available/readme/USAGE.md
  purchase_order_line_stock_available/static/description/icon.png
  purchase_order_line_stock_available/static/description/index.html
  purchase_order_line_stock_available/tests/__init__.py
  purchase_order_line_stock_available/tests/test_purchase.py
  purchase_order_line_stock_available/views/purchase_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2436 [15.0][FIX] purchase_delivery_split_date: prevent error when adding a PO line on confirmed POs
  purchase_delivery_split_date/models/purchase.py
Labels: approved, ready to merge, bot is merging ⏳

#2235 [17.0][MIG] sale_purchase_force_vendor: Migration to 17.0
  sale_purchase_force_vendor/README.rst
  sale_purchase_force_vendor/__init__.py
  sale_purchase_force_vendor/__manifest__.py
  sale_purchase_force_vendor/i18n/es.po
  sale_purchase_force_vendor/i18n/it.po
  sale_purchase_force_vendor/i18n/nl.po
  sale_purchase_force_vendor/i18n/sale_purchase_force_vendor.pot
  sale_purchase_force_vendor/models/__init__.py
  sale_purchase_force_vendor/models/res_company.py
  sale_purchase_force_vendor/models/res_config_settings.py
  sale_purchase_force_vendor/models/sale_order_line.py
  sale_purchase_force_vendor/models/stock_move.py
  sale_purchase_force_vendor/pyproject.toml
  sale_purchase_force_vendor/readme/CONFIGURE.md
  sale_purchase_force_vendor/readme/CONTRIBUTORS.md
  sale_purchase_force_vendor/readme/DESCRIPTION.md
  sale_purchase_force_vendor/readme/USAGE.md
  sale_purchase_force_vendor/static/description/icon.png
  sale_purchase_force_vendor/static/description/index.html
  sale_purchase_force_vendor/tests/__init__.py
  sale_purchase_force_vendor/tests/common.py
  sale_purchase_force_vendor/tests/test_sale_purchase_force_vendor.py
  sale_purchase_force_vendor/views/res_config_settings_view.xml
  sale_purchase_force_vendor/views/sale_order_view.xml
Labels: bot is merging ⏳

#2524 [18.0][MIG] purchase_order_qty_change_no_recompute
  purchase_order_qty_change_no_recompute/README.rst
  purchase_order_qty_change_no_recompute/__init__.py
  purchase_order_qty_change_no_recompute/__manifest__.py
  purchase_order_qty_change_no_recompute/i18n/es.po
  purchase_order_qty_change_no_recompute/i18n/it.po
  purchase_order_qty_change_no_recompute/i18n/purchase_order_qty_change_no_recompute.pot
  purchase_order_qty_change_no_recompute/monkeypatching.py
  purchase_order_qty_change_no_recompute/pyproject.toml
  purchase_order_qty_change_no_recompute/readme/CONTRIBUTORS.md
  purchase_order_qty_change_no_recompute/readme/DESCRIPTION.md
  purchase_order_qty_change_no_recompute/readme/USAGE.md
  purchase_order_qty_change_no_recompute/static/description/icon.png
  purchase_order_qty_change_no_recompute/static/description/index.html
  purchase_order_qty_change_no_recompute/tests/__init__.py
  purchase_order_qty_change_no_recompute/tests/test_purchase_order_qty_change.py
Labels: approved, bot is merging ⏳

#2506 [18.0][MIG] purchase_exception: Migration to 18.0
  purchase_exception/README.rst
  purchase_exception/__init__.py
  purchase_exception/__manifest__.py
  purchase_exception/data/purchase_exception_data.xml
  purchase_exception/i18n/es.po
  purchase_exception/i18n/fr.po
  purchase_exception/i18n/it.po
  purchase_exception/i18n/purchase_exception.pot
  purchase_exception/i18n/zh_CN.po
  purchase_exception/models/__init__.py
  purchase_exception/models/exception_rule.py
  purchase_exception/models/purchase.py
  purchase_exception/models/purchase_line.py
  purchase_exception/pyproject.toml
  purchase_exception/readme/CONTRIBUTORS.md
  purchase_exception/readme/CREDITS.md
  purchase_exception/readme/DESCRIPTION.md
  purchase_exception/security/ir.model.access.csv
  purchase_exception/static/description/icon.png
  purchase_exception/static/description/index.html
  purchase_exception/tests/__init__.py
  purchase_exception/tests/test_purchase_exception.py
  purchase_exception/views/purchase_view.xml
  purchase_exception/wizard/__init__.py
  purchase_exception/wizard/purchase_exception_confirm.py
  purchase_exception/wizard/purchase_exception_confirm_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2533 [16.0][FIX] purchase_security: Compute field correctly and prevent conflicts with other modules
  purchase_security/models/purchase_order.py
Labels: bot is merging ⏳

#2355 [17.0][MIG] purchase_fop_shipping: Migration to 17.0
  purchase_fop_shipping/README.rst
  purchase_fop_shipping/__init__.py
  purchase_fop_shipping/__manifest__.py
  purchase_fop_shipping/i18n/de.po
  purchase_fop_shipping/i18n/es.po
  purchase_fop_shipping/i18n/es_PE.po
  purchase_fop_shipping/i18n/fr.po
  purchase_fop_shipping/i18n/fr_BE.po
  purchase_fop_shipping/i18n/gl.po
  purchase_fop_shipping/i18n/hr.po
  purchase_fop_shipping/i18n/it.po
  purchase_fop_shipping/i18n/nl.po
  purchase_fop_shipping/i18n/nl_NL.po
  purchase_fop_shipping/i18n/pt_BR.po
  purchase_fop_shipping/i18n/purchase_fop_shipping.pot
  purchase_fop_shipping/i18n/ro.po
  purchase_fop_shipping/i18n/sl.po
  purchase_fop_shipping/i18n/vi_VN.po
  purchase_fop_shipping/models/__init__.py
  purchase_fop_shipping/models/partner.py
  purchase_fop_shipping/models/purchase.py
  purchase_fop_shipping/pyproject.toml
  purchase_fop_shipping/security/res_groups.xml
  purchase_fop_shipping/static/description/icon.png
  purchase_fop_shipping/tests/__init__.py
  purchase_fop_shipping/tests/test_fop_shipping.py
  purchase_fop_shipping/views/purchase_order.xml
  purchase_fop_shipping/views/res_partner.xml
Labels: approved, bot is merging ⏳
