Repository OCA/purchase-workflow, pull requests merged in 2025-07, with the labels that each got.

#2744 [15.0][IMP] sale_purchase_secondary_unit: Move method to sale_stock_secondary_unit
  sale_purchase_secondary_unit/models/stock_rule.py
Labels: approved, bot is merging ⏳

#2693 [18.0][IMP] purchase_invoice_plan: compute name display in invoice plan
  purchase_invoice_plan/models/purchase_invoice_plan.py
  purchase_invoice_plan/tests/test_purchase_invoice_plan.py
Labels: approved, ready to merge, bot is merging ⏳

#2745 [18.0][MIG] product_supplierinfo_purchase_contact: Migration to 18.0
  product_supplierinfo_purchase_contact/README.rst
  product_supplierinfo_purchase_contact/__init__.py
  product_supplierinfo_purchase_contact/__manifest__.py
  product_supplierinfo_purchase_contact/i18n/es.po
  product_supplierinfo_purchase_contact/i18n/it.po
  product_supplierinfo_purchase_contact/i18n/product_supplierinfo_purchase_contact.pot
  product_supplierinfo_purchase_contact/models/__init__.py
  product_supplierinfo_purchase_contact/models/product_supplierinfo.py
  product_supplierinfo_purchase_contact/models/stock_rule.py
  product_supplierinfo_purchase_contact/pyproject.toml
  product_supplierinfo_purchase_contact/readme/CONTEXT.md
  product_supplierinfo_purchase_contact/readme/CONTRIBUTORS.md
  product_supplierinfo_purchase_contact/readme/DESCRIPTION.md
  product_supplierinfo_purchase_contact/readme/USAGE.md
  product_supplierinfo_purchase_contact/static/description/icon.png
  product_supplierinfo_purchase_contact/static/description/index.html
  product_supplierinfo_purchase_contact/tests/__init__.py
  product_supplierinfo_purchase_contact/tests/test_stock_rule.py
  product_supplierinfo_purchase_contact/views/product_supplierinfo_view.xml
Labels: approved, bot is merging ⏳

#2483 [18.0][MIG] purchase_no_rfq: Migration to 18.0
  purchase_no_rfq/README.rst
  purchase_no_rfq/__init__.py
  purchase_no_rfq/__manifest__.py
  purchase_no_rfq/hooks.py
  purchase_no_rfq/i18n/es.po
  purchase_no_rfq/i18n/fr.po
  purchase_no_rfq/i18n/it.po
  purchase_no_rfq/i18n/pt_BR.po
  purchase_no_rfq/i18n/purchase_no_rfq.pot
  purchase_no_rfq/i18n/sv.po
  purchase_no_rfq/models/__init__.py
  purchase_no_rfq/models/purchase_order.py
  purchase_no_rfq/pyproject.toml
  purchase_no_rfq/readme/CONTRIBUTORS.md
  purchase_no_rfq/readme/DESCRIPTION.md
  purchase_no_rfq/reports/ir_actions_report.xml
  purchase_no_rfq/reports/purchase_order_template.xml
  purchase_no_rfq/static/description/icon.png
  purchase_no_rfq/static/description/index.html
  purchase_no_rfq/static/description/purchase_order_form.png
  purchase_no_rfq/static/description/purchase_order_tree.png
  purchase_no_rfq/views/view_purchase_order.xml
Labels: approved, bot is merging ⏳

#2768 [IMP] purchase_no_rfq: Complete migration to 17.0
  purchase_no_rfq/README.rst
  purchase_no_rfq/hooks.py
  purchase_no_rfq/models/purchase_order.py
  purchase_no_rfq/readme/CONTRIBUTORS.md
  purchase_no_rfq/static/description/index.html
  purchase_no_rfq/views/view_purchase_order.xml
Labels: bot is merging ⏳
