Repository OCA/purchase-workflow, pull requests merged in 2025-08, with the labels that each got.

#2763 [18.0][MIG] purchase_order_line_original_date: Migration to 18.0
  purchase_order_line_original_date/README.rst
  purchase_order_line_original_date/__init__.py
  purchase_order_line_original_date/__manifest__.py
  purchase_order_line_original_date/i18n/purchase_order_line_original_date.pot
  purchase_order_line_original_date/models/__init__.py
  purchase_order_line_original_date/models/purchase_order.py
  purchase_order_line_original_date/models/purchase_order_line.py
  purchase_order_line_original_date/pyproject.toml
  purchase_order_line_original_date/readme/CONTRIBUTORS.md
  purchase_order_line_original_date/readme/DESCRIPTION.md
  purchase_order_line_original_date/readme/USAGE.md
  purchase_order_line_original_date/static/description/icon.png
  purchase_order_line_original_date/static/description/index.html
  purchase_order_line_original_date/tests/__init__.py
  purchase_order_line_original_date/tests/test_purchase_order_line_original_date.py
  purchase_order_line_original_date/views/purchase_order_line_views.xml
  purchase_order_line_original_date/views/purchase_order_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2764 [18.0][MIG] purchase_representative: Migration to 18.0
  purchase_representative/README.rst
  purchase_representative/__init__.py
  purchase_representative/__manifest__.py
  purchase_representative/i18n/purchase_representative.pot
  purchase_representative/models/__init__.py
  purchase_representative/models/stock_rule.py
  purchase_representative/pyproject.toml
  purchase_representative/readme/CONTRIBUTORS.md
  purchase_representative/readme/DESCRIPTION.md
  purchase_representative/readme/USAGE.md
  purchase_representative/static/description/icon.png
  purchase_representative/static/description/index.html
  purchase_representative/tests/__init__.py
  purchase_representative/tests/test_purchase_representative.py
Labels: approved, ready to merge, bot is merging ⏳

#2407 [16.0][MIG] purchase_fully_invoiced: Migration to v16
  purchase_fully_invoiced/README.rst
  purchase_fully_invoiced/__init__.py
  purchase_fully_invoiced/__manifest__.py
  purchase_fully_invoiced/i18n/purchase_fully_invoiced.pot
  purchase_fully_invoiced/models/__init__.py
  purchase_fully_invoiced/models/purchase.py
  purchase_fully_invoiced/readme/CONTRIBUTORS.rst
  purchase_fully_invoiced/readme/DESCRIPTION.rst
  purchase_fully_invoiced/readme/USAGE.rst
  purchase_fully_invoiced/static/description/icon.png
  purchase_fully_invoiced/static/description/index.html
  purchase_fully_invoiced/tests/__init__.py
  purchase_fully_invoiced/tests/test_purchase_fully_invoiced.py
  purchase_fully_invoiced/views/purchase_views.xml
  setup/purchase_fully_invoiced/odoo/addons/purchase_fully_invoiced
  setup/purchase_fully_invoiced/setup.py
Labels: approved, bot is merging ⏳

#2408 [16.0][MIG] purchase_fully_received: Migration to v16
  purchase_fully_received/README.rst
  purchase_fully_received/__init__.py
  purchase_fully_received/__manifest__.py
  purchase_fully_received/i18n/purchase_fully_received.pot
  purchase_fully_received/models/__init__.py
  purchase_fully_received/models/purchase.py
  purchase_fully_received/readme/CONTRIBUTORS.rst
  purchase_fully_received/readme/DESCRIPTION.rst
  purchase_fully_received/readme/USAGE.rst
  purchase_fully_received/static/description/icon.png
  purchase_fully_received/static/description/index.html
  purchase_fully_received/tests/__init__.py
  purchase_fully_received/tests/test_purchase_fully_received.py
  purchase_fully_received/views/purchase_views.xml
  setup/purchase_fully_received/odoo/addons/purchase_fully_received
  setup/purchase_fully_received/setup.py
Labels: bot is merging ⏳

#2624 [18.0][MIG] purchase_stock_manual_currency: Migration to 18.0
  purchase_stock_manual_currency/README.rst
  purchase_stock_manual_currency/__init__.py
  purchase_stock_manual_currency/__manifest__.py
  purchase_stock_manual_currency/i18n/purchase_stock_manual_currency.pot
  purchase_stock_manual_currency/models/__init__.py
  purchase_stock_manual_currency/models/stock_move.py
  purchase_stock_manual_currency/pyproject.toml
  purchase_stock_manual_currency/readme/CONTRIBUTORS.md
  purchase_stock_manual_currency/readme/DESCRIPTION.md
  purchase_stock_manual_currency/static/description/icon.png
  purchase_stock_manual_currency/static/description/index.html
  purchase_stock_manual_currency/tests/__init__.py
  purchase_stock_manual_currency/tests/test_purchase_stock_manual_currency.py
Labels: approved, bot is merging ⏳

#2695 [18.0][MIG] purchase_work_acceptance_invoice_plan
  purchase_work_acceptance_invoice_plan/README.rst
  purchase_work_acceptance_invoice_plan/__init__.py
  purchase_work_acceptance_invoice_plan/__manifest__.py
  purchase_work_acceptance_invoice_plan/data/server_action.xml
  purchase_work_acceptance_invoice_plan/i18n/purchase_work_acceptance_invoice_plan.pot
  purchase_work_acceptance_invoice_plan/models/__init__.py
  purchase_work_acceptance_invoice_plan/models/purchase.py
  purchase_work_acceptance_invoice_plan/models/work_acceptance.py
  purchase_work_acceptance_invoice_plan/pyproject.toml
  purchase_work_acceptance_invoice_plan/readme/CONTRIBUTORS.md
  purchase_work_acceptance_invoice_plan/readme/DESCRIPTION.md
  purchase_work_acceptance_invoice_plan/readme/USAGE.md
  purchase_work_acceptance_invoice_plan/security/ir.model.access.csv
  purchase_work_acceptance_invoice_plan/static/description/icon.png
  purchase_work_acceptance_invoice_plan/static/description/index.html
  purchase_work_acceptance_invoice_plan/tests/__init__.py
  purchase_work_acceptance_invoice_plan/tests/test_purchase_work_acceptance_invoice_plan.py
  purchase_work_acceptance_invoice_plan/views/purchase_views.xml
  purchase_work_acceptance_invoice_plan/views/work_acceptance_view.xml
  purchase_work_acceptance_invoice_plan/wizard/__init__.py
  purchase_work_acceptance_invoice_plan/wizard/select_work_acceptance_invoice_plan_wizard.py
  purchase_work_acceptance_invoice_plan/wizard/select_work_acceptance_invoice_plan_wizard_views.xml
  purchase_work_acceptance_invoice_plan/wizard/select_work_acceptance_wizard.py
Labels: approved, bot is merging ⏳

#2775 [16.0][FIX] purchase_blanket_order: use env.company as default company_id
  purchase_blanket_order/models/blanket_orders.py
Labels: approved, bot is merging ⏳
