Repository OCA/purchase-workflow, pull requests merged in 2025-06, with the labels that each got.

#2646 [16.0][IMP] purchase_lot: remove sale_order_lot_selection dependency
  purchase_lot/README.rst
  purchase_lot/__manifest__.py
  purchase_lot/models/purchase_order_line.py
  purchase_lot/pyproject.toml
  purchase_lot/readme/DESCRIPTION.rst
  purchase_lot/static/description/index.html
  purchase_lot/tests/test_purchase_lot.py
  purchase_lot/views/purchase_order_view.xml
Labels: approved, bot is merging ⏳

#2623 [18.0][MIG] purchase_manual_currency: Migration to 18.0
  purchase_manual_currency/README.rst
  purchase_manual_currency/__init__.py
  purchase_manual_currency/__manifest__.py
  purchase_manual_currency/i18n/es.po
  purchase_manual_currency/i18n/purchase_manual_currency.pot
  purchase_manual_currency/models/__init__.py
  purchase_manual_currency/models/purchase.py
  purchase_manual_currency/models/purchase_order_line.py
  purchase_manual_currency/models/res_company.py
  purchase_manual_currency/models/res_config_settings.py
  purchase_manual_currency/pyproject.toml
  purchase_manual_currency/readme/CONTRIBUTORS.md
  purchase_manual_currency/readme/DESCRIPTION.md
  purchase_manual_currency/readme/USAGE.md
  purchase_manual_currency/static/description/icon.png
  purchase_manual_currency/static/description/index.html
  purchase_manual_currency/tests/__init__.py
  purchase_manual_currency/tests/test_purchase_manual_currency.py
  purchase_manual_currency/views/purchase_views.xml
  purchase_manual_currency/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#2692 [18.0][MIG] purchase_tag: Migration to 18.0
  purchase_tag/README.rst
  purchase_tag/__init__.py
  purchase_tag/__manifest__.py
  purchase_tag/i18n/es.po
  purchase_tag/i18n/it.po
  purchase_tag/i18n/pt_BR.po
  purchase_tag/i18n/purchase_tag.pot
  purchase_tag/models/__init__.py
  purchase_tag/models/purchase_order.py
  purchase_tag/models/purchase_tag.py
  purchase_tag/pyproject.toml
  purchase_tag/readme/CONTRIBUTORS.md
  purchase_tag/readme/DESCRIPTION.md
  purchase_tag/readme/USAGE.md
  purchase_tag/security/ir.model.access.csv
  purchase_tag/static/description/icon.png
  purchase_tag/static/description/index.html
  purchase_tag/tests/__init__.py
  purchase_tag/tests/test_purchase_tag.py
  purchase_tag/views/purchase_tag_view.xml
  purchase_tag/views/purchase_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2700 [ADD] product_supplierinfo_update_price: New module
  product_supplierinfo_update_price/README.rst
  product_supplierinfo_update_price/__init__.py
  product_supplierinfo_update_price/__manifest__.py
  product_supplierinfo_update_price/models/__init__.py
  product_supplierinfo_update_price/models/purchase_order_line.py
  product_supplierinfo_update_price/readme/CONTRIBUTORS.md
  product_supplierinfo_update_price/readme/DESCRIPTION.md
  product_supplierinfo_update_price/readme/USAGE.md
  product_supplierinfo_update_price/static/description/icon.png
  product_supplierinfo_update_price/static/description/index.html
  product_supplierinfo_update_price/tests/__init__.py
  product_supplierinfo_update_price/tests/test_purchase_order_line.py
  product_supplierinfo_update_price/views/purchase_views.xml
  setup/product_supplierinfo_update_price/odoo/addons/product_supplierinfo_update_price
  setup/product_supplierinfo_update_price/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2168 [16.0][IMP] purchase_packaging_level_qty store total_transport_qty
  purchase_packaging_level_qty/models/purchase_order.py
  purchase_packaging_level_qty/tests/test_purchase_packaging_level_qty.py
Labels: bot is merging ⏳

#2462 [18.0][MIG] purchase_order_general_discount: Migration to 18.0
  purchase_order_general_discount/README.rst
  purchase_order_general_discount/__init__.py
  purchase_order_general_discount/__manifest__.py
  purchase_order_general_discount/i18n/es.po
  purchase_order_general_discount/i18n/it.po
  purchase_order_general_discount/i18n/pt.po
  purchase_order_general_discount/i18n/purchase_order_general_discount.pot
  purchase_order_general_discount/models/__init__.py
  purchase_order_general_discount/models/purchase_order.py
  purchase_order_general_discount/models/res_company.py
  purchase_order_general_discount/models/res_config_settings.py
  purchase_order_general_discount/models/res_partner.py
  purchase_order_general_discount/pyproject.toml
  purchase_order_general_discount/readme/CONFIGURE.md
  purchase_order_general_discount/readme/CONTRIBUTORS.md
  purchase_order_general_discount/readme/DESCRIPTION.md
  purchase_order_general_discount/readme/USAGE.md
  purchase_order_general_discount/static/description/icon.png
  purchase_order_general_discount/static/description/index.html
  purchase_order_general_discount/tests/__init__.py
  purchase_order_general_discount/tests/test_purchase_order_general_discount.py
  purchase_order_general_discount/views/purchase_order_view.xml
  purchase_order_general_discount/views/res_config_view.xml
  purchase_order_general_discount/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#2486 [18.0][MIG] purchase_warn_message: Migration to 18.0
  purchase_warn_message/README.rst
  purchase_warn_message/__init__.py
  purchase_warn_message/__manifest__.py
  purchase_warn_message/i18n/es.po
  purchase_warn_message/i18n/it.po
  purchase_warn_message/i18n/purchase_warn_message.pot
  purchase_warn_message/models/__init__.py
  purchase_warn_message/models/purchase_order.py
  purchase_warn_message/pyproject.toml
  purchase_warn_message/readme/CONTRIBUTORS.md
  purchase_warn_message/readme/DESCRIPTION.md
  purchase_warn_message/static/description/icon.png
  purchase_warn_message/static/description/index.html
  purchase_warn_message/tests/__init__.py
  purchase_warn_message/tests/test_purchase_warn_message.py
  purchase_warn_message/views/purchase_order_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2527 [MIG] purchase_receipt_expectation: Migration to 18.0
  purchase_receipt_expectation/README.rst
  purchase_receipt_expectation/__init__.py
  purchase_receipt_expectation/__manifest__.py
  purchase_receipt_expectation/i18n/fr.po
  purchase_receipt_expectation/i18n/purchase_receipt_expectation.pot
  purchase_receipt_expectation/models/__init__.py
  purchase_receipt_expectation/models/purchase_order.py
  purchase_receipt_expectation/pyproject.toml
  purchase_receipt_expectation/readme/CONTRIBUTORS.md
  purchase_receipt_expectation/readme/DESCRIPTION.md
  purchase_receipt_expectation/readme/USAGE.md
  purchase_receipt_expectation/static/description/icon.png
  purchase_receipt_expectation/static/description/index.html
  purchase_receipt_expectation/tests/__init__.py
  purchase_receipt_expectation/tests/test_purchase_receipt_expectation.py
  purchase_receipt_expectation/views/purchase_order.xml
Labels: approved, bot is merging ⏳

#2271 [17.0][MIG] purchase_order_product_recommendation
  purchase_order_product_recommendation/README.rst
  purchase_order_product_recommendation/__init__.py
  purchase_order_product_recommendation/__manifest__.py
  purchase_order_product_recommendation/i18n/es.po
  purchase_order_product_recommendation/i18n/it.po
  purchase_order_product_recommendation/i18n/pt_BR.po
  purchase_order_product_recommendation/i18n/purchase_order_product_recommendation.pot
  purchase_order_product_recommendation/pyproject.toml
  purchase_order_product_recommendation/readme/CONTRIBUTORS.md
  purchase_order_product_recommendation/readme/DESCRIPTION.md
  purchase_order_product_recommendation/readme/USAGE.md
  purchase_order_product_recommendation/security/ir.model.access.csv
  purchase_order_product_recommendation/static/description/icon.png
  purchase_order_product_recommendation/static/description/index.html
  purchase_order_product_recommendation/tests/__init__.py
  purchase_order_product_recommendation/tests/test_recommendation.py
  purchase_order_product_recommendation/views/purchase_order_view.xml
  purchase_order_product_recommendation/wizards/__init__.py
  purchase_order_product_recommendation/wizards/purchase_order_recommendation.py
  purchase_order_product_recommendation/wizards/purchase_order_recommendation_view.xml
Labels: approved, bot is merging ⏳

#2554 [18.0][MIG] purchase_sale_link_by_origin: Migration to version 18.0
  purchase_sale_link_by_origin/README.rst
  purchase_sale_link_by_origin/__init__.py
  purchase_sale_link_by_origin/__manifest__.py
  purchase_sale_link_by_origin/i18n/it.po
  purchase_sale_link_by_origin/i18n/purchase_sale_link_by_origin.pot
  purchase_sale_link_by_origin/models/__init__.py
  purchase_sale_link_by_origin/models/purchase_order.py
  purchase_sale_link_by_origin/models/sale_order.py
  purchase_sale_link_by_origin/pyproject.toml
  purchase_sale_link_by_origin/readme/CONTRIBUTORS.md
  purchase_sale_link_by_origin/readme/CREDITS.md
  purchase_sale_link_by_origin/readme/DESCRIPTION.md
  purchase_sale_link_by_origin/static/description/icon.png
  purchase_sale_link_by_origin/static/description/index.html
  purchase_sale_link_by_origin/tests/__init__.py
  purchase_sale_link_by_origin/tests/test_sale_purchase.py
Labels: bot is merging ⏳

#2019 [16.0][FIX] purchase_request: fix report
  purchase_request/models/purchase_request_line.py
  purchase_request/reports/report_purchase_request.xml
Labels: approved, bot is merging ⏳, stale

#2550 [17.0][MIG] purchase_requisition_order_remaining_qty: Migration to 17.0
  purchase_requisition_order_remaining_qty/README.rst
  purchase_requisition_order_remaining_qty/__init__.py
  purchase_requisition_order_remaining_qty/__manifest__.py
  purchase_requisition_order_remaining_qty/i18n/es.po
  purchase_requisition_order_remaining_qty/i18n/purchase_requisition_order_remaining_qty.pot
  purchase_requisition_order_remaining_qty/models/__init__.py
  purchase_requisition_order_remaining_qty/models/purchase_order.py
  purchase_requisition_order_remaining_qty/models/purchase_requisition_line.py
  purchase_requisition_order_remaining_qty/models/purchase_requisition_type.py
  purchase_requisition_order_remaining_qty/pyproject.toml
  purchase_requisition_order_remaining_qty/readme/CONFIGURE.md
  purchase_requisition_order_remaining_qty/readme/CONTRIBUTORS.md
  purchase_requisition_order_remaining_qty/readme/DESCRIPTION.md
  purchase_requisition_order_remaining_qty/readme/USAGE.md
  purchase_requisition_order_remaining_qty/static/description/icon.png
  purchase_requisition_order_remaining_qty/static/description/index.html
  purchase_requisition_order_remaining_qty/tests/__init__.py
  purchase_requisition_order_remaining_qty/tests/test_purchase_requisition_order_remaining_qty.py
  purchase_requisition_order_remaining_qty/views/purchase_requisition_view.xml
Labels: approved, bot is merging ⏳

#2423 [17.0][MIG] purchase_order_general_discount: Migration to 17.0
  purchase_order_general_discount/README.rst
  purchase_order_general_discount/__init__.py
  purchase_order_general_discount/__manifest__.py
  purchase_order_general_discount/i18n/es.po
  purchase_order_general_discount/i18n/it.po
  purchase_order_general_discount/i18n/pt.po
  purchase_order_general_discount/i18n/purchase_order_general_discount.pot
  purchase_order_general_discount/models/__init__.py
  purchase_order_general_discount/models/purchase_order.py
  purchase_order_general_discount/models/res_company.py
  purchase_order_general_discount/models/res_config_settings.py
  purchase_order_general_discount/models/res_partner.py
  purchase_order_general_discount/pyproject.toml
  purchase_order_general_discount/readme/CONFIGURE.md
  purchase_order_general_discount/readme/CONTRIBUTORS.md
  purchase_order_general_discount/readme/DESCRIPTION.md
  purchase_order_general_discount/readme/USAGE.md
  purchase_order_general_discount/static/description/icon.png
  purchase_order_general_discount/static/description/index.html
  purchase_order_general_discount/tests/__init__.py
  purchase_order_general_discount/tests/test_purchase_order_general_discount.py
  purchase_order_general_discount/views/purchase_order_view.xml
  purchase_order_general_discount/views/res_config_view.xml
  purchase_order_general_discount/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#2329 [16.0][MIG] purchase_work_acceptance_evaluation
  purchase_work_acceptance_evaluation/README.rst
  purchase_work_acceptance_evaluation/__init__.py
  purchase_work_acceptance_evaluation/__manifest__.py
  purchase_work_acceptance_evaluation/demo/evaluation_data.xml
  purchase_work_acceptance_evaluation/i18n/es.po
  purchase_work_acceptance_evaluation/i18n/purchase_work_acceptance_evaluation.pot
  purchase_work_acceptance_evaluation/models/__init__.py
  purchase_work_acceptance_evaluation/models/res_config_settings.py
  purchase_work_acceptance_evaluation/models/work_acceptance.py
  purchase_work_acceptance_evaluation/models/work_acceptance_evaluation.py
  purchase_work_acceptance_evaluation/readme/CONFIGURE.rst
  purchase_work_acceptance_evaluation/readme/CONTRIBUTORS.rst
  purchase_work_acceptance_evaluation/readme/DESCRIPTION.rst
  purchase_work_acceptance_evaluation/readme/USAGE.rst
  purchase_work_acceptance_evaluation/report/__init__.py
  purchase_work_acceptance_evaluation/report/work_acceptance_evaluation_report.py
  purchase_work_acceptance_evaluation/report/work_acceptance_evaluation_report.xml
  purchase_work_acceptance_evaluation/security/ir.model.access.csv
  purchase_work_acceptance_evaluation/security/security.xml
  purchase_work_acceptance_evaluation/static/description/icon.png
  purchase_work_acceptance_evaluation/static/description/index.html
  purchase_work_acceptance_evaluation/tests/__init__.py
  purchase_work_acceptance_evaluation/tests/test_purchase_work_acceptance_evaluation.py
  purchase_work_acceptance_evaluation/views/res_config_settings_views.xml
  purchase_work_acceptance_evaluation/views/work_acceptance_evaluation_views.xml
  purchase_work_acceptance_evaluation/views/work_acceptance_views.xml
  setup/purchase_work_acceptance_evaluation/odoo/addons/purchase_work_acceptance_evaluation
  setup/purchase_work_acceptance_evaluation/setup.py
Labels: approved, bot is merging ⏳

#2313 [17.0] [MIG] procurement_purchase_sale_no_grouping: Migration to 17.0
  procurement_purchase_sale_no_grouping/README.rst
  procurement_purchase_sale_no_grouping/__init__.py
  procurement_purchase_sale_no_grouping/__manifest__.py
  procurement_purchase_sale_no_grouping/i18n/procurement_purchase_sale_no_grouping.pot
  procurement_purchase_sale_no_grouping/models/__init__.py
  procurement_purchase_sale_no_grouping/models/purchase_order.py
  procurement_purchase_sale_no_grouping/models/sale_order.py
  procurement_purchase_sale_no_grouping/pyproject.toml
  procurement_purchase_sale_no_grouping/readme/CONFIGURE.md
  procurement_purchase_sale_no_grouping/readme/CONTRIBUTORS.md
  procurement_purchase_sale_no_grouping/readme/DESCRIPTION.md
  procurement_purchase_sale_no_grouping/static/description/icon.png
  procurement_purchase_sale_no_grouping/static/description/index.html
  procurement_purchase_sale_no_grouping/tests/__init__.py
  procurement_purchase_sale_no_grouping/tests/test_procurement_purchase_no_grouping.py
Labels: approved, bot is merging ⏳

#2503 [18.0][MIG] purchase_force_invoiced_quantity: Migration to 18.0
  purchase_force_invoiced_quantity/README.rst
  purchase_force_invoiced_quantity/__init__.py
  purchase_force_invoiced_quantity/__manifest__.py
  purchase_force_invoiced_quantity/demo/demo_product.xml
  purchase_force_invoiced_quantity/demo/demo_purchase_order.xml
  purchase_force_invoiced_quantity/i18n/it.po
  purchase_force_invoiced_quantity/i18n/purchase_force_invoiced_quantity.pot
  purchase_force_invoiced_quantity/models/__init__.py
  purchase_force_invoiced_quantity/models/purchase_order_line.py
  purchase_force_invoiced_quantity/pyproject.toml
  purchase_force_invoiced_quantity/readme/CONFIGURE.md
  purchase_force_invoiced_quantity/readme/CONTEXT.md
  purchase_force_invoiced_quantity/readme/CONTRIBUTORS.md
  purchase_force_invoiced_quantity/readme/DESCRIPTION.md
  purchase_force_invoiced_quantity/readme/USAGE.md
  purchase_force_invoiced_quantity/static/description/icon.png
  purchase_force_invoiced_quantity/static/description/index.html
  purchase_force_invoiced_quantity/tests/__init__.py
  purchase_force_invoiced_quantity/tests/test_purchase_force_invoiced_quantity.py
  purchase_force_invoiced_quantity/views/purchase_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#2709 [18.0][MIG] purchase_order_line_sequence: Migration to 18.0
  purchase_order_line_sequence/README.rst
  purchase_order_line_sequence/__init__.py
  purchase_order_line_sequence/__manifest__.py
  purchase_order_line_sequence/i18n/de.po
  purchase_order_line_sequence/i18n/es.po
  purchase_order_line_sequence/i18n/fr.po
  purchase_order_line_sequence/i18n/purchase_order_line_sequence.pot
  purchase_order_line_sequence/models/__init__.py
  purchase_order_line_sequence/models/account_move_line.py
  purchase_order_line_sequence/models/purchase.py
  purchase_order_line_sequence/models/purchase_line.py
  purchase_order_line_sequence/models/stock_move.py
  purchase_order_line_sequence/pyproject.toml
  purchase_order_line_sequence/readme/CONTRIBUTORS.md
  purchase_order_line_sequence/readme/DESCRIPTION.md
  purchase_order_line_sequence/readme/ROADMAP.md
  purchase_order_line_sequence/readme/USAGE.md
  purchase_order_line_sequence/static/description/icon.png
  purchase_order_line_sequence/static/description/index.html
  purchase_order_line_sequence/tests/__init__.py
  purchase_order_line_sequence/tests/test_po_lines_sequence.py
  purchase_order_line_sequence/views/account_move_view.xml
  purchase_order_line_sequence/views/purchase_view.xml
  purchase_order_line_sequence/views/report_invoice.xml
  purchase_order_line_sequence/views/report_purchaseorder.xml
  purchase_order_line_sequence/views/report_purchasequotation.xml
Labels: approved, ready to merge, bot is merging ⏳

#2588 [18.0][MIG] purchase_work_acceptance
  purchase_work_acceptance/README.rst
  purchase_work_acceptance/__init__.py
  purchase_work_acceptance/__manifest__.py
  purchase_work_acceptance/data/work_acceptance_sequence.xml
  purchase_work_acceptance/i18n/es.po
  purchase_work_acceptance/i18n/it.po
  purchase_work_acceptance/i18n/purchase_work_acceptance.pot
  purchase_work_acceptance/models/__init__.py
  purchase_work_acceptance/models/account_move.py
  purchase_work_acceptance/models/purchase.py
  purchase_work_acceptance/models/res_config_settings.py
  purchase_work_acceptance/models/stock_picking.py
  purchase_work_acceptance/models/work_acceptance.py
  purchase_work_acceptance/pyproject.toml
  purchase_work_acceptance/readme/CONFIGURE.md
  purchase_work_acceptance/readme/CONTRIBUTORS.md
  purchase_work_acceptance/readme/DESCRIPTION.md
  purchase_work_acceptance/readme/USAGE.md
  purchase_work_acceptance/security/ir.model.access.csv
  purchase_work_acceptance/security/security.xml
  purchase_work_acceptance/static/description/icon.png
  purchase_work_acceptance/static/description/index.html
  purchase_work_acceptance/tests/__init__.py
  purchase_work_acceptance/tests/test_purchase_work_acceptance.py
  purchase_work_acceptance/views/account_move_views.xml
  purchase_work_acceptance/views/purchase_views.xml
  purchase_work_acceptance/views/res_config_settings_views.xml
  purchase_work_acceptance/views/stock_picking_type_views.xml
  purchase_work_acceptance/views/stock_picking_views.xml
  purchase_work_acceptance/views/work_acceptance_views.xml
  purchase_work_acceptance/wizard/__init__.py
  purchase_work_acceptance/wizard/select_work_acceptance_wizard.py
  purchase_work_acceptance/wizard/select_work_acceptance_wizard_views.xml
  purchase_work_acceptance/wizard/work_accepted_date_wizard.py
  purchase_work_acceptance/wizard/work_accepted_date_wizard.xml
Labels: bot is merging ⏳

#2715 [18.0][MIG] purchase_lot: Migration to 18.0
  purchase_lot/README.rst
  purchase_lot/__init__.py
  purchase_lot/__manifest__.py
  purchase_lot/i18n/es.po
  purchase_lot/i18n/it.po
  purchase_lot/i18n/purchase_lot.pot
  purchase_lot/models/__init__.py
  purchase_lot/models/purchase_order_line.py
  purchase_lot/models/stock_rule.py
  purchase_lot/pyproject.toml
  purchase_lot/readme/CONTRIBUTORS.md
  purchase_lot/readme/DESCRIPTION.md
  purchase_lot/static/description/icon.png
  purchase_lot/static/description/index.html
  purchase_lot/tests/__init__.py
  purchase_lot/tests/test_purchase_lot.py
  purchase_lot/views/purchase_order_view.xml
Labels: approved, bot is merging ⏳

#2724 [16.0][FIX] purchase_request: Add noupdate=1 to mail message subtypes
  purchase_request/README.rst
  purchase_request/__manifest__.py
  purchase_request/data/purchase_request_data.xml
  purchase_request/migrations/16.0.2.3.0/pre-migration.py
  purchase_request/static/description/index.html
Labels: approved, bot is merging ⏳

#2723 [16.0][ADD] product_supplierinfo_security: New module
  product_supplierinfo_security/README.rst
  product_supplierinfo_security/__init__.py
  product_supplierinfo_security/__manifest__.py
  product_supplierinfo_security/readme/CONTEXT.md
  product_supplierinfo_security/readme/CONTRIBUTORS.md
  product_supplierinfo_security/readme/DESCRIPTION.md
  product_supplierinfo_security/readme/ROADMAP.md
  product_supplierinfo_security/readme/USAGE.md
  product_supplierinfo_security/static/description/index.html
  product_supplierinfo_security/tests/__init__.py
  product_supplierinfo_security/tests/test_product_supplierinfo_security.py
  product_supplierinfo_security/views/product_views.xml
  setup/product_supplierinfo_security/odoo/addons/product_supplierinfo_security
  setup/product_supplierinfo_security/setup.py
Labels: needs review, approved, bot is merging ⏳

#2728 [18.0][FIX] purchase_force_invoiced: restore force invoiced flag editable status
  purchase_force_invoiced/view/purchase_order.xml
Labels: bot is merging ⏳

#2590 [16.0][IMP] purchase_discount: Discount < 100% constraint on product supplierinfo
  purchase_discount/models/product_supplierinfo.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#2733 [17.0][IMP] purchase_request: Add specific subtypes for using subscribed partners in some messages
  purchase_request/data/purchase_request_data.xml
  purchase_request/i18n/es.po
  purchase_request/i18n/purchase_request.pot
  purchase_request/models/purchase_order.py
  purchase_request/models/stock_move_line.py
Labels: approved, bot is merging ⏳
