Repository OCA/purchase-workflow, pull requests merged in 2025-05, with the labels that each got.

#2666 [16.0][FIX] purchase_request: Change the types of messages that are created to notes
  purchase_request/models/purchase_order.py
  purchase_request/models/purchase_request_allocation.py
  purchase_request/models/stock_move_line.py
Labels: approved, bot is merging ⏳

#2669 [16.0][IMP] purchase_request: Allow a user with read permissions to create messages
  purchase_request/models/purchase_request.py
Labels: approved, bot is merging ⏳

#2672 [17.0][FIX] purchase_request: Change the types of messages that are created to notes.
  purchase_request/models/purchase_order.py
  purchase_request/models/purchase_request_allocation.py
  purchase_request/models/stock_move_line.py
Labels: approved, bot is merging ⏳

#2673 [18.0][FIX] purchase_request: Change the types of messages that are created to notes
  purchase_request/models/purchase_order.py
  purchase_request/models/purchase_request_allocation.py
  purchase_request/models/stock_move_line.py
Labels: approved, bot is merging ⏳

#2674 [17.0][IMP] purchase_request: Allow a user with read permissions to create messages
  purchase_request/models/purchase_request.py
Labels: approved, bot is merging ⏳

#2676 [18.0][IMP] purchase_request: Allow a user with read permissions to create messages
  purchase_request/models/purchase_request.py
Labels: approved, bot is merging ⏳

#2301 [14.0][MIG] purchase_requisition_line_description
  purchase_requisition_line_description/README.rst
  purchase_requisition_line_description/__init__.py
  purchase_requisition_line_description/__manifest__.py
  purchase_requisition_line_description/i18n/purchase_requisition_line_description.pot
  purchase_requisition_line_description/models/__init__.py
  purchase_requisition_line_description/models/purchase_requisition_line.py
  purchase_requisition_line_description/readme/CONTRIBUTORS.rst
  purchase_requisition_line_description/readme/DESCRIPTION.rst
  purchase_requisition_line_description/readme/USAGE.rst
  purchase_requisition_line_description/report/purchase_requisition_report.xml
  purchase_requisition_line_description/static/description/icon.png
  purchase_requisition_line_description/static/description/index.html
  purchase_requisition_line_description/tests/__init__.py
  purchase_requisition_line_description/tests/test_purchase_requisition_line_description.py
  purchase_requisition_line_description/views/purchase_requisition.xml
  setup/purchase_requisition_line_description/odoo/addons/purchase_requisition_line_description
  setup/purchase_requisition_line_description/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2653 [18.0] [MIG] purchase_requisition_line_description: Migration to 18.0
  purchase_requisition_line_description/README.rst
  purchase_requisition_line_description/__init__.py
  purchase_requisition_line_description/__manifest__.py
  purchase_requisition_line_description/i18n/purchase_requisition_line_description.pot
  purchase_requisition_line_description/models/__init__.py
  purchase_requisition_line_description/models/purchase_requisition_line.py
  purchase_requisition_line_description/pyproject.toml
  purchase_requisition_line_description/readme/CONTRIBUTORS.md
  purchase_requisition_line_description/readme/DESCRIPTION.md
  purchase_requisition_line_description/readme/USAGE.md
  purchase_requisition_line_description/report/purchase_requisition_report.xml
  purchase_requisition_line_description/static/description/icon.png
  purchase_requisition_line_description/static/description/index.html
  purchase_requisition_line_description/tests/__init__.py
  purchase_requisition_line_description/tests/test_purchase_requisition_line_description.py
  purchase_requisition_line_description/views/purchase_requisition.xml
Labels: approved, bot is merging ⏳

#2689 [17.0][FIX] sale_purchase_force_vendor: Change the done status of sales orders (does not exist) to sale
  sale_purchase_force_vendor/views/sale_order_view.xml
Labels: bot is merging ⏳

#2649 [17.0][ADD] product_supplierinfo_disable_autocreation: prevent supplier auto-creation
  product_supplierinfo_disable_autocreation/README.rst
  product_supplierinfo_disable_autocreation/__init__.py
  product_supplierinfo_disable_autocreation/__manifest__.py
  product_supplierinfo_disable_autocreation/i18n/ca_ES.po
  product_supplierinfo_disable_autocreation/i18n/es.po
  product_supplierinfo_disable_autocreation/models/__init__.py
  product_supplierinfo_disable_autocreation/models/purchase_order.py
  product_supplierinfo_disable_autocreation/models/res_company.py
  product_supplierinfo_disable_autocreation/models/res_config_settings.py
  product_supplierinfo_disable_autocreation/pyproject.toml
  product_supplierinfo_disable_autocreation/readme/CONTRIBUTORS.md
  product_supplierinfo_disable_autocreation/readme/DESCRIPTION.md
  product_supplierinfo_disable_autocreation/readme/USAGE.md
  product_supplierinfo_disable_autocreation/static/description/icon.png
  product_supplierinfo_disable_autocreation/static/description/index.html
  product_supplierinfo_disable_autocreation/tests/__init__.py
  product_supplierinfo_disable_autocreation/tests/test_purchase_pricelist_disable.py
  product_supplierinfo_disable_autocreation/views/res_config_settings_views.xml
Labels: approved, merged 🎉
