Repository OCA/purchase-workflow, pull requests merged in 2025-04, with the labels that each got.

#2629 [17.0][FIX] purchase_advance_payment: use commercial partner
  purchase_advance_payment/wizard/purchase_advance_payment_wizard.py
Labels: approved, bot is merging ⏳

#2626 [18.0][MIG] purchase_advance_payment
  purchase_advance_payment/README.rst
  purchase_advance_payment/__init__.py
  purchase_advance_payment/__manifest__.py
  purchase_advance_payment/data/ir_config_parameter.xml
  purchase_advance_payment/i18n/es.po
  purchase_advance_payment/i18n/fr.po
  purchase_advance_payment/i18n/it.po
  purchase_advance_payment/i18n/pt_BR.po
  purchase_advance_payment/i18n/purchase_advance_payment.pot
  purchase_advance_payment/models/__init__.py
  purchase_advance_payment/models/account_move.py
  purchase_advance_payment/models/payment.py
  purchase_advance_payment/models/purchase_order.py
  purchase_advance_payment/models/res_config_settings.py
  purchase_advance_payment/pyproject.toml
  purchase_advance_payment/readme/CONTRIBUTORS.md
  purchase_advance_payment/readme/CREDITS.md
  purchase_advance_payment/readme/DESCRIPTION.md
  purchase_advance_payment/readme/USAGE.md
  purchase_advance_payment/security/ir.model.access.csv
  purchase_advance_payment/static/description/icon.png
  purchase_advance_payment/static/description/index.html
  purchase_advance_payment/tests/__init__.py
  purchase_advance_payment/tests/test_purchase_advance_payment.py
  purchase_advance_payment/views/account_payment_views.xml
  purchase_advance_payment/views/purchase_view.xml
  purchase_advance_payment/views/res_config_settings_views.xml
  purchase_advance_payment/wizard/__init__.py
  purchase_advance_payment/wizard/purchase_advance_payment_wizard.py
  purchase_advance_payment/wizard/purchase_advance_payment_wizard_view.xml
Labels: approved, bot is merging ⏳

#2522 [17.0][MIG] purchase_stock_manual_currency
  purchase_stock_manual_currency/README.rst
  purchase_stock_manual_currency/__init__.py
  purchase_stock_manual_currency/__manifest__.py
  purchase_stock_manual_currency/i18n/purchase_stock_manual_currency.pot
  purchase_stock_manual_currency/models/__init__.py
  purchase_stock_manual_currency/models/stock_move.py
  purchase_stock_manual_currency/pyproject.toml
  purchase_stock_manual_currency/readme/CONTRIBUTORS.md
  purchase_stock_manual_currency/readme/DESCRIPTION.md
  purchase_stock_manual_currency/static/description/icon.png
  purchase_stock_manual_currency/static/description/index.html
  purchase_stock_manual_currency/tests/__init__.py
  purchase_stock_manual_currency/tests/test_purchase_stock_manual_currency.py
Labels: approved, ready to merge, bot is merging ⏳

#2573 [17.0][FIX] purchase_manual_delivery: always call the full confirmation stack
  purchase_manual_delivery/models/purchase_order.py
Labels: approved, bot is merging ⏳

#2485 [18][MIG] purchase_fop_shipping
  purchase_fop_shipping/README.rst
  purchase_fop_shipping/__init__.py
  purchase_fop_shipping/__manifest__.py
  purchase_fop_shipping/i18n/de.po
  purchase_fop_shipping/i18n/es.po
  purchase_fop_shipping/i18n/es_PE.po
  purchase_fop_shipping/i18n/fr.po
  purchase_fop_shipping/i18n/fr_BE.po
  purchase_fop_shipping/i18n/gl.po
  purchase_fop_shipping/i18n/hr.po
  purchase_fop_shipping/i18n/it.po
  purchase_fop_shipping/i18n/nl.po
  purchase_fop_shipping/i18n/nl_NL.po
  purchase_fop_shipping/i18n/pt_BR.po
  purchase_fop_shipping/i18n/purchase_fop_shipping.pot
  purchase_fop_shipping/i18n/ro.po
  purchase_fop_shipping/i18n/sl.po
  purchase_fop_shipping/i18n/vi_VN.po
  purchase_fop_shipping/models/__init__.py
  purchase_fop_shipping/models/partner.py
  purchase_fop_shipping/models/purchase.py
  purchase_fop_shipping/pyproject.toml
  purchase_fop_shipping/security/res_groups.xml
  purchase_fop_shipping/static/description/icon.png
  purchase_fop_shipping/tests/__init__.py
  purchase_fop_shipping/tests/test_fop_shipping.py
  purchase_fop_shipping/views/purchase_order.xml
  purchase_fop_shipping/views/res_partner.xml
Labels: approved, ready to merge, merged 🎉

#2631 [14.0][IMP] purchase_advance_payment: add unit test advance_payment_status with bill
  purchase_advance_payment/tests/test_purchase_advance_payment.py
Labels: approved, bot is merging ⏳

#2630 [17.0][FIX] purchase_advance_payment: do not create starting false param
  purchase_advance_payment/data/ir_config_parameter.xml
Labels: approved, bot is merging ⏳

#2500 [18.0][MIG] purchase_order_supplierinfo_update: Migration to 18.0
  purchase_order_line_menu/README.rst
  purchase_order_supplierinfo_update/README.rst
  purchase_order_supplierinfo_update/__init__.py
  purchase_order_supplierinfo_update/__manifest__.py
  purchase_order_supplierinfo_update/i18n/it.po
  purchase_order_supplierinfo_update/i18n/pt_BR.po
  purchase_order_supplierinfo_update/i18n/purchase_order_supplierinfo_update.pot
  purchase_order_supplierinfo_update/models/__init__.py
  purchase_order_supplierinfo_update/models/purchase_order.py
  purchase_order_supplierinfo_update/pyproject.toml
  purchase_order_supplierinfo_update/readme/CONTRIBUTORS.md
  purchase_order_supplierinfo_update/readme/DESCRIPTION.md
  purchase_order_supplierinfo_update/readme/ROADMAP.md
  purchase_order_supplierinfo_update/readme/USAGE.md
  purchase_order_supplierinfo_update/static/description/icon.png
  purchase_order_supplierinfo_update/static/description/index.html
  purchase_order_supplierinfo_update/tests/__init__.py
  purchase_order_supplierinfo_update/tests/test_purchase_order_supplierinfo_update.py
  purchase_order_type/README.rst
  purchase_request_department/README.rst
Labels: approved, ready to merge, bot is merging ⏳

#2645 [18.0][IMP] purchase_order_supplierinfo_update - add discount logic in the readme & trigger update when discount is changed
  purchase_order_supplierinfo_update/README.rst
  purchase_order_supplierinfo_update/models/purchase_order.py
  purchase_order_supplierinfo_update/readme/DESCRIPTION.md
  purchase_order_supplierinfo_update/readme/USAGE.md
  purchase_order_supplierinfo_update/static/description/index.html
Labels: approved, bot is merging ⏳

#2517 [17.0][MIG] purchase_stock_price_unit_sync
  purchase_stock_price_unit_sync/README.rst
  purchase_stock_price_unit_sync/__init__.py
  purchase_stock_price_unit_sync/__manifest__.py
  purchase_stock_price_unit_sync/i18n/it.po
  purchase_stock_price_unit_sync/i18n/purchase_stock_price_unit_sync.pot
  purchase_stock_price_unit_sync/models/__init__.py
  purchase_stock_price_unit_sync/models/purchase_order.py
  purchase_stock_price_unit_sync/pyproject.toml
  purchase_stock_price_unit_sync/readme/CONTRIBUTORS.md
  purchase_stock_price_unit_sync/readme/DESCRIPTION.md
  purchase_stock_price_unit_sync/static/description/icon.png
  purchase_stock_price_unit_sync/static/description/index.html
  purchase_stock_price_unit_sync/tests/__init__.py
  purchase_stock_price_unit_sync/tests/test_purchase_stock_price_unit_sync.py
Labels: approved, bot is merging ⏳

#2637 [15.0][FIX] purchase_advance_payment: fix advance_payment_status with bill
  purchase_advance_payment/models/purchase_order.py
  purchase_advance_payment/tests/test_purchase_advance_payment.py
Labels: bot is merging ⏳

#2639 [17.0][FIX] purchase_advance_payment: fix advance_payment_status with bill
  purchase_advance_payment/models/purchase_order.py
  purchase_advance_payment/tests/test_purchase_advance_payment.py
Labels: approved, ready to merge, bot is merging ⏳

#2638 [16.0][FIX] purchase_advance_payment: fix advance_payment_status with bill
  purchase_advance_payment/models/purchase_order.py
  purchase_advance_payment/tests/test_purchase_advance_payment.py
Labels: approved, ready to merge, bot is merging ⏳

#2650 [16.0][IMP] purchase_request: copy estimated cost to PO (Port from #2197)
  purchase_request/tests/test_purchase_request_to_rfq.py
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
  purchase_request/wizard/purchase_request_line_make_purchase_order_view.xml
Labels: approved, bot is merging ⏳

#2634 [16.0][FIX] purchase_open_qty
  purchase_open_qty/init_hook.py
Labels: approved, ready to merge, bot is merging ⏳

#2499 [17.0][MIG] purchase_order_supplierinfo_update: Migration to 17.0
  purchase_order_supplierinfo_update/README.rst
  purchase_order_supplierinfo_update/__init__.py
  purchase_order_supplierinfo_update/__manifest__.py
  purchase_order_supplierinfo_update/i18n/it.po
  purchase_order_supplierinfo_update/i18n/pt_BR.po
  purchase_order_supplierinfo_update/i18n/purchase_order_supplierinfo_update.pot
  purchase_order_supplierinfo_update/models/__init__.py
  purchase_order_supplierinfo_update/models/purchase_order.py
  purchase_order_supplierinfo_update/pyproject.toml
  purchase_order_supplierinfo_update/readme/CONTRIBUTORS.md
  purchase_order_supplierinfo_update/readme/DESCRIPTION.md
  purchase_order_supplierinfo_update/readme/ROADMAP.md
  purchase_order_supplierinfo_update/readme/USAGE.md
  purchase_order_supplierinfo_update/static/description/icon.png
  purchase_order_supplierinfo_update/static/description/index.html
  purchase_order_supplierinfo_update/tests/__init__.py
  purchase_order_supplierinfo_update/tests/test_purchase_order_supplierinfo_update.py
Labels: approved, ready to merge, bot is merging ⏳

#2331 [17.0][MIG] Migration of module purchase_lot
  purchase_lot/README.rst
  purchase_lot/__init__.py
  purchase_lot/__manifest__.py
  purchase_lot/i18n/es.po
  purchase_lot/i18n/it.po
  purchase_lot/i18n/purchase_lot.pot
  purchase_lot/models/__init__.py
  purchase_lot/models/purchase_order_line.py
  purchase_lot/models/stock_rule.py
  purchase_lot/pyproject.toml
  purchase_lot/readme/CONTRIBUTORS.md
  purchase_lot/readme/DESCRIPTION.md
  purchase_lot/static/description/icon.png
  purchase_lot/static/description/index.html
  purchase_lot/tests/__init__.py
  purchase_lot/tests/test_purchase_lot.py
  purchase_lot/views/purchase_order_view.xml
Labels: approved, bot is merging ⏳

#2465 [16.0][ADD] purchase_split_by_route
  purchase_split_by_route/README.rst
  purchase_split_by_route/__init__.py
  purchase_split_by_route/__manifest__.py
  purchase_split_by_route/models/__init__.py
  purchase_split_by_route/models/purchase_order.py
  purchase_split_by_route/models/stock_route.py
  purchase_split_by_route/models/stock_rule.py
  purchase_split_by_route/readme/CONTRIBUTORS.rst
  purchase_split_by_route/readme/DESCRIPTION.rst
  purchase_split_by_route/static/description/index.html
  purchase_split_by_route/tests/__init__.py
  purchase_split_by_route/tests/test_purchase_route.py
  purchase_split_by_route/views/stock_route.xml
  setup/purchase_split_by_route/odoo/addons/purchase_split_by_route
  setup/purchase_split_by_route/setup.py
Labels: approved, bot is merging ⏳

#2445 [18.0][MIG] : Migration purchase_partner_incoterm to 18.0
  purchase_partner_incoterm/README.rst
  purchase_partner_incoterm/__init__.py
  purchase_partner_incoterm/__manifest__.py
  purchase_partner_incoterm/i18n/it.po
  purchase_partner_incoterm/i18n/purchase_partner_incoterm.pot
  purchase_partner_incoterm/models/__init__.py
  purchase_partner_incoterm/models/purchase_order.py
  purchase_partner_incoterm/models/res_partner.py
  purchase_partner_incoterm/pyproject.toml
  purchase_partner_incoterm/readme/CONTRIBUTORS.md
  purchase_partner_incoterm/readme/CREDITS.md
  purchase_partner_incoterm/readme/DESCRIPTION.md
  purchase_partner_incoterm/static/description/icon.png
  purchase_partner_incoterm/static/description/index.html
  purchase_partner_incoterm/tests/__init__.py
  purchase_partner_incoterm/tests/test_purchase_partner_incoterm.py
  purchase_partner_incoterm/views/partner_view.xml
  purchase_partner_incoterm/views/purchase_view.xml
Labels: approved, bot is merging ⏳

#2659 [17.0][FIX] purchase_open_qty
  purchase_open_qty/init_hook.py
Labels: approved, bot is merging ⏳

#2660 [18.0][FIX] purchase_open_qty
  purchase_open_qty/init_hook.py
Labels: approved, bot is merging ⏳

#2640 [18.0][FIX] purchase_advance_payment: fix advance_payment_status with bill
  purchase_advance_payment/models/purchase_order.py
  purchase_advance_payment/tests/test_purchase_advance_payment.py
Labels: approved, bot is merging ⏳
