Repository OCA/purchase-workflow, pull requests merged in 2025-03, with the labels that each got.

#2558 [18.0][MIG] purchase_analytic_global: Migration to 18.0
  purchase_analytic_global/README.rst
  purchase_analytic_global/__init__.py
  purchase_analytic_global/__manifest__.py
  purchase_analytic_global/i18n/es.po
  purchase_analytic_global/i18n/fr.po
  purchase_analytic_global/i18n/purchase_analytic_global.pot
  purchase_analytic_global/models/__init__.py
  purchase_analytic_global/models/purchase_order.py
  purchase_analytic_global/pyproject.toml
  purchase_analytic_global/readme/CONTRIBUTORS.md
  purchase_analytic_global/readme/CREDITS.md
  purchase_analytic_global/readme/DESCRIPTION.md
  purchase_analytic_global/static/description/icon.png
  purchase_analytic_global/static/description/index.html
  purchase_analytic_global/tests/__init__.py
  purchase_analytic_global/tests/test_purchase_analytic_global.py
  purchase_analytic_global/views/purchase_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#2584 [18.0][FIX] purchase_invoice_plan: replace old tree node by list node
  purchase_invoice_plan/views/purchase_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2583 [18.0][FIX] purchase_exception: replace old tree node by list node
  purchase_exception/views/purchase_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2594 [18.0][MIG] purchase_partner_selectable_option: Migration to 18.0
  purchase_partner_selectable_option/README.rst
  purchase_partner_selectable_option/__init__.py
  purchase_partner_selectable_option/__manifest__.py
  purchase_partner_selectable_option/data/ir_config_parameter.xml
  purchase_partner_selectable_option/i18n/es.po
  purchase_partner_selectable_option/i18n/it.po
  purchase_partner_selectable_option/i18n/pt_BR.po
  purchase_partner_selectable_option/i18n/purchase_partner_selectable_option.pot
  purchase_partner_selectable_option/models/__init__.py
  purchase_partner_selectable_option/models/purchase_order.py
  purchase_partner_selectable_option/models/res_partner.py
  purchase_partner_selectable_option/pyproject.toml
  purchase_partner_selectable_option/readme/CONFIGURE.md
  purchase_partner_selectable_option/readme/CONTRIBUTORS.md
  purchase_partner_selectable_option/readme/DESCRIPTION.md
  purchase_partner_selectable_option/readme/USAGE.md
  purchase_partner_selectable_option/static/description/icon.png
  purchase_partner_selectable_option/static/description/index.html
  purchase_partner_selectable_option/tests/__init__.py
  purchase_partner_selectable_option/tests/test_purchase_partner_selectable_option.py
  purchase_partner_selectable_option/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#2578 [18.0][MIG] purchase_order_secondary_unit: Migration to 18.0
  purchase_order_secondary_unit/README.rst
  purchase_order_secondary_unit/__init__.py
  purchase_order_secondary_unit/__manifest__.py
  purchase_order_secondary_unit/i18n/de.po
  purchase_order_secondary_unit/i18n/es.po
  purchase_order_secondary_unit/i18n/fr.po
  purchase_order_secondary_unit/i18n/it.po
  purchase_order_secondary_unit/i18n/ja.po
  purchase_order_secondary_unit/i18n/purchase_order_secondary_unit.pot
  purchase_order_secondary_unit/models/__init__.py
  purchase_order_secondary_unit/models/product_product.py
  purchase_order_secondary_unit/models/product_template.py
  purchase_order_secondary_unit/models/purchase_order.py
  purchase_order_secondary_unit/pyproject.toml
  purchase_order_secondary_unit/readme/CONTRIBUTORS.md
  purchase_order_secondary_unit/readme/DESCRIPTION.md
  purchase_order_secondary_unit/readme/USAGE.md
  purchase_order_secondary_unit/reports/purchase_order_templates.xml
  purchase_order_secondary_unit/reports/purchase_quotation_templates.xml
  purchase_order_secondary_unit/static/description/icon.png
  purchase_order_secondary_unit/static/description/index.html
  purchase_order_secondary_unit/tests/__init__.py
  purchase_order_secondary_unit/tests/test_purchase_order_secondary_unit.py
  purchase_order_secondary_unit/views/product_views.xml
  purchase_order_secondary_unit/views/purchase_order_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2599 [16.0][REF] purchase_triple_discount: Consolidate discount in std field
  purchase_discount/tests/test_purchase_discount.py
  purchase_triple_discount/__init__.py
  purchase_triple_discount/__manifest__.py
  purchase_triple_discount/hooks.py
  purchase_triple_discount/migrations/16.0.3.0.0/post-migrate.py
  purchase_triple_discount/migrations/16.0.3.0.0/pre-migrate.py
  purchase_triple_discount/models/__init__.py
  purchase_triple_discount/models/product_supplierinfo.py
  purchase_triple_discount/models/purchase_order.py
  purchase_triple_discount/models/res_partner.py
  purchase_triple_discount/models/triple_discount_mixin.py
  purchase_triple_discount/report/purchase_report.py
  purchase_triple_discount/tests/test_purchase_discount.py
  purchase_triple_discount/views/product_supplierinfo_view.xml
  purchase_triple_discount/views/purchase_order_report.xml
  purchase_triple_discount/views/purchase_view.xml
  purchase_triple_discount/views/res_partner_view.xml
Labels: bot is merging ⏳

#2597 [16.0][FIX] purchase_landed_cost: Avoid access error reading act_window
  purchase_landed_cost/models/purchase_cost_distribution.py
Labels: approved, bot is merging ⏳

#2603 [16.0][FIX] purchase_discount: typo error in post-migrate script.
  purchase_triple_discount/migrations/16.0.3.0.0/post-migrate.py
Labels: approved, bot is merging ⏳

#2593 [18.0][FIX] purchase_request: Ensure correct HTML rendering in chatter mesages
  purchase_request/models/purchase_order.py
  purchase_request/models/purchase_request_allocation.py
  purchase_request/models/stock_move_line.py
Labels: approved, ready to merge, bot is merging ⏳

#2581 [16.0][FIX] purchase_landed_cost + purchase_allowed_product + purchase_order_uninvoiced_amount: Post-install test + fallback to load CoA
  purchase_allowed_product/tests/test_purchase_allowed_product.py
  purchase_landed_cost/tests/test_purchase_landed_cost.py
  purchase_order_uninvoiced_amount/tests/test_purchase_order_uninvoiced_amount.py
Labels: bot is merging ⏳

#2601 [18.0][IMP] purchase_request: add 'In Progress' state
  purchase_request/i18n/es.po
  purchase_request/i18n/purchase_request.pot
  purchase_request/models/orderpoint.py
  purchase_request/models/purchase_request.py
  purchase_request/models/purchase_request_line.py
  purchase_request/tests/test_purchase_request.py
  purchase_request/views/purchase_request_line_view.xml
  purchase_request/views/purchase_request_view.xml
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: approved, bot is merging ⏳

#2598 [17.0][IMP] purchase_request: add 'In Progress' state
  purchase_request/i18n/es.po
  purchase_request/i18n/purchase_request.pot
  purchase_request/models/orderpoint.py
  purchase_request/models/purchase_request.py
  purchase_request/models/purchase_request_line.py
  purchase_request/tests/test_purchase_request.py
  purchase_request/views/purchase_request_line_view.xml
  purchase_request/views/purchase_request_view.xml
  purchase_request/wizard/purchase_request_line_make_purchase_order.py
Labels: approved, bot is merging ⏳

#2606 [16.0][FIX] purchase_force_invoiced: Fallback to load CoA
  purchase_force_invoiced/tests/test_purchase_force_invoiced.py
Labels: approved, bot is merging ⏳

#2608 [17.0][IMP] purchase_request: Misc changes (hide company_id field + set groups to group_id field)
  purchase_request/data/purchase_request_sequence.xml
  purchase_request/models/purchase_request_line.py
  purchase_request/views/purchase_request_line_view.xml
  purchase_request/views/purchase_request_view.xml
  purchase_request_tier_validation/__manifest__.py
  purchase_request_tier_validation/demo/tier_definition.xml
  purchase_request_tier_validation/static/description/index.html
Labels: approved, bot is merging ⏳

#2610 [18.0][FIX] purchase_request: Make currency_id field invisible
  purchase_request/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳

#2611 [16.0][IMP] purchase_request: Define analytic_distribution field hidden by default
  purchase_request/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳

#2614 [16.0][FIX] purchase_request: Display the status of the purchase in the corresponding language
  purchase_request/models/purchase_request_line.py
Labels: bot is merging ⏳

#2612 [16.0][IMP] purchase_request_type: Remove "PR Type" string
  purchase_request_type/i18n/es.po
  purchase_request_type/i18n/purchase_request_type.pot
  purchase_request_type/models/purchase_request.py
  purchase_request_type/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳

#2617 [17.0][FIX] purchase_request: Display the status of the purchase in the corresponding language
  purchase_request/models/purchase_request_line.py
Labels: bot is merging ⏳

#2620 [18.0][IMP] purchase_request_tier_validation: Hide Confirm button if the validation is pending or rejected
  purchase_request_tier_validation/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳

#2613 [18.0][MIG] supplier_calendar
  supplier_calendar/README.rst
  supplier_calendar/__init__.py
  supplier_calendar/__manifest__.py
  supplier_calendar/i18n/es.po
  supplier_calendar/i18n/it.po
  supplier_calendar/i18n/supplier_calendar.pot
  supplier_calendar/models/__init__.py
  supplier_calendar/models/product.py
  supplier_calendar/models/purchase.py
  supplier_calendar/models/res_partner.py
  supplier_calendar/models/stock_rule.py
  supplier_calendar/pyproject.toml
  supplier_calendar/readme/CONFIGURE.md
  supplier_calendar/readme/CONTRIBUTORS.md
  supplier_calendar/readme/DESCRIPTION.md
  supplier_calendar/readme/USAGE.md
  supplier_calendar/static/description/icon.png
  supplier_calendar/static/description/index.html
  supplier_calendar/tests/__init__.py
  supplier_calendar/tests/test_supplier_calendar.py
  supplier_calendar/views/product_view.xml
  supplier_calendar/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#2567 [16.0][MIG] purchase_minimum_amount: Migration to 16.0
  purchase_minimum_amount/README.rst
  purchase_minimum_amount/__init__.py
  purchase_minimum_amount/__manifest__.py
  purchase_minimum_amount/data/purchase_block_reason_data.xml
  purchase_minimum_amount/i18n/de.po
  purchase_minimum_amount/i18n/es.po
  purchase_minimum_amount/i18n/es_MX.po
  purchase_minimum_amount/i18n/fr.po
  purchase_minimum_amount/i18n/it.po
  purchase_minimum_amount/i18n/pt_BR.po
  purchase_minimum_amount/i18n/purchase_minimum_amount.pot
  purchase_minimum_amount/i18n/sl.po
  purchase_minimum_amount/models/__init__.py
  purchase_minimum_amount/models/partner.py
  purchase_minimum_amount/models/purchase_order.py
  purchase_minimum_amount/readme/CONFIGURE.rst
  purchase_minimum_amount/readme/CONTRIBUTORS.rst
  purchase_minimum_amount/readme/DESCRIPTION.rst
  purchase_minimum_amount/readme/USAGE.rst
  purchase_minimum_amount/static/description/icon.png
  purchase_minimum_amount/static/description/index.html
  purchase_minimum_amount/tests/__init__.py
  purchase_minimum_amount/tests/test_po_minimum_amount_block.py
  purchase_minimum_amount/views/purchase_order_view.xml
  purchase_minimum_amount/views/res_partner_view.xml
  setup/purchase_minimum_amount/odoo/addons/purchase_minimum_amount
  setup/purchase_minimum_amount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2595 [18.0][MIG] purchase_blanket_order: Migration to 18.0
  purchase_blanket_order/README.rst
  purchase_blanket_order/__init__.py
  purchase_blanket_order/__manifest__.py
  purchase_blanket_order/data/ir_cron.xml
  purchase_blanket_order/data/sequence.xml
  purchase_blanket_order/i18n/es.po
  purchase_blanket_order/i18n/it.po
  purchase_blanket_order/i18n/purchase_blanket_order.pot
  purchase_blanket_order/models/__init__.py
  purchase_blanket_order/models/blanket_orders.py
  purchase_blanket_order/models/purchase_config_settings.py
  purchase_blanket_order/models/purchase_order.py
  purchase_blanket_order/pyproject.toml
  purchase_blanket_order/readme/CONTRIBUTORS.md
  purchase_blanket_order/readme/DESCRIPTION.md
  purchase_blanket_order/readme/USAGE.md
  purchase_blanket_order/report/report.xml
  purchase_blanket_order/report/templates.xml
  purchase_blanket_order/security/ir.model.access.csv
  purchase_blanket_order/security/security.xml
  purchase_blanket_order/static/description/BO_actions.png
  purchase_blanket_order/static/description/BO_form.png
  purchase_blanket_order/static/description/BO_lines.png
  purchase_blanket_order/static/description/BO_menu.png
  purchase_blanket_order/static/description/PO_BOLine.png
  purchase_blanket_order/static/description/PO_from_BO.png
  purchase_blanket_order/static/description/icon.png
  purchase_blanket_order/static/description/index.html
  purchase_blanket_order/tests/__init__.py
  purchase_blanket_order/tests/test_purchase_blanket_order.py
  purchase_blanket_order/tests/test_purchase_order.py
  purchase_blanket_order/views/purchase_blanket_order_views.xml
  purchase_blanket_order/views/purchase_config_settings.xml
  purchase_blanket_order/views/purchase_order_views.xml
  purchase_blanket_order/wizard/__init__.py
  purchase_blanket_order/wizard/create_purchase_orders.py
  purchase_blanket_order/wizard/create_purchase_orders.xml
Labels: approved, bot is merging ⏳

#2557 [16.0][IMP] purchase_only_by_packaging round up product qty
  purchase_only_by_packaging/models/purchase_order_line.py
Labels: approved, ready to merge, bot is merging ⏳

#2556 [15.0][FIX] purchase_order_revision: Allow non-admins to view revisions
  purchase_order_revision/models/purchase_order.py
Labels: approved, bot is merging ⏳

#2529 [16.0][[MIG] purchase_order_revision: Migration to 16.0
  purchase_order_revision/README.rst
  purchase_order_revision/__init__.py
  purchase_order_revision/__manifest__.py
  purchase_order_revision/i18n/purchase_order_revision.pot
  purchase_order_revision/models/__init__.py
  purchase_order_revision/models/purchase_order.py
  purchase_order_revision/readme/CONTRIBUTORS.rst
  purchase_order_revision/readme/DESCRIPTION.rst
  purchase_order_revision/readme/INSTALL.rst
  purchase_order_revision/static/description/icon.png
  purchase_order_revision/static/description/index.html
  purchase_order_revision/tests/__init__.py
  purchase_order_revision/tests/test_purchase_order_revision.py
  purchase_order_revision/view/purchase_order.xml
  setup/purchase_order_revision/odoo/addons/purchase_order_revision
  setup/purchase_order_revision/setup.py
Labels: approved, bot is merging ⏳

#2521 [17.0][MIG] purchase_manual_currency
  purchase_manual_currency/README.rst
  purchase_manual_currency/__init__.py
  purchase_manual_currency/__manifest__.py
  purchase_manual_currency/i18n/es.po
  purchase_manual_currency/i18n/purchase_manual_currency.pot
  purchase_manual_currency/models/__init__.py
  purchase_manual_currency/models/purchase.py
  purchase_manual_currency/models/purchase_order_line.py
  purchase_manual_currency/models/res_company.py
  purchase_manual_currency/models/res_config_settings.py
  purchase_manual_currency/pyproject.toml
  purchase_manual_currency/readme/CONTRIBUTORS.md
  purchase_manual_currency/readme/DESCRIPTION.md
  purchase_manual_currency/readme/USAGE.md
  purchase_manual_currency/static/description/icon.png
  purchase_manual_currency/static/description/index.html
  purchase_manual_currency/tests/__init__.py
  purchase_manual_currency/tests/test_purchase_manual_currency.py
  purchase_manual_currency/views/purchase_views.xml
  purchase_manual_currency/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#2078 [16.0][MIG] purchase_invoice_new_picking_line
  purchase_invoice_new_picking_line/README.rst
  purchase_invoice_new_picking_line/__init__.py
  purchase_invoice_new_picking_line/__manifest__.py
  purchase_invoice_new_picking_line/models/__init__.py
  purchase_invoice_new_picking_line/models/purchase_order.py
  purchase_invoice_new_picking_line/readme/CONTRIBUTORS.rst
  purchase_invoice_new_picking_line/readme/DESCRIPTION.rst
  purchase_invoice_new_picking_line/static/description/index.html
  purchase_invoice_new_picking_line/tests/__init__.py
  purchase_invoice_new_picking_line/tests/test_invoice.py
  setup/purchase_invoice_new_picking_line/odoo/addons/purchase_invoice_new_picking_line
  setup/purchase_invoice_new_picking_line/setup.py
Labels: approved, bot is merging ⏳

#2625 [18.0][MIG] purchase_request_type: Migration to 18.0
  purchase_request_type/README.rst
  purchase_request_type/__init__.py
  purchase_request_type/__manifest__.py
  purchase_request_type/demo/purchase_request_type.xml
  purchase_request_type/i18n/es.po
  purchase_request_type/i18n/it.po
  purchase_request_type/i18n/purchase_request_type.pot
  purchase_request_type/models/__init__.py
  purchase_request_type/models/purchase_request.py
  purchase_request_type/models/purchase_request_type.py
  purchase_request_type/pyproject.toml
  purchase_request_type/readme/CONFIGURE.md
  purchase_request_type/readme/CONTRIBUTORS.md
  purchase_request_type/readme/DESCRIPTION.md
  purchase_request_type/readme/ROADMAP.md
  purchase_request_type/readme/USAGE.md
  purchase_request_type/security/ir.model.access.csv
  purchase_request_type/security/security.xml
  purchase_request_type/static/description/icon.png
  purchase_request_type/static/description/index.html
  purchase_request_type/tests/__init__.py
  purchase_request_type/tests/test_purchase_request_type.py
  purchase_request_type/views/purchase_request_type_view.xml
  purchase_request_type/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳

#2627 [17.0][IMP] purchase_request: Define analytic_distribution field hidden by default
  purchase_request/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳

#2628 [18.0][IMP] purchase_request: Define analytic_distribution field hidden by default
  purchase_request/views/purchase_request_view.xml
Labels: approved, bot is merging ⏳

#2572 [14.0][FIX] purchase_advance_payment: fix payment_state
  purchase_advance_payment/models/purchase_order.py
Labels: approved, ready to merge, bot is merging ⏳
